### ISSUE TITLE
Issue with Applied Energistics or CofhCore ?

### ISSUE THREAD

**Issue by Neodark7** [InfinityRaider/AgriCraft#100]
http://pastebin.com/vdyCbTvF
http://pastebin.com/01VJgqP0

**Comment by InfinityRaider** [comment]
Fixed it, thanks for reporting

**Comment by Neodark7** [comment]
no problem :) thanks for your great work !

**Comment by Neodark7** [comment]
where can i found your latests dev builds ? :D

**Comment by Imasius** [comment]
Travis doesnt store build artifacts. We sometimes push alpha builds automatically over on curseforge. I think @InfinityRaider did just one a few minutes ago.

**Comment by Neodark7** [comment]
okay :) thanks

**Comment by InfinityRaider** [comment]
That one doesn't have this fix yet though. If you really want to I can compile a new one for you

**Comment by Neodark7** [comment]
yep thanks :) as you want ^^

**Comment by InfinityRaider** [comment]
Okay the build should appear on curseforge in a bit. It may take some time before it is approved though.
