### ISSUE TITLE
Thermal Foundation compatibility bug

### ISSUE THREAD

**Issue by arrowbounce** [InfinityRaider/AgriCraft#102]
When Agricraft is used with COFHcore, COFH library, and Thermal Foundation, the Iron ingot--> nuggets recipe is turned to an iron ingot --> 9 pulverized iron recipe. This completely breaks balance with regards to iron.

COFH core and library, and Thermal Foundation without Agricraft.
![2015-02-22_18 20 29](https://cloud.githubusercontent.com/assets/7119127/6322239/d8c4624a-bac4-11e4-966c-0e878398f39c.png)

Agricraft added
![2015-02-22_18 21 57](https://cloud.githubusercontent.com/assets/7119127/6322240/dabca33c-bac4-11e4-8765-89e7b3930338.png)

I did turn around between the two screenshots, it's still the same world.

Using: 
Minecraft 1.7.10.
Forge 10.13.2.1307-1.7.10
Agricraft 1.2.2
CoFHCore-[1.7.10]3.0.0RC1-181.jar
CoFHLib-[1.7.10]1.0.0B9-112.jar
ThermalFoundation-[1.7.10]1.0.0RC2-53.jar

**Comment by InfinityRaider** [comment]
Can you check if pulverized iron is mistakenly oredicted as ingotIron? If so then this is a Thermal Foundation bug if not, it is an AgriCraft bug.

**Comment by Kubuxu** [comment]
ThermalFoundation has some weird bug with remapping.

**Comment by InfinityRaider** [comment]
I've uploaded a new alpha version (alpha5) to CurseForge, can you check if it persists there, as I am failing to reproduce this.

**Comment by InfinityRaider** [comment]
I tested in a non dev-environment with alpha5 + the latest version on curseforge of the COFH mods and this is not an issue, so I'll consider this fixed.
