### ISSUE TITLE
Crash between Agricraft and MagicalCrops Agricraft Version 1.2.2

### ISSUE THREAD

**Issue by jamzam90** [InfinityRaider/AgriCraft#103]
Crash report
http://pastebin.com/pDbZYZW4
Magic Crops Version is 
4.0.0 Beta 13a

**Comment by thephoenixlodge** [comment]
This just looks like Magical fertilizer is no longer a thing or has had its class directory changed in that version. Agricraft is built against the publically available version rather than the patreon betas

**Comment by jamzam90** [comment]
Is there a way you could work around this slight issue? I'd like to have a use for agricraft in my modpack.

**Comment by thephoenixlodge** [comment]
There should be a config option to disable the magical fertilizer working as higher level bonemeal. Try disable that and see if it helps. If it doesn't you may need to disable the magic crops compat stuff completely, though this won't stop them from being plantable on crops.

**Comment by InfinityRaider** [comment]
I make it get the Magical Fertilizer from the Item Registry instead of directly referencing the external class. This will fix the crash, but it won't make magical fertilizer work.
Is there any particular reason why you are using a beta build instead of a public build?

**Comment by jamzam90** [comment]
Mostly that i had access it and like it more then the public. I prefer to use the latest version of any mods when im able to. I'd rather not switch to the public version mostly because im using the newer things from magic crops quite heavly.

**Comment by thephoenixlodge** [comment]
It's my pet peeve for magical crops. The fact that there are versions only ever released to the authors Patrons, yet said versions are still allowed to be released in modpacks but not for normal download ticks me off as it just seems a bit backhanded to me.

**Comment by InfinityRaider** [comment]
Well doesn't matter, his mod, his choice. I fixed this crash, I'm using the internal name instead of directly referencing the class. This will make it a thad slower but won't crash it. Besides if the internal name stays the same, it will still work.
