### ISSUE TITLE
Agricraft gives empty NBT Strings

### ISSUE THREAD

**Issue by V55V551N** [InfinityRaider/AgriCraft#104]
The game starts up, but nei is NOT starting anymore
(its the FTB-Infinity Pack)

Crash report:

http://pastebin.com/Ud7Dyatv

**Comment by V55V551N** [comment]
And another Error related to the same problem...:

http://pastebin.com/cXtFci0y

**Comment by InfinityRaider** [comment]
What version?

**Comment by InfinityRaider** [comment]
Also this is the first report I've had of this coming from the Infinity pack, did you add any mods, and so which ones?

**Comment by V55V551N** [comment]
the version is:
infinity version is 1.2.0 (not reccomendet yet i know)
AgriCraft-1.7.10-1.2.2.jar
The problem occures in this section of your code:
com.InfinityRaider.AgriCraft.utility.NBTHelper;

public static NBTTagCompound getMaterialTag(ItemStack stack) {
        NBTTagCompound tag = new NBTTagCompound();
        if(stack!=null && stack.getItem()!=null) {
            tag.setString(Names.NBT.material, Block.blockRegistry.getNameForObject(((ItemBlock) stack.getItem()).field_150939_a));
            tag.setInteger(Names.NBT.materialMeta, stack.getItemDamage());
        }
        return tag;
    }

i made a quick fix which makes the stack variable always null so it skipps this portion of the code
now its not crashing anymore...

i edited the bytecode of the NBThelper class

new net/minecraft/nbt/NBTTagCompound
dup
invokespecial net/minecraft/nbt/NBTTagCompound/<init>()V
astore_1
### aload_0          -->changed to-->   aconst_null
ifnull 24
aload_0
...

**Comment by V55V551N** [comment]
change this code:
tag.setString(Names.NBT.material, Block.blockRegistry.getNameForObject(((ItemBlock)stack.getItem()).field_150939_a));

to this:
if (! Block.blockRegistry.getNameForObject(((ItemBlock) stack.getItem()).field_150939_a.isEmpty()){
     tag.setString(Names.NBT.material, Block.blockRegistry.getNameForObject(((ItemBlock)stack.getItem()).field_150939_a));
}

should fix the problem i think

**Comment by InfinityRaider** [comment]
I know how to fix it, I want to know whats causing it. Because people shouldn't add itemblocks without a block...

**Comment by V55V551N** [comment]
it could be some problem with a cauldron plugin
 it happens when playing on a server that runs cauldron

**Comment by V55V551N** [comment]
if you want to check it for yourself i can give you the server wher it occures!

**Comment by InfinityRaider** [comment]
Thanks, but that won't be necessary, are you positive that this only happens when Cauldron is installed? I'm wondering if it is actually Cauldron or a mod that doesn't go nicely with Cauldron. I'll add in a check to prevent this exception. I'm still quite curious what is causing it though. Once the fix is out, can you compare the all the tanks with all the kinds of planks in your instance?
