### ISSUE TITLE
crops conflict with buildcraft woodengear AgriCraft-1.7.10-1.3.0-alpha6-b378, buildcraft-6.4.0

### ISSUE THREAD

**Issue by sircrimer** [InfinityRaider/AgriCraft#106]
Hi,

could you make the crop recipe shaped instead of shapeless?

Thx.
sircrimer

**Comment by InfinityRaider** [comment]
I'm not going to make it shapeless, I'll just delay its recipe registering so Minecraft finds the gear recipe before it finds mine.

**Comment by sircrimer** [comment]
Ok. Just to clarify right now it is shapeless.
