### ISSUE TITLE
Sprinkler particle reduction

### ISSUE THREAD

**Issue by Avalonzo** [InfinityRaider/AgriCraft#107]
Hello, I like to request that when particles are turned down/reduced that the sprinklers particles get reduced please. Thank you very much for the awesome mod.

**Comment by InfinityRaider** [comment]
I will not disable them, but I can reduce the number of them.

**Comment by Avalonzo** [comment]
Yeah don't disable them but it would be nice that when you turn particles down in the options that the sprinklers particles also reduce.
