### ISSUE TITLE
Removed AgriCraft entirely and still getting bombed with console messages

### ISSUE THREAD

**Issue by shortybsd** [InfinityRaider/AgriCraft#110]
I had Agricraft installed at one time til I kept getting server crashes and locking up when people explored in main world as well as making new MystCraft ages. "Skipping Piece with id AgriCraft:Greenhouse" constantly spammed a couple of hundred times then crashed. I removed Agricraft due to that, now every time I make a new Mystcraft world it spams that when AgriCraft is no longer installed on my server or clients. It then holds the Mystcraft world loaded (as if a chunk loader were there) due to it spamming the Greenhouse error. Where is it getting that information from so I can rid it of the lag and spam?

**Comment by InfinityRaider** [comment]
That spam was because of the lack of an empty constructor in the greenhouse code. It's been fixed afaik.

**Comment by shortybsd** [comment]
With it removed from my server and clients, how can I get rid of the Greenhouse messages which still continue to spam?

**Comment by InfinityRaider** [comment]
Delete the Mystcraft dimensions that where generated with this error

**Comment by shortybsd** [comment]
Does it in my main world too, cannot delete that one. Is there something as simple as a dat file i can edit to remove it?

**Comment by InfinityRaider** [comment]
No clue, maybe use McEdit to regenerate the Chunks containing villages?

**Comment by shortybsd** [comment]
Thanks will definitely check that out. When removing any mod and restarting the server, forge will remove all invalid block/item ids via /fml confirm. So the Greenhouse shouldn't even exist. It should be blank of where it was. So I have no clue why it is still saying that. Does/did your mod write to the World\Data folder and append or create any files?

**Comment by InfinityRaider** [comment]
It doesn't, all it does is add a new structure to the Map of structures. I have no idea what is done internally with it. I can look at the code and try to figure out what is going on with the entries of the map.
My guess is they are saved to a file and loaded from there again, this is the only explanation I can come up with as to why it stills try to find the Greenhouse Structure even though the mod is gone. But this is just speculation.
