### ISSUE TITLE
Mystical Flowers not working.

### ISSUE THREAD

**Issue by AaronSutter** [InfinityRaider/AgriCraft#111]
Before harvesting
![2015-03-01_20 33 03](https://cloud.githubusercontent.com/assets/6901811/6434261/9dc15a7a-c052-11e4-8bfd-49b6fd9b02d8.png)

After
![2015-03-01_20 32 58](https://cloud.githubusercontent.com/assets/6901811/6434266/b06863da-c052-11e4-8872-caf1f7b44862.png)

I am running version 1.2.2 and Botania v166 This issue happens with all Mystical flower seeds, tested in creative.

**Comment by InfinityRaider** [comment]
Has been fixed for 1.3
