### ISSUE TITLE
Some Natura Seeds Cannot Be Planted On Vanilla Farmland Or on Grass With Vanilla Farming Enabled

### ISSUE THREAD

**Issue by mikeloeven** [InfinityRaider/AgriCraft#113]
Just a small issue i double-checked the configuration for AgriCraft and dispite vanilla farming enabled some seeds from Natura are not plantable on their normal blocks

Additionally there is a seed duplication issue since natura crops do not have recipies for making seeds and breaking a crop only gives you one there is no current method of propagating natura plants

**Comment by InfinityRaider** [comment]
I'll look into the planting issue.
Also AgriCraft does not interfere with the breaking of plants from other mods, so you'll have to look somewhere else for that.

**Comment by mikeloeven** [comment]
Broken crops only leave one seed for natura plants if broken in the wild their seed yields are normal. 
the main issue is that the natura plant products do not have a seed crafting recipe in agricraft

**Comment by InfinityRaider** [comment]
I don't think you understand the mod mechanics. If you place a set of cross crops next to a mature crop it will eventually spread onto it and sprout a new plant.
