### ISSUE TITLE
Crash on world start with latest version 1.30 b407

### ISSUE THREAD

**Issue by Slither88** [InfinityRaider/AgriCraft#115]
Hi

In another pack of mine the client crashes as soon as the world loads. I can see it has something to do with magical crops and fastcraft, but beyond that idk.

Crash Report: http://pastebin.com/yNTaDFx3

**Comment by Slither88** [comment]
The crash does not occur when magical crops is not present. So it seems to be something related to magical crops.

**Comment by InfinityRaider** [comment]
Did you update Magical Crops? They also changed the Fertiliser class and that caused crashes before.

**Comment by Slither88** [comment]
I will get the latest version of Magical crops. Thanks for all the help.

**Comment by Slither88** [comment]
I am still getting the crash on world start with the latest agricraft 1.3.0 b407 and Magical crops 4.0.0 beta 13a which is the latest magical crops I could get my hands on. Works fine with agricraft 1.2.3 though.

**Comment by InfinityRaider** [comment]
The latest build on CurseForge does not have these fixes yet.
I'm going to wait and fix a few more things before I release 1.3.1, patience my friend, patience.

**Comment by Slither88** [comment]
No worries. I am glad to wait. The latest version of agricraft works perfectly. Thanks for the replies. Thanks for the awesome mod.
