### ISSUE TITLE
Unable to place crops on Soul Sand

### ISSUE THREAD

**Issue by Avalonzo** [InfinityRaider/AgriCraft#117]
Hello, I'm currently using v1.3.0 in the Regrowth pack and mentioned to thephoenixlodge that I could no longer place crops on soul sand to grow/farm netherwart the AgriCraft way & was asked to report it here. A little more information I even tried to see if I could till it using both a hoe & mattock to no avail but I am still able to place it down vanilla style.

**Comment by thephoenixlodge** [comment]
I will double check this myself in the morning too

**Comment by Avalonzo** [comment]
Current uploading a 5 second video of the bug to youtube as I thought a video would be even more helpful will post link when done.

**Comment by InfinityRaider** [comment]
Okay time to remove the dust from my dev environment and get back to work. Ill look if I can reproduce this.

**Comment by Avalonzo** [comment]
Here is the link to the video - http://youtu.be/zWXyaXyGkSE

**Comment by InfinityRaider** [comment]
Is it only with soul sand or also with mycelium?

**Comment by Avalonzo** [comment]
Mycelium is works ok - http://i.imgur.com/kWf1paHh.png

**Comment by InfinityRaider** [comment]
Okay I know why this is happening, I'm registering soils when new blocks are created, but becasue nether wart already exists, its soil is never registered. I can either add a new crop that uses soul sand to bypass this, or I can hardcode soul sand to the list.
I think I'll go for the first option.

**Comment by Avalonzo** [comment]
Thank you for being so quick off the mark. If you like when you have a build ready to test the new crop/fix I can test it out.

**Comment by InfinityRaider** [comment]
Make a new ticket for that please
