### ISSUE TITLE
Сan not collect seeds....

### ISSUE THREAD

**Issue by Pilad** [InfinityRaider/AgriCraft#119]
Сan not collect seeds from the cotton after landing on his perch in mod Pam's HarvestCraft 1.7.10g

**Comment by InfinityRaider** [comment]
I don't understand what you mean with that, sorry

**Comment by Pilad** [comment]
OK... I take video from game... Sorry. I Russian man (((

**Comment by InfinityRaider** [comment]
No response in 4 days, closing this.
