### ISSUE TITLE
Support for Pam's Mob Drop Crops

### ISSUE THREAD

**Issue by InkDragon** [InfinityRaider/AgriCraft#122]
Requesting support for pam's mob drop crops
http://minecraft.curseforge.com/mc-mods/221919-pams-mob-drop-crops

Alternatively adding mob drop seeds as resource seeds would also be acceptable

**Comment by InfinityRaider** [comment]
Ah yes I remember that, there was an issue in Pam's code where it would always return null when calling the method to get the seed. I sent her a message but she never got a reply, I'll check if it has been fixed.

Also I personally don't like the concept of mob drop seeds so it will not go into the mod, there is functionality to add it yourself though.

**Comment by InfinityRaider** [comment]
This is fully implemented in the crop rewrite
