### ISSUE TITLE
Resource plants enabled, mutation is in the config file, but mutation isn't working

### ISSUE THREAD

**Issue by kotoroshinoto** [InfinityRaider/AgriCraft#123]
no idea what is wrong. I am using the pre-released version (it fixes botania flowers)

**Comment by kotoroshinoto** [comment]
Specifically the mutation of blue orchid + pink tulip -> lapender isn't working.

**Comment by thephoenixlodge** [comment]
You've got the appropriate Ore underneath the farmland right?

**Comment by kotoroshinoto** [comment]
On 3/9/2015 6:25 AM, thephoenixlodge wrote:
>
> You've got the appropriate Ore underneath the farmland right?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/InfinityRaider/AgriCraft/issues/123#issuecomment-77829638>.
>
didn't realize it needed the ore as the farmland.

Whoops


---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by kotoroshinoto** [comment]
would it be the lapis ore block for the lapis or a block of lapis ?

**Comment by thephoenixlodge** [comment]
If you're using 1.3+ then it will say the baseblock in the NEI mutation handler
