### ISSUE TITLE
Crop sticks duplicating when right-click harvesting

### ISSUE THREAD

**Issue by InvaderAZ** [InfinityRaider/AgriCraft#124]
Just added AgriCraft-1.7.10-1.3.1.jar to my custom pack with a plethora of other mods, including HarvestCraft (1.7.10f) and HungerOverhaul (1.7.10-beta.2).

Doesn't seem to matter which crop I have planted, but when I right-click harvest a fully grown crop, it gives me the seed, the produced crop, and a set of the crop sticks even though it leaves a set of the crop sticks in the ground.

**Comment by InfinityRaider** [comment]
Can I have a specific list of mods?

**Comment by InvaderAZ** [comment]
Here ya go

https://docs.google.com/spreadsheets/d/1Ox6plGNc7swdtNh5pID8ALbiPwfEHb_UIXBQVCgqpxU/edit?usp=sharing

**Comment by InfinityRaider** [comment]
I'm comparing with infinity and regrowth, can you make a new instance with all the mods that are not in one of these and remove one by one to see wich one is causing it? I'm thinkin one of them is tampering with the harvest event

**Comment by InvaderAZ** [comment]
Will work on that this evening

**Comment by InfinityRaider** [comment]
First test it with an instance with AgriCraft alone, something weird might be happening, if it occurs there, itll save you quite some time.

**Comment by InvaderAZ** [comment]
Ok it's definitely HungerOverhaul.

With just AgriCraft, AppleCore and HungerOverhaul the duplication happens, simply removing HungerOverhaul stops the duplication

**Comment by InfinityRaider** [comment]
This is weird, what version of Hunger Overhaul are you using?

**Comment by InvaderAZ** [comment]
Hrm ok I was using beta2, after updating to beta5 the problem is fixed.
