### ISSUE TITLE
[1.3.1]Witchery Garlic not producing fruit.

### ISSUE THREAD

**Issue by thephoenixlodge** [InfinityRaider/AgriCraft#125]
In its newest update (0.23.0) witchery added a new garlic crop. It seems to act similar to nether wart in that the garlic item is both the seed and the intended product. The issue however is that when on crops it is not recognized as having any fruit, so harvesting it just lowers the growth % but gives no item.

**Comment by InfinityRaider** [comment]
Witchery has been on the agenda for a while, The plants also don't show the correct texture (it get the mature one too soon).

**Comment by InfinityRaider** [comment]
I'll probably do a bugfixing session this weekend, but I'll wait with a release. A temporary fix for you is to add the seed as seedWolfsbane and the produce as cropWolfsbane to the oredictionary with Minetweaker.

**Comment by InfinityRaider** [comment]
Fixed in rewrite
