### ISSUE TITLE
IC flax fix

### ISSUE THREAD

**Issue by InfinityRaider** [InfinityRaider/AgriCraft#126]
Flax doesnt use the correct textures and doesn't harvest

**Comment by hron84** [comment]
Same with BluePower flax as it's a double-tall crop and only yields if both half is mature.

**Comment by InfinityRaider** [comment]
Still debating if I want to implement an exception for crops that are multiple blocks tall or shove them into a single block

**Comment by Timeslice42** [comment]
These should work now, right? (Once you release the next version)

**Comment by InfinityRaider** [comment]
They should

**Comment by InfinityRaider** [comment]
Apparently IC2 doesn't have flax, my bad, but Blue Power flax is fully supported now

**Comment by Timeslice42** [comment]
You aren't crazy. It's GT that adds flax to IC2 crops.

**Comment by InfinityRaider** [comment]
I'm going to try to support the IC2 crops eventually, my rewrite should make that possible, but for now I have lots of other things to worry about.
