### ISSUE TITLE
BaseBlock method no longer works with still water/lava

### ISSUE THREAD

**Issue by ubermentat** [InfinityRaider/AgriCraft#129]
After updating to AgriCraft 1.3.1, the BaseBlock method doesn't seem to want to register still water or lava. MineTweaker puts this error in the chat window: `a method available but none matches the parameters (minetweaker.item.IItemStack, minetweaker.item.IItemStack, int)`

A sample of the code in question follows:
```
import mods.agricraft.growing.BaseBlock;
BaseBlock.set(<AgriCraft:seedSugarcane>, <minecraft:water>, 2);
BaseBlock.set(<magicalcrops:magicalcrops_MagicSeedsNether>, <minecraft:lava>, 2);
```

This code executed just fine with the final version of 1.3.0

**Comment by InfinityRaider** [comment]
Oright it needs a boolean for being oredict specific or not, I'll make it so if you set it to <ore:...> it is an oredict requirement. For now just add false as 4th argument
