### ISSUE TITLE
Make <ore:name> set baseblocks as an oredict requirement instead of using a boolean

### ISSUE THREAD

**Issue by InfinityRaider** [InfinityRaider/AgriCraft#134]
(as seen in #129)

**Comment by Maokuma** [comment]
Will this make it possible to use different ores from other mods and add more ore flowers? I would love to see that as a feature in the mod.
//Thanks and I love your work

**Comment by InfinityRaider** [comment]
That is already possible

**Comment by Nephatrine** [comment]
Will this allow my sandy crops to grow on both normal sand and red sand by setting baseblock to <ore:sand>? It's frustrating that I cannot grow my custom desert crops on both types of vanilla sand.

**Comment by InfinityRaider** [comment]
Yes it will.
