### ISSUE TITLE
Garlic from witchery won't give anything

### ISSUE THREAD

**Issue by JadeDrgn** [InfinityRaider/AgriCraft#139]
I got garlic fully grown, stats at 10-10-10, it grows fine but when I right click it they don't give anything, they get harvested but they just don't drop anything.

**Comment by thephoenixlodge** [comment]
https://github.com/InfinityRaider/AgriCraft/issues/125
Look through existing issues before posting new ones.

**Comment by JadeDrgn** [comment]
Sorry, can't believe I didn't see that... I tried looking before but apparently I'm blind.
