### ISSUE TITLE
[1.3.1] Poisonous Potatoes not dropping as a side drop from Potatoes

### ISSUE THREAD

**Issue by thephoenixlodge** [InfinityRaider/AgriCraft#141]
It may be that I didn't use a large enough sample size, but bonemealing the plant for 64 harvests didn't produce a single poisonous potato, in any light level.

**Comment by Timeslice42** [comment]
Do you mean without explicitly adding poisonous potatos to the crop? Or did that not work either? I noticed that you guys have that line commented out of your script.

**Comment by Timeslice42** [comment]
Also, I liked IC2's method of leaving potatos unharvested too long caused them to turn poisonous (tubers exposed to light will have increased solanine production, so this makes sense).
