### ISSUE TITLE
Channels not empting of water when gate is closed.

### ISSUE THREAD

**Issue by Gunner76th** [InfinityRaider/AgriCraft#142]
I am running release 1.2.2, and have noticed that even if you put in a gate, the irrigation channels never fully empty of water, they stop at 3mb. This also holds true if I disconnect the channel from the tank as well. It seems that once water is put into the channel, the channel always has at least 3mb of water left in it, meaning that your sprinklers never run out of water or stop working.

I am running the Infinity pack from FTB, and just checked your CurseForge and noticed that the pack is a few releases behind. I will manually update to your most recent version and see if this is still an issue.

**Comment by InfinityRaider** [comment]
This has been reported multiple times, and you are running 3 versions behind, so please don't most bug reports for out of date versions

**Comment by Gunner76th** [comment]
Has this been fixed in the most recent version?

**Comment by InfinityRaider** [comment]
Yes it has
