### ISSUE TITLE
VillagerRegistry error

### ISSUE THREAD

**Issue by drago87** [InfinityRaider/AgriCraft#145]
The game is crashing at game start after i upgraded from agricraft 1.2.2 to 1.3.1
Crash report: http://pastebin.com/yANd535U
OpenEye: http://openeye.openmods.info/crashes/8c8ee11a017d1cdb3282c1c2f9925224

**Comment by InfinityRaider** [comment]
Villager id conflict, change the id of the villager in the config file or disable the villager
