### ISSUE TITLE
scanning seeds issue

### ISSUE THREAD

**Issue by Bentenmaru** [InfinityRaider/AgriCraft#149]
I'm having some problems when im scanning seeds with the analyzer, weird is that some time it works fine and sometimes it not. Im playing on a private server i use for myself only, server is ok so its only on the client side 

http://pastebin.com/Ck3VWYvY

**Comment by InfinityRaider** [comment]
What version are you using and can you give some more details?

**Comment by Bentenmaru** [comment]
currently using the latest agricraft that is 1.3.1 and forge is 1291 that is latest recommended

**Comment by InfinityRaider** [comment]
I honestly have no idea what is causing this. Is there a journal in the analyser or not?

**Comment by Bentenmaru** [comment]
yea..there is a journal in the analyzer

**Comment by InfinityRaider** [comment]
Remove it, and see if it crashes then please, just for the sake of trying to narrow it down.

**Comment by Bentenmaru** [comment]
works fine if no journal in the analyzer but once i put it back in and scan seeds it crashes for me

**Comment by InfinityRaider** [comment]
Does your journal already have entries? If so, try to copy it and see if that crashes you.

**Comment by Bentenmaru** [comment]
currently there are 12 entries in my journal, and what you mean by copying it? make a new journal and start scanning new seeds and see if that makes it crash?

**Comment by InfinityRaider** [comment]
By copying I mean putting it in a crafting grid with a book and quil. I suspect the NBT tag on the book became corrupted, not sure though.

**Comment by Bentenmaru** [comment]
that didnt work, worked a few times fine but then crash again

**Comment by InfinityRaider** [comment]
But you can successfully copy the journal? Try with a brand new one please.

**Comment by Bentenmaru** [comment]
can copy journal fine, tried with a brand new journal but still getting crash, weird is though if i delete my world im having this problem with and make a brand new one and let it run scanning, with both brand new seeds and seeds with different stats it works just fine

**Comment by InfinityRaider** [comment]
Thats strange, I'm sorry, but I have absolutely no idea how and why this is happening

**Comment by Timeslice42** [comment]
Have him give you the NBT tag. I'm pretty sure RR uses minetweaker, so you should be able to put "/mt tooltips" in the console to get extended information on items. If the tag doesn't fit on screen, would "/mt hand" fit either?

**Comment by InfinityRaider** [comment]
I've rewritten a whole deal so this is no longer valid, if it persists with the new build feel free to create a new issue with the relevant crash log.
