### ISSUE TITLE
Seed Analyzer causes massive fps drop while active

### ISSUE THREAD

**Issue by MatthiasMann** [InfinityRaider/AgriCraft#150]
The seed analyzer causes a block update and network packets every tick while it is active.

It should be enough to have the automatic inventory sync done my MC - and simulate the progress on the client side. Once the server finished the work it will update it's inventory anyway. Which would reduce the network traffic and the block updates a lot.

**Comment by InfinityRaider** [comment]
The block updates aren't necessary you're right, I believe its a side effect from rewriting my base tile entity code a while ago, i'll optimise this, thanks for bringing this to my attention.

**Comment by Zaflis** [comment]
Do block updates have more dramatic effect the more there are tile entities near it? I'm getting a pretty dramatic fps drop from 60 down to 20 fps when using seed analyzer. Base is pretty midgame, large farm and machines near it.

Regards to seed analyzer, it's also not changing its visual state (seed still showing in UI after it's scanned) until i right click it open again. Agricraft 1.3.1.

**Comment by InfinityRaider** [comment]
The block updates and network packets have been limited to only one when analyzing is done.

@Zaflis what do you mean the steed still shows up? Can you be more specific about this? (preferably in a new issue).
