### ISSUE TITLE
Opencomputer/Computercraft support for the seed analyser

### ISSUE THREAD

**Issue by LordTy** [InfinityRaider/AgriCraft#152]
Can we get an Opencomputer/Computercraft interface on the seed analyser? This would allow us to automate seed sorting/breeding.

**Comment by InfinityRaider** [comment]
I don't like the analyser itself being a peripheral, but I can add in a new block that is suited more for automation and can be a peripheral.

**Comment by LordTy** [comment]
Yeah that would be a better solution, Thanks.
