### ISSUE TITLE
level 10-10-10 seed will ignore all requirements

### ISSUE THREAD

**Issue by Goten87** [InfinityRaider/AgriCraft#158]
well my title saying it al i think a fully upgraded seed needs to ignore all requirements

its most likely be the netherward that will be nice
so we dont need to have it in a dark room anymore but can grow it outside as well

i dont think it will be nice to let them dont need water but like the ground there place on can be all as well
so weath can grow on sand and netherward on farmland or dirt

**Comment by InfinityRaider** [comment]
It's a good suggestion and I'll try and come up with a way to make the strength stat affect growth requirements.
I'm planning to rewrite growt requirements from true/false to a growth rate multiplier anyway.
