### ISSUE TITLE
No greenhouses when using BoP worldtype

### ISSUE THREAD

**Issue by ate0ate** [InfinityRaider/AgriCraft#160]
Using various versions of agricraft and Biomes o Plenty up to the most recent of each, it seems that greenhouses do not spawn in BoP world types. I am also Using Witchery, Tinker's Construct, Flaxbeard's steam mod and Thaumcraft, all of which add custom village generation which does appear to spawn correctly.

**Comment by InfinityRaider** [comment]
I believe it's simply due to the fact that the footprint of the building is too large.

**Comment by ate0ate** [comment]
Drats! That makes me sad. The greenhouse pic's I've seen thus far look very nice. Thank you for the quick response.

**Comment by InfinityRaider** [comment]
I'm not sure, i'll have to add in some debug info to see when it is called to generate and why it can't
