### ISSUE TITLE
Psychedelicraft compatibility issue

### ISSUE THREAD

**Issue by SteyrTMP** [InfinityRaider/AgriCraft#162]
Psychedelicraft seeds do not drop the correct products. Instead of the plant's products, it's actually dropping an item copy of the plant's tile entity.

**Comment by InfinityRaider** [comment]
I've already reported this to the author of psychedelicraft, he is registering his seeds as seed<PlantName>, but instead of registering his fruits as crop<PlantName> he registers his crops.
Should be fixed in a newer version of the mod.
If you can't wait, use Minetweaker to change the oredict tags.
