### ISSUE TITLE
Config option for mature seeds only

### ISSUE THREAD

**Issue by Timeslice42** [InfinityRaider/AgriCraft#164]
This is a feature request for a config option to make seeds only drop from mature crops, similar to how IC2 crops work. Actually, IC2 is mature-1 or mature, so like that would be good.

This option would be to help combat the trivialization of breeding for stats. The first growth stage happens rather quickly, and being able to get seeds from that stage vastly speeds up the breeding process compared to IC2 crops.

**Comment by InfinityRaider** [comment]
Very well, but I shall disable it by default.

**Comment by Timeslice42** [comment]
I should hope so :)

**Comment by InfinityRaider** [comment]
I've been thinking of this, if you accidently plant a seed in the wrong spot and it cannot grow, you lost your seed.

**Comment by Timeslice42** [comment]
That's actually part of the point. You're meant to be more careful with your seeds. This will also encourage the use of the trowel to move misplaced crops.

**Comment by InfinityRaider** [comment]
Of course, the trowel.

**Comment by Timeslice42** [comment]
Thank you :)
