### ISSUE TITLE
"Require Rakes" option is too "soft"

### ISSUE THREAD

**Issue by Timeslice42** [InfinityRaider/AgriCraft#165]
This is another feature request. Even with require rakes turned on, it is still trivial to just break the cropsticks instead of using a rake. It would be nice to have some sort of option which would make weeds more tenacious. Say, increase the hardness (not the mining level) of crop sticks with weeds so that they take much longer to break, which would encourage the use of rakes.

**Comment by InfinityRaider** [comment]
What about destroying the crop sticks?

**Comment by Timeslice42** [comment]
You mean if you try to break cropsticks that have weeds, they break but you get nothing? I would be okay with this if crops weren't so easy to break as it is. But either method is a decent deterrent, so go with your best judgement.

**Comment by InfinityRaider** [comment]
I've decided to implement it my way: if crop sticks are broken with weeds on them, the crop sticks get destroyed in the process (if enabled in the config)
