### ISSUE TITLE
[Enhancement] Reduce number of NEI entries

### ISSUE THREAD

**Issue by Cobra1117** [InfinityRaider/AgriCraft#171]
Feature request:
It would be nice if only one of the tanks/channels/valves were displayed in NEI. Otherwise, on heavily-moded servers, searching for "tank" yields 1.5 pages of Agricraft and 1 page of everything else. (Plus NEI lag can be reduced by having fewer items for it to search through.)

I'm pretty sure that the NEI API allows you to condense multiple recipes into a single icon, but I honestly haven't looked at the API in a few years.

**Comment by InfinityRaider** [comment]
I know, I've been meaning to do this for a while but never got around to doing it. I'll do it for the next update, it's a big one anyway.

**Comment by Cobra1117** [comment]
Github really needs a "like this comment" button :-)

**Comment by InfinityRaider** [comment]
This is implemented now
