### ISSUE TITLE
[Enhancement] Option to pass identified seeds through seed analyzer

### ISSUE THREAD

**Issue by Cobra1117** [InfinityRaider/AgriCraft#172]
Feature request:
It would be nice if there was a way to have the seed analyzer accept seeds that have already been identified, and immediately make them applicable for removal. That way, if you have an automated seed IDing system, you don't have to manually sort the seeds--you can just dump all the seeds from your inventory into the "input" chest and come back later and get them all from the "output" chest.

If this isn't a good thing to do by default, then perhaps a checkbox in the corner of the analyzer for this would be possible?

**Comment by InfinityRaider** [comment]
So you just want them to be able to go into the slot?

**Comment by Cobra1117** [comment]
Yeah. That way you can automate it like this:
Chest 1 -> Hopper -> Seed Analyzer -> Hopper -> Chest 2
Then you just drop all your seeds in Chest 1, and get them back from Chest 2 later. (This works now, but you have to manually sort out the ones that have already been ID'ed.)

**Comment by InfinityRaider** [comment]
I can do that ye.

**Comment by InfinityRaider** [comment]
Has been added
