### ISSUE TITLE
In MineTweaker scripts, setting max brightness to 16 should be allowed

### ISSUE THREAD

**Issue by HMPerson1** [InfinityRaider/AgriCraft#173]
[GrowthRequirement.maxBrightness](https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/farming/GrowthRequirement.java#L24) is exclusive and has a default value of 16, but a max brightness of 16 in a MineTweaker script is not allowed.

Fix: Change [this line](https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/compatibility/minetweaker/Growing.java#L255) to less-than-or-equals (<=) instead of less-than (<).

(Also, the error messages [here](https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/compatibility/minetweaker/Growing.java#L251) and [here](https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/compatibility/minetweaker/Growing.java#L254) should be swapped.)

**Comment by InfinityRaider** [comment]
Light goes from 0 to 15, 15 included, so having 16 as an exlcuded upper limit is fine.
http://minecraft.gamepedia.com/Light#Brightness

**Comment by InfinityRaider** [comment]
Okay derp I see your point, consider it fixed
