### ISSUE TITLE
Quartz Grains

### ISSUE THREAD

**Issue by Maelstraz** [InfinityRaider/AgriCraft#174]
There is metal plants, sooo...

How about certus quartz (AE intergration) and nether quartz plants?

Probably require sand / soul sand as soil and sugarcane (sand) / nether wart(soul sand) + mushrooms (growing crystals) as parents.

**Comment by InfinityRaider** [comment]
Give me a good name for it and I'll add it in

**Comment by BBoldt** [comment]
Hey, I've added tons of crops to my personal instance, for almost every single ore type in my modpack.

Certus Quartz is called "Certophus" 
It is made with Lapender and Emeryllis, with Certus quartz ore below.
Vanilla Quartz is called "Qwart"
It is made with Nitor Wart and Emeryllis, on soul sand, with quartz below.

Btw, you should set up an IRC channel on esper.net, I would love to discuss some things with you live. The channel "#agricraft" hasn't been taken yet.

**Comment by InfinityRaider** [comment]
I'll add the vanilla quartz one in, I'm not going to start doing every modded resource because this is not Magical Crops.
