### ISSUE TITLE
Fix standalone crops

### ISSUE THREAD

**Issue by BBoldt** [InfinityRaider/AgriCraft#178]
Not sure if this is a bug or intended. Seeds planted on regular soil will ignore all growth requirements and ignore whatever block is below the soil.

**Comment by InfinityRaider** [comment]
A bug, to be honest I never really bothered much with seeds not growing on plant, I guess I should fix that sooner or later.

**Comment by InfinityRaider** [comment]
I've fixed this a couple of commits ago, forgot this was open so I didn't reference.
