### ISSUE TITLE
Request: Crops have a chance of consuming the block below the soil

### ISSUE THREAD

**Issue by BBoldt** [InfinityRaider/AgriCraft#179]
I'm adding some custom mob drop crops, and I thought it would be cool if they could consume mob essence or something else. 

This could also work for other crops, you could for instance have a block of fertilizer or something that gets consumed which you have to replace regularly.

**Comment by InfinityRaider** [comment]
I have thought about this and I will not be adding this, sorry.
I'm planning to extend irrigation systems with fertilizer anyway
