### ISSUE TITLE
Crash at startup (java.lang.NoSuchFieldError: seedBeet)

### ISSUE THREAD

**Issue by eranor** [InfinityRaider/AgriCraft#182]
I get a crash on startup. It works without AgriCraft.
Any chance that you know what is the cause?

Crash report:
http://puu.sh/hmQv2/f0b254d686.txt

**Comment by InfinityRaider** [comment]
This is because Plant Mega Pack updated and I was directly referencing their classes and I should feel bad about it, but I don't, I fixed this already so you will either have to remove agricraft or use the previous version of PMP until I release the next update.

**Comment by eranor** [comment]
Thanks. :)

**Comment by psouza4** [comment]
Kind of stuck in an endless loop on this one until you publish a release.  I always hate to rush a developer, but since PMP does not have archival versions available, users have to choose between the two mods currently.

Looking forward to your next release

**Comment by InfinityRaider** [comment]
I'm sorry to hear that, release won't be for this month though, got a lot of things I want to finish up and add in and I have my exams coming up.

**Comment by psouza4** [comment]
Fully appreciate the reply nonetheless.  Will look forward to using AgriCraft again when it's patched up.  Good luck with your finals

**Comment by InfinityRaider** [comment]
If I can get the things I did in the meantime stable I might do a quick inbetween release, nonofficial, probably here on github.

**Comment by Dulciphi** [comment]
That would be a huge help if at all possible. If there's anything I or anyone else can do to help, just say. 'Till then, all the best with your exams.

**Comment by themalkav** [comment]
java.lang.NoSuchFieldError: seedBeet

I was reading the posts and noticed its nearing July and was asking how that status is on this fix, what with your exams and all going on. I'm running a heavy plant/tech pack (-minus botania). And while I was gathering the mods together and about to server start and recorded, it was the only things malfunctioning in the pack. Not to rush anything by any means, just getting a prospective of a time frame if able to plan for it in the pack or not. 

V/R
Coffee_Nutz

**Comment by InfinityRaider** [comment]
http://minecraft.curseforge.com/mc-mods/225635-agricraft/files
