### ISSUE TITLE
NoSuchFieldError:SeedBeet Crash

### ISSUE THREAD

**Issue by MtnDrew** [InfinityRaider/AgriCraft#186]
Just added Agricraft and Plant Mega Pack to my game, and it crashed as I was trying to load Minecraft. 

I'm not good with Crash Reports but I did see that Agricraft was the mod that errored and I'm assuming it has to do with the Plant Mega Pack as well?

This is the crash report: http://pastebin.com/jpQbVV8r

Hopefully it's a simple fix. I can't have a good game without Agricraft.

**Comment by MtnDrew** [comment]
Agricraft loads in properly on its own and Minecraft starts. The problem arises when I add in the Plant Mega Pack.

**Comment by MtnDrew** [comment]
Found a fix for it. Sorry about this.

**Comment by InfinityRaider** [comment]
np
