### ISSUE TITLE
Forestry squeezer compatibility

### ISSUE THREAD

**Issue by BBoldt** [InfinityRaider/AgriCraft#187]
I think Agricraft seeds should be able to be squeezed into seed oil in Forestry's squeezer.

**Comment by InfinityRaider** [comment]
All my seeds are oredicted, so they could use that on their side, will be the easyest solution for everyone in my opinion.

**Comment by BBoldt** [comment]
Currently talking to members of the forestry team about it on IRC.

**Comment by InfinityRaider** [comment]
I assume they haven't added it from their side, so I guess I'll do it from mine, how much mB per seed do you propose (yes it's been ages since I played minecraft)

**Comment by thephoenixlodge** [comment]
They have added it in the dev builds, just hasn't made it into a public release yet.

**Comment by BBoldt** [comment]
https://github.com/ForestryMC/ForestryMC/commit/c3322de12a5765d5bb3e3da39e0a7a827fa474a3

Wont work for custom added crops though, you may want to do something to make that work on your end.

**Comment by InfinityRaider** [comment]
Custom added crops are automatically added to the oredictionary as well, so if they're using that tag, it should still work.

**Comment by BBoldt** [comment]
Forestry team have told me they can't use the oredictionary tag in that machine for some reason.

Minetweaker doesn't support forestry. Modtweaker does, but modtweaker seems to break constantly, and is always in a state of flux.

**Comment by InfinityRaider** [comment]
I'll do it from my side then, I'll look at what they put as values and mimic that.

**Comment by Nirek-K** [comment]
I added all the seeds that existed to me in game, I could add custom ones if they have some sort of consistent naming internally (agricraft:customseed1, 2, 3) or similar.
Normal seeds produce 10mb of oil.

**Comment by InfinityRaider** [comment]
@Nirek-K, thanks, all my seeds are named "agricraft:seed<cropName>", where cropName is the name I have given it or the end user (in the case of custom crops). 
However I believe it'd be a lot easyer for the both of us if I do it on my side (since you're not using the ore dictionary) because whenever I decide to add a new crop you'd have to update your code, which is impractical.
