### ISSUE TITLE
Mutation/spread breeding does not check configuration max stats

### ISSUE THREAD

**Issue by Heytunk** [InfinityRaider/AgriCraft#188]
When cross breeding or spreading a crop the handler doesn't check the configuration max stat, and allows you to breed crops with higher than config max stats.
This allows crops with stats up to max int.

Easy way to test it is to cross breed two 10 10 10 or max stat crops and hit them with the debugger.

Seeds generated from these crops are checked and pegged to config max however.
  
Suggested fix:
Check stats on mutation and spread.  

Additional comment:
Adding config options for 'soft' caps that allows > config max stats with increasing/exponential difficulty would be cool, as this is a pretty neat mechanic (> max stats, but can't analyze or move it easily).

**Comment by InfinityRaider** [comment]
Will fix that, thanks, little oversight on my part.
I don't really get what you mean with soft caps though.

**Comment by Heytunk** [comment]
A soft cap is a mechanic where either leveling becomes significantly harder, or effectiveness of additional stats becomes less effective as they get higher once the player reaches the soft cap.

**Comment by InfinityRaider** [comment]
I've decided not to implement the hard cap.
