### ISSUE TITLE
Custom Crop Texture Probs

### ISSUE THREAD

**Issue by teamMK** [InfinityRaider/AgriCraft#189]
Hi,

i tried to get some textures to my new custom crops, but with forge 1373 i only get the pink&black squares. I copy paste it to my regrowth installation (forge 1291) and everything works. maybe the forge troubles can be fixed?

**Comment by InfinityRaider** [comment]
I'll have to investigate this then

**Comment by InfinityRaider** [comment]
I updated my dev env to forge 1373 and I am failing to duplicate this issue, make sure the textures are named correctly and that you have actually enabled the resourcepack.
