### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by RagaRBM** [InfinityRaider/AgriCraft#194]
Hello. I want to know the cause of a startup crash I'm having when I install AgriCraft. I use Forge .1370.

This is my modlist : 
Enchiridion-1.7.X-1.2b.jar
fastcraft-1.21.jar
Pam's HarvestCraft 1.7.10h.jar
BuildcraftAdditions-1.7.10-2.1.2.jar
Mariculture-Deluxe-1.7.10-1.2.4.2a.jar
plantmegapack-4.17-1.7.10-1230.jar
Ganys Surface-1.11.0.jar
Railcraft_1.7.10-9.6.1.0.jar
CodeChickenCore-1.7.10-1.0.6.43-universal.jar
Eureka-1.7.10-3.0.2.jar
buildcraft-6.4.14.jar
FloodLights-1.7.10-0.4.3-62.jar
forestry_1.7.10-3.6.0.545-unstable.jar
NotEnoughItems-1.7.10-1.0.4.106-universal.jar
Factorization-1.7.10-0.8.89.jar
GlowstoneWire-1.7.x-1.0.2.113.jar
CodeChickenLib-1.7.10-1.1.3.136-universal.jar

**Comment by InfinityRaider** [comment]
Crashlog would be nice

**Comment by ubermentat** [comment]
Downgrade Plant Mega Pack.

**Comment by InfinityRaider** [comment]
Ah yes, PMP integration is fixed for the next release.
