### ISSUE TITLE
Compatiblity Question

### ISSUE THREAD

**Issue by Speiger** [InfinityRaider/AgriCraft#195]
Well i know AgriCraft is based on the Idea of IC2 Crops which had a lot of things as basement (i even think that Bees and everything further with breeding has his basement there), but here is my question. How hard would it be to make a Compatiblity to IC2 Classic... Well about Exp i have no control.
I would enjoy it to make it possible that IC2 Crops can breed together with Agricraft Crops and make even more interesting combinations to it...

Just asking for it.

**Comment by InfinityRaider** [comment]
I've been thinking of this as well and I've looked into it a bit, the rewritten code should allow this, however I'm not sure if it'll ever be implemented by me.

I know that someone else is making a small addon to AgriCraft that reproduces the IC2 & GT crops for AgriCraft.

**Comment by Speiger** [comment]
Ok. First the addon you can forget^^" Because the breeding part is at IC2 is random. And with random i mean not your type of random where you still can see what could be the result...

Also the idea i had in mind would be that you can combine IC2 and AgriCraft while you breed. So a Agricraft crop breeds with a IC2 Crop, or if the agricraft speed of plantgrowing/drops is not fast enough then you can simply jumpover to ic2 classic without problems. The stats would be still there.

Another thing: Your mutation engine is interessting and pretty basic. The difference between the ic2 crops is that your mutation are hardcoded and you can only get breeds from combining 2 set crops.
With IC2 is it a little bit differend. The mutation is not set by mc load. (At least not everything)
Instead of having set everything during the load it chooses a crop when its start to breed. And the Description&Tier of a crop are the key points. For every matching discription it give the crop it may get points and then it chooses randomly a plant based on these points.
That simply you can get almost every crop through 1 cropset. Some are simply locket by a tier (so if your crop tier is to low it will not get added to the chance list).
^^" Thats why the ic2 crops are so hard to breed. But their stats can be way higher then Agricraft crops. ^^"

But if you are not interested of making compatiblity (which is only possible at ic2 classic side with special internal code), then it is ok^^"

**Comment by InfinityRaider** [comment]
Well the way my mutations work are like that because I wanted them like that, I like IC2 crops, I just don't like the implementation.
So from my side you'll probably never see compatibility like the one you are describing.

**Comment by Speiger** [comment]
Its just that what i was thinking. If you have a better idea then tell me.
^^" I am not the god of ideas you know
