### ISSUE TITLE
Rework soils and base blocks

### ISSUE THREAD

**Issue by InfinityRaider** [InfinityRaider/AgriCraft#197]
Define different types of soils per crop, strenght stat should now also define where a plant can grow (#158).
Plant growth rate will be determined by the soil (#84) s well as the growth stat.
Also allow more than one required baseblock (#147)

**Comment by WolfieWaffle** [comment]
Would this include support for Biomes' O Plenty Loamy/Silty/Sandy grass support?

**Comment by InfinityRaider** [comment]
Not by default but you'll be able to register them as valid universal soils or per crop.

**Comment by hron84** [comment]
Will this allow use oredictionary ores as a baseblock? In 1.4 alpha, only one block taken (or, at least, only one ore revealed in NEI).

**Comment by InfinityRaider** [comment]
Oredictionary should already work for ores

**Comment by hron84** [comment]
@InfinityRaider it depends on what do you mean under "work". I can imagine it can work for seeds (e.g., seeds can recognize oredictionary ores), but NEI shows me only one ore as a base block. Maybe it is a NEI issue, I dunno.

**Comment by InfinityRaider** [comment]
NEI shows only one ore yes, but any ore will work.

**Comment by hron84** [comment]
Ahh, I see, thanks.

**Comment by RlonRyan** [comment]
We can probably set the base block check to perform on the placement of the crops, and on calls of the onNeighbor changed method, for best performance.

Also it would be cool to add water as a baseblock to grow things like lily pads and squid plant from pneumatic craft.

**Comment by InfinityRaider** [comment]
OnNeighbour changed is only called on the neighbours, so can't use that.
PneumaticCraft plants are supported, but I contacted MineMaarten and he said the plants will dissappear.

**Comment by Maelstraz** [comment]
How about to make higher Strength stat allowing plant to ignore some requirements?
Not only farm/soil quality, but also some things like required blocks, required light level, etc, etc, etc.

It also can be used as bonus to mutation/crossbreed bonus chances.

**Comment by InfinityRaider** [comment]
Well it won't be that crop that soil anymore, it will be that crop, that soiltype (humidity, nutrient contents and acidity), higher strength will increase the range.
At least that's the plan...

**Comment by Maelstraz** [comment]
But then we need not only soil-type requirements but also soil-type bonuses to have a reason to even use it, imo. Because, you know, who even care about choise with no benefits? Like "why should i use to harder soil, if default one is working fine?". 

Or, if there is dead planet theme in the modpack, "I only have bad soil to use, how to deal with it?". Will there be fertilizers or smtn? Well, just like in IC origin: grass/bug killer, soil enricher, water cells etc, etc, etc.

**Comment by hron84** [comment]
Slightly connected to this, we will need some anti-weed technique since fighting with weed is quite hard when you just breed the plants. Maybe some craftable soil has tend spawn less weed than normal dirt or other stuff.
