### ISSUE TITLE
No strawberry seeds mutation

### ISSUE THREAD

**Issue by Timeslice42** [InfinityRaider/AgriCraft#206]
When generating the default mutations file, harvestcraft strawberry seeds do not have a mutation making a large branch of seeds unreachable.

What did you intend the mutation to be? (So I can add it in myself in the mean time)

**Comment by InfinityRaider** [comment]
Weird, It should be radish + poppy. Can you regenerate the mutations and see if it is there or not?

**Comment by Timeslice42** [comment]
I already did that twice. I'll go ahead and add that manually. It would be helpful to know if anyone else is or isn't having this problem.

**Comment by InfinityRaider** [comment]
Is there no line at all adding strawberry mutation or is it errorring reading the mutations?

**Comment by Timeslice42** [comment]
No errors. Everything else generates (AFAICT), just no strawberries.

**Comment by InfinityRaider** [comment]
But its right there:https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/utility/IOHelper.java#L309

wtf

**Comment by Timeslice42** [comment]
WTF indeed.
I added it manually copying and pasting it right as you have it in the code, and it works fine (without the newline character, of course). Just to be triple sure I deleted the mutations file and regenerated it. No strawberries. This is with AgriCraft-1.7.10-1.3.1

If you can confirm other people are *not* having this problem, then I'm cool with you just closing it.

**Comment by WolfieWaffle** [comment]
IIRC, I did not have the mutation as well. I just added the seed to the grass drop list.

**Comment by InfinityRaider** [comment]
Apparently this was something I looked over and fixed just after the latest release, I actually forgot this was already fixed, rendering this issue irrelevant.

**Comment by Timeslice42** [comment]
Well, that explains it then :)
