### ISSUE TITLE
hand rake

### ISSUE THREAD

**Issue by bookerthegeek** [InfinityRaider/AgriCraft#207]
Would it be possible to always have the hand rake craftable, even with seeds turned off. This would allow clients who play on multiple servers to not have to have another instance to play on server with seeds enabled or not enabled.

**Comment by InfinityRaider** [comment]
That's a valid suggestion but I won't do it. The rake will also have the function to remove a plant from crop sticks without destroying the crop sticks, so the rake will be there regardless of weeds being enabled/disabled :D
