### ISSUE TITLE
Biomes O' Plenty Support

### ISSUE THREAD

**Issue by WolfieWaffle** [InfinityRaider/AgriCraft#210]
Basically support for the different types of soil it has and the turnip crop. Not super high priority, but would be nice. You would be able to grow crops on the different soil types and be able to grow the turnips. (maybe the toadstools and berry bushes too)

**Comment by InfinityRaider** [comment]
ill have a look at it

**Comment by ate0ate** [comment]
I don't know how possible this would be yet. I'm pretty sure that the new BoP soil types are unfinished and currently cannot even be tilled. They just recently patched them to allow for mob spawning and torch/bed placement. Would be great in the future though!

**Comment by WolfieWaffle** [comment]
IIRC, in the most recent 1.7.10 version, they can be tilled. I tried
putting crops on them but they wouldn't. Mostly, I just would like to be
able to grow turnips :P

**Comment by ate0ate** [comment]
Testing the latest BoP for 1.7.10, build 1283, and sadly the new soil variants, loamy, sandy, and silty, still cannot be tilled. Grass finally does spread to bare blocks and mobs can spawn on them, but no tilling and sheep cannot eat them. I don't know if the soil types can be implemented as they are now, but I most certainly agree that turnips would be a nice little addition.

**Comment by InfinityRaider** [comment]
Soils can be registered already regardless if they are tilled or not.

**Comment by WolfieWaffle** [comment]
Thanks!

**Comment by InfinityRaider** [comment]
Builds are done automatically and then discarded, unless I tell them to push to GitHub releases or CurseForge

**Comment by WolfieWaffle** [comment]
So I couldn't get any sort of snapshot build? It's fine If I can't I'm not
trying to pressure you into updating or anything :P I just know
IguanaTweaks has a place to download the latest build, and was wondering if
Agricraft had something similar.

**Comment by InfinityRaider** [comment]
I'm not compiling somethign half done, if you can't wait noone will stop you from compiling it yourself.

**Comment by WolfieWaffle** [comment]
I know, I understand why you wouldn't. I'm not trying to make you compile
builds for me, I just couldn't get my own compilation to work, so I was
just wondering if there was already a build that someone made, not telling
you to make one or anything.
