### ISSUE TITLE
Botania Alternate Textures Support

### ISSUE THREAD

**Issue by WolfieWaffle** [InfinityRaider/AgriCraft#211]
Botania has a config option to use alternate textures, which I personally prefer. However, the Botania crops in Agricraft still use the default textures. My request would be to obey this config option in Botania, but I'm unsure if it's possible to access another mods config file. Either way, it would be nice to see.

I realize that the crops would require growing textures as well, so somebody would need to create them. If the developer wants, I could attempt to create the textures for the growth stages if they don't want to. I'm no professional, but I'm not too bad, and I think I could make some textures for it.

This isn't a huge issue, but for people who use the alternate Botania textures, it would be nice.

**Comment by InfinityRaider** [comment]
I suck at textures and I don't like doing it, so if you could provide me with them, I can have a look at it.

**Comment by WolfieWaffle** [comment]
Ok, I'll start on them.

**Comment by WolfieWaffle** [comment]
OK, I almost forgot I made this request, but I finally finished the textures. I don't know how to make a pull request since I don't know how to set up agricraft in eclipse, so I'll just put them here.

![cropbotaniabrown1](https://cloud.githubusercontent.com/assets/8770485/7823013/75ff00e4-03b6-11e5-8964-aeed09d19013.png)
![cropbotaniabrown2](https://cloud.githubusercontent.com/assets/8770485/7823017/7604c326-03b6-11e5-87e8-21a1fbee9dd4.png)
![cropbotaniabrown3](https://cloud.githubusercontent.com/assets/8770485/7823014/760184f4-03b6-11e5-82eb-b7ed2674412c.png)
![cropbotaniabrown4](https://cloud.githubusercontent.com/assets/8770485/7823015/760286c4-03b6-11e5-9b02-f9139e713f1e.png)
![cropbotaniacyan1](https://cloud.githubusercontent.com/assets/8770485/7823016/7602f438-03b6-11e5-9682-727cf5b66fa2.png)
![cropbotaniacyan2](https://cloud.githubusercontent.com/assets/8770485/7823019/760f7046-03b6-11e5-8a84-cf64c52047b7.png)
![cropbotaniacyan3](https://cloud.githubusercontent.com/assets/8770485/7823018/760f5aca-03b6-11e5-9b7f-f41b01143882.png)
![cropbotaniacyan4](https://cloud.githubusercontent.com/assets/8770485/7823020/76120216-03b6-11e5-9892-9b0aed3ebad4.png)
![cropbotaniagray1](https://cloud.githubusercontent.com/assets/8770485/7823021/7612b030-03b6-11e5-8386-1a2021c7c8a8.png)
![cropbotaniagray2](https://cloud.githubusercontent.com/assets/8770485/7823022/76148112-03b6-11e5-9b78-f9402cb14d35.png)
![cropbotaniagray3](https://cloud.githubusercontent.com/assets/8770485/7823023/76164f6a-03b6-11e5-98bf-ff375538c4e2.png)
![cropbotaniagray4](https://cloud.githubusercontent.com/assets/8770485/7823024/7620701c-03b6-11e5-95de-34eb5c2a1ec9.png)
![cropbotaniagreen1](https://cloud.githubusercontent.com/assets/8770485/7823025/7620f7e4-03b6-11e5-8df2-1a02bd586a1e.png)
![cropbotaniagreen2](https://cloud.githubusercontent.com/assets/8770485/7823027/7622b99e-03b6-11e5-8fc9-7b447630ab7d.png)
![cropbotaniagreen3](https://cloud.githubusercontent.com/assets/8770485/7823026/76229036-03b6-11e5-8f62-a42fa86450c5.png)
![cropbotaniagreen4](https://cloud.githubusercontent.com/assets/8770485/7823028/76253282-03b6-11e5-932a-3e6fc42eb027.png)
![cropbotanialightblue1](https://cloud.githubusercontent.com/assets/8770485/7823029/7625d4d0-03b6-11e5-995e-491ccb4105b9.png)
![cropbotanialightblue2](https://cloud.githubusercontent.com/assets/8770485/7823030/762f9376-03b6-11e5-8c91-02a3b0b65615.png)
![cropbotanialightblue3](https://cloud.githubusercontent.com/assets/8770485/7823031/7631236c-03b6-11e5-89b4-2919f65acacd.png)
![cropbotanialightblue4](https://cloud.githubusercontent.com/assets/8770485/7823032/76312bb4-03b6-11e5-827d-03e63710438a.png)
![cropbotanialightgray1](https://cloud.githubusercontent.com/assets/8770485/7823034/7634ebaa-03b6-11e5-8cc9-a2b53b11e4c5.png)
![cropbotanialightgray2](https://cloud.githubusercontent.com/assets/8770485/7823035/7635edc0-03b6-11e5-9285-08fb2cf14a3d.png)
![cropbotanialightgray3](https://cloud.githubusercontent.com/assets/8770485/7823033/76347080-03b6-11e5-8e99-c531f0980b28.png)
![cropbotanialightgray4](https://cloud.githubusercontent.com/assets/8770485/7823036/7640a602-03b6-11e5-8f89-a984ff3254db.png)
![cropbotanialime1](https://cloud.githubusercontent.com/assets/8770485/7823039/7642f36c-03b6-11e5-81ec-41acf3864534.png)
![cropbotanialime2](https://cloud.githubusercontent.com/assets/8770485/7823038/7642c054-03b6-11e5-8d8e-50341483efa2.png)
![cropbotanialime3](https://cloud.githubusercontent.com/assets/8770485/7823037/7642c8a6-03b6-11e5-981f-608c17163b68.png)
![cropbotanialime4](https://cloud.githubusercontent.com/assets/8770485/7823040/7644cbce-03b6-11e5-9ddb-39789dc925f0.png)
![cropbotaniamagenta1](https://cloud.githubusercontent.com/assets/8770485/7823041/7646b358-03b6-11e5-8cba-51a79c3ca627.png)
![cropbotaniamagenta2](https://cloud.githubusercontent.com/assets/8770485/7823042/76501010-03b6-11e5-82bc-efd4d945de7d.png)
![cropbotaniamagenta3](https://cloud.githubusercontent.com/assets/8770485/7823043/765313dc-03b6-11e5-8fc7-b39b6578bf2d.png)
![cropbotaniamagenta4](https://cloud.githubusercontent.com/assets/8770485/7823044/7653ddda-03b6-11e5-9902-5366fbcdf42c.png)
![cropbotaniaorange1](https://cloud.githubusercontent.com/assets/8770485/7823045/7653fbe4-03b6-11e5-9967-29601c74c624.png)
![cropbotaniaorange2](https://cloud.githubusercontent.com/assets/8770485/7823046/76544c02-03b6-11e5-8c8a-1b89e841d1af.png)
![cropbotaniaorange3](https://cloud.githubusercontent.com/assets/8770485/7823047/7655bf06-03b6-11e5-9b1f-b24ef6ec1087.png)
![cropbotaniaorange4](https://cloud.githubusercontent.com/assets/8770485/7823048/765f13c6-03b6-11e5-85b6-0ad9f5fef801.png)
![cropbotaniapink1](https://cloud.githubusercontent.com/assets/8770485/7823049/76640818-03b6-11e5-99ac-20b5615d56a7.png)
![cropbotaniapink2](https://cloud.githubusercontent.com/assets/8770485/7823051/7665e5d4-03b6-11e5-85ce-3b5b6764acbd.png)
![cropbotaniapink3](https://cloud.githubusercontent.com/assets/8770485/7823050/7665f632-03b6-11e5-9120-5aa74805c22b.png)
![cropbotaniapink4](https://cloud.githubusercontent.com/assets/8770485/7823052/766606ea-03b6-11e5-9b3d-8af929b681ac.png)
![cropbotaniapurple1](https://cloud.githubusercontent.com/assets/8770485/7823053/766b78e6-03b6-11e5-8ab0-ab5ce1af4da2.png)
![cropbotaniapurple2](https://cloud.githubusercontent.com/assets/8770485/7823054/766f829c-03b6-11e5-84a3-7d0468536719.png)
![cropbotaniapurple3](https://cloud.githubusercontent.com/assets/8770485/7823055/7674a95c-03b6-11e5-999c-4d62256767c9.png)
![cropbotaniapurple4](https://cloud.githubusercontent.com/assets/8770485/7823056/7677382a-03b6-11e5-9348-51ea1c6ad2d5.png)
![cropbotaniared1](https://cloud.githubusercontent.com/assets/8770485/7823057/76790b46-03b6-11e5-8b4b-b6ba40c08af3.png)
![cropbotaniared2](https://cloud.githubusercontent.com/assets/8770485/7823058/767af44c-03b6-11e5-96d8-6495eb21e506.png)
![cropbotaniared3](https://cloud.githubusercontent.com/assets/8770485/7823059/767bb2b0-03b6-11e5-8b3d-aaac56d6b1be.png)
![cropbotaniared4](https://cloud.githubusercontent.com/assets/8770485/7823060/767d1e5c-03b6-11e5-8c2f-9be128f7af86.png)
![cropbotaniawhite1](https://cloud.githubusercontent.com/assets/8770485/7823061/76845a32-03b6-11e5-8fc4-479ed78c1bbd.png)
![cropbotaniawhite2](https://cloud.githubusercontent.com/assets/8770485/7823062/76881ba4-03b6-11e5-8522-c93f68879f37.png)
![cropbotaniawhite3](https://cloud.githubusercontent.com/assets/8770485/7823066/768d99e4-03b6-11e5-8167-670f46b33077.png)
![cropbotaniawhite4](https://cloud.githubusercontent.com/assets/8770485/7823064/768cf5c0-03b6-11e5-825a-ab93e4e572d3.png)
![cropbotaniayellow1](https://cloud.githubusercontent.com/assets/8770485/7823065/768d8710-03b6-11e5-91e9-26313155e6b0.png)
![cropbotaniayellow2](https://cloud.githubusercontent.com/assets/8770485/7823063/768cacfa-03b6-11e5-965b-00b8b48c1d89.png)
![cropbotaniayellow3](https://cloud.githubusercontent.com/assets/8770485/7823067/7692cf4a-03b6-11e5-8bd8-31551d292627.png)
![cropbotaniayellow4](https://cloud.githubusercontent.com/assets/8770485/7823068/769ada3c-03b6-11e5-951a-1d19e08de2a4.png)
![cropbotaniablack1](https://cloud.githubusercontent.com/assets/8770485/7823069/769c9aac-03b6-11e5-9463-0749c368e7e4.png)
![cropbotaniablack2](https://cloud.githubusercontent.com/assets/8770485/7823072/769e4320-03b6-11e5-8b60-f52fd98f5737.png)
![cropbotaniablack3](https://cloud.githubusercontent.com/assets/8770485/7823070/769d968c-03b6-11e5-9946-a52be299f103.png)
![cropbotaniablack4](https://cloud.githubusercontent.com/assets/8770485/7823071/769dfca8-03b6-11e5-9ef1-e9dba49a1974.png)
![cropbotaniablue1](https://cloud.githubusercontent.com/assets/8770485/7823073/76a663c0-03b6-11e5-959e-0334e0eb8844.png)
![cropbotaniablue2](https://cloud.githubusercontent.com/assets/8770485/7823074/76aacdd4-03b6-11e5-90e2-47242277bfa0.png)
![cropbotaniablue3](https://cloud.githubusercontent.com/assets/8770485/7823075/76ac3322-03b6-11e5-8d99-403a817c9e81.png)
![cropbotaniablue4](https://cloud.githubusercontent.com/assets/8770485/7823012/75fec8e0-03b6-11e5-888c-c469d1faa5e9.png)

**Comment by InfinityRaider** [comment]
You're making this difficult for me :p

To make a pull request, first fork this repo (first switch to the croprewrite branch please) by pressing the "fork" button. Then clone that newly forked repo into the desktop, throw those new textures into the assets/textures/blocks folder and call them something like CropBotaniaBlueAlternate1 and so on.
Then push the changes to your repo and then you can create a pull request.

**Comment by WolfieWaffle** [comment]
OK, sorry ._. I have tried making a pull request, and HOPEFULLY I didn't mess anything up, since this is my first time using git.

**Comment by InfinityRaider** [comment]
You did fine, thanks

**Comment by WolfieWaffle** [comment]
your welcome, I'm glad it worked
