### ISSUE TITLE
Growth Rate Config

### ISSUE THREAD

**Issue by WolfieWaffle** [InfinityRaider/AgriCraft#212]
I would like a config option that is essentially a global modifier on all plant growth speed. Basically if it was set to 0.5, crops would take twice as long to grow.

I'm not a modder, but I have some basic knowledge of code, and I imagine that you could just use a variable that is multiplied to the chance each tick for a plant to grow or something.

Anyways, It would help for hardcore packs, IMHO. I think it's always good to have more configuration options.

**Comment by InfinityRaider** [comment]
Seems reasonable

**Comment by Timeslice42** [comment]
In the meantime Hunger Overhaul provides this functionality. InfinityRaider said he thinks it should work, but he hasn't tested it.

**Comment by WolfieWaffle** [comment]
I don't feel like it works, that's why I created this issue. I have HO
installed, and it seems to grow at the regular rate.
