### ISSUE TITLE
Allow exceptions to disabled vanilla farming

### ISSUE THREAD

**Issue by Timeslice42** [InfinityRaider/AgriCraft#213]
Not to be confused with mandrakes: https://sites.google.com/site/witcherymod/minedrake

In the meantime I will have to create a crafting recipe for my modpack, but this seems like a good argument for having a vanilla planting whitelist added to the config for when vanilla planting is disabled.

**Comment by InfinityRaider** [comment]
I see, you can't plant mandrakes to create the minedrakes, took me a while to figure that out.
But yes a list with exceptions would be possible.

**Comment by Timeslice42** [comment]
Dangit... it seems I forgot a sentance when I created this issue. Sorry about that. Glad you figured it out anyways.

**Comment by InfinityRaider** [comment]
I don't remember if its in the previous release or not, but I certainly added code to allow plants on the blacklist to be planted outside of crop sticks if vanilla farming is disabled.
Can you check if that is the case please? If so feel free to close this and if not I'll check if it works in the code I have right now.

**Comment by InfinityRaider** [comment]
The code was there, but there was a derp in it, which I have now fixed.

**Comment by Timeslice42** [comment]
Cool, thanks. When do you think the next release will be?

**Comment by Timeslice42** [comment]
Also, can you reopen this? What I'd really like is to be able to breed and harvest the witchery crops using agricraft, but be able to plant them without cropsticks whenever they are needed for (witchery) mutation purposes.

**Comment by Timeslice42** [comment]
Thank you.
