### ISSUE TITLE
bug or feature with bone meal

### ISSUE THREAD

**Issue by DirkSch** [InfinityRaider/AgriCraft#215]
In the version AgriCraft-1.7.10-1.3.1 can not all plants grow up with bone meal. I have test it with nitor wart spore, aurigold and ferranium. 
redstodendron, lapender and petinia ist grow up with bone meal. all other not tested by me.
please can you make a option in config file or fix this, if it's a bug.

**Comment by InfinityRaider** [comment]
Only tier 1-3 can be bonemealed
