### ISSUE TITLE
Shearing some crops drops the flower

### ISSUE THREAD

**Issue by WolfieWaffle** [InfinityRaider/AgriCraft#219]
Basically instead of dropping red dye, it would allow you to drop roses instead. Or botania flowers rather than botania petals. Like how it is with cactus.

This would be nice, since I was exited when I saw you could farm flowers, but disappointed when you could only farm the dyes they produce.

**Comment by InfinityRaider** [comment]
I was going to add for some crops that if you shear them it would have a chance to drop 0-2 flowers, but apparently there isn't an issue open for that here, so Ill leave this open for it
