### ISSUE TITLE
Horn of the Wild (Botania) Compatibility

### ISSUE THREAD

**Issue by Croebh** [InfinityRaider/AgriCraft#220]
Currently using the Horn of the Wild from Botania (r191) anywhere near AgriCraft (1.3.1) crops causes all of the crops to be harvested AND drop the seed. This causes you to have to replant all your crops.

**Comment by InfinityRaider** [comment]
This is completely intended, if I'm not mistaken the Horn of the Wild uproots all nearby plants, before it would also remove the cropsticks, so I made it so the plant is removed but the crop sticks stay.
