### ISSUE TITLE
Enabling resource crops on server causes client connection issues

### ISSUE THREAD

**Issue by Feone** [InfinityRaider/AgriCraft#221]
Clients with resource crops disabled can't connect to servers where these crops are enabled due to missing block ID's. This makes it extremely impractical to enable these crops on servers if it isn't in a modpack that enables them by default.

**Comment by InfinityRaider** [comment]
There is nothing I can do about that, items are registered during startup, so I can't get the config from the server, because when you are connecting to the server the game is already running.
