### ISSUE TITLE
IndexOutOfBoundsException on server startup (possibly Minefactory Reloaded)

### ISSUE THREAD

**Issue by stardustrider** [InfinityRaider/AgriCraft#224]
I'm using a build from the latest commit, and I'm getting the following when I try to start my server. The client seems to be perfectly fine.

http://pastebin.com/Ut6hQMSS

Forge: 10.13.4.1448

**Comment by InfinityRaider** [comment]
Did you remove the fruits of a crop with minetweaker?
I'll add in a check so this doesn't happen anymore.

**Comment by stardustrider** [comment]
I'm using Minetweaker for stuff, but I've not used it to change Agricraft in any way. It's weird.

I hadn't updated any mods in a while, so I did a bit of a huge wave, and this is what I was presented with.

**Comment by InfinityRaider** [comment]
Well something has been messing with the products of one of my crops and hasn't done it correctly, In my code I'm assuming a crop will always have a fruit, so I didn't put a check, however I should have, and will add it.
For now I suggest you mcedit out your mfr harvester so you can play in the meantime.

**Comment by stardustrider** [comment]
Yea, I'm thinking that might be needed, as I've getting a ticking block entity crash with the fix. Still, thank you!

**Comment by InfinityRaider** [comment]
You compiled it yourself I presume, and where is it crashing now?

**Comment by stardustrider** [comment]
Yea. Almost the same error as before: http://pastebin.com/5MCZ7nsF

Still putting the MFR Harvester as the problem.

**Comment by InfinityRaider** [comment]
This should do it, we'll find out soon
