### ISSUE TITLE
Resource crops wont spread

### ISSUE THREAD

**Issue by l2edeyejedi** [InfinityRaider/AgriCraft#225]
There is a post on /r/feedthebeast. I cannot for the life of me get resource crops to spread to cross crops. Here's a video explanation. Im playing the infinity pack.http://www.reddit.com/r/feedthebeast/comments/39lxh4/blah_agricraft_help_me_plz/

**Comment by InfinityRaider** [comment]
Thats weird, can you check the config to see what the mutation chance is set to?

**Comment by l2edeyejedi** [comment]
I can tell you from memory. 1.0. I reset it to hurry along the process.

Sent from Yahoo Mail on Android

**Comment by InfinityRaider** [comment]
Yea, that chance is to determine what happens if a spread is triggered. so now you will have 100% chance for a mutation and 0% chance for spreading.

**Comment by l2edeyejedi** [comment]
So if I turn that down it will fix it. Awesome thanks. Maybe post
Something to the reddit so if anyone else has the issue it wont show up on your tracker again

Sent from Yahoo Mail on Androi

**Comment by InfinityRaider** [comment]
I don't have a reddit account, and I don't plan to make one, I have added a more detailed description in the config for that setting though.
