### ISSUE TITLE
Missing Optionals for alchemicalWizardry.[...].IHarvestHandler

### ISSUE THREAD

**Issue by asiekierka** [InfinityRaider/AgriCraft#226]

**Comment by InfinityRaider** [comment]
I don't understand what you mean by that, sorry.

**Comment by asiekierka** [comment]
You need to add an @Optional.Interface for IHarvestHandler in the class you're loading (or not load that class), otherwise the mod will crash if the IHarvestHandler class from AlchemicalWizardry (whatever that is!?) is not present. Like it did for me.

**Comment by InfinityRaider** [comment]
But it is there though:
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/compatibility/bloodmagic/BloodMagicHarvesthandler.java#L10

**Comment by InfinityRaider** [comment]
I think it crashes when the BloodMagicHelper class is loaded (https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/compatibility/bloodmagic/BloodMagicHelper.java#L18)  to find out if its methods should be called, thusly I have replaced the direct referencing with reflection, should fix the problem. Feel free to reopen this if it persists.

**Comment by asiekierka** [comment]
Thanks a lot. I am fiddling with AgriCraft 1.4 for my pack and am excited for the improvements! \o/

**Comment by InfinityRaider** [comment]
Yes the improvements I've been working on were more than necessary
