### ISSUE TITLE
no nether wart info + incapability of mutating to red mushroom 

### ISSUE THREAD

**Issue by reddler97** [InfinityRaider/AgriCraft#227]
i noticed that there is no information on nether wart in the book, i found this out because i was not able to get red mushroom seeds from the mutation of nether wart and poppy seeds, it shows the mutation in NEI but i suspect that it is because of the lighting differences of the poppy wanting  light while nether wart wants darkness. i can easily place a torch (x) blocks away if i knew what light level and below nether wart needed, so i went to check the book for the exact light level and noticed that there was no information 

If you want me to start a separate issue for each i can, right now i am just telling my story (playing on Agrarian Skies 2 by the way)

**Comment by InfinityRaider** [comment]
Light level is never shown in the book. If you need to breed crops with different light requirements, first grow the first one in darkness until mature. Then grow the other one in brightness and then set the condition to the crop you want.

**Comment by reddler97** [comment]
I thought i tried that, but ok

**Comment by InfinityRaider** [comment]
What do you mean?

**Comment by Timeslice42** [comment]
He's saying that netherwart, which is a vanilla plant, has no flavor text/description in the journal, unlike most (all?) other vanilla plants.

**Comment by InfinityRaider** [comment]
Ah a description text, well I'll fix that then

**Comment by InfinityRaider** [comment]
Apparently I added a description a while ago.
