### ISSUE TITLE
Crash with plantmegapack mod version 4.23

### ISSUE THREAD

**Issue by EBrarian** [InfinityRaider/AgriCraft#228]
When AgriCraft-1.7.10-1.3.1 is used in conjunction with the plantmegpack mod version 4.23 for 1.7.10, the following crash occurs :

Caused by: java.lang.NoSuchFieldError: seedBeet
	at com.InfinityRaider.AgriCraft.reference.SeedInformation.init(SeedInformation.java:91)

see also :

http://pastebin.com/UpV9BkuF

Not sure which mod is at fault though...

**Comment by InfinityRaider** [comment]
Has been fixed long time ago, either rollback pmp or wait for my new release
