### ISSUE TITLE
Issues using agricraft seeds in the Phytogenic Insulator from Thermal Expansion

### ISSUE THREAD

**Issue by BBoldt** [InfinityRaider/AgriCraft#229]
Basically, all the seed to crop recipes show up in NEI as working for the Phytogenic Insulator, but it actually only works with seeds that have no metadata or growth information.

I'm not sure that agricraft plants are meant to be used in that machine in the first place, but like I said, the recipes show up in NEI. May want to look into either adding full compatibility or preventing those recipes from showing up.

**Comment by InfinityRaider** [comment]
I think it'll only work with seeds that don't have NBT (stats), I'll have a look at the TE API if there is something there I could use.

**Comment by InfinityRaider** [comment]
Small update: I got in touch with KingLemming and there he would look into adding an option to ignore the NBT tag of the input stack and transfer it to the output stack.

**Comment by BBoldt** [comment]
sweet

**Comment by kane-thornwyrd** [comment]
Thank you ! :)

**Comment by Divran** [comment]
Hey, any updates on this?

**Comment by InfinityRaider** [comment]
Does it? I contactedKingLemming ages ago and apparently he implemented this, don't thank me, thank him.
Anyway I'm going to close this then.

**Comment by Divran** [comment]
Well, it doesn't copy the stats over, but at least it can use seeds with metadata, and that's all I needed.

**Comment by InfinityRaider** [comment]
Oh
