### ISSUE TITLE
blazingdaisy seeds

### ISSUE THREAD

**Issue by djlazz3** [InfinityRaider/AgriCraft#230]
Hi, im using the agrarian skies 2 modpack and i noticed that it is almost impossible to breed blazing daisy seeds and i say almost but that is because i am uncertain if it is or is not possible.
the reason i say this is because to grow netherwart you need to put it in a block with low brightness and  to grow the orange dye flowers in regular brightness but not in darkness so you can only have either the netherwart with the ability to breed or the orange dye flower with the ability to breed at any given time. So what ends up happening is that it will make a copy of the one that can breed as if the other plant was not there.

**Comment by InfinityRaider** [comment]
It doesn't matter if the parents can grow or not, as long as they are mature its fine. Mature the first one in its conditions, then mature the second one in its conditions and then apply the conditions for the mutation.

**Comment by djlazz3** [comment]
thank you i was going nuts trying to make that work but i actually had to do nothing
