### ISSUE TITLE
Plant doesn't drop its products

### ISSUE THREAD

**Issue by accessdenied0** [InfinityRaider/AgriCraft#233]
Dear AgriCraft-Team,

I got with this mod in the past time an issue with crops. Every-time I try to harvest (with right-click) the full growing plant, I got nothing back and my console put this error out: http://puu.sh/itZEx/4ce53f4542.png. (I want to point out I play on SSP)

I'm not sure where this issue is caused from, but I got a similar issue with https://github.com/Ellpeck/ActuallyAdditions/issues/6, which is fixed now.

hopefully you can help me here, too,

access_denied

**Comment by InfinityRaider** [comment]
Is it happening for every crop or only for specific plants?

**Comment by accessdenied0** [comment]
Every. At least in the "crops-sticks"...

**Comment by InfinityRaider** [comment]
The only reason I can think of is that there must be another mod in your istance that meddles with harvesting.

**Comment by accessdenied0** [comment]
I searched already for a config option and a mod which allowed "right-click" harvesting and disabled them. It didn't solved the problem. I have here my mod-list:  http://pastebin.com/c0dvfBTq maybe it helps a bit.

**Comment by porteriscool** [comment]
Im having the same problem, I grow my crop to have a growth percentage of 100, and I harvest the crop with both something in my hands, and with nothing in my hands, and I don't get the harvest of the crop at all.

**Comment by InfinityRaider** [comment]
Can you both list all the mods in your instances?

**Comment by porteriscool** [comment]
Mod | Version
------------ | -------------
AE2 Stuff | (v. 0.4.038)
AgriCraft | (v. 1.4.0-alpha)
Applied Energistics 2 | (v. rv3-alpha-pr1619)
Ars Magica 2 | (v. 1.4.0.008)
BD Lib | (v. 1.8.2.92)
BiblioCraft | (v. 1.10.4)
Big Reactors | (v. 0.4.3A)
Binnie Core | (v. 2.0-pre12)
Blood Magic | (v. 1.3.0Beta)
Blue Power | (v. 0.2.947)
Botania | (v. r1.6-190)
Carpenter's Blocks | (v. 3.3.7)
ChickenChunks | (v. 1.3.4.19)
Chisel 2 | (v. 2.4.0.122)
CodeChickenCore | (v. 1.0.6.43)
CoFH Core | (v. 3.0.2)
ComputerCraft | (v. 1.73)
Cookie Core | (v. 1.3.1-7)
Dense Ores | (v. 1.6.2)
Doors | (v. 4.0.1)
EE3 Helper | (v. 2.2a)
Ender IO | (v. 2.3.0.388_beta)
EnderStorage | (v. 1.4.7.36)
Equivalent Exchange 3 | (v. 0.3.507)
Extra Utilities | (v. 1.2.6)
Forbidden Magic | (v. 0.562)
Forestry in Minecraft | (v. 3.5.4.13)
Forge Multipart | (v. 1.2.0.344)
Funky Locomotion | (v. beta-5c)
GenDustry | (v. 1.4.12.92)
Industrial Craft 2 | (v. 2.2.736-experimental)
iChunUtil | (v. 4.2.2)
Iguana Tinker Tweaks | (v. 2.1.5)
Immersive Engineering | (v. 0.2.3)
In-Game wiki Mod | (v. 1.1.3-18)
Inventory Tweaks | (v. 1.58-147-645ca10)
Iron Chest | (v. 6.0.62.742)
JABBA | (v. 1.2.1a)
Journey Map | (v. 5.0.1)
Magic Bees | (v. 2.1.22)
Magical Crops | (v. 4.0.0_PUBLIC_BETA3)
Malisis' Doors | (v. 1.7)
MalisisCore | (v. 0.11.4)
Mantle | (v. 0.3.2.jenkins184)
MineFactory Reloaded | (v. 2.8.0)
MineTweaker 3 | (v. 3.0.9C)
ModTweaker 2 | (v. 0.8.1)
Morph | (v. 0.9.1)
Mystcraft | (v. 0.11.7.01)
NEI Addons | (v. 1.12.7.21)
NEI Integration | (v. 1.0.9)
Nether Ores | (v. 2.3.0)
NotEnoughItems | (v. 1.0.4.106)
OpenBlocks | (v. 1.4.3)
OpenMods | (v. 0.7.3)
Portal Gun | (v. 4.0.0-beta-4)
Progressive Automation | (v. 1.6.16)
QmunityLib | (v. 0.1.107)
Railcraft | (v. 9.6.1.0)
Realistic World Gen | (v. alpha-1.3.2)
Simply Jetpacks | (v. 1.4.1)
Steve's Factory Manager | (v. A93)
Storage Drawers | (v. 1.4.6)
Thaumcraft | (v. 4.2.3.5)
Thaumic Exploration | (v. Pre 0.6.0b)
Thaumic Tinkerer | (v. 2.5-1.7.10-164)
Thermal Dynamics | (v. 1.0.0)
Thermal Expansion | (v. 4.0.1)
Thermal Foundation | (v. 1.0.0)
TiC Tooltips | (v. 1.2.4)
Tinkers' Construct | (v. 1.8.5)
Tinkers' Mechworks | (v. 0.2.14.100)
Tinkers' Steelworks | (v. 1.1.0-16)
Translocator | (v. 1.1.1.14)
Treecapitator | (v. 2.0.4)
Vein Miner | (v. 0.27.1)
Waila | (v. 1.5.10)
Witchery | (v. 0.24.1)
zCraftingManager | (v. 0.7.5)

**Comment by accessdenied0** [comment]
@InfinityRaider, 

Of course, I already did but here is the updated version: http://pastebin.com/JLeuHZ2c
(The old version: http://pastebin.com/c0dvfBTq) I changed and added some minor things, but the issue is still not solved...

anyway here I got it for you

access_denied

**Comment by InfinityRaider** [comment]
I can't reproduce this and honestly I have no idea why this is happening. Does it also happen in an instance with only agricraft?

**Comment by InfinityRaider** [comment]
I have managed to replicate the issue and will find out why its happening.
