### ISSUE TITLE
SMP crash on startup

### ISSUE THREAD

**Issue by iarspider** [InfinityRaider/AgriCraft#234]
Crash log: http://paste.ubuntu.com/11752481/
Latest version build from source (commit 7ddf59db9eb5cb3b2cd08b0a9daf4e784bf48ce9)

**Comment by iarspider** [comment]
Same spot as #223

**Comment by InfinityRaider** [comment]
There where some missing @SideOnly(Side.CLIENT) annotations in the PneumaticCraft class, I've created a PR to fix this, we'll see what MineMaarten has to say.

**Comment by InfinityRaider** [comment]
PR has been merged, you'll have to use the next version of PneumaticCraft
