### ISSUE TITLE
Water Tanks Don't Collect Rain From Corosauce's Local Weather & Storms Mod

### ISSUE THREAD

**Issue by UndeadZeratul** [InfinityRaider/AgriCraft#235]
http://www.coros.us/mods/weather2

Due to the way this mod overrides vanilla weather behavior, unless it is set to use vanilla's rain mechanic, the water tanks don't fill during the rain, as shown below.  Would it be possible to add a hook into this mod?  Thanks!

![Y u no fill](https://i.imgur.com/2xOsegs.png)

I'm currently using the following versions:
 - Forge 1448
 - Agricraft 1.3.1
 - CoroUtil 1.1.2
 - Weather 2.3.7

**Comment by InfinityRaider** [comment]
Small headsup: I looked at implementing this, however I didn't find a direct and easy way to do it, it might not be there, I might have overlooked it. In any case, I've sent a message to Corosus and I'm awaiting his reply.

**Comment by UndeadZeratul** [comment]
Hmm, I was hoping for an easy event hook, but I guess it's not so simple.  In the meantime, I can set his mod to use the vanilla weather, and it'll work as expected.

**Comment by RlonRyan** [comment]
This would take a separate mod interface and special case checks. I recommend against the addition of support for the mod, from a code simplicity standpoint (tanks are complicated enough).

Or, at least, push this way off, until we have a better codebase to work with.

**Comment by InfinityRaider** [comment]
Dedicated seperate addon mod would indeed be better, and because I still haven't had a reply from Corosus I'm not going to give much attention to this anymore, sorry.

**Comment by UndeadZeratul** [comment]
Ah, that's fine; I was hoping it'd be something simple like event hooks, but if it's not, no big deal.  Thanks for the effort!
