### ISSUE TITLE
Custom crop crash

### ISSUE THREAD

**Issue by medsal15** [InfinityRaider/AgriCraft#236]
Line of the crashing crop:
cobaltine,TConstruct:materials:28,soulsand,TConstruct:SearedBrick:1,5,6,Grows some cobalt around and creates a fruit.
What happened: I try to plant this crop on soulsand, it doesn't work. So I try with all soils, none work. Because of this, I decide to see which soil is required to plant the crop, I put the seed in the analyzer with the book, the seed is analyzed. I decide to open the book to see the soil and then:
---- Minecraft Crash Report ----
// You're mean.

Time: 24.06.15 15:50
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.InfinityRaider.AgriCraft.utility.RenderHelper.getBlockResource(RenderHelper.java:44)
	at com.InfinityRaider.AgriCraft.gui.GuiJournal.drawSeedTitle(GuiJournal.java:388)
	at com.InfinityRaider.AgriCraft.gui.GuiJournal.drawSeedPage(GuiJournal.java:303)
	at com.InfinityRaider.AgriCraft.gui.GuiJournal.func_73863_a(GuiJournal.java:159)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.InfinityRaider.AgriCraft.utility.RenderHelper.getBlockResource(RenderHelper.java:44)
	at com.InfinityRaider.AgriCraft.gui.GuiJournal.drawSeedTitle(GuiJournal.java:388)
	at com.InfinityRaider.AgriCraft.gui.GuiJournal.drawSeedPage(GuiJournal.java:303)
	at com.InfinityRaider.AgriCraft.gui.GuiJournal.func_73863_a(GuiJournal.java:159)

-- Screen render details --
Details:
	Screen name: com.InfinityRaider.AgriCraft.gui.GuiJournal
	Mouse location: Scaled: (329, 209). Absolute: (986, 139)
	Screen size: Scaled: (456, 256). Absolute: (1366, 768). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['medsal15'/162, l='MpServer', x=-485.83, y=5.62, z=114.17]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-492,4,111), Chunk: (at 4,0,15 in -31,6; contains blocks -496,0,96 to -481,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 90931 game time, 90931 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 48 total; [EntitySheep['Sheep'/29, l='MpServer', x=-544.09, y=4.00, z=163.09], EntityCow['Cow'/33, l='MpServer', x=-533.84, y=4.00, z=106.81], EntityPig['Pig'/34, l='MpServer', x=-535.69, y=4.00, z=118.81], EntityPig['Pig'/35, l='MpServer', x=-540.56, y=4.00, z=119.75], EntityPig['Pig'/36, l='MpServer', x=-536.88, y=4.00, z=119.13], EntityPig['Pig'/37, l='MpServer', x=-536.84, y=4.00, z=117.97], EntitySheep['Sheep'/38, l='MpServer', x=-533.97, y=4.00, z=117.69], EntitySheep['Sheep'/39, l='MpServer', x=-541.78, y=4.00, z=117.41], EntitySheep['Sheep'/40, l='MpServer', x=-534.22, y=4.00, z=116.06], EntityCow['Cow'/41, l='MpServer', x=-542.78, y=4.00, z=122.69], EntityCow['Cow'/42, l='MpServer', x=-531.50, y=4.00, z=159.50], EntityCow['Cow'/43, l='MpServer', x=-529.50, y=4.00, z=158.19], EntityPig['Pig'/44, l='MpServer', x=-531.22, y=4.00, z=165.22], EntityPig['Pig'/45, l='MpServer', x=-532.81, y=4.00, z=166.81], EntitySheep['Sheep'/46, l='MpServer', x=-534.50, y=4.00, z=166.50], EntitySheep['Sheep'/47, l='MpServer', x=-536.50, y=4.00, z=165.50], EntitySheep['Sheep'/48, l='MpServer', x=-536.50, y=4.00, z=169.50], EntityCow['Cow'/49, l='MpServer', x=-531.50, y=4.00, z=162.50], EntityItem['item.item.egg'/1015101, l='MpServer', x=-451.09, y=4.13, z=98.31], EntityItem['item.item.egg'/1149732, l='MpServer', x=-449.47, y=4.13, z=92.28], EntityCow['Cow'/63, l='MpServer', x=-527.78, y=4.00, z=125.75], EntityPig['Pig'/64, l='MpServer', x=-525.69, y=4.00, z=161.16], EntityPig['Pig'/65, l='MpServer', x=-522.03, y=4.00, z=175.06], EntityCow['Cow'/66, l='MpServer', x=-523.91, y=4.00, z=167.88], EntityChicken['Chicken'/72, l='MpServer', x=-499.50, y=4.00, z=37.50], EntityChicken['Chicken'/73, l='MpServer', x=-496.50, y=4.00, z=36.50], EntityItem['item.item.egg'/828869, l='MpServer', x=-448.66, y=4.13, z=99.41], EntitySheep['Sheep'/77, l='MpServer', x=-501.97, y=4.00, z=66.94], EntityCow['Cow'/78, l='MpServer', x=-494.25, y=4.00, z=66.31], EntityPig['Pig'/79, l='MpServer', x=-486.91, y=4.00, z=146.91], EntityChicken['Chicken'/83, l='MpServer', x=-479.53, y=4.00, z=70.56], EntityItem['item.item.egg'/1275968, l='MpServer', x=-479.13, y=4.13, z=71.72], EntityPig['Pig'/84, l='MpServer', x=-460.59, y=4.00, z=77.13], EntityChicken['Chicken'/85, l='MpServer', x=-449.56, y=4.00, z=91.56], EntityPig['Pig'/86, l='MpServer', x=-449.09, y=4.00, z=95.97], EntityPig['Pig'/87, l='MpServer', x=-463.31, y=4.00, z=81.13], EntityPig['Pig'/88, l='MpServer', x=-460.84, y=4.00, z=83.69], EntityPig['Pig'/90, l='MpServer', x=-449.16, y=4.00, z=99.44], EntitySheep['Sheep'/91, l='MpServer', x=-451.91, y=4.00, z=96.06], EntitySheep['Sheep'/92, l='MpServer', x=-451.72, y=4.00, z=100.63], EntityChicken['Chicken'/93, l='MpServer', x=-449.63, y=4.00, z=98.56], EntityPig['Pig'/94, l='MpServer', x=-450.75, y=4.00, z=103.09], EntityChicken['Chicken'/95, l='MpServer', x=-448.63, y=4.00, z=98.63], EntitySheep['Sheep'/97, l='MpServer', x=-451.97, y=4.00, z=104.22], EntityPig['Pig'/98, l='MpServer', x=-473.84, y=4.00, z=149.88], EntityChicken['Chicken'/99, l='MpServer', x=-445.63, y=4.00, z=108.41], EntityChicken['Chicken'/103, l='MpServer', x=-406.44, y=4.00, z=83.41], EntityClientPlayerMP['medsal15'/162, l='MpServer', x=-485.83, y=5.62, z=114.17]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 464916992 bytes (443 MB) / 1032286208 bytes (984 MB) up to 1223426048 bytes (1166 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmx1200M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1472 101 mods loaded, 101 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1472-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1472} [Minecraft Forge] (forge-1.7.10-10.13.4.1472-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	ExtraFixes{1.2.4b} [Extra Fixes] (minecraft.jar) 
	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.95} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.95-universal.jar) 
	UCHIJAAAA	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
	UCHIJAAAA	OpenModsCore{0.7.3} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	Trapcraft{v2.2.1a} [Trapcraft] ([1.7.10] Trapcraft - v2.3.0a.zip) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) 
	UCHIJAAAA	ActuallyAdditions{1.7.10-0.0.6.0} [Actually Additions] (ActuallyAdditions-1.7.10-0.0.6.0.jar) 
	UCHIJAAAA	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) 
	UCHIJAAAA	aobdbb{1.0.4} [Another One Bites The Dust: Berry Bushes] (AOBDBB-1.0.4.jar) 
	UCHIJAAAA	AquaTweaks{1.0} [AquaTweaks] (AquaTweaks-1.7.10-1.0.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	BetterSand{1.1(1.7.10)} [Better Sand] (BetterSand-1.1(1.7.10).jar) 
	UCHIJAAAA	betterstorage{0.13.1.126} [BetterStorage] (BetterStorage-1.7.10-0.13.1.126.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1351-universal.jar) 
	UCHIJAAAA	BuildCraft|Core{7.0.12} [BuildCraft] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.0.12} [BC Energy] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.0.12} [BC Factory] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.0.12} [BC Transport] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.0.12} [BC Builders] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.0.12} [BC Silicon] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.0.12} [BC Robotics] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	colourfulportalsmod{1.4.3} [Colourful Portals] (ColourfulPortals-1.4.3.jar) 
	UCHIJAAAA	cookiecore{1.3.1} [Cookie Core] (CookieCore-1.7.10-1.3.1-8.jar) 
	UCHIJAAAA	enderutilities{0.4.1} [Ender Utilities] (enderutilities-1.7.10-0.4.1.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) 
	UCHIJAAAA	evilcraft{0.8.6} [EvilCraft] (EvilCraft-1.7.10-0.8.6.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.6} [Extra Utilities] (extrautilities-1.2.6.jar) 
	UCHIJAAAA	farseek{1.0.8} [Farseek] (Farseek-1.0.8.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	fluxedcrystals{1.0.3} [Fluxed-Crystals] (fluxedCrystals-1.0.3.jar) 
	UCHIJAAAA	Forestry{3.7.0.606-unstable} [Forestry for Minecraft] (forestry_1.7.10-3.7.0.606-unstable.jar) 
	UCHIJAAAA	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) 
	UCHIJAAAA	foundry{1.0.0.0} [Foundry] (Foundry-1.7.10-1.0.0.0.jar) 
	UCHIJAAAA	ganysend{1.10.0} [Gany's End] (Ganys End-1.10.0.jar) 
	UCHIJAAAA	ganysnether{1.8.0} [Gany's Nether] (Ganys Nether-1.8.0.jar) 
	UCHIJAAAA	ganyssurface{1.11.1} [Gany's Surface] (Ganys Surface-1.11.1.jar) 
	UCHIJAAAA	headcrumbs{1.5.4} [Headcrumbs] (Headcrumbs-1.5.4.jar) 
	UCHIJAAAA	InventoryPets{1.1.2a} [Inventory Pets] (inventorypets-1.7.10-1.1.2a.jar) 
	UCHIJAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAA	levelup{0.10} [Level Up!] (LevelUp!-0.10(1.7.10).jar) 
	UCHIJAAAA	mcicraft{1.0.6c} [MCICraft] (mcicraft_core-1.0.6c_MC-1.7.10.jar) 
	UCHIJAAAA	mcicraft_farming{1.0.6c} [MCICraft Farming] (mcicraft_farming-1.0.6c_MC-1.7.10.jar) 
	UCHIJAAAA	mcicraft_machines{1.0.6c} [MCICraft Machines] (mcicraft_machines-1.0.6c_MC-1.7.10.jar) 
	UCHIJAAAA	mcicraft_redstone{1.0.6c} [MCICraft Redstone] (mcicraft_redstone-1.0.6c_MC-1.7.10.jar) 
	UCHIJAAAA	natureoverhaul{0.10.0} [Nature Overhaul] (NatureOverhaul-0.10.0(1.7.10).jar) 
	UCHIJAAAA	NEIAddons{1.12.9.32} [NEI Addons] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.9.32} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.9.32} [NEI Addons: Botany] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.9.32} [NEI Addons: Forestry] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.9.32} [NEI Addons: Crafting Tables] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.9.32} [NEI Addons: Ex Nihilo] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.0.10} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.10.jar) 
	UCHIJAAAA	neresources{0.1.0.101} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.101.jar) 
	UCHIJAAAA	OpenMods{0.7.3} [OpenMods] (OpenModsLib-1.7.10-0.7.3.jar) 
	UCHIJAAAA	OpenBlocks{1.4.3} [OpenBlocks] (OpenBlocks-1.7.10-1.4.3.jar) 
	UCHIJAAAA	MapWriter{2.1.2} [MapWriter] (Opis-1.2.5_1.7.10.jar) 
	UCHIJAAAA	Opis{1.2.5} [Opis] (Opis-1.2.5_1.7.10.jar) 
	UCHIJAAAA	fodc{1.6.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.6.1.jar) 
	UCHIJAAAA	mod_pndc{0.1} [Peaceful Nights, Dangerous Caves] (pndc-1.7.10-0.1.jar) 
	UCHIJAAAA	JotatosPracticalities{0.6.2} [Practicalities] (practicalities-1.7.10-0.6.2.jar) 
	UCHIJAAAA	quiverchevsky{b100} [QuiverBow] (QuiverBow_1.7.10_b100.zip) 
	UCHIJAAAA	quivermobchevsky{b14} [QuiverMob] (QuiverMob_1.7.10_b14.zip) 
	UCHIJAAAA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCHIJAAAA	Reconstructor{2.3} [Reconstructor] (Reconstructor-2.3.jar) 
	UCHIJAAAA	RefinedRelocation{1.0.8b} [Refined Relocation] (RefinedRelocation-1.7.10-1.0.8b.jar) 
	UCHIJAAAA	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UCHIJAAAA	xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) 
	UCHIJAAAA	RIO{2.2} [RemoteIO] (RemoteIO-1.7.10-2.2.B1-universal.jar) 
	UCHIJAAAA	rfdrills{1.4.1} [RFDrills] (RFDrills-1.7.10-1.4.1.jar) 
	UCHIJAAAA	Sampler{1.33} [Sampler] (sampler-1.33.jar) 
	UCHIJAAAA	screwdriver{2.0} [Hlestakov's Screwdriver] (screwdriver-2.4.jar) 
	UCHIJAAAA	simplyjetpacks{1.5.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.1.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.5.7} [Storage Drawers] (StorageDrawers-1.7.10-1.5.7.jar) 
	UCHIJAAAA	StorageDrawersForestry{1.7.10-1.0.1} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.0.1.jar) 
	UCHIJAAAA	StorageDrawersNatura{1.7.10-1.0.2} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.0.2.jar) 
	UCHIJAAAA	streams{0.1.4} [Streams] (Streams-0.1.4.jar) 
	UCHIJAAAA	thecorruptedsector{1.0.1} [The Corrupted Sector] (TheCorruptedSector-MC1.7.10-1.0.1.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) 
	UCHIJAAAA	recycling{0.4.0} [Thermal Recycling] (ThermalRecycling-1.7.10-0.4.0.jar) 
	UCHIJAAAA	TSteelworks{1.7.10-1.1.0} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.0-16.jar) 
	UCHIJAAAA	TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) 
	UCHIJAAAA	TinyStorage{1.14.1} [Tiny Storage] (TinyStorage-1.14.1.jar) 
	UCHIJAAAA	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UCHIJAAAA	ttCore{MC1.7.10-0.1.1-76} [ttCore] (ttCore-MC1.7.10-0.1.1-76.jar) 
	UCHIJAAAA	tts{0.6} [Tube Transport System] (TubeTransportSystem_1.7.10-0.6.jar) 
	UCHIJAAAA	wecraft{0.2} [w3(r4ft Mod] (W3(r4ft-0.2(1.7.10).jar) 
	UCHIJAAAA	WLM{1.4.3} [The Wasteland Mod] (Wasteland mod-1.4.4.jar) 
	UCHIJAAAA	zipline{1.0} [Zipline] (Zipline-1.0(1.7.10).jar) 
	UCHIJAAAA	aobd{2.6.3} [Another One Bites The Dust] (AOBD-2.6.3.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3408' Renderer: 'Intel(R) HD Graphics'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@26ebbede) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@516a69de) returned non-null result: 0
	CoFHCore: -[1.7.10]3.0.2-262
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.0-80
	ThermalDynamics: -[1.7.10]1.0.0-122
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Launched Version: 1.7.10-Forge10.13.4.1472-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3408, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ubermentat** [comment]
You need to use minecraft:soulsand, not just soulsand.

**Comment by medsal15** [comment]
Oh, I see

**Comment by medsal15** [comment]
Still doesn't work

**Comment by InfinityRaider** [comment]
I think its minecraft:soul_sand

**Comment by medsal15** [comment]
I works, thanks. I recommend you to change the custom crops config.

**Comment by InfinityRaider** [comment]
It works fine, just use the correct tools to find out block ID's

**Comment by medsal15** [comment]
Weird, I used "sand" instead of "minecraft:sand" and it worked.

**Comment by InfinityRaider** [comment]
That only works for minecraft blocks so don't try it with any modded blocks
