### ISSUE TITLE
Village Crop Support

### ISSUE THREAD

**Issue by WolfieWaffle** [InfinityRaider/AgriCraft#237]
This is minor, but right now, if you have vanilla farming disabled, the village farms still don't use crops. Once a plant has been broken in a village with vanilla farming disabled, the only way to re-plant it is using crops.

**Comment by InfinityRaider** [comment]
And why is that a problem?

**Comment by WolfieWaffle** [comment]
It's not a major problem, I said it was minor. It's just a minor
enhancement that could be added if vanilla farming is disabled, since
village farms use vanilla farming.

**Comment by InfinityRaider** [comment]
But what exactly do you want me to add because I'm really not following?

**Comment by WolfieWaffle** [comment]
I was just saying maybe add a config option to set village farms to use
AgriCraft crops rather than vanilla, but now I'm thinking it might be
incompatible with harvestcraft+hunger overhaul, since those mods add other
plants to village farms.

**Comment by InfinityRaider** [comment]
It should be possible though, I'll look into it

**Comment by InfinityRaider** [comment]
So since the greenhouses are fixed now, what about a config option to disable the generation of vanilla farms in general instead of replacing them with a custom field.
Or I could do both...

**Comment by WolfieWaffle** [comment]
Disabling farm generation could have interesting effects on hardcore
packs... I don't know If it would use that option, but I think you should
add both if possible, additional configuration can almost never go wrong :)

**Comment by hron84** [comment]
@InfinityRaider the ugliest response following: make it configurable :-)

**Comment by InfinityRaider** [comment]
I've decided not to do it, replacing the Vanilla gardens won't be a problem, but there are other mods out there that add/replace the gardens as well (HarvestCraft, PMP, BoP, ...).
And I don't want to have different cases for all of them.
