### ISSUE TITLE
Config option to sync with Hunger Overhaul

### ISSUE THREAD

**Issue by WolfieWaffle** [InfinityRaider/AgriCraft#238]
I thought I heard something about this, but It does not appear to be there on the version of Agricraft I'm using, and I don't know if it was ever actually implemented.

Basically it would allow you to get a global crop growth modifier based off of Hunger Overhaul's growth option. If HO says crops take 3 times a long to grow, Agricraft crops also will. Sprinklers should still help it grow.

If this already implemented, just tell me and close the issue, because I have sometimes suggested things that already exist and I just didn't notice them...

**Comment by InfinityRaider** [comment]
There is a global crop growth modifier implemented in the new version

**Comment by WolfieWaffle** [comment]
Which version is that, I have 1.3.1. Will I have to remove my config files to get the new options?

**Comment by InfinityRaider** [comment]
1.4.0, and you should probably regenerate your config files when upgrading

**Comment by WolfieWaffle** [comment]
Thanks
