### ISSUE TITLE
Make config options to disable any mod integration

### ISSUE THREAD

**Issue by Xiaminou** [InfinityRaider/AgriCraft#239]
Crash on startup, problem with Pneumaticraft's compatibility? is there no option to disable it?
My client works, so might be a problem with what's already in my world.

Forge: 1448
Agricraft: 1.4.0-alpha
Crash Report: http://pastebin.com/f2Htuu0f

**Comment by InfinityRaider** [comment]
Yes I made a pull request to the PneumaticCraft repo to fix this, I'm not sure if the version with the fix is out yet.
But you raise a good point to make a config option to disable mod integration

**Comment by Xiaminou** [comment]
Yeah, I saw that some of the other mods had integrations config to enable/disable, so doing the same for all of the compatible mods would be even better.
