### ISSUE TITLE
Irrigation channel bounds

### ISSUE THREAD

**Issue by 0tho** [InfinityRaider/AgriCraft#24]
Even when connected their bounds are the same as a single irrigation channel block. So in the middle of two connected channels, you can hit the block behind.

**Comment by Imasius** [comment]
Commit de1d71672e198b0a16c8010f0d9bb2086c567a24 fixes at least the visual bounds (grid lines). I have to investigate further how the whole collision bb stuff works.

**Comment by bookerthegeek** [comment]
I would check out the BuildCraft code for the pipes, or the code from tinkers for the casting channels.

**Comment by InfinityRaider** [comment]
Thanks for the hint, I already did that, but I wasn't motivated to add it in at the time

**Comment by bookerthegeek** [comment]
Lol, no worries. Love the mod by the way, and sorry for the necro post.

**Comment by InfinityRaider** [comment]
I don't really consider necroposting a thing on GitHub, except for issues that have been closed for ages and arent relevant anymore. This is still relevant.

**Comment by RlonRyan** [comment]
It looks like this is still an issue. Luckily, I think there is already a solution in the grate class, the intersection method. (If I could get you to port that method please @InfinityRaider).

**Comment by InfinityRaider** [comment]
No, the selection bounding box is always a rectangular prism, so to make it appear to follow the block's bounds, we have to do a raytrace to check what part of the block the player is looking at.
