### ISSUE TITLE
Steamcraft2 Tea Support

### ISSUE THREAD

**Issue by WolfieWaffle** [InfinityRaider/AgriCraft#241]
It would be nice to have support for tea plants in this mod: https://github.com/BrassGoggledCoders/SteamCraft2

**Comment by InfinityRaider** [comment]
I tried 5 versions but I can't get any to work in my dev env. So if you want compatibility ask it to be added from their side.

**Comment by WolfieWaffle** [comment]
Ok, yeah, their dev environment is crazy, I forgot about that. The main dev
says he is going to change it so maybe then this can be looked at again.
I'll ask their side about it though.
