### ISSUE TITLE
Ticking block entity

### ISSUE THREAD

**Issue by Starhero** [InfinityRaider/AgriCraft#245]
http://openeye.openmods.info/crashes/d9ecac7e2ca3f0fd278310fab2f505df

This happened after breaking a water tank part while it was full on water. Just one peace was broken, with a pickaxe. The tank was also partly on the ground.

If you would like the full log, I'll paste bin it later. 

This is world breaking, though I might have deleted it on NBT explore, waiting for it to load......

EDIT: Yes, I was able to recover the world via deleteing that NBT entry located at the coords given by the error.

**Comment by InfinityRaider** [comment]
Thanks for the report I'll fix it.
