### ISSUE TITLE
Prevent villager ID conflicts

### ISSUE THREAD

**Issue by Mattabase** [InfinityRaider/AgriCraft#247]
http://pastebin.com/xv403SfS

This happens when I added Version 3.11 Of RFTools

Which adds a its own villager now.

**Comment by ubermentat** [comment]
You need to change either AgriCraft's or RFTools's villager id in the config files.

**Comment by InfinityRaider** [comment]
I probably should do something to make it assign the villager to a free id dynamically, but for now changing or disabling the id of the villager in the config should indeed fix it.

**Comment by Mattabase** [comment]
Yeah, I am terrible I should not submit an issue when I am tired. I changed the ID, however my issue post did not reflect that.
