### ISSUE TITLE
Crash after updating mods

### ISSUE THREAD

**Issue by anishin** [InfinityRaider/AgriCraft#248]
I have crash with AgriCraft (with 1.3.1 and with 1.4-alpha) after updating my mods.
Maybe, RFTools v3.11 cause this problem (with RFTools v3.10 I haven't this crash).

Crash report: http://pastebin.com/78zpYRDh

**Comment by ubermentat** [comment]
Same issue as #247

**Comment by InfinityRaider** [comment]
Indeed
