### ISSUE TITLE
Hunger Overhaul Incompatibility(?)

### ISSUE THREAD

**Issue by WolfieWaffle** [InfinityRaider/AgriCraft#250]
Hunger Overhaul 1.7.10-1.0.0
AgriCraft 1.7.10-1.4.0-alpha-1.7.10

On the snapshot release, I found some strange behavior with crops. Hunger overhaul overrides crops so that they do not drop seeds, and this worked fine with Agricraft in earlier releases. But when I updated Agricraft, crops started dropping seeds again. I don't know if whose side this is on, but I figured I'll put it here since it appeared when I updated this mod and didn't touch Hunger Overhaul.

If you need more info, just ask me, I don't exactly know what to provide.

**Comment by InfinityRaider** [comment]
This broke because of the same reason Waila broke I accidentally shifted my IMC messages to post init.
This has been fixed.
