### ISSUE TITLE
Crop Sticks Dropping at Wrong Times

### ISSUE THREAD

**Issue by WolfieWaffle** [InfinityRaider/AgriCraft#251]
On AgriCraft 1.7.10-1.4.0-alpha-1.7.10, when I right click harvest a crop, it drops crop sticks as well as seeds and produce, but the crop sticks don't disappear in block form when I do this - it essentially gives you infinite crop sticks. (Also IIRC, the name of the crop sticks item is not capitalized).

Furthermore, I believe that when I left click (broke) the crops, the crop sticks did not break. It's like the "should I drop crop sticks" is inverted.

**Comment by InfinityRaider** [comment]
Does this happen in an instance with only agricraft or is Hunger Overhaul installed as well?

**Comment by WolfieWaffle** [comment]
Yes, I just tested with only the above mods plus AppleCore (dependency) and it still happens. However, to edit what I said before, the crop sticks DO drop when you break the crop. They drop in both situations.

**Comment by InfinityRaider** [comment]
And without Hunger Overhaul?

**Comment by WolfieWaffle** [comment]
Without HO, the issue is not present - they only drop on left click.

**Comment by InfinityRaider** [comment]
Then this is fixed by fixing my IMC derp
