### ISSUE TITLE
Harvestcraft Crops Yield Nothing

### ISSUE THREAD

**Issue by ReportBot9009** [InfinityRaider/AgriCraft#252]
Hi,

Running the 1.4 Beta with Forge 1448.

Pam's Harvestcraft crops will not yield anything. Right clicking reverts the crop maturity back to 0 and left clicking destroys the crop and plant yielding only its seed. Vanilla crops work fine.

Thanks

**Comment by InfinityRaider** [comment]
What does NEI say about the drops.
What version of Harvestcraft?

**Comment by ReportBot9009** [comment]
I'm not sure what you mean about NEI and the drops. Do you mean the seed that drops if I destroy the crop and the plant? The seed gives the normal info that any Agricraft seed would give: Unidentified or the level of that particular seed.

Running Pam's Harvestraft 1.7.10i

I included a picture of a 7x7 farm of bell peppers yielding the first plant I right click on upon load of the game. It does this normally. It only drops the first plant, which gives one when the plant is lvl 10s across the board.

http://imgur.com/GEIumQd

Also, I know you mentioned the irrigation and sprinklers being much less laggy, but I'm the same effect as earlier versions: They are still very laggy. I have a really good computer that doesn't struggle with huge modpacks and my own custom that runs 240+ mods. Here are two pictures with FPS included. One with sprinklers off and one with 6 sprinklers on:

http://i.imgur.com/QuPlwS6.jpg and sprinklers on http://i.imgur.com/TYA5NlY.jpg

That's almost an 80fps drop from 6 spinklers. Not sure if you're continuing to improve this as well.

Thanks again :)

**Comment by InfinityRaider** [comment]
So the first plant you harvest gives the fruit correctly and then it doesnt work anymore? then this is identical to (#242).

Those sprinklers, thats mainly fps lag then?

**Comment by ReportBot9009** [comment]
Hi Infinity,

Yes, it would seem it's almost identical. I haven't tried the pumpkins that person is referring to. I wouldn't say it is giving the fruit "correctly" as the first one only yield 1 fruit and that is a level 10 crop, so it should be giving ~3?

Well, yes FPS lag and the game does start to jitter and hitch a bit, with very noticeable FPS spikes. Example is I'll be walking and I'm all of a sudden 1 step ahead of where I should be or if I were to twirl in 360 degrees, it wouldn't be smooth and kinda of hitch and jitter all the way around. So, sorry in my description, it is not just FPS lag.

Thanks for taking the time to answer me :). Good luck!
