### ISSUE TITLE
[1.4.0-alpha-1 and 2] Render Error Crash with Canola seed (RotaryCraft)

### ISSUE THREAD

**Issue by Xeollron** [InfinityRaider/AgriCraft#255]
When the canola seed from rotary craft is placed in the seed analyser my client crashes with this log http://pastebin.com/dCqYAuGP and then every time I reconnect with the server the crash reoccurs.

Sorry, I'm new at this and not a programmer

Love the mod and the new added support in the update!

**Comment by InfinityRaider** [comment]
Thanks for the report, I added a null check.
The seed will probably render as a missing texture (purple black) now, I'll have to check how to fix that, but its not that critical.
Does it crash when you plant the seeds on crop sticks?

**Comment by Xeollron** [comment]
Ok great, they render fine when on crop sticks.
I don't know if this is caused by agricraft or rotarycraft or if I should submit it as another bug but when harvested the canola plants drop canola seed husks rather than canola seeds which are the item they are farmed for.

**Comment by InfinityRaider** [comment]
I'm using a hacky workaround to convert and IIcon to a ResourceLocation and I think Reika isn't doing the conventional IIcon registering for Items, hence my workaround fails.

**Comment by Xeollron** [comment]
All-right thanks! Again so glad you added the integration, love the mod. keep up the great work.

**Comment by Xeollron** [comment]
Render Error crash still occurs in 1.4.0 alpha-3 will do more testing with only agricraft and rotarycraft installed

**Comment by InfinityRaider** [comment]
Log please

**Comment by Xeollron** [comment]
Yep, here they are

Log: http://pastebin.com/gtNAtbZx
Crash Report: http://pastebin.com/TKn5xQgZ
and MultiMC Log: http://paste.ee/p/QnokG

**Comment by KaneHart** [comment]
Since our mate here worked on testing all the seeds here is what he had to say and did:

https://i.imgur.com/qybR8CR.png

Every seed in the chest above and to the left of the book is what Agricraft can scan, every seed in the chest to the right and below the book is something that registers in an NEI search for "seed" that Agricraft can not scan. The one lone seed in the hotbar (Canola from Rotarycraft) crashes the game with those crash reports. It is a conflict between Agricraft and Rotarycraft.

**Comment by InfinityRaider** [comment]
What mod are the seeds after the Thaumic Tinkerer seeds from?

**Comment by KaneHart** [comment]
When I asked I got this response:

Fossil and archeology (you would have to ask passion/krylyah if they are even crop seeds or just scenic plants), biomes o'plenty sunflower seeds (food item doesn't grow crops (but it totally should)), atum flax (used to scan but didn't grow anything, now they don't scan, they do not produce enough seeds to sustainably grow in "vanilla" state), saguaro fruit from natura (can be planted as a seed to grow saguaro cactus or eaten), treefyd seed from witchery (plant that grows into a defender mob inspired by old horror film).
