### ISSUE TITLE
[1.4.0] Server Crash on startup

### ISSUE THREAD

**Issue by Xiaminou** [InfinityRaider/AgriCraft#257]
Agricraft: 1.7.10-1.4.0-alpha-3-1.7.10

Crash Report: http://pastebin.com/G5rVApY1

Client works fine.

**Comment by InfinityRaider** [comment]
Derp, I always forget to check if the server launches when I rewrite stuff. Will fix, apologies

**Comment by Xiaminou** [comment]
That's why I'm here ;)

**Comment by Mattabase** [comment]
Any chance you could push to curse?

**Comment by InfinityRaider** [comment]
I'm in the middle of debugging a dupe bug with the seed storage system so you'll have to have some patience

**Comment by InfinityRaider** [comment]
I uploaded a new version with the fix to CurseForge, can be downloaded once its approved.
