### ISSUE TITLE
Crash with cotton seeds 

### ISSUE THREAD

**Issue by zed-hex** [InfinityRaider/AgriCraft#259]
If a player right clicks a fully grown cotton plant from pam’s harvest craft it will cause a crash. I also noticed there are 2 different types of cotton plant one called “cotton” this is the one that you get when you plant the seeds and “cotton seeds” these can only be found in green houses and do not have the crash issues. (I found the names of the plants with waila)
Relevant mods to the crash and versions: 
AgriCraft-1.7.10-1.4.0-alpha-4-1.7.10
Pam’s harvest craft 1.7.10i 
Forge10.13.4.1448-1.7.10
Crash log: http://pastebin.com/AcfdEYQG

**Comment by InfinityRaider** [comment]
I'll have a look at it this evening, thanks for the report.

**Comment by InfinityRaider** [comment]
I managed to replicate the issue. Cotton itself is instance of ItemSeeds as well, don't ask me why, but it is. I've added an exception to ignore it while scanning for harvestcraft seeds.
