### ISSUE TITLE
optional config not optional

### ISSUE THREAD

**Issue by bdudek** [InfinityRaider/AgriCraft#260]
for the custom crops the shearable that is labled as optional still needs  to be in the line for the custom crop. the exzample shows :

#Example: claysanthemum,minecraft:clay,minecraft:sand,minecraft:hardened_clay,2,6,a crop that extracts clay from the soil to grow clay buds.

it doesnt show the part for shearable. if it is left out we get this crash : http://pastebin.com/a43FUaJj

so is the line for that suppose to be optional or is it suppose to be in the code because with out it there crashing.

**Comment by InfinityRaider** [comment]
Indeed I forgot to check if the argument is actually there, my apologies.
