### ISSUE TITLE
Water tanks cause chunk updates.

### ISSUE THREAD

**Issue by Kubuxu** [InfinityRaider/AgriCraft#261]
It causes extreme frame rate drops.

**Comment by InfinityRaider** [comment]
What version?

**Comment by Kubuxu** [comment]
1.4.0-alpha

**Comment by InfinityRaider** [comment]
I must have fucked something up then, I changed it to reduce the number of block updates, I'll investigate.
Is it worse than in 1.3?

**Comment by Kubuxu** [comment]
Not sure. The issue gets serious when you have a lot of crops and tank in the same view chunk (16x16x16).

**Comment by InfinityRaider** [comment]
I have code that turns the tanks and channels into hybrid TESR/ISRBH where the water is a TESR, the registering is commented out because i can't get the water to render correctly, but I can add a config option to enable it anyways.

**Comment by SanAndreasP** [comment]
I can confirm this. Having a network of irrigation channels with sprinklers (and one tank to provide everything with power) in a 32x32 area causes a ca. 10 FPS drop.

**Comment by InfinityRaider** [comment]
I'll rewrite irrigation systems when I find some time, because they were written at a time when I was new to modding, and it received a few patches, but its still a monster.

**Comment by InfinityRaider** [comment]
Tanks and Channels are now hybrid TESR-ISBRH's, the water is rendered as TESR and the rest as an ISBRH (https://github.com/InfinityRaider/AgriCraft/commit/0fd5f344fa17c8e59a5d4f2d567031a2e632958c).
Fluid levels are now synced with a seperate packet. Now there will no longer be block updates when the discrete fluid level changes.
