### ISSUE TITLE
[1.4.0] Forcing mutations does not work.

### ISSUE THREAD

**Issue by cloakable** [InfinityRaider/AgriCraft#264]
![2015-07-08_15 43 48](https://cloud.githubusercontent.com/assets/1534182/8573186/3295ac38-2588-11e5-8ba8-ee9e64c4622b.png)
I have what -should- be required to mutate Nitor Wart and bonemeal forcing mutations set to true, but I've stuffed six stacks of bonemeal onto the crosscrops so far with zero result.

**Comment by InfinityRaider** [comment]
Probably because it needs darkness, the plant will never sprout there when the conditions arent right.

**Comment by kotoroshinoto** [comment]
how are we supposed to get it to mutate when the dark conditions make the orange tulip unhappy?

**Comment by InfinityRaider** [comment]
Mature the orange tulip in brightness, then when it is mature, make it dark, then it doesn't matter anymore for the tulip.
