### ISSUE TITLE
harvastcraft compatibility

### ISSUE THREAD

**Issue by vagaprime** [InfinityRaider/AgriCraft#266]
Was looking through the journal after scanning a bunch of seeds when the game crashed.

Here is a copy of the crash log. http://pastebin.com/aDi8J82V

AgriCraft-1.7.10-1.4.0-alpha-4
Harvestcraft 1.7.10i
forge 10.13.3

**Comment by InfinityRaider** [comment]
What seed?

**Comment by vagaprime** [comment]
I want to say it was the journal entry for cotton seeds that I crashed on but seeing has how the game froze up when trying to load the journal page before crashing I am not sure.

**Comment by InfinityRaider** [comment]
It was probably not cotton seeds, but cotton itself because that is instance of ItemSeeds as well, AgriCraft thought it was a different plant than the seeds. I already added an exception to ignore Cotton. But to be sure I also made sure the subString calls wont crash anymore.
