### ISSUE TITLE
Crash Loop v2.0 - java.lang.NullPointerException: Rendering Block Entity

### ISSUE THREAD

**Issue by KaneHart** [InfinityRaider/AgriCraft#268]
One of our players are having this looping crash client only server is fine.

http://stonelegion.com/threads/crash-loop-v2-0.3032/

**Comment by InfinityRaider** [comment]
Thanks for the report, two requests: Update to the latest alpha build and tell me what seed.

**Comment by KaneHart** [comment]
I will have to wait till tomorrow morning to get the alpha build.

This what I was told:
Rotary Craft Canola seeds in Agricraft Seed Analyzers

I'm using AgriCraft-1.7.10-1.4.0-alpha-2-1.7.10.jar not sure if you pushed another one on curse forge or not.

**Comment by InfinityRaider** [comment]
Same as #255, going to close this.
