### ISSUE TITLE
[1.4.0] Immersive Engineering Hemp Seeds not considered "seeds"

### ISSUE THREAD

**Issue by Killarflame** [InfinityRaider/AgriCraft#269]
I use minetweaker to add custom mutations. When I attempt to make a mutation with industrial hemp seeds from Immersive Engineering (" ImmersiveEngineering:seed ") I get this error: 

ERROR: Adding mutation with result 'Industrial Hemp Seeds' failed. All 3 have to be of type ItemSeeds.

There isn't any other message in console, and this only happens with the industrial hemp seeds.

**Comment by InfinityRaider** [comment]
Ah this is a remnant of my old crop system where seeds had to be instance of ItemSeeds, thanks for the report, I'll fix it this evening.
