### ISSUE TITLE
Custom crops minetweaker script only works after /mt reload

### ISSUE THREAD

**Issue by BBoldt** [InfinityRaider/AgriCraft#271]
* AgriCraft-1.7.10-1.4.0-alpha-4-1.7.10
* Forge 1481
* MineTweaker3-1.7.10-3.0.9C

When first loading the game I get the message:
"ERROR: Error executing Agricraft.zs: null"

But upon reloading the script with /mt reload, everything works as expected.
![](http://i.imgur.com/NtSzKRr.png)

Agricraft.zs: https://gist.github.com/e9507f353059f5cb6c31
Minetweaker log: https://gist.github.com/ca41f0eb9deed49de245

**Comment by InfinityRaider** [comment]
SSP or SMP?

**Comment by InfinityRaider** [comment]
It's nothing to do with what I thought it was, it was just that MineTweaker runs its scripts before I had Initialized my mutations.
