### ISSUE TITLE
Issue reloading single player world

### ISSUE THREAD

**Issue by Killarflame** [InfinityRaider/AgriCraft#272]
MineTweaker3-1.7.10-3.0.9C
AgriCraft-1.7.10-1.4.0-alpha-4-1.7.10

I cannot reload a single player game. I do not know if this is an issue with minetweaker or with agricraft. 
I don't have a script changing growing baseblocks.

pastebin: http://pastebin.com/P2Q5sVym

**Comment by Killarflame** [comment]
This also prevents me from creating new single player worlds.

**Comment by InfinityRaider** [comment]
Can you also give me your Minetweaker script please, I'll try to duplicate and fix this.

**Comment by InfinityRaider** [comment]
I added a null check so this shouldnt happen anymore
