### ISSUE TITLE
Runtime exception in Initialization 

### ISSUE THREAD

**Issue by AegisLesha** [InfinityRaider/AgriCraft#274]
http://pastebin.com/YP0V9ih3
Might be related to Villager's ID, going to test it right now

**Comment by AegisLesha** [comment]
Was indeed caused by IDs

If I may suggest, you should consider to warn on your FTB thread the inexperienced users that they may encounter this issue

**Comment by InfinityRaider** [comment]
This should never occur again as I'm now assigning the villager id to the first free one.
