### ISSUE TITLE
Crash When Harvesting Village Water Tanks

### ISSUE THREAD

**Issue by ReportBot9009** [InfinityRaider/AgriCraft#275]
Here is the crash report: http://pastebin.com/ecJ46Fua

Good Luck!

Edit - I'm so sorry, I forgot to specify the version. Running Agricraft 1.4.0 alpha 4.

**Comment by Kubuxu** [comment]
It was resolved in #262, #263, #265.

**Comment by InfinityRaider** [comment]
Yes indeed, if you upgrade to alpha 5 it should be fixed
