### ISSUE TITLE
Blizz powder is not craftable on thermal expansion fluid transposer

### ISSUE THREAD

**Issue by Kazzamkablam** [InfinityRaider/AgriCraft#276]
I did some testing and found out that blizz power is not craftable from snowballs + redstone in fluid transposer as it should be with newest version of agricraft. Moment I downgraded to older version it was working fine again, so it has definitely something to do with agricraft.

Versions:
AgriCraft-1.7.10-1.4.0-alpha
forge-1.7.10-10.13.4.1490
CoFHCore-[1.7.10]3.0.3B3-301
RedstoneArsenal-[1.7.10]1.1.1B1-85
ThermalDynamics-[1.7.10]1.1.0B3-156
ThermalExpansion-[1.7.10]4.0.2B3-216
ThermalFoundation-[1.7.10]1.2.0B2-101

**Comment by InfinityRaider** [comment]
I am not changing/adding/removing recipes for Thermal Expansions. All I'm doing is adding an ore dictionary tag to snowballs because they are produced by the Witchery Snowbell plant.
Take this to the Thermal Expansion issue tracker because I am not going to do anything about this on my side.
