### ISSUE TITLE
5 minor water pad issues

### ISSUE THREAD

**Issue by Timeslice42** [InfinityRaider/AgriCraft#277]
1.) Water pads don't count as a hydration source for tilled dirt.
2.) Digging a (dry) water pad is not compatable with Tinker's Construct shovels and mattocks. This bug might not be on your side, as it works with other non-vanilla shovels.
3.) Filling a water pad doesn't work with non-vanilla water buckets.
4.) You have to sneak to place a crop stick on a water pad.
5.) Water pads break instantly. Crop sticks also have this problem.

**Comment by InfinityRaider** [comment]
I'll fix all of these, except for the crop sticks breaking instantly, that's intended.

**Comment by InfinityRaider** [comment]
Should all be fixed now

**Comment by Timeslice42** [comment]
Thank you :)
