### ISSUE TITLE
Journal "Change Page" arrow texture issue

### ISSUE THREAD

**Issue by Killarflame** [InfinityRaider/AgriCraft#280]
AgriCraft-1.7.10-1.4.0-alpha-6-1.7.10

This happens both in the seed analyzer when viewing the journal and when using the journal normally. 

![2015-07-13_16 02 48](https://cloud.githubusercontent.com/assets/13263287/8659560/c2bd6888-2979-11e5-9c0f-aebc1b0b7360.png)

It seems to happen on almost all the crop pages. The only page I found where it didn't happen was belladonna from witchery.

**Comment by InfinityRaider** [comment]
That's annoying, I'll see what's going on, thanks for the report.

**Comment by InfinityRaider** [comment]
Fixed in 4b645c0a512701ec5d9544a78be8b507277c7313
(forgot to reference)
