### ISSUE TITLE
AE2 certus quartz support

### ISSUE THREAD

**Issue by NoX-programer** [InfinityRaider/AgriCraft#281]
I've noticed about there is no Applied Energistics 2 support in the Agricraft. So I make definition to add custom crop growing certus quartz:
CustomCrops.txt:
certus,appliedenergistics2:item.ItemMultiMaterial:0,appliedenergistics2:tile.BlockSkyStone,appliedenergistics2:tile.OreQuartz,4,6,A crop that grows generic certus quartz
Mutations.txt:
AgriCraft:seedCertus=AgriCraft:seedPlatiolus+AgriCraft:seedEmeryllis
I suggest you add something similar for able to grow AE2 quartz.

**Comment by InfinityRaider** [comment]
Thanks for the suggestion, but I'm developping agricraft and not magical crops, I think I've added enough resource crops already. And I also gave people the option to add their own crops if they aren't satisfied with what I offer.
So sorry, I will not add this.

**Comment by Ricket** [comment]
@NoX-programer I appreciate you sharing the contents of the files. I added those but the textures are missing. Did you create textures for the certus seed and crop as well? Or do you just use it with the missing texture graphic? It'd be nice if you could share your texture images. Otherwise I might try to make some (but I'm absolutely terrible at art).

**Comment by NoX-programer** [comment]
@Ricket Here: https://www.dropbox.com/s/l8aft1rvl1ikhl7/add-Agricraft.zip?dl=0 You need to extract archive and include that folder to Agricraft*.jar. I don'k know how to do that more properly, but it's works. And my art is terrible too ;) And because of this, the seed is looks almost like platinum.

**Comment by InfinityRaider** [comment]
You can also make a resource pack and put the textures there, put ye putting them in the jar directly is also possible
