### ISSUE TITLE
Mod Incompatibility - Growthcraft Rice

### ISSUE THREAD

**Issue by Killarflame** [InfinityRaider/AgriCraft#282]
I know that you don't strictly have compatibility with this mod, but the recent addition of water pads has caused an issue with rice from Growthcraft. Rice Paddies (GC) and water pads are made in the same way, and the water pads appear to take precedence. This makes it impossible to farm rice from growthcraft (barring the addition of a recipe for the rice paddy through minetweaker, which isn't preferred). 

I don't know if this is an issue that should be posted here specifically, but I felt you should at least be made aware of it.

**Comment by InfinityRaider** [comment]
If growthcraft rice has an item that is used as a seed then yes I can do that.

**Comment by Killarflame** [comment]
The fruit is the seed. 
<Growthcraft|Rice:grc.rice>
Thank you.
