### ISSUE TITLE
Feature Request: Thaumic Tinkerer Compatibility

### ISSUE THREAD

**Issue by Killarflame** [InfinityRaider/AgriCraft#283]
Thaumic tinkerer (an add-on to Thaumcraft) adds infused seeds to the game which are harvested to gain special items used in thaumcraft brewing. 

Was hoping it would be possible to have these growing through agricraft rather than the bizarre soil altering method that the mod adds to allow mutation.

**Comment by InfinityRaider** [comment]
I know, I've had a look at it and decided not to bother, sorry. Maybe now that the API is almost done Nekosune will consider it, but I doubt it'll ever be thing.
