### ISSUE TITLE
NPE when moving a crop using a trowel

### ISSUE THREAD

**Issue by Timeslice42** [InfinityRaider/AgriCraft#287]
I got a null pointer exception when moving a partially grown unscanned daisy from one crop stick to another. The trowel picked up okay, but crashed on placing.

https://www.dropbox.com/s/mk8985kfwbxaert/trowelcrash.zip?dl=0

**Comment by Timeslice42** [comment]
The NBT for the trowel is as follows
```
<AgriCraft:trowel:1>.withTag({strength: 1 as short, seed: {id: 5410 as short, Damage: 0 as short, Count: 1 as byte}, matMeta: 4 as short, analyzed: 0 as byte, growth: 1 as short, gain: 2 as short})
```

**Comment by InfinityRaider** [comment]
I'll take a look at it
