### ISSUE TITLE
Stats for plants don't cap out at ten.

### ISSUE THREAD

**Issue by ralse** [InfinityRaider/AgriCraft#288]
Stats for plants don't cap out at ten.  As long as you don't break the parents before they spawn children you can continue to increase their stats.  As soon as you break the plants the seeds revert to 10/10/10.  I only noticed this because I started to get more than 4 yield from a harvest.  I don't recall off hand but this crop was giving me 6-7 wheat per harvest.

![seedstats](https://cloud.githubusercontent.com/assets/13343793/8690621/e0769172-2a84-11e5-8ceb-c8b1d929f9e8.jpg)

**Comment by InfinityRaider** [comment]
Thanks for the report, canyou be more specific with what you mean when you say "dont break the parents?

**Comment by Kubuxu** [comment]
You crossbreed w/o picking up seeds. (I think)

**Comment by ralse** [comment]
Like Kubuxu said.  

I'd wait until the parent crops had grown to maturity, place down the crop sticks to make the crosscrop, have new children plants get created, break the parents, grow the new crop to maturity, and start again with the current generation's children plants being the next generations parents.  So I would breed each new generation together and the stats would increase with each new generation.

**Comment by InfinityRaider** [comment]
Okay thanks for the clarification, I was confused a bit confused.

**Comment by InfinityRaider** [comment]
What version are you on?

**Comment by Timeslice42** [comment]
How are you getting that debug scan? Is there an agricraft developer tool that doesn't show up in NEI?

**Comment by ralse** [comment]
AgriCraft-1.7.10-1.3.1.  
The tool is called debugger, and it shows up in NEI for Agricraft for me.

**Comment by ralse** [comment]
AgriCraft-1.7.10-1.3.1.  
The tool is called debugger, and it shows up in NEI for Agricraft for me.

**Comment by InfinityRaider** [comment]
I'm failing to reproduce this in my 1.4 dev env. I'm going to close this, if it persists after you upgrade, feel free to reopen.

**Comment by InfinityRaider** [comment]
Also, the debugitem is now hidden from NEI if you arent in debug mode (enabled via the config)
