### ISSUE TITLE
Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION

### ISSUE THREAD

**Issue by jgrimes900** [InfinityRaider/AgriCraft#289]
In the crash report it came to java.lang.NoClassDefFoundError: vazkii/botania/api/item/IGrassHornExcempt

I don't have botania installed and it knows that!
So I was also in a coding environment (eclipse) to get it to work with my mod.
I have try installing botania and it work ok!

so can you try to find out more, or am I just crazy and did something wrong in my code.
thanks in advance,
jgrimes900

**Comment by InfinityRaider** [comment]
Normally FML strips the interface from the class if Botania is not loaded at runtime. Its probably failing at compile time, so I suggest adding the botania api jar to your dev environment.

**Comment by InfinityRaider** [comment]
Closing this due to lack of response and not really an issue.
