### ISSUE TITLE
Sprinklers not hydrating often enough

### ISSUE THREAD

**Issue by Timeslice42** [InfinityRaider/AgriCraft#292]
If I start with a fully tilled and hydrated field and then remove all hydration sources except the sprinklers, the farmland will slowly dry out and eventually turn back into dirt.

**Comment by InfinityRaider** [comment]
I'll have a look at it

**Comment by InfinityRaider** [comment]
Are you sure the sprinkler isn't too high or runs out of water? I've been standing here for a while and it stayed like this the entire time:
http://puu.sh/jceLb/3dc8f3d8eb.jpg

**Comment by Timeslice42** [comment]
http://imgur.com/J0cRtCL

This distance worked before... is it too high now?

**Comment by Timeslice42** [comment]
I have a decent guess as to what is going on... the sprinklers are in range of the crops but not the soil they are planted on. Does that sound right?

**Comment by InfinityRaider** [comment]
I believe so, but Ill increase the height one more because I made the height I wanted for crops.
