### ISSUE TITLE
Texture Bug?

### ISSUE THREAD

**Issue by bdudek** [InfinityRaider/AgriCraft#293]
updated to the latest agricraft caused this
![2015-07-21_08 02 01](https://cloud.githubusercontent.com/assets/8053683/8802150/776191e2-2f8d-11e5-89b3-6a12552f9444.png)

it only appears to happen to vinilla mobs and i know its agricraft bc when i remove it textures are back

**Comment by bdudek** [comment]
it appers to be trying to give all the vinilla mobs the same skin i reloaded the world and now every mob from vinilla is trying to use the iron golem skin

**Comment by InfinityRaider** [comment]
Oh waw, does anything come up in the log?

**Comment by Timeslice42** [comment]
Could you provide a full list of the mods you're using? I'm even using optifine and I don't have this issue.

**Comment by bdudek** [comment]
log from load up: http://pastebin.com/SJjDcJL2
and mod list: https://docs.google.com/document/d/1SktCLuMeTFAfHSRUZAOKodhGtYSE73vd-mD6kd4eikY/edit?usp=sharing

im going to try and redo my intire minecraft to see if something went wrong with it all i sayi8ng is aplha version6 doesnt give me this problem only alpha 7 does/did

**Comment by Killarflame** [comment]
I use the same pack as bdudek. 
![2015-07-21_17 21 16](https://cloud.githubusercontent.com/assets/13263287/8812912/0b59b7be-2fcd-11e5-9d7d-543c31f82b38.png)
And I also appear to have the issue with mobs not having textures. 

Here's my log: http://pastebin.com/Qzu7DfAT

I wasn't having this issue prior to adding the latest (Alpha 7) version of agricraft and that is the only mod that I've changed.

**Comment by bdudek** [comment]
ok delete me minecrafrt instance and re did everything vinillla mobs are still broken for me rolled bake to alpha 6 and vinnila mobs have textures again

**Comment by InfinityRaider** [comment]
Does it still happen when the villager is disabled?

**Comment by bdudek** [comment]
yes this is still happening for me with villagers disabled

**Comment by InfinityRaider** [comment]
Can you zip up the pack (mods + configs) and send it to me somehow?

**Comment by bdudek** [comment]
https://www.dropbox.com/s/in7q13ovomuwisw/minecraft.zip?dl=0 here is the pack im using and it includes the mods configs and the custom files

**Comment by InfinityRaider** [comment]
Okay thanks, I'll try to find out what mod combination is causing it and why and if I can fix it

**Comment by bdudek** [comment]
rodger

**Comment by Timeslice42** [comment]
Defiance of Fate uses these mods: http://imgur.com/PBWqPVk with Forge 1448
The pack is still in beta, but if you want to install it put this URL into the technic launcher: http://api.technicpack.net/modpack/defiance-of-fate

**Comment by InfinityRaider** [comment]
Its Optifine, I'll try to fix it

**Comment by Timeslice42** [comment]
So the fact that I use Optifine is why mine is working? That's a first...

**Comment by bdudek** [comment]
me and killar have optifine aswell so that statement would be false

**Comment by Timeslice42** [comment]
Do you guys both use C1 HD Ultra?

**Comment by bdudek** [comment]
yes

**Comment by Timeslice42** [comment]
Me too... ><

**Comment by InfinityRaider** [comment]
I figured it out, I think I just can't use GL call lists when rendering stuff, its experimental anyway, so no worries.
