### ISSUE TITLE
[Enhancement] Trowel in seed analyzer

### ISSUE THREAD

**Issue by Timeslice42** [InfinityRaider/AgriCraft#294]
Would you be willing to add the ability to put a trowel holding a crop into the seed analyzer to get the stats on the crop?

**Comment by InfinityRaider** [comment]
Thanks for this suggestion, I really like it, this was also the perfect opportunity to rewrite the trowel.
Also, forgot to reference: https://github.com/InfinityRaider/AgriCraft/commit/f8b10e07d5e3df77268dc0d79f079947119d2054

**Comment by Timeslice42** [comment]
I'm glad you like the idea :)
