### ISSUE TITLE
Shears not working on cactus crops

### ISSUE THREAD

**Issue by Timeslice42** [InfinityRaider/AgriCraft#295]
When using shears on cactus crops I receive neither green dye nor a cactus block. The shears work fine on poppies.

**Comment by InfinityRaider** [comment]
Is the gain higher than 4?

**Comment by Timeslice42** [comment]
No.

**Comment by InfinityRaider** [comment]
Increase gain one more point and try again.

**Comment by Timeslice42** [comment]
I haven't tried the higher gain yet, but my expectation as a user is that I would get exactly as many cactus blocks as I do dye, since it's a 1:1 ratio for cactus to dye. This particular crop is giving me one dye per normal harvest.

**Comment by InfinityRaider** [comment]
Ye but I'm not going to write exceptions for every crop thats not a 1:2 ratio, sorry

**Comment by Timeslice42** [comment]
How about just cactus? Why do these crops even behave this way anyways? I hate that they give me the dye instead of the flower, etc.

**Comment by InfinityRaider** [comment]
Because I consider it one of the vanilla flowers, and I like consistency.

**Comment by Timeslice42** [comment]
I never liked that the flowers did this either. Not in agricraft, and not in IC2. It doesn't make any sense. When I harvest any other crop I get the crop, not some byproduct of the crop.

Anyways, the reason this is an issue in my skyblock modpack is that now there is no way to get a cactus block. I'll have to think about how I want to fix this.

**Comment by InfinityRaider** [comment]
If you shear a cactus with gain >= 4 you get cactus blocks. You can also change the fruits of crops with MineTweaker.

**Comment by Timeslice42** [comment]
I have the max stats set to 3/3/3 since gain 4 is where you start getting double output, but changing the output with MineTweaker is exactly the right answer. Thank you :)
