### ISSUE TITLE
PneumaticCraft seeds crash server

### ISSUE THREAD

**Issue by Wolf68k** [InfinityRaider/AgriCraft#296]
On a server,  right-click PneumaticCraft plants in the crop sticks then it crashes. Single player seems fine.
Started in 1.4.0-alpha then 1.4.0-alpha-6. Haven't tested with 1.4.0-alpha-7 yet.

http://pastebin.com/cxPTZ6tH

**Comment by InfinityRaider** [comment]
See #258
