### ISSUE TITLE
[Enhancement] Add back cactus block drop option

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#297]
Please add back the old option to drop cactus block instead of green dye for cactus seed. It seems the option was vanished from the generated config and I'm unsure if AgriCraft still honor it. I hope, but I have a doubt.

**Comment by thephoenixlodge** [comment]
This is due to that function being superceded by the new shearing mechanic. Increase the growth of the crop and then harvest while holding shears to get an intact plant at a rate of one for every 2 that it would produce. This applies to all the flowers including the botania ones too.

**Comment by hron84** [comment]
@thephoenixlodge ohh, i didn't hear about it yet. Sounds cool.
