### ISSUE TITLE
Automate seed production

### ISSUE THREAD

**Issue by oleduc** [InfinityRaider/AgriCraft#298]
Hey,

I'm playing in a mod that has Immersive Engineering which requires mass production of Hemp seeds. Howerver, there doesn't seem to be any obvious way to autmate seed production.

I attempted to automate cloning and harvesting of seeds using autonomous activators and update detectors, but that didn't work too well. 

Is there any mod integration that allows automation of seed production?

**Comment by InfinityRaider** [comment]
There's no way to automate seeds, however you're probably wanting to farm seeds for the squeezer?
Pumpkins are a good alternative, they give less seed oil, but you get 4 seeds per pumpkin.
