### ISSUE TITLE
Growthcraft Compatibility

### ISSUE THREAD

**Issue by kaovalin** [InfinityRaider/AgriCraft#299]
Growthcraft bamboo sticks can't be turned into their block form (2x2 of bamboo sticks) in the alpha 6 version of agricraft. Prior release did not override this behavior and I was able to turn them into their block form. Probably an ore dictionary with stick recipes. 

Growthcraft rice paddies can't be made in alpha 6 as well. The method of using a shovel on tilled soil causes them to turn into agricraft waterpad instead.

**Comment by Killarflame** [comment]
The growthcraft rice issue was mentioned previously and should be fixed in the latest alpha (alpha 7). 
#282

**Comment by InfinityRaider** [comment]
Correct, thanks for the clarification Killarflame,
