### ISSUE TITLE
Unable to remove product from non-Agricraft seed

### ISSUE THREAD

**Issue by Killarflame** [InfinityRaider/AgriCraft#300]
AgriCraft-1.7.10-1.4.0-alpha-8-1.7.10
MineTweaker3-1.7.10-3.0.9C

My pack contains both Harvestcraft and Witchery. The garlic plant from harvestcraft has both kinds of garlic listed as products. 
I attempted to remove the witchery garlic from the harvestcraft plant and received an error stating that it was not a valid seed. 

This is the code line I used: 
CropProduct.remove(<harvestcraft:garlicseedItem>, <witchery:garlic>);

The function is imported properly (I use it earlier in the script and it works). 

The arrow brackets don't appear properly on here, but they are there in the code itself.

**Comment by InfinityRaider** [comment]
Yes it only works for my crops.

**Comment by InfinityRaider** [comment]
Oh okay I see what you mean now. This is because apparently garlic from witchery is also listed as "cropGarlic" in the ore dictionary. This is why my code is pickign it up as a valid fruit as well.

**Comment by Killarflame** [comment]
I wasn't aware that it used oredictionary. I thought it was just using individual items.
