### ISSUE TITLE
Particle Reduction Request

### ISSUE THREAD

**Issue by natedogith1** [InfinityRaider/AgriCraft#301]
Could we have a way to majorly reduce particles produced by sprinklers? I have 75 sprinklers constantly running, and that produces way too many particles. (the particles fall half a block or so before disappearing due to too many particles) The reason I have so many sprinklers is because I'm using them to hydrate three 25x25 farms.

**Comment by InfinityRaider** [comment]
I've already made it scale the number of particles according to the particle setting.
I'm not goin got reduce it any more, sorry.

**Comment by MaPePeR** [comment]
Comparing to how [OpenBlocks scales](https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/tileentity/TileEntitySprinkler.java#L48) [the amount of Particles](https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/tileentity/TileEntitySprinkler.java#L126-L128), i think,  you should consider reducing the amount of particles more (based on particle settings).

Spawning [a Particle every 3rd tick](https://github.com/InfinityRaider/AgriCraft/blob/6173ec1f5000c0ef2ab7d7c0087082b9c4dcde7e/src/main/java/com/InfinityRaider/AgriCraft/tileentity/irrigation/TileEntitySprinkler.java#L142-L144) is not cutting it on Minimal Particle Settings. (OpenBlocks does every 20th tick on Minimal)
