### ISSUE TITLE
Harvestcraft rice doesn't like AgriCraft or v.v?

### ISSUE THREAD

**Issue by MoonCutter2B** [InfinityRaider/AgriCraft#302]
I get some rice from Harvestcrafts gardens. I turn them into seeds.
If I plant them right off - the plants despawn after a few seconds.
If I analyze them first turning them into Agricraft seeds the cannot be planted on crops.
All other seeds I'v tried (and that is almost 100% of them) works both planting them as they are and turning them into agricraft seeds.

**Comment by InfinityRaider** [comment]
If you are on version 1.3.1 then this is irrelevant and you will have to update.
If you are on version 1.4.0-alpha, then that means you have to plant rice on water pads.
