### ISSUE TITLE
Multiple registered versions of the same crop yields multiple versions of the product on harvest

### ISSUE THREAD

**Issue by bogatyr-n** [InfinityRaider/AgriCraft#305]
Attempting to harvest a crop registered by two or more mods yields unpredictable results. Crops yield products from any of them, and can yield multiple versions of the same crop from the same harvest action.

Tested with the latest Harvestcraft, Plant Mega Pack, Growthcraft, and AppleMilkTea installed.

**Comment by InfinityRaider** [comment]
I've added a way to seperate different types of the same food so it'll only get registered once. I'm using the Ore Dictionary to get fruits from seeds for some crops. I'm discriminating based on the internal name of the item if it is the same 'type' e.g. PMP brocoli is equivalent to HC brocoli so only one may drop.
It works for PMP and HC, for other mods it would depend on how the item is registered though.
