### ISSUE TITLE
RotaryCraft Canola seeds cause a crash when put in the Seed Analyzer

### ISSUE THREAD

**Issue by Bomber57** [InfinityRaider/AgriCraft#306]
So I did notice that this issue was posted before, but I'm not 100% sure it was fixed (or if it was possible, or who's mod was the issue or whatever), especially considering its happening. Simply enough, I put canola seeds in the Seed Analyzer and it crashed my game, and whenever I try to log back in it crashes again. I use RotaryCraft 1.7.10 V7f and the most recent AgriCraft 1.4.0 alpha-8.

Crash Log: http://pastebin.com/dVtNxHsv

Canola Seeds work perfectly fine when it comes to being planted on crop sticks and when harvested they give Canola Seeds like they should, but putting them in the Seed Analyzer results in the crash.

**Comment by InfinityRaider** [comment]
Oh right I made them render in 3D instead of 2D and I must've removed the null check.
I'm going to contact Reika to see how I can get an IIcon from his item though.

**Comment by Bomber57** [comment]
Is it possible for you to temporarily add back the null check until then please? I would really appreciate it.

**Comment by InfinityRaider** [comment]
Yes of course I'm adding it back in ;)

**Comment by Xeollron** [comment]
Hey, I believe this should go here?
The client crashes on launch. I ran it in my test environment with just Rotarycraft Agricraft and NEI etc.
Seems to be an issue with the null check? http://pastebin.com/khscNjuE

**Comment by InfinityRaider** [comment]
Has nothing to do with RotaryCraft, I'm guessing you have some blocks disabled in the config? If so then this is an easy fix, so can you enable everything and see if it crashes?

**Comment by Xeollron** [comment]
I'm sorry, I'm not a programmer, and using the default config resolved the problem thanks!

**Comment by InfinityRaider** [comment]
NP theres no way of knowing.
