### ISSUE TITLE
[ALPHA] Agricraft villager issues

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#307]
I found two weird issue with new AgriCraft villager:
 - He does not have any ThaumCraft aspect (it seems like he have a different entity ID or something)
 - He seems like teleporting even in SSP where all other villagers are moving normally.

AgriCraft 1.4.0-alpha-7

**Comment by InfinityRaider** [comment]
Hes his own entity because he has a seperate AI routine (he seeks and removes weeds from crops)
And the "teleporting" I have seen before, and I'm thinking it's just really fast movement speed.
I haven't gotten around to lookign at it, but I certainly will.

**Comment by hron84** [comment]
@InfinityRaider ohh, then another bug: he actually does not do his work. I have a greenhouse with full of weed. Actually, there was a mystical purple flower at last visit, but after that I see only weed. I was very kind for him, and let him do his work but... 

Btw, this means I can stole him from the village and he'll keep clean my farm? :smile:

**Comment by InfinityRaider** [comment]
Ye, just make sure he doesnt run off, also he only has a limited range to look for weeds. I've put him in a pit with empty crops being irrigated and sat there afk for an hour, when I came back no weeds, so I'm quite sure it's working.

**Comment by hron84** [comment]
Hmm... he is out of the green house, that would be a problem then. Somehow he spawned outside or wandered out from the house, I do now know since the village is too far from my base to check it every time. But i will try to teleport him back somehow.

**Comment by hron84** [comment]
Update: I moved him back in a safari net, and he started working, but he opened a door remotely (from 5-6 block)... I think it should be slightly related to he can also rake out weeds remotely (more far than the normal player range can reach).

**Comment by InfinityRaider** [comment]
So Apparently I set the updatefrequency to 5 secs, for some reason >< so it was moving on the server, but its position was only synced to the client every 5 seconds, and as such it seemed to teleport.
This is fixed now.

Also
To derp or not to derp

**Comment by hron84** [comment]
I'll test it with the next release.

**Comment by InfinityRaider** [comment]
I'll do some testing myself first ^^

**Comment by InfinityRaider** [comment]
This seems to be fully fixed now.

**Comment by hron84** [comment]
Cool, thx
