### ISSUE TITLE
Growthcraft Compatibility (Bamboo)

### ISSUE THREAD

**Issue by kaovalin** [InfinityRaider/AgriCraft#308]
Trying Alpha 8 and still have an issue with the bamboo blocks from growthcraft. I can't craft bamboo blocks because they are crafted from 2x2 of bamboo sticks. This was not an issue prior to v1.4. Really dont want to add minetweaker for just one item in the game if possible.

**Comment by InfinityRaider** [comment]
I've said before that I'm not going to tweak recipes if certain mods are installed or not. Either use MineTweaker or ask the GrowthCraft dev to change the recipe.
