### ISSUE TITLE
Fix tanks crossing chunk boundaries bugging out on chunk loading

### ISSUE THREAD

**Issue by Terpo** [InfinityRaider/AgriCraft#312]
Happens for our map on server and clientside. Forge asks for missing blocks/items, creates the backup and tries to load the map. While loading the whole game stalles. Client is sitting in the MC main screen and trying to connect to a server (with stalled map) causes a simple timeout.

Forge 1448
AgriCraft-1.7.10-1.4.0-beta-1-1.7.10.jar

http://blog.terpo.org/upload/mc/modlist.txt

http://pastebin.com/fuqY2mMV
http://pastebin.com/NHAUuXfL

It only happens for our large server map. A small test world is loading fine. Could this happen if a large tank is not fully chunkloaded? After removing one large tank the map is loading, but it stalls again with the same issue.

**Comment by InfinityRaider** [comment]
What version did you update from?

**Comment by InfinityRaider** [comment]
Apparently I was saving the block name instead of the Block object itself, dont ask me why, I don't even know myself. I changed that, itll improve a little, but I don't think itll fix this.

If you can start the server on an older version, I recommend changing all tanks so that they don't cross chunk boundaries.

**Comment by InfinityRaider** [comment]
Another thing that crossed my mind, did you remove any mods that add planks that might have been used in the creation of a tank?

**Comment by Terpo** [comment]
I told my member today that everybody should respect the chunk boundries and I will also give it a last test tomorrow. After deleting the tanks in SP (testwise) it did work. So it should be ok for the update hopefully :). 

The server update is from AgriCraft-1.7.10-1.3.1

**Comment by InfinityRaider** [comment]
Well I'm going to have to something about this, so I'll leave this open.

**Comment by InfinityRaider** [comment]
haven't been able to reproduce after #404
