### ISSUE TITLE
Config typo ( yeah its me again )

### ISSUE THREAD

**Issue by Neodark7** [InfinityRaider/AgriCraft#314]
Man.... Ahaha Its a joke right ? :') 

https://github.com/InfinityRaider/AgriCraft/issues/313

https://github.com/InfinityRaider/AgriCraft/commit/c1ec88eca2f1168c798f9150b690d2ba5781e89b

**Comment by InfinityRaider** [comment]
:D

**Comment by Neodark7** [comment]
You get it right ? ^^

**Comment by InfinityRaider** [comment]
Ye, I'm starting to think I'm dyslectic

**Comment by InfinityRaider** [comment]
Also this is the pi*100'th issue, gz.
