### ISSUE TITLE
Forge Server Issue (FG #1448) - Getting crash when starting server

### ISSUE THREAD

**Issue by BlackHawkDoesGaming** [InfinityRaider/AgriCraft#315]
Hello, I've recently have been trying out my new forge server, running on build 1448, and once I drop the Agricraft mod into the mods folder with the all 250 other mods, and start the server, it then crashes, and the crash report reads that Agricraft is trying to find client-side file paths that obviously don't exist on a server. I don't know if this is a bug, or if I'm doing something wrong. 

My pack does include IC2 ...756-exp, and mekinisem. If you'd like the entire list of mods, you can find the unofficial pack here (get 1.7.10_1.4.1): https://goo.gl/zrN038

Crash Report: http://pastebin.com/raw.php?i=TrS4JQgN

**Comment by InfinityRaider** [comment]
Disable PneumaticCraft compatibility in the config
