### ISSUE TITLE
[request] Thaumic Bases support / Custom crop improvement

### ISSUE THREAD

**Issue by EdC94** [InfinityRaider/AgriCraft#316]
Thaumic Bases is, in my opinion, a great mod and add a fair share of plants but sadly they aren't compatible with agricraft crops, could you please add crop compatibility to them ?

Additionnaly, the custom crop function is great but would it be possible to add the possibility of creating custom crops using existing mod seeds so people could add mod support themself ?

**Comment by InfinityRaider** [comment]
There's too much too that to make it happen decently. The API will almost be released though so you then you can ask any other mod to add compatibility from their side.
I'll take a look at Thaumic Bases though.

**Comment by InfinityRaider** [comment]
I took a look at Thaumic Bases and its crops are all too different, it would be too much work to add an individual case for each of them.
If you want compatibility, go to the author of the mod and ask to add it from his side.
