### ISSUE TITLE
Seed strength when crossbreeding

### ISSUE THREAD

**Issue by xenoflot** [InfinityRaider/AgriCraft#317]
Hi,

I'm running a custom pack with Agricraft and a few complementary mods. I've found that when crossbreeding, some 'trash' seeds (IE same as the parent, not the desired hybrid) are random strength, others are 10,10,10 copies of the parent. Sadly I didn't record exactly which ones are doing this but right now I'm working on Alliums (from poppies and blue orchids). From triple 10 parents, the Allium seeds are 5's and 6's as expected. Trash blue orchid seeds are all 10s however the poppy trash seeds are also 5's and 6's.

Agricraft 1.3.1

Hunger Overhaul 1.0.0

Pam's 1.7.10i

Spice of Life 1.2.3

**Comment by InfinityRaider** [comment]
What do you mean with 'trash seeds'?

**Comment by xenoflot** [comment]
If you have (for example) 2 x Blue Orchid and 2 x Poppy, you're hoping to get Allium seeds.
By "trash seeds" I mean the blue orchid and poppies that you get instead of allium seeds.

For some plans they're at the normal child level (50-60% of the parents) but for some, they're the same level as the parent. I don't mind either way, just pointing out that it's not consistent.

**Comment by InfinityRaider** [comment]
I think I know what you mean, you'll probably have the config option set to the highest diffulty. Blue Orchids have Poppies as parents, meaning they can inherit stats from them. The poppies however don't have orchid as a parent so they will have a negative influence on the stats of the spread flower.
This behaviour is completely intended.

**Comment by xenoflot** [comment]
Ah, I see. Thanks for the clarification.

**Comment by InfinityRaider** [comment]
np
