### ISSUE TITLE
Server crashing when Seed Storage Box is put down

### ISSUE THREAD

**Issue by Galaxy2Alex** [InfinityRaider/AgriCraft#318]
Crashlog: http://paste.ubuntu.com/12038199

After a player tried to place down a Seed Storage Box on a custom modpack, the server decided to give up. After the restart, the box is not placed down, and if the player tried to place it down again, the server crashed again.

AgriCraft Version 1.4.0 beta-1
FastCraft is installed, full mod list can be found in the crash log.
Any additional information can be provided if necessary.

**Comment by InfinityRaider** [comment]
Thanks for the report, I'm able to reproduce the issue, however I'm  puzzled as to why it's happening.

**Comment by InfinityRaider** [comment]
Okay... I'm clueless...

**Comment by InfinityRaider** [comment]
Well I finally figured it out I think, fix incoming.

**Comment by Galaxy2Alex** [comment]
Thank you very much :)
