### ISSUE TITLE
New resource crops from 1.4 are not craftable

### ISSUE THREAD

**Issue by Mach12** [InfinityRaider/AgriCraft#319]
The title pretty much says it all: the new resource crops you added in 1.4 (Cinderpearl, Tainted Root, Shimmerleaf and Quartzantheum) cannot be obtained in survival mode as of now.

By the way, thank you for adding ways of farming these. I'm a Thaumcraft maniac and, even though these are technically craftable, crafting Cinderpearls and Shimmerleaves using vanilla Thaumcraft is painful so far.

Oh and I am aware that this might be just something you did not implement yet, I am just filing a ticket to ensure whether or not it is known, and follow the mod's development progress.

**Comment by InfinityRaider** [comment]
Set regenerate mutations to true in the main config.
If you've added your own mutations, back them up and copy them back in after.

**Comment by Mach12** [comment]
That worked indeed. In fact, I tried that before reading your comment, but after posting this.

My bad, I went too fast. Though, I don't remember seeing a notice telling that one should regenerate mutation upon updating. Did I miss it or is it missing?

**Comment by InfinityRaider** [comment]
No but it has been like that since the start.
I guess I should put a FAQ somewhere.
