### ISSUE TITLE
[Request] NetherCrops

### ISSUE THREAD

**Issue by UnRealDinnerbone** [InfinityRaider/AgriCraft#320]
I would be nice if there was a confit option so you can use crops in the nether and they would grow

**Comment by dmaster8** [comment]
That would be sweet! :P

**Comment by InfinityRaider** [comment]
I've thought about letting crops only grow in certain dimensions, however I haven't implemented this for the same reason that plants arent tied to biomes either: it's annoying if you have your base somewhere and you'd have to have multiple farms, and then people start chunkloading and so on.
Maybe I'll consider it after I reworked the soils and the strength stat.

**Comment by UnRealDinnerbone** [comment]
Ok
