### ISSUE TITLE
[Crash Report] GuiHandler accessing ClientOnly classes on server.

### ISSUE THREAD

**Issue by zlainsama** [InfinityRaider/AgriCraft#321]
Mod Version: 1.7.10-1.4.0-beta-1
Minecraft Version: 1.7.10
Forge Version: 10.13.4.1481
isServer: true
withFastcraft: false
isCauldronServer: true
Crash Report: http://pastebin.com/a3iSUG8h

how to reproduce: place down an oak seed storage in a server, right click on it.

Edit: this server is using chinese localization, part of the report is localized in chinese.

**Comment by InfinityRaider** [comment]
Is already fixed, see #318

**Comment by zlainsama** [comment]
oh, sorry. thanks.

**Comment by InfinityRaider** [comment]
np
