### ISSUE TITLE
Setting for disable low light requirement

### ISSUE THREAD

**Issue by erucolindo** [InfinityRaider/AgriCraft#322]
It would be nice to have a setting to disable the low light requirement for example netherwart, to make it have the same requirements as in vanilla.

I'm not experienced enough to add this feature myself. But looking at the code, I would probably just check the config file for a "require darkness for dark crop" setting and then instead of setting req.setBrightnessRange(0, 8), set it to (0,15).

**Comment by InfinityRaider** [comment]
Can be done with MineTweaker on a per crop basis, and there aren't that many crops that require low light levels.

**Comment by erucolindo** [comment]
I guess I should have done more reading, didn't know you could do that with MineTweaker. Thank you!

There might be a bug though. I've set the nether wart brightness to be 15:

    mods.agricraft.growing.Brightness.set(<minecraft:nether_wart>, 0, 15);

But it only grows when the blocklight is 13. And if I change it to 14, it only grows in 12 or under. Am I doing something wrong, or is there a bug?

Running Agricraft 1.3.1 and MineTweaker 3.0.9C

**Comment by erucolindo** [comment]
Just upgraded to 1.4.0-beta-1 and did some testing. Now it seems like the value is 1 lower. So if I set the brightness to 15 the netherwart grows at 14 or lower. The same for the other low light level crops.

**Comment by InfinityRaider** [comment]
Ye that was a little bug, which was fixed.
