### ISSUE TITLE
[Beta 1 - 1.4.0] Poisonous potatoes drop too frequently

### ISSUE THREAD

**Issue by ZiaAvenicia** [InfinityRaider/AgriCraft#323]
I've noticed that poisonous potatoes seem to drop a lot more frequently with AgriCraft than with vanilla farming. Is this intentional, or is this a bug?

**Comment by InfinityRaider** [comment]
normal potato weight is 100
Poisonous potato weight is 10, so it'll be 10/110 chance that you'll get a poisonous potato.
If it seems more, than its just RNG and if you don't like the numbers, you can always change them with MineTweaker.
