### ISSUE TITLE
Computercraft Support?

### ISSUE THREAD

**Issue by austin5919** [InfinityRaider/AgriCraft#324]
There seems to be a lot of ComputerCraft related code in this mod, but I cant seem to access any of it with a computer. Has it not been fully implemented yet or maybe I'm missing something?

* AgriCraft Version 1.7.10 - 1.3.1
* ComputerCraft Version 1.74

**Comment by InfinityRaider** [comment]
AgriCraft 1.3.1 is months old, if you would look at the builds on curseforge you'd see that there is a beta release available.
However this doesn't have the peripheral implemented yet because its still a WIP
