### ISSUE TITLE
Improper item removal

### ISSUE THREAD

**Issue by sfPlayer1** [InfinityRaider/AgriCraft#325]
After updating from version 1.2.3 to 1.4.0 the following blocks/items are being reported as missing:

> AgriCraft:cropMelon
> AgriCraft:cropPumpkin
> AgriCraft:cropPumpkin
> AgriCraft:cropMelon
> AgriCraft:sprinklerItem

If they are supposed to be removed, FMLMissingMappingsEvent (FML @Mod event) should be used to explicitly ignore the missing mapping.

**Comment by InfinityRaider** [comment]
Didn't know that, I'll go take a look at it, thanks for letting me know.

**Comment by sfPlayer1** [comment]
It's probably as easy as this:

```java
@EventHandler
public void onMissingMappings(FMLMissingMappingsEvent event) {
	for (MissingMapping mapping : event.get()) {
		if (dropped.contains(mapping.name)) {
			mapping.ignore();
		}
	}
}
```

with dropped being a set with all removed names (like AgriCraft:cropMelon).

**Comment by InfinityRaider** [comment]
I'll finish some more things and then I'll push a new build to CurseForge.
