### ISSUE TITLE
Custom Crop Enhancement

### ISSUE THREAD

**Issue by teamMK** [InfinityRaider/AgriCraft#326]
It would be nice to have some enhancements to the crops:

1. Lightlevel: A control for your crops in wich light level they can grow [Depending on plants strength: MinLL (Strength 10) and MaxLL(Strength 1) between maybe linear scale].

2. Biome Control: In wich Biomes these plants can grow (Maybe the plants get new biome addition due mutation with other crops).

3. Proprabillity: A second output option, where you can specify the porpability for another output.

4. Humidity/Dryness: Maybe some plants like it dry and some humid, dry plants die by constant irrigation, some die when there is no irrigation system.

Thats some things wich could enhance the mod :-)

**Comment by thephoenixlodge** [comment]
1 and 3 are already achievable with the Minetweaker integration.
2 and 4 are up to InfinityRaider.

**Comment by InfinityRaider** [comment]
Thanks for the suggestion, and indeed, drops and growth conditions can be altered with MineTweaker.
I will not tie plants to biomes, because when you have your base in one biome, you'd have to go look for another biome and start crossbreeding there. Humidity will be part of the new soil system.

**Comment by lawremi** [comment]
While I agree that crops should not be restricted to specific biomes, one could use the biome when modeling the humidity and rainfall. Growing a crop in a non-ideal biome could simply require a different level of irrigation and soil engineering.
