### ISSUE TITLE
[BETA] weed took over the world

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#327]
So, as I said, after logging in I walked to the garden to see what can I do today with my garden and the whole garden was overtaken  by weed, only the standalone crops survived (I have few flowers prepared for breeding Botania stuffs). I definitely remember the status was not as bad as I found it now, especially because I usually do not leave an empty crop or crosscrop without my control. I do not know what can be happened, this is never happened with me before - and because I spent a loooot of time in Regrowth, this means a long time. Maybe I did not noticed something, but...

The modlist is still same as in #310. If you need any other information, I will be happy if I can help to solve this problem.

**Comment by InfinityRaider** [comment]
Did you update any other mods between updating?

**Comment by hron84** [comment]
@InfinityRaider no, the modlist is exactly same that you already know, I have BETA-1 of AgriCraft, and that mods that I already sent to you.

**Comment by hron84** [comment]
The only thing you do not know yet is my config: https://gist.github.com/hron84/8e639081bbe5ee66dc8f

**Comment by InfinityRaider** [comment]
You're sure you didn't overlook one empty crop? I've just planted a field full of crops and I'll go afk for a while to see if they get overtaken by weeds or not.

**Comment by hron84** [comment]
This was a 3x3 sugarcane improver thingie (plant on sides, crossbreed on edges and on the center, the center breeds the best stats) and on right side I had a poppy to crossbreed a cactus. I had a cactus green in my inventory but no cactus seed so I'm pretty sure the cactus was there and the poppy was never removed since I wanted to make a backup cactus seed later. The cactus green cannot go into my inventory another way since I do not have a desert in 1000 block range.

**Comment by InfinityRaider** [comment]
Do you have a backup of your world?

**Comment by hron84** [comment]
Yep, but a bit old.

**Comment by InfinityRaider** [comment]
Okay, can you copy that backup and load it up with the new version of agricraft and see if any plants got removed from existing crops?

**Comment by hron84** [comment]
With  BETA-2?

**Comment by InfinityRaider** [comment]
yes

**Comment by hron84** [comment]
@InfinityRaider do you online on IRC (esper)? Can we continue there? I do not think we should fill issues with the whole details of the debugging.... Same nick.

**Comment by InfinityRaider** [comment]
No I'm not on IRC, but I am on the FTB TeamSpeak

**Comment by InfinityRaider** [comment]
Any update on this? Is this still happening, because I have not been able to reproduce it myself yet.

**Comment by hron84** [comment]
It did not popped up yet, so I think it's solved. If it happens again, I will mention you in this issue and/or ping you on TS.

**Comment by InfinityRaider** [comment]
I guess it was just some weirdness with the ItemRegistry being fucked up after I removed some items incorrectly.
