### ISSUE TITLE
[BETA] Agricultural journal sometimes list ingredients as mutation

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#329]
So, I usually scan all my seeds and now I just started to check Agricultural journal, and sometimes it lists the source of the breeding at mutations page, sometimes it doesn't. For example, Mystical Blue Flower seeds + cactus seeds = Mystical Black seed listed both on Black and Blue flower page. Also, Poppy seeds page lists Cactus + Pumpkin = Poppy recipe at Mutations page. 

I have no problem with listing source and target mutations, but 1) it should be consequent and 2) we should separate the two recipe with different titles.

Also I think the seed analyzer plays book opening sound more than one times at once, so it makes a very loud pitch. It should be more mild.

**Comment by InfinityRaider** [comment]
It will list the mutation, doesnt matter if its a parent or a child, as long as all three seeds are analyzed, if one of them isn't, the mutation will not show up.

I'll take a look at the sound thing.

**Comment by hron84** [comment]
But is there a way to separate parent/child mutations visually?

**Comment by InfinityRaider** [comment]
I could do that yes

**Comment by InfinityRaider** [comment]
I made it so:
http://puu.sh/jEDDy/2f7b041975.png

**Comment by hron84** [comment]
I think you swapped the titles, but otherwise I'm lovin' it.

**Comment by hron84** [comment]
@InfinityRaider also, coould you fix the sound thing? I'm pretty sure it plays the sound at least twice. I had a small slowness in my laptop yesterday, and now I heard the two sound separatedly.
