### ISSUE TITLE
[BETA] Shears does not drop anything

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#332]
If i use a shear on a cropstick it does not drop neither the normal product neither the block. For example, if I use shears on cactus block I expect it drop a cactus green or a cactus block, no drop received. 

Crop growth state become updated.

**Comment by InfinityRaider** [comment]
Shears start working from higher growth levels only, whats the gain on the cactus

**Comment by hron84** [comment]
@InfinityRaider so it means shears not working unless cactus has big gain level? but why "ungrow" the plant then?

**Comment by InfinityRaider** [comment]
Its a harvest attempt, it just drops the amount of fruits/2, because flowers give you twice the dye.
And 1/2 = 0.
