### ISSUE TITLE
Greenhouse resource crops

### ISSUE THREAD

**Issue by Thiana** [InfinityRaider/AgriCraft#333]
Could you please add an option to allow only basic vanilla crops in greenhouses? As it is, you often see resource crops like redstone generating in the greenhouse. 

Thanks.

Version Used: 1.4 beta 2

**Comment by InfinityRaider** [comment]
I didn't do the "basic vanilla crops", instead I added a config option for the maximum allowable tier in greenhouses.

**Comment by thephoenixlodge** [comment]
A note to add to this, could Witchery Wormwood be blacklisted from appearing in greenhouses? It's normally gated behind spirit world access.

**Comment by InfinityRaider** [comment]
I'll increase the tier of it
