### ISSUE TITLE
Feature Request: Advent of Ascension Support

### ISSUE THREAD

**Issue by Killarflame** [InfinityRaider/AgriCraft#334]
This mod is also known as nevermine and it contains 14 crops at present. 
I was hoping that support could be added for this.

**Comment by MaienM** [comment]
While this adds support for the crops in AoA, it does not seem to add resource crops for it's ores. I don't know what the policy on this is, and whether there is any way to add these yourself (I saw that MineTweaker support is incomplete, so probably not).

**Comment by InfinityRaider** [comment]
Why would MineTweaker support be incomplete?
If you want resource crops for other ores, there is the possibility to add custom crops yourself.

**Comment by MaienM** [comment]
I saw the "MineTweaker3 integration is currently in development" on the README of this repository, and I understood that to mean the integration was not yet complete/functional. Looking at it again, I now see that I completely missed the link to the MineTweaker3 docs above that, so my bad for not reading all of the readme properly. Sorry for wasting your time!

**Comment by InfinityRaider** [comment]
Oh ye, that readme hasn't been updated in ages, my bad.
