### ISSUE TITLE
[BETA agricraft] Texture displacement

### ISSUE THREAD

**Issue by 23Link89** [InfinityRaider/AgriCraft#336]
When I place tanks or irrigation channels the texture is place 2 blocks away but the hitbox is still there. It just might be optifine.

**Comment by InfinityRaider** [comment]
Can you add a screenshot of this, and try without Optifine as well?
Also, what version is this?

**Comment by 23Link89** [comment]
It working fine without optifine
![2015-08-20_10 52 26](https://cloud.githubusercontent.com/assets/8294697/9388225/c62e18dc-4729-11e5-91fd-e6d9cbd9096e.png)

**Comment by InfinityRaider** [comment]
Update to the last beta and see if it persists, I changed a small thingy in that one.

**Comment by 23Link89** [comment]
Well now it's just taking a while to put the texture there but it shows up then when I break the blocks it flashes the texture. .-.

**Comment by InfinityRaider** [comment]
huh?

**Comment by 23Link89** [comment]
When I place a block down it shows up but when I break it the texture will flash from being there to not being there.

**Comment by InfinityRaider** [comment]
But is that a problem when you break the block?

**Comment by 23Link89** [comment]
Yes because the block isn't there but the texture for it flashes being there to not being there.

**Comment by InfinityRaider** [comment]
So the texture stays or what?

**Comment by 23Link89** [comment]
The texture shows up but when you break it it flashes the texture.

**Comment by InfinityRaider** [comment]
I'm sorry I have no idea what you mean by that :s

**Comment by 23Link89** [comment]
1. You place block 2. texture shows up in the right spot 3. When da block broken = texture still there but it flashes the texture from being there to not being there but the actual block isn't there. meakz da centz?

**Comment by InfinityRaider** [comment]
"The texture flashes...", okay thats a minor nuisance, 
"...from being there to not being there but the actual block isn't there", so no texture and no block, I don't see the problem?

**Comment by 23Link89** [comment]
Flashing texture when block broken

**Comment by InfinityRaider** [comment]
Okay, thanks, now I understand

**Comment by InfinityRaider** [comment]
Sadly I have no idea why it's happening and there's no way for me to debug this. You'll either have to play with Optifine settings, or take this to the Optifine devs.
