### ISSUE TITLE
[REQ] Return Vanilla-like behavior and look for some crops

### ISSUE THREAD

**Issue by anion155** [InfinityRaider/AgriCraft#338]
First of all I think this mod is great!
I like almost everything about this mod. I like the way seeds attributes implemented, like the mutation mechanism.
I like all plants common interface, so I can work with all of them the same way. But it's also the only thing I ~~hate~~ dislike about this mod.
In Vanilla MC I was have to make different farms for different types of plants, like sugarcane farm, melon and pumpkins farms, cactus farm. And I really miss this in AC.

I have couple of suggestions (that I probably must put in different threads, witch I will do if ~~you don't call me crazy~~ someone else will like it :) ):
* Vanilla-like models for sugarcane and cactus;
* Vanilla-like limitations for sugarcane (block of water nearby) and cactus (no blocks nearby);
* Vanilla-like growth behavior for sugarcane and cactus: when it's mature it growth couple blocks upper depending on crop growth-factor, and obviously when harvested block all uppers harvests too, but when bottom block with crops harvested it goes with standard AC mechanics. For cactus upper blocks, if they detect block nearby they will harvest automatically;
I want pumpkins and melons be more like vanilla too, but still don't know how.

**Comment by anion155** [comment]
It's worth to mention.

This features doesn't change automation capabilities of crops, machines still can interact with crops block.

Sugarcane and cactus feature must be easy to implement.
Add a block that has only 2 features: show plant, and when harvested, harvest upper blocks.
To crops block for mature state add ability to produce one block described above. 3 additional blocks max for 10 growth attribute, and 0 for 1.

**Comment by InfinityRaider** [comment]
Thank you for your opinion and suggestion, I appreciate that, however it doesn't quite fit with what I want for my mod so I will not implement it.
