### ISSUE TITLE
Allow mid-file comments for custom crops.

### ISSUE THREAD

**Issue by Kubuxu** [InfinityRaider/AgriCraft#34]
It would allow grouping custom crops in config.

**Comment by InfinityRaider** [comment]
Add in a hashtag as the first character of a line and the line will be skipped

**Comment by Kubuxu** [comment]
But when I tried it last time it was only working on the beginning of the file.

**Comment by InfinityRaider** [comment]
What version are you using?
Is it crashing if you try that?

**Comment by Kubuxu** [comment]
It might work now. We have tried it a bit of time ago.

**Comment by InfinityRaider** [comment]
Problem is my configs are quite fiddly, if you do it wrong, it crashes. I've added in error checking for every config (ecb710260eb5a32fcf9d2ae401c53377ed90c0dd) to prevent it from crashing. If you do something wrong, it will tell you in the log.
