### ISSUE TITLE
RotaryCraft Canola is duping

### ISSUE THREAD

**Issue by lesdmark** [InfinityRaider/AgriCraft#340]
When you plant the canola on crop sticks it plants another set of seeds on tilled soil that doesn't have cropsticks. was able to reproduce the issue everytime I tried.

**Comment by InfinityRaider** [comment]
What version of AgriCraft?

**Comment by lesdmark** [comment]
1.4.0 beta 1. I just tested it in 1.4.0 beta 2 as well. What happens is whenever you place canola on the crop sticks the square of farmland your standing on with no cropsticks also gets canola and it adds 111 canola in your inventory slot as well. I am using minetweaker but only to define mutations and I have the config set to not let you plant anything without crop sticks

**Comment by InfinityRaider** [comment]
Thats weird

**Comment by lesdmark** [comment]
Correction cheat mode was what was causing the 111. but the other stuff still happens. you plant one and it plants another non crop stick one beside it. It's very strange

**Comment by InfinityRaider** [comment]
I apparently already changed right click behaviour after the last update, this should have fixed that:
https://github.com/InfinityRaider/AgriCraft/commit/3074f998a601ee9a01f87be85e991651a629a6a4#diff-766954c4303b52309bfefd01003d3d75L283

**Comment by lesdmark** [comment]
Glad it's already fixed will just wait on the patched version then and ignore the bug

**Comment by InfinityRaider** [comment]
There's two things I want to finish before the final beta release, but I find myself with a lack of time lately, so I can't tell you when it will be.

**Comment by lesdmark** [comment]
No rush. Better to be done right then to be done now. I just appreciate you looking into it and letting me know what's going on. :)
