### ISSUE TITLE
Omega Garden (Suggestion)

### ISSUE THREAD

**Issue by teamMK** [InfinityRaider/AgriCraft#341]
Hey,

maybe a late game farming idea. The omega garden multiblock structure wich will grow your crops more efficient but use water and rf. the Count of plants that can grow inside depends on the structure size 3*3*X.

Additions/Upgrades/Crossmod Integration:

1. Autofarming Upgrade
2. Lamp of Growth Neon lights (replace the normal lights with some kind of thaumic green lamp of growth)
3. Mana Injector ( machine can use mana for some placed agricarnation flowers)
4. Efficiency Upgrade (lower rf and water cost)
5. UV Lamp, weak crops grow at night.
6. Fertilizer Injector ( Additonal Resource Output [use some Bonemeal/Fertilizer])

Edit: This is a pic of the omega garden in rl:
http://www.ecofriend.com/wp-content/uploads/2012/07/omega_2_lAwTC_69.jpg
https://a1-images.myspacecdn.com/images01/124/d223746de2f0e42eb6aa89a7beddc949/full.jpg

**Comment by InfinityRaider** [comment]
Thanks for the suggestion, I like the idea, however I don't want to make my mod into an RF-mod. Don't get me wrong, I like RF, but I just don't want AgriCraft to be an RF-mod.
This could be made into an addon though.
