### ISSUE TITLE
[BETA] Agricraft + Harvestcraft Candleberry harvesting crash

### ISSUE THREAD

**Issue by TigersFangs** [InfinityRaider/AgriCraft#342]
Here is the pastebin of the error that crashed the game:  http://pastebin.com/tJbuSxFa

This error occurred several times while trying to right-click harvest the Candleberry crop from Harvestcraft that has been planted on Agricraft crop sticks.  The plant grows perfectly, and mutates correctly(stat increase only, have not tried mutating the crop or mutating from the crop yet), but will not let me harvest and shows no produce at all in NEI.

As a side note, I have tried to add the Candleberry as a fruit of the crop using Minetweaker and it tells me when I try to load the script that 'Candleberry Seed' is not a valid seed.  For reference, here is the script that I am trying to use:

`import mods.agricraft.CropProduct;`

`val seedCandle = <harvestcraft:candleberryseedItem>;`
`val fruitCandle = <harvestcraft:candleberryItem>;`

`CropProduct.add(seedCandle*1, fruitCandle*1, 10);`

Not sure if I coded the MT script right, but that is not the purpose of this bug report. ;)

The only other bug that I've run into was not having a registered recipe for Silverweed mutation.  That was easy enough to fix in the configs though. :)

**Comment by InfinityRaider** [comment]
Update to prevent crashing
and go bug Pam to correctly register the seed and fruit to the OreDictionary
also, see #304
