### ISSUE TITLE
Seeds base-block choosing specific ore instead of oredict entries

### ISSUE THREAD

**Issue by kotoroshinoto** [InfinityRaider/AgriCraft#343]
It wants me to use immersive enginnering ores for a good number of them rather than any given version. Its quite annoying.

**Comment by kotoroshinoto** [comment]
i'm aware that nei only shows one base block, but i'm trying to mutate a copper seed and just having no success (75% mutation rate is being used)

**Comment by kotoroshinoto** [comment]
oh wait... wrong tulip

**Comment by InfinityRaider** [comment]
:p
