### ISSUE TITLE
[Feature Inquiry] Non-general soil whitelist

### ISSUE THREAD

**Issue by kotoroshinoto** [InfinityRaider/AgriCraft#345]
Is it possible to put a block type in the whitelist without having it registered as a generic soil?

(like if I wanted to make a custom crop that needed ender cores or end stone, but didn't want to use those as a base block, and just use them directly as a soil type)

**Comment by InfinityRaider** [comment]
Any block given as a soil will be able to have crop sticks planted on them

**Comment by kotoroshinoto** [comment]
Do you mean defined as the soil for the custom crop?

**Comment by InfinityRaider** [comment]
Yes
