### ISSUE TITLE
Corrupt Ex Nihilo recipe

### ISSUE THREAD

**Issue by DreamingLamb** [InfinityRaider/AgriCraft#346]
The Ex Nihilo to Agricraft seed recipes are corrupt in AgriCraft-1.7.10-1.4.0-beta-2-1.7.10.  The recipes work as normal in AgriCraft-1.7.10-1.4.0-beta-1-1.7.10.

Affected seed recipes:
Sugar Cane
Cactus
Potato
Carrot

**Comment by chaoskagami** [comment]
Hardcore Ender Expansion is also complaining about this one. :/

This occurs in the lastest source on git as well (I built it to test.)

**Comment by InfinityRaider** [comment]
I'll have a look at this right now.
