### ISSUE TITLE
Soil got infertile after placing a sign for identification

### ISSUE THREAD

**Issue by Fogrits** [InfinityRaider/AgriCraft#349]
Sounds ridiculous, but that's what I get from placing a sign on the wall above the crop stick D:

Before placing the sign: (note the text in Waila: This plant is fertile and can grow)
![2015-09-01_18 31 07](https://cloud.githubusercontent.com/assets/14002834/9617183/a194d8c8-50d7-11e5-8954-3c471251de2a.png)

After placing the sign (note the text in Waila: This plant can not grow here)
![2015-09-01_18 31 18](https://cloud.githubusercontent.com/assets/14002834/9617184/a19a3ed0-50d7-11e5-8cab-7c2e7eb9120c.png)

**Comment by thephoenixlodge** [comment]
IIRC, due to the compatibility with 2 block tall plants in 1.4, the block above the crop sticks needs to be empty.

**Comment by InfinityRaider** [comment]
Yes, the block above the crop has to be air.
