### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Chupp4-Jo3** [InfinityRaider/AgriCraft#352]
https://www.dropbox.com/s/moayqoqd44hy6j3/Agricraft%20Possibly.txt?dl=0

I have no idea if this is Agricraft's fault but game works when I disable it

**Comment by InfinityRaider** [comment]
Villager ID conflict. Change the ID in the config, or update the mod.

**Comment by Chupp4-Jo3** [comment]
Ah thanks
