### ISSUE TITLE
[BUG][BETA] Generated multiblock tanks in villages does not form

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#354]
I started to discover a newly generated world, and I met with this structure: 
![2015-09-07_08 17 43](https://cloud.githubusercontent.com/assets/88636/9710290/2b98b340-5539-11e5-873a-8df34cc4ebce.png). The tanks however does not formed the multiblock, I had to break and re-place one tank block to form the multiblock.

Agricraft: 1.4.0-beta-2

**Comment by InfinityRaider** [comment]
Thanks for reporting this, I could confirm and I also confirmed the fix works
