### ISSUE TITLE
Javadoc & Commenting

### ISSUE THREAD

**Issue by RlonRyan** [InfinityRaider/AgriCraft#356]
The documentation for the code is quite sparse, and needs some work.

Also it may be nice to post the Javadoc on the GH-Pages branch for other authors wishing to interact with this mod.

**Comment by InfinityRaider** [comment]
I'm aware of it, but I am also a bit lazy, I'll try to document a method if I do some work on it from now on.
And what exactly does posting the javadoc on GitHub pages involve?

**Comment by RlonRyan** [comment]
You just copy the generated javadoc to the gh-pages branch.

**Comment by RlonRyan** [comment]
Are you on IRC espernet? It would make it a whole lot easier to run things by you if you were.

**Comment by InfinityRaider** [comment]
I don't use IRC, sry

**Comment by RlonRyan** [comment]
Oh and we should add the jar form of the java doc to the release pages the next time we do a release.

**Comment by RlonRyan** [comment]
Is there a formatting specification to use? Just for the sake of sanity...

**Comment by InfinityRaider** [comment]
If it's only one line, only use the one line.
One line to separate parameters from the description, and thats about it I guess.

**Comment by RlonRyan** [comment]
Lol... I think if I wasn't adding javadoc everywhere, my contributions would be mainly deletions...

(How is deleting contributing?)

**Comment by InfinityRaider** [comment]
Less code for the same job is better

**Comment by RlonRyan** [comment]
Amen to that brother.
