### ISSUE TITLE
Occupied Seed Storage Breaks Rendering For Grates to East

### ISSUE THREAD

**Issue by RlonRyan** [InfinityRaider/AgriCraft#357]
It's really quite funny...
![2015-09-08_00 43 49](https://cloud.githubusercontent.com/assets/3212966/9728091/d991ef3c-55c2-11e5-9afe-e82c07c81c25.png)

It only lasts to the edge of the chunk, however.

**Comment by RlonRyan** [comment]
Still pretty funny, however... Isn't it always interesting how bugs work?

**Comment by InfinityRaider** [comment]
Ye well, I was doing a hacky workaround to render that item on there, but I didn't do it correctly obviously.
