### ISSUE TITLE
Flower without fruit.

### ISSUE THREAD

**Issue by Kubuxu** [InfinityRaider/AgriCraft#36]
Before this update we were adding flower which was giving no fruit.
It turns out that after config parsing improvements it is not longer possible.
```
Error when adding custom crop: Invalid fruit (line: vitaTherionis,minecraft:air,minecraft:soul_sand,2,6,It Give Nothing You Filthy Mothercoder!)
```
Is there any way to create flower giving nothing?

**Comment by InfinityRaider** [comment]
I didn't really consider the fact that people might want to add crops that provide nothing, I'll make this possible.

**Comment by InfinityRaider** [comment]
Here's a hotfix version with this functionality. For a fruitless crop, write "null" where the fruit should go (don't include the ").
Link: http://www.mediafire.com/download/9hnk3gc1vt5423a/AgriCraft-1.1.1a.jar
