### ISSUE TITLE
Neighbour update crash (incompatibility with AppEng?)

### ISSUE THREAD

**Issue by Cypher121** [InfinityRaider/AgriCraft#366]
Crash report: http://pastebin.com/AymJNbyt
Same happens with beta version. May be Applied Energistics problem.

**Comment by InfinityRaider** [comment]
Can you update to 1.4 and give me a new crash report? I can't do anything with that stacktrace.

**Comment by Cypher121** [comment]
This one is 1.4: http://pastebin.com/uRQsvNXY

**Comment by Cypher121** [comment]
NVM, it seems that my world is just broken after update and tileentities don't match blocks
