### ISSUE TITLE
[BETA] Water pad cannot created

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#367]
I still use beta-2 jar and the watered farmland that is needed for witchery water artichoke cannot created with BluePower shovel neither with vanilla wooden shovel. Is there any new release that I can try out? Or it is an actual issue? I cannot decide.

I tried to right click with a BluePower and vanilla wooden shovel to a wet farmland and the water pad does not form.

Modlist:

```
AdminCommandsToolbox-0.0.2a_1.7.10
AgriCraft-1.7.10-1.4.0-beta-2-1.7.10
appliedenergistics2-rv2-stable-9
Aroma1997Core-1.7.10-1.0.2.14
AromaBackup-1.7.10-0.0.0.5
Artifacts-1.1.2
AsieLib-1.7.10-0.4.1
Automagy-1.7.10-0.25
Bagginses-2.1.1
bdlib-1.9.0.94-mc1.7.10
BiblioCraft[v1.10.4][MC1.7.10]
BiblioWoods[Forestry][v1.7]
BluePower-1.7.10-0.2.954-universal
Botania r1.6-193
buildcraft-7.0.13
buildcraft-compat-7.0.8
Carpenters Blocks v3.3.6 - MC 1.7.10
CGOrigin-1.7.10-3.2.0
Chisel2-2.4.1.40
ChiselFacades-1.7.10-2.11-cricket
CodeChickenCore-1.7.10-1.0.6.43-universal
CoFHCore-[1.7.10]3.0.3-303
Computronics-1.7.10-1.5.1
CustomMainMenu-MC1.7.10-1.6
D3Core-1.7.10-1.1.0.29 (1)
EnchantingPlus-1.7.10-3.0.2-d
EnderIO-1.7.10-2.3.0.393_beta
EnderStorage-1.7.10-1.4.7.36-universal
EnderZoo-1.7.10-1.0.9.18
extrautilities-1.2.5
fastcraft-1.21
Forbidden Magic-1.7.10-0.562
forestry_1.7.10-3.5.7.16
ForgeMultipart-1.7.10-1.1.2.332-universal
GekosLasers-1.7.10-0.8
growthcraft-core-1.7.10-2.1.0a
growthcraft-fishtrap-1.7.10-2.1.0a
iChunUtil-4.2.2
ImmersiveEngineering-0.4.4
ImmersiveIntegration-0.4.1
industrialcraft-2-2.2.757-experimental
INpureCore-[1.7.10]1.0.0B9-62
InventoryTweaks-1.59-dev-152
ironchest-1.7.10-6.0.62.742-universal
Jabba-1.2.1a_1.7.10
JourneyMap5.0.1_Unlimited_MC1.7.10
MineTweaker3-1.7.10-3.0.9C
MmmMmmMmmMmm-1.6
ModTweaker 2-0.7.5
ModularArmour-1.7.10-1.0.15-38
Morph-Beta-0.9.1
Morpheus-1.7.10-1.6.4
neiaddons-1.12.10.33-mc1.7.10 (1)
NEIPlugins-MC1.7.10-1.1.0.11-unofficial
NotEnoughItems-1.7.10-1.0.4.107-universal
NotEnoughKeys-1.7.10-1.0.0b29
ObsidiPlates-1.7.10-universal-3.0.0.18
OpenBlocks-1.7.10-1.4.1
OpenComputers-MC1.7.10-1.5.13.27-pre.1-universal
OpenModsLib-1.7.10-0.7.1
pressure-1.2.1.108-mc1.7.10
ProgressiveAutomation-1.7.10-1.6.18
QmunityLib-1.7.10-0.1.114-universal
Railcraft_1.7.10-9.6.1.0
RedstoneArsenal-[1.7.10]1.1.1B1-85
ResourceLoader-1.2
SimplyJetpacks-MC1.7.10-1.5.1
SolarFlux-1.7.10-0.8a
StevesWorkshop-0.5.1
StorageDrawers-1.7.10-1.5.12
supercraftingframe-1.7.10.3
tcnodetracker-1.7.10-1.1.1
Thaumcraft-1.7.10-4.2.3.5
thaumcraftneiplugin-1.7.10-1.7
thaumicenergistics-0.8.10.5
ThaumicExploration-1.7.10-1.1-37
thaumichorizons-1.7.10-1.1.1
ThermalDynamics-[1.7.10]1.1.0-161
ThermalExpansion-[1.7.10]4.0.3B1-218
ThermalFoundation-[1.7.10]1.2.0-102
ThermalRecycling-1.7.10-0.3.9.7
TorchTools-1.7.10-1.2.0.26 (1)
TravellersGear-1.7.10-1.16.4
Tubes-1.7.10-2.0.5
Waila-1.5.10_1.7.10
WailaHarvestability-mc1.7.x-1.1.2
witchery-1.7.10-0.24.1
WitchingGadgets-1.7.10-1.1.9
```

**Comment by InfinityRaider** [comment]
You are rightclicking tilled soil, correct? It works fine for me.

**Comment by hron84** [comment]
I right click on a tilled farmland (NEI says it's a farmland and optically it seems like wet) but nothing happens. What tool do you use for it? Wooden shovel would be eligible to do this?

**Comment by InfinityRaider** [comment]
Any shovel, try removing GrowthCraft to see if that is interfering.

**Comment by hron84** [comment]
@InfinityRaider I removed GrowthCraft. now wooden shovel works, but BluePower shovel not.

**Comment by InfinityRaider** [comment]
That might be an inocmpatibility, yes. I've set the priority of my handler to highest, that's all I can do.

**Comment by hron84** [comment]
Thank you very much. Btw, no hurry, but when we can expect next beta? You did so many awesome improvement and I would like to test them out... No ETA expected here, just... okay, I'm impatient.

**Comment by InfinityRaider** [comment]
I watn to finish the peripheral, then I'll put out the final beta.

**Comment by hron84** [comment]
I'm glad to hear.

**Comment by RlonRyan** [comment]
I don't think that there is a good way to determine what tools can create the water pad on right click outside of vanilla, since there are too many tools that do odd things when you right-click in modded Minecraft. I suppose the only option would be a tool right-click white list in the configuration files, for modpack creators to determine what will and will not work.

**Comment by InfinityRaider** [comment]
instanceof ItemSpade works fine.

**Comment by RlonRyan** [comment]
I was thinking that should work, but some shovel-type items do different things on the right click, like the mattock from TiC. I suppose, however, if we consume the right click, that would prevent the different behavior making it work.

**Comment by InfinityRaider** [comment]
TiC is already handled

**Comment by RlonRyan** [comment]
Yeah I see that now, sorry.

**Comment by hron84** [comment]
Mattock works only on untilled soil, and it does nothing on tilled one. No
functional collision here.
2015.09.17. 18:41 ezt írta ("RlonRyan" <notifications@github.com>):

**Comment by RlonRyan** [comment]
Should this be closed? This does not appear to really be all that much of agricraft's fault?

**Comment by hron84** [comment]
I think raising the priority of the handler should be enough, even if I can't try it out without a released version of the fix. 

Can be closed from my part, if this is still an issue, I will poke him and ask to reopen.

**Comment by InfinityRaider** [comment]
Very well
