### ISSUE TITLE
[Enhancement] Add seed as a secondary drop to some plants

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#369]
It would be good if Industrial Hemp (from IE) and Flax (from Blue Power) can yield a seed as a secondary drop, since - especially with hemp - the seed is more important item than the primary yield.

I think to same thing like poisonous potato for potato and icy needle for witchery snowbell.

**Comment by hron84** [comment]
For BluePower, check [this](https://github.com/Qmunity/BluePower/blob/master/src/main/java/com/bluepowermod/block/worldgen/BlockCrop.java#L162), for IE, it has only [this](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/plant/BlockIECrop.java#L113) but maybe it would not help for you. I think both plant need a bit better chances than poisonous potato yields.

**Comment by InfinityRaider** [comment]
This has been requested before, however it doesn't fit into how agricraft works, It's possible to set up an automated system to have one crop spread to 4 neighbours and then harvest the newly spread crop (plant + crop sticks) and apply a new set of crossing crops.
You could even just use autonomous activators to use a rake and crop sticks to farm seeds.
Options enough.

**Comment by hron84** [comment]
Yep, but as your support spread over all farming mods, there would no easy way to automatically farm stuff by breaking the whole block (crop+plant).

AA can work - if you have any block like this, but cannot work in a ThermalExpansion-less world, especially in magic-focused worlds (flax seeds are for make paint buckets so they're purely asthetical and no industrial style included here).

**Comment by SkinHeadBaby** [comment]
i think there must be a config option or something for industrial hemp seeds since with disabled vanilla farming you cant farm industrial hemp seeds unless doing it manualy with the clipper or cross breeding which is a pain
