### ISSUE TITLE
Replace direct referencing of other mods with reflection

### ISSUE THREAD

**Issue by InfinityRaider** [InfinityRaider/AgriCraft#371]
These mods' classes are still directly being referenced on initialization, has to be replaced with reflection:
 - [x] Botania: Configuration class
 - [x] Forge Multipart
 - [x] Pam's Wee Flowers: seed classes
 - [x] Pam's Mob Drop Crops: seed classes
 - [x] Tinker's construct: cache pointers to certain tool classes
 - [x] Witchery: Item registry class

**Comment by RlonRyan** [comment]
Well done. I looked into getting gradle to pull the deps automatically using ivy and curse forge, but that took forever, and still had some major issues.

**Comment by RlonRyan** [comment]
Something you could look at is placing the mods to test with in a libs file on each git branch, so different branches could test different mods. It might make it easier to update the versions too, and quicker for travis...

**Comment by InfinityRaider** [comment]
I like to have all libs there, and I just toggle provided/compile to what I want to test.

**Comment by RlonRyan** [comment]
I was talking about migrating the libs out of dropbox to the repo.

**Comment by InfinityRaider** [comment]
Some mods don't have open distributing permissions, and the installdeps.sh kinda 'hides' them.

**Comment by RlonRyan** [comment]
That's too bad...
