### ISSUE TITLE
[Minor] Quartzanthemum Seeds have a weird name

### ISSUE THREAD

**Issue by gabor6505** [InfinityRaider/AgriCraft#375]
They called ``Quartzanthemum seeds.name`` and they should be called like ``Quartzanthemum Seeds``. I tried to override it with MineTweaker 3, and also with Resource Loader, but none seems to work. I can only fix it by editing this line in the Mod's Core Language file:
``item.agricraft:seedQuartzanthemum=Quartzanthemum seeds``
to:
``item.agricraft:seedQuartzanthemum.name=Quartzanthemum Seeds˙˙

Screenshot:
![2015-09-15_20 17 52](https://cloud.githubusercontent.com/assets/12859334/9886005/73a344d8-5be8-11e5-83f6-cb0e28a8508e.png)

AgriCraft Version: 1.4.0-beta-2

Thanks for the help! If you need forge logs, modlist, or anything like that, tell me.

**Comment by InfinityRaider** [comment]
This is a bug I wasn't aware of, will be fixed asap. Thanks for informing me.
