### ISSUE TITLE
Possible crash with Gany's Surface

### ISSUE THREAD

**Issue by ganymedes01** [InfinityRaider/AgriCraft#378]
This was reported to me and the said to be caused by when Gany's Surface and Agricraft are put together in the same modpack: http://pastebin.com/VmsBU1Fa

I don't see how Gany's Surface could be causing it, but maybe someone here can give me some insight :)

**Comment by InfinityRaider** [comment]
It's nothing to do with Gany's surface, he's using an old version of AgriCraft and should update to 1.4

**Comment by ganymedes01** [comment]
Okay, thank you for the information.

**Comment by InfinityRaider** [comment]
Happy to help.
