### ISSUE TITLE
Java Version Upgrade

### ISSUE THREAD

**Issue by RlonRyan** [InfinityRaider/AgriCraft#379]
While not entirely necessary, a conversion from Java 1.6 to 1.7 may be advisable.

Note:
- This would end JRE 1.6 support, ending support for a very small percent of users.
- Java 1.6 was marked EOL about two years ago, meaning that all java users have been encouraged to migrate already.
- Java 1.7 may run better in certain cases.
- Java 1.7 provides a few code niceties, such as the diamond operator and the try-with-resources statement.
- Other mods have already moved to Java 1.7

**Comment by InfinityRaider** [comment]
I am using 1.7

**Comment by RlonRyan** [comment]
Really? The code is still compliant with Java 1.6, so I couldn't tell, sorry.

**Comment by InfinityRaider** [comment]
I'm trying to keep it compatible if possible

**Comment by RlonRyan** [comment]
Ah.
