### ISSUE TITLE
"Disable Vanilla Farming"  config interferes with other mods

### ISSUE THREAD

**Issue by shaggy1395** [InfinityRaider/AgriCraft#380]
Currently, if "Disable Vanilla Farming"=true, then vanilla Hoes (specifically stone and wood) cannot be crafted at all.  This interferes with other mods that use vanilla hoes as a crafting component, such as EnterIO, Progressive Automation, and BetterChests

With that in mind, it may be better to implement the IguanaTinkerTweaks method. This method allows the items to be crafted but modifies the tools so they don't perform their intended purpose with a red NBT tag that states the item is for crafting purposes only.  For example, avanilla pick won't mine anything or a vanilla sword won't deal any damage.

Our current workaround is to use MineTweaker to recreate the recipes.

If this change is implemented it will allow your mod to remain compatible with other mods, while keeping the original purpose of disabling vanilla farming methods.

**Comment by InfinityRaider** [comment]
Currenty if "Disable Vanilla Farming"=true, then seeds cannot be planted, I do  not remove any recipes.

**Comment by InfinityRaider** [comment]
Possibly it might be TiC, that has a config option to disable vanilla tool recipes. If it's not that, you'll have to look further.

**Comment by shaggy1395** [comment]
Ugh, finally managed to find it.  Seems I overlooked it in a mod I've already checked multiple times.  Thanks for the quick response though, sorry about the false report.

**Comment by InfinityRaider** [comment]
No problem
