### ISSUE TITLE
Water duplication bug

### ISSUE THREAD

**Issue by InfinityRaider** [InfinityRaider/AgriCraft#382]
Placing an empty water tank next to one holding water duplicates liquid.

**Comment by RlonRyan** [comment]
Yeah I noticed some fluid duplication... I think part of the issue is all the casts...

In truth, no offense, the whole irrigation is kinda a mess...

**Comment by InfinityRaider** [comment]
I know, it's still code from the initial alpha days, where I didn't know what I was doing.

**Comment by RlonRyan** [comment]
I know the feeling.

(I might have tried to redo parts of it... but it's hard.)

**Comment by RlonRyan** [comment]
By the way, are the increasingly disparate fluid level syncs on larger and larger tanks intentional? As in a single tank will sync every few hundred millibuckets, whereas larger ones will only sync in after changes of multiple buckets?

**Comment by InfinityRaider** [comment]
Well, the height difference remains the same, the volume of water increases, but visually it doesnt, its separated in 32 discrete levels.

**Comment by RlonRyan** [comment]
It doesn't as the 32 discrete levels grow increasingly far apart, as they are a function of the tank's maximum capacity.

**Comment by RlonRyan** [comment]
I mean you don't want the syncs to occur too frequently that it bogs down the server, but they shouldn't be so disparate that it makes it look like the water level isn't changing to the client.

**Comment by InfinityRaider** [comment]
Ye but if the discrete level wasnt there, the level would also rise slow/fast depending on the footprint of the tanks.

**Comment by RlonRyan** [comment]
I know that. I mean that it will show as the same fluid level in WAILA for longer periods of time, to the point that clicking on a tank with a water bucket looks like nothing was added.

**Comment by RlonRyan** [comment]
Perhaps implement a max sync delta at 1 bucket?

**Comment by Darquewolf** [comment]
just as a note on this bug it was not in version 1.3.1 but in the new 1.4.0 its there.

https://youtu.be/HOLT__aWQvk

**Comment by InfinityRaider** [comment]
We are aware, its a consequence of a major performance improvement.

**Comment by InfinityRaider** [comment]
Fixed by #404
