### ISSUE TITLE
[1.4.0-beta2]Witchery Mandrake never spawning the Mandrake mob on harvest

### ISSUE THREAD

**Issue by thephoenixlodge** [InfinityRaider/AgriCraft#383]
It seems that when planted on crops Mandrake seeds no longer respect the Witchery harvest patterns of Mandrake like they did with 1.3.1. The intention is that harvesting in the day has a 90% chance to spawn the mandrake mob and 10% chance to directly give the root, with the chances reversed at night.

**Comment by InfinityRaider** [comment]
Yes, but I made the strength stat influence those odds.

**Comment by InfinityRaider** [comment]
As you can see here: https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/compatibility/witchery/CropPlantMandrake.java#L34
During the day there is 90% -(strenght-10)*10% chance for a mandrake to spawn, and this works fine by my testing.

**Comment by thephoenixlodge** [comment]
Okay yea I have no idea what was going on when I tested this, it was definitely day and not spawning any, but since then I've seen them spawning them properly
