### ISSUE TITLE
[Mod Interaction][Bug] Canola AgC dropping husks

### ISSUE THREAD

**Issue by ReikaKalseki** [InfinityRaider/AgriCraft#386]
...Why is the AgC canola plant dropping canola husks? Only seeds are harvested from the plant; husks are the result of the grinder.

**Comment by InfinityRaider** [comment]
What version? I'm aware they used to drop the husks, but that should've been fixed already.

**Comment by ReikaKalseki** [comment]
OK, so they are using an old version.

**Comment by InfinityRaider** [comment]
I'm not sure, according to the code it should drop metadata 0, and thats the same as the seeds.
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/compatibility/rotarycraft/CropPlantCanola.java#L25

**Comment by ReikaKalseki** [comment]
> they didnt mention a version?

>hey i've discovered something you might wanna know about, but the agricraft stuff is dropping canola seeds's grindered version. im using the latest of both mods.

**Comment by InfinityRaider** [comment]
Just send them to me, no point in you relaying messages for me.

**Comment by ReikaKalseki** [comment]
Given the kind of people I deal with, you may regret those words... :P
