### ISSUE TITLE
Weird request.

### ISSUE THREAD

**Issue by bookerthegeek** [InfinityRaider/AgriCraft#389]
Love your mod, love it.

Have a very odd mod integration request... IC2. Wierd, right?

Here is my thoughts. (Feel free to shot me down in a blaze of rage!) I would love for their to be a configuration option that when IC2 (and gasp... Maybe even the dreaded gregtech) are detected, that one of two options are enabled.

1) Be able to grow and bread the IC2 / Gregtech  plants in your mods, using your mechanics.

2) The other way around, and add all of your plants into the IC2 system. 

I hope that you will find at least part of my idea worth implamenting, but if not, alas I shall not perish. :)

**Comment by InfinityRaider** [comment]
1) I've looked into implementing support for IC2 crops, but the way they are implemented is too different from how AgriCraft is doing it, so this won't be happening anytime soon, sorry.

2) AgriCraft's system is built in such a way that it allows for almost any seed/crop to be planted on crop sticks, IC2 's system isn't.
