### ISSUE TITLE
[BETA] Thaumcraft compatibility broken

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#391]
Thaumcraft golems cannot harvest cropsticks anymore (by right clicking), instead they break the whole block (crop and plant) and refuses to replant them even with order upgrade. 

Could you check it?

Affected versions:

 - Agricraft 1.4.0 beta 2
 - Thaumcraft 4.2.3.511

Modpack: FTB Regrowth 0.8.2

**Comment by catzs** [comment]
Fixed in next version: https://github.com/InfinityRaider/AgriCraft/issues/92
Very end of thread

**Comment by hron84** [comment]
It can be closed then, because of dupe. I can't wait the next (beta) release since it have a lot of fixes I want.

**Comment by InfinityRaider** [comment]
I'll guess I'll build a new beta soon, as a model is only a minor thing.
Expect a new build tomorrow morning.

**Comment by hron84** [comment]
I'm really excited.

**Comment by catzs** [comment]
Me too!!!

**Comment by InfinityRaider** [comment]
Build is up

**Comment by Exlatus** [comment]
@InfinityRaider 
Hello.
Have a problem with automation.

Twitch launcher + Modern Skyblock 3
AgriCraft 2.12.0
ThaumCraft 1.12.2-6.1 (BETA26)

Golems harvest plants with Crop Sticks. Please, change it.
