### ISSUE TITLE
Crash After Updating

### ISSUE THREAD

**Issue by lilmoefow** [InfinityRaider/AgriCraft#394]
Trying to update my server from version AgriCraft-1.7.10-1.4.0-beta-2-1.7.10.jar to version AgriCraft-1.7.10-1.4.0-beta-3-hotfix-1.7.10.jar and im getting this crash

http://pastebin.com/fPASBGHu

I deleted configs and let them regen. I am able to open the world in single player but it crashes in SMP.

**Comment by RlonRyan** [comment]
Dang sheep...

**Comment by lilmoefow** [comment]
I was able to fix the crash and load up the world

I needed to set this config here to true then load the world, stop the server, reset the config to false, the start the server back up
    # set to true if you want to disable irrigation systems [default: false]
    B:"Disable Irrigation"=false

**Comment by RlonRyan** [comment]
Looks like it might be a @ sideonly thing.

**Comment by RlonRyan** [comment]
Confirmed the issue is present in testing.

**Comment by lilmoefow** [comment]
Another thing.. Im using custom crops on my private server, when updating all the item id's reset. They were the only seeds that "disappeared" when updating.  for example, they all changed from seedseedname to seedSeedname.  Not too much of a big deal. just had to reimburse my friends with items cheated in from NEI

**Comment by RlonRyan** [comment]
Huh... Might need to look into the seed thing... I think @InfinityRaider would be better for that, as that last commit was all that I had time for sorry... (Plus, only he can merge and post builds).

**Comment by InfinityRaider** [comment]
Testing servers is somethign I always overlook, sorry.
About the custom crops changing name, that was actually a bug in the previous beta which is fixed now. If I didn't fix the lowercasing, all packs updating from 1.3 wouldve had their seeds removed as well.

**Comment by InfinityRaider** [comment]
I'll try to remap missing ID's

**Comment by lilmoefow** [comment]
No worries from me. It actually let me fix the village generation.  All the custom crops i added were spawning in villages ( which i didn't want) so updating broke the id's causing them to vanish from villages(which im actually happy about) only problem i had was replacing players crops, especially ones that were already bread up to 10 10 10 on traits. I was able to manage.
