### ISSUE TITLE
Nei Custom Crops

### ISSUE THREAD

**Issue by SheppeR** [InfinityRaider/AgriCraft#396]
Hi, i have a problem with custom crops mutation.
NEI does not show any recipes and texture are a black pink square.

Here is my cfg folder http://s000.tinyupload.com/index.php?file_id=13906638319256761927

I am using AgriCraft v1.4.0-alpha-8-1.7.10 on a dedicated server

**Comment by InfinityRaider** [comment]
First, you didn't specify any mutations for them in the Mutations.txt file.
And regarding the textures, did you put the required textures in a resource pack?

**Comment by SheppeR** [comment]
In fact the cfg folder was in agrarian skies 2 mod pack, my bad forgot to edit Mutation.txt.
I haven't put any texture in texture pack.

Thanks for your reply

**Comment by SheppeR** [comment]
Sry i re post there for prevent or flood the issue thread
After a lot of try, i am not able to show/use custom crops

here is my server log with a lot of "Error when reading mutation: resulting stack is not correct (line: AgriCraft:seedSignalweed=AgriCraft:seedCuprosia+AgriCraft:seedSilverweed)"
https://gist.github.com/SheppeR/260f039c89a78c262f8b

My CustomCrops.txt
https://gist.github.com/SheppeR/7bb2f52e7215bb3777c8

My Mutations.txt
https://gist.github.com/SheppeR/8ed9b87747f89f96f343

**Comment by InfinityRaider** [comment]
I just saw you're still on alpha, so can you please first update to the newest version, because there was a bug with lower/upper casing concerning custom crops?

**Comment by SheppeR** [comment]
Ok i will update the mod now a give a feedback in 5 minutes

**Comment by SheppeR** [comment]
Everything seems fine ;) textures, recipes, all is fine.
Latest build fix my issue

Thanks for your time and support
SheppeR

**Comment by InfinityRaider** [comment]
yw
