### ISSUE TITLE
Forestry fertilizer Won't works beta3 hotfix

### ISSUE THREAD

**Issue by jem991** [InfinityRaider/AgriCraft#399]
Pls help

**Comment by InfinityRaider** [comment]
Forestry fertilizer is for the multifarms, it never did anything.

**Comment by jem991** [comment]
Forestry version 3.6.9.28 1.7.10

**Comment by jem991** [comment]
But works beta 2

**Comment by jem991** [comment]
And vanilla crops works Good but won't works agricraft crops

**Comment by InfinityRaider** [comment]
Tell me what exactly worked before and doesnt now

**Comment by jem991** [comment]
Right click fertilizer crops bonemeal effect and grow. Beta 3 won't works

**Comment by InfinityRaider** [comment]
Hmm, I didn't change anyhting concerning that. Did you update forestry as well or not?

**Comment by jem991** [comment]
I'm try beta3 hotfix and beta2 agricraft, same version of forestry beta2 works but beta3 hotfix not works.

**Comment by jem991** [comment]
This is beta 2
![adsiz1](https://cloud.githubusercontent.com/assets/2676681/10219664/7fea596c-6849-11e5-9cc9-92c4cce073f1.jpg)
and this is beta3 hotfix
![adsiz2](https://cloud.githubusercontent.com/assets/2676681/10219665/801d784c-6849-11e5-97d9-e96a504b314c.jpg)

**Comment by RlonRyan** [comment]
1. According to the FTBWiki, forestry fertilizer should not work when applied manually to anything.

2. The only changes made to the fertilizer code that I know of, should have increased the number of things that can be fertilized. Git blame confirms this, with the added not that there is no code change that could have possibly lead to fertilizer not working properly...

3. In my testing, bonemeal works fine...

**Comment by jem991** [comment]
İt is works manuely try yourself forestry version 3.6.9.28 its Like works bonemeal I'm play 2 mount this

**Comment by InfinityRaider** [comment]
Does it work on normal crops (meaning seeds directly planted on soil)? I'm asking this because there might be some tweak mod adding that functionality.

**Comment by jem991** [comment]
Yeah is works normal crops.

**Comment by InfinityRaider** [comment]
Apparently forestry fertilizer should indeed behave as bonemeal:
https://github.com/ForestryMC/ForestryMC/blob/8b7d3e5d15575adce85577ada6f5a3fe4196ff84/src/main/java/forestry/plugins/PluginCore.java#L172
https://github.com/ForestryMC/ForestryMC/blob/31e4d93e331cf31a6c8662884fbe3dd84ffb1711/src/main/java/forestry/core/items/ItemForestry.java#L42-L53

I have no idea why it stopped working between the versions, but I'll do some experimenting with this.

**Comment by InfinityRaider** [comment]
Actually, try shift-right clicking

**Comment by InfinityRaider** [comment]
I think it's because of htis: in the previous beta the onBockActivated() (https://github.com/InfinityRaider/AgriCraft/blob/976a4592cc29944fd71f5c1885900084454dbff3/src/main/java/com/InfinityRaider/AgriCraft/blocks/BlockCrop.java#L283) returned false, now it returns true (https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/blocks/BlockCrop.java#L305) to avoid certain annoying things from happening.

**Comment by jem991** [comment]
Ohhh Shift-right click works

**Comment by InfinityRaider** [comment]
That's what I thought, I'm closing this then.
