### ISSUE TITLE
Water Tanks / Irrigation Channel - Extra Utilities Wood

### ISSUE THREAD

**Issue by Samtrion** [InfinityRaider/AgriCraft#40]
Hey,

there is a render issue with Water Tanks / irrigation Channels based on ExtraUtilities Planks.
See screenshot: http://imgur.com/ZB50WSf

**Comment by InfinityRaider** [comment]
Extra Utilities is not open source, they probably do something unconventional for getting textures. I have no idea how i would fix this.

**Comment by InfinityRaider** [comment]
Extra Utilities wood had been disabled for now
