### ISSUE TITLE
[1.4.0-beta] CustomCrops configuration file ignores metadata.

### ISSUE THREAD

**Issue by OneEyeMaker** [InfinityRaider/AgriCraft#401]
Title says it all. CustomCrops configuration file ignores metadata at all. For example, I want to define resource crop, that will grow salt (RotaryCraft:rotarycraft_item_powders:5). But when I define that crop, I get one, that generates (as NEI shows)... netherrack dust (RotaryCraft:rotarycraft_item_powders:0)! The same problem with soils and base blocks.
And I can't plant my custom crops, because mod can't detect specified soil and shows in NEI ... fire (block with id 51) in NEI.
Please, fix that!

P. S. Sorry for my English, I'm from Russia.

**Comment by InfinityRaider** [comment]
I'm able to reproduce this, thanks for reporting, I'll have a look at what changed in the code.
