### ISSUE TITLE
Harvest-on-rightclick conflicts with mutating sprig

### ISSUE THREAD

**Issue by kutschkem** [InfinityRaider/AgriCraft#402]
Relevant SO-Question:http://gaming.stackexchange.com/questions/238466/how-to-get-wormwood-on-phoenix-reborn

In order to make Witchery Wormwood, one needs to right-click fully grown wheat with a mutating sprig. See https://sites.google.com/site/witcherymod/wormwood

However, it only gets harvested (I suppose it is this mod that adds harvest-on-right-click?). I don't know  where to report witchery issues, but imho the best way for this issue to be resolved would be if both

1) Mutating sprig right-click gets handled before the harvesting action.
2) Wheat on crops works as centerpiece of the transformation, too.

**Comment by InfinityRaider** [comment]
If the wheat is planted on crop sticks, then yes itll get harvested, however I could implement that it changes into wormwood.
If its just regular wheat, then no, it's some other mod doing it.

**Comment by kutschkem** [comment]
Ok maybe the right-click harvesting comes from harvestcraft. Anyway, it would be nice if you could make it such that wheat on crop sticks behaves like regular wheat in creating wormwood. See the wiki page i linked. I don't think wormwood is supported by your mod yet? (I like the witchery support btw. :-) )

**Comment by InfinityRaider** [comment]
WormWood is supported, the creation isn't (yet).

**Comment by InfinityRaider** [comment]
I don't think HarvestCraft adds right clicking for vanilla crops, it might, but I doubt it. AppleCore or Hunger Overhaul does it, TTcore does it ass well.

**Comment by kutschkem** [comment]
Thanks, that fix was quick. :+1:
