### ISSUE TITLE
Bugged textures with resources seeds

### ISSUE THREAD

**Issue by DavidHack38** [InfinityRaider/AgriCraft#403]
Hi, I would like to warn you, I'm French :p
I use Agricraft for a long time and I saw that we could add resources seed in the configuration file.
I added the mutations in the file mutations.txt
I autorized resources seeds.
But, when I go in the game, I write in NEI "agricraft" and resources seed are here but with bugged textures.
Somebody can help me?

**Comment by InfinityRaider** [comment]
Like it says in the config, you have to create a resource pack and supply it with the correct textures.

**Comment by DavidHack38** [comment]
I must create my own resource pack or there is one on internet?

**Comment by DavidHack38** [comment]
I found it thanks
