### ISSUE TITLE
API jar is a requested download on Curse Voice Launcher

### ISSUE THREAD

**Issue by AlexPlus117** [InfinityRaider/AgriCraft#405]
Hi, I'm here to report you a minor issue about downloading your last update. I'm using Curse Voice Launcher to make modpacks and it tells me I have to upgrade your mod but it downloads the API jar not the real mod, so can you remove the API jar from your files list, please?

**Comment by InfinityRaider** [comment]
That's no my fault, but Curse's, I'm hosting my API jar there, together with the corresponding version of AgriCraft, idk how I uploaded the API as an additional file, Idk why it's downloading that as default.

**Comment by InfinityRaider** [comment]
I marked it as beta, even though it is a release, maybe that helps.

**Comment by AlexPlus117** [comment]
Here's the problem:
![immagine](https://cloud.githubusercontent.com/assets/8421361/10269219/8c98ab12-6ad0-11e5-9a64-68b3529e93df.png)

**Comment by InfinityRaider** [comment]
Marking it as a beta should have fixed that, however this really isn't my fault, but Curse's
