### ISSUE TITLE
Crash when looking up recipes with NEI in lan worlds

### ISSUE THREAD

**Issue by Nyxar3212** [InfinityRaider/AgriCraft#416]
a friend was hosting a lan world and i kept crashing trying to look up various recipes, 
Crash Report : http://pastebin.com/Pspud8VB
Can someone please at least help me understand what caused it?
also, how do i tag this as a bug?

**Comment by InfinityRaider** [comment]
This is a consequence of #411. Mutations are not synced from the server to the client if you are connecting to a lan world, resulting in this crash.
And you can't tag issues, but I can.
