### ISSUE TITLE
MineTweaker3 support

### ISSUE THREAD

**Issue by Imasius** [InfinityRaider/AgriCraft#42]
What "recipe types" do we need to support via MineTweaker? Some ideas are:

- [x] CustomWood items (Tank, Channel and Valve)
- [x] Mutations of seeds (config file already in place for this)
- [x] Blacklist seeds trough minetweaker
- [x] Whitelist soils trough minetweaker
- [x] Override spread chances trough minetweaker

I guess this depends highly on the requirements of pack developers.

**Comment by InfinityRaider** [comment]
* Blacklist seeds trough minetweaker
* Whitelist soils trough minetweaker
*Override spread chances trough minetweaker

**Comment by Imasius** [comment]
SoilWhitelisting seems to be buggy in general. Needs some more investigation. It is disabled for now.

**Comment by InfinityRaider** [comment]
a88e913fa3d8323fe2679f7dfc2127937aa255f9 Fixes this
