### ISSUE TITLE
Wrong rendering type of Custom crops.

### ISSUE THREAD

**Issue by OneEyeMaker** [InfinityRaider/AgriCraft#420]
Hello.
The title says it all: custom crops always render in '#' pattern regardless of which type of render is defined (1 = 'X'-pattern or 6 = '#'-pattern).

**Comment by InfinityRaider** [comment]
X-pattern means it will render one X on all four crop sticks, hashtag means it will render 4 planes parallel to the edges:
http://puu.sh/kGbVF/8742f89c19.png
