### ISSUE TITLE
[Suggestion] Sprinkler Settings

### ISSUE THREAD

**Issue by Neodark7** [InfinityRaider/AgriCraft#421]
Hi, can you add a config to choose the sprinkler radius ( for example 2, 3 and 4 radius for 5x5 7x7 or 9x9 farm instead of just 7x7 ) and a config to disable the particles cause it cost 10-20 fps on my instance :(

**Comment by InfinityRaider** [comment]
I've stated several times that the sprinkler will never do a larger radius than 7x7, in the future I might do a pressurized irrigation system with metal pipes and sprinklers with a larger radius.
I'll throw in a clientside only config for particles if it really impacts your performance that much.

**Comment by Neodark7** [comment]
Okay thx :)
