### ISSUE TITLE
getSoilRequirement() method for CC seedAnalyzer

### ISSUE THREAD

**Issue by callmebackdraft** [InfinityRaider/AgriCraft#422]
Hi,

Would you be willing to add an extra method to the new Computer Controlled seed Analyzer ?

The one I am suggesting is one that would return the needed soil for the specimen in the seed analyzer I think this would greatly improve the usability of the device, which is allready awesome by the way.

Looking forward for your insight in this situation.
Kind regards.

**Comment by InfinityRaider** [comment]
I don't see why not, that method should already be there. If you think there are any more methods missing, just give me a shout.

**Comment by callmebackdraft** [comment]
Thanks infinity raider, 
I have been working on an elaborate cc program which uses alot of information from the analyzer.

If i find a need for more or stumble upon something i will surely give you a headsup

**Comment by InfinityRaider** [comment]
Actually there's a lot of methods about growing conditions for crops, but not for the specimen itself, Im going to refactor some code to make it work for the specimen if no argument is given.
