### ISSUE TITLE
CC Analyzer as turtle peripheral

### ISSUE THREAD

**Issue by callmebackdraft** [InfinityRaider/AgriCraft#423]
Hi,

Would you be willing to add a CC turtle that has a CC seed analyzer attached to it, and with that off course also the wireless variant of it.

Seeing the current Methods of the analyzer it would benefit the methods which read out crop sticks.

Looking forward to your response
Kind regards,

**Comment by InfinityRaider** [comment]
Do you mean a turtle with the functionality of the CC Seed Analyzer? Or can turtles not wrap the peripheral at the moment?

**Comment by callmebackdraft** [comment]
Hi,

Although i have not fully tested it i am pretty sure the turtles are able to use the CC Seed Analyzer as a regular peripheral. What i meant was an actual "analyzing turtle" and "wireless analyzing turtle" in the same way you would have a "felling turtle" for cutting trees if you catch my drift. The reason i think this would be a great addition is elaborated below.

I see that the analyzer has some methods which can get information from the (cross)crops which are placed next to it. 

If someone would have a bigger farm for mutating it would be a real hassle of moving the turtle and the seed analyzer everytime something needs to be checked. 
Although this would be possible to do with a turtle which places and breaks the analyzer on the needed locations I think if you would have an "analyzing turtle" as a fully outfitted turtle, one could just let the turtle do all the dirty work.

**Comment by InfinityRaider** [comment]
You're right, I'll look into this.

**Comment by callmebackdraft** [comment]
Any news or update on this one ?

(not tryin to rush you here ;) just askingg )

**Comment by InfinityRaider** [comment]
No progress, on much really from my side, really busy period in my life atm, and when I have time to do modding I'm usually burnt out due to other work.
