### ISSUE TITLE
[Suggestion] Auto generate seeds that have no textures..?

### ISSUE THREAD

**Issue by koalalord9999** [InfinityRaider/AgriCraft#426]
I have no idea how difficult it would be to implement this (probably pretty difficult) But would it be possible to have a png generator that pulls modded items gets their color, and pastes them to a seed?
Example: Tin Seeds pulls minecraft seed and pulls a tin ingot from Thermal Expansion, or other mods with tin in them, copys a pixel on the ingot and "fills" a specific color on vanilla seed, and keeps doing so until the seed is no longer the same color...

so you'd probably get a seed with a base of cloudy blue, some white and maybe a little bit of gray.

As I write this out, it becomes more apparent that something like this would require a ton of effort and probably be not worth the time, but would be amazing at the same time xD

**Comment by InfinityRaider** [comment]
I've thought of this, of having a couple of textures for stalks and leaves, and a couple of textures for different flowers, and then dynamically recoloring and combining different stalks and leaves with different flowers. But I simply don't know how and it would be quite some work to learn and implement it, added that I don't have a lot of time lately this won't be a thing very soon, but thanks for the suggestion.
