### ISSUE TITLE
Crop Mutation and Config issues.

### ISSUE THREAD

**Issue by VT-14** [InfinityRaider/AgriCraft#428]
I'm trying to get Sugarcane.  I have both carrots and wheat with 10,10,10 stats.  The Sugarcane always ends up with 1,1,1 stats.  I haven't tried any of the other mutations yet.

I've tried playing with the configs.  I've tried Crop Divisor set to both 1 and 2.  I've also tried adjusting Farming Difficulty from 3 to 2.

The config file has several issues.  Farming Difficulty no longer has a description, and many entries have multiple lines setting the same variable (there are at least 2 copies of both Crop Divisor and Farming Difficulty).  The Regenerate new mutation file also doesn't set itself back to false.

Agricraft 1.7.10-1.4.1

**Comment by InfinityRaider** [comment]
Farming difficulty no longer exists as a config option, it's split up in two settings: one to define what are considered valid parents for stat calculations, and one to define if non-valid parent plants should affect stat gain negatively.
If you config got derped up, I recommend deleting and regenerating it, apologies for the hassle.

**Comment by VT-14** [comment]
Deleting and making a new config fixed the issues with the config file.  (I updated from 1.3 several days ago, so I assume that's why it got "derped")

However, Sugarcane still gets dumped to 1,1,1 stats with 10,10,10 parent mutation crops.  I have also tested it with Pumpkins and they have the same issue.

Here are the relevant config settings I have:
    # The maximum attainable value of the stats on a crop [range: 1 ~ 10, default: 10]
    I:"Crop stat cap"=10

    # On a mutation the stats on the crop will be divided by this number [range: 1 ~ 3, default: 2]
    I:"Crop stat divisor"=1

(lots of text)
    B:"Hardcore stats"=false

    # True means any crop that is not considered a valid parent will affect stat gain negatively [default: true]
    B:"Non parent crops affect stats negatively"=true

    # What are considered valid parents for stat increasing: 1 = Any. 2 = Mutation parents and identical crops. 3 = Only identical crops [range: 1 ~ 3, default: 2]
    I:"Valid parents"=2

**Comment by InfinityRaider** [comment]
As you can see, there was a bug here: https://github.com/InfinityRaider/AgriCraft/commit/642fd054261c2ca67d2df1fac06523a00e4d2339
The config used 1, 2 and 3, but in the code I was using 0, 1 and 2 meaning the setting you think it is, is not really it. This is fixed in the meantime.
