### ISSUE TITLE
Clipper

### ISSUE THREAD

**Issue by therealericbj** [InfinityRaider/AgriCraft#429]
I think I'm doing something wrong.

NEI isn't showing any receipt for the Clippers.

# Set to false to disable the Clipper [default: true]
    B:"Enable Clipper"=true

How do I fix this?

AgriCraft-1.7.10-1.4.1-1.7.10.jar
Forge 1492

**Comment by InfinityRaider** [comment]
I forgot to add a recipe, this is fixed in the meantime, apologies: https://github.com/InfinityRaider/AgriCraft/commit/c65fa60a321b5542d1e421e1ca9c8cee10a6673e
