### ISSUE TITLE
I Can't Get Brown Mushroom Spores to Grow Naturally

### ISSUE THREAD

**Issue by VT-14** [InfinityRaider/AgriCraft#430]
Agricraft 1.4.1 (Minecraft 1.7.10, Forge 10.13.4.1492)

I can't seem to get my Brown Mushrooms to grow without bonemeal.  The one sample I have is planted on Mycelium and in darkness (surrounded by slabs in my example below, though I also tried using an Extra Utilities watering can in a dark room and different biomes).  I haven't tried to grow these before, so I could just be missing something.

I appear to have the same issue with the Tarma Root, thought I'm not certain if that is suppose to need light or darkness.

Both the Mushrooms and Tarma Root grow just fine with Bonemeal using the setup in the picture below.

Quick sidenote: Is Netherwart only growing in the Nether an intentional change?  If so, can there be a config option to turn that off?

In this picture, the computercraft monitor has a timer going.  It shows over 2 hours of this area being loaded since the last time the server stopped (SSP, last crash caused by another mod).  I can make a conservative estimate of 6+ hours with no signs growth.  I believe I'm in a Plains Biome, if that matters (I also tried a Mushroom Island Shore via Mystcraft and the Nether).
![2015-10-20_23 38 31](https://cloud.githubusercontent.com/assets/12564251/10627235/cf12890c-7784-11e5-8552-6888d07a5c0b.png)

**Comment by InfinityRaider** [comment]
There's a block above them, that's why they aren't growing.
And no Nether Wart will grow on soul sand, anywhere if the light level is below 8.

**Comment by VT-14** [comment]
Ok, the issue was having blocks on top.  In previous versions, that setup use to work for Nether Wart, and my setup in the Nether happened to not have a block on top.
