### ISSUE TITLE
Crash with constructing multiblock tank

### ISSUE THREAD

**Issue by RedsaphirCZ** [InfinityRaider/AgriCraft#431]
With placing tank block next to another game crashes. 
Version 1.4.2 
http://pastebin.com/R0F8UhQi

**Comment by InfinityRaider** [comment]
I was already aware of this, but thanks for reporting anyways.
All issues concerning tanks are resolved with the rewrite: https://github.com/InfinityRaider/AgriCraft/commit/7bf19df6c34fe11681ccf4b1cb2cd5ba573b9cc2
