### ISSUE TITLE
Compatibility with Botanical Add-Ons

### ISSUE THREAD

**Issue by SkullyGamingMC** [InfinityRaider/AgriCraft#432]
There's an addon for Botania under the title of Botanical Add-Ons. The main feature that it adds is Colored Dirt that can be used as Farmland and doesn't require Water. However, it does not allow me to place Crop Sticks on them to plant crops with AgriCraft.

**Comment by InfinityRaider** [comment]
Soils can be added with MineTweaker: https://github.com/InfinityRaider/AgriCraft/wiki/%5B1.3.*%5D-MineTweaker3
