### ISSUE TITLE
Allow modify drops of vanilla crops?

### ISSUE THREAD

**Issue by Nephatrine** [InfinityRaider/AgriCraft#437]
I understand why you do not allow minetweaker to change other mods' crop drops, but why does that apply to the vanilla crops? I mean, the whole point of mods is to change the vanilla experience. I'd very much like to modify the returns of the pumpkin and melon plants (particularly since I don't think we can make replacement custom crops with the stem plant renderer).

**Comment by InfinityRaider** [comment]
I don't see why not, sure. Also I'll implement the ability to create stem plants with the custom crops config.

**Comment by InfinityRaider** [comment]
I'm sorry but due to the way crops are coded this is not really possible, my apologies.
It is possible, but it would require a decent effort and rewriting, and I really don't feel like doing that.

**Comment by Nephatrine** [comment]
Thanks for looking into it at least. Would changing the item dropped from breaking a pumpkin block be reflected in what item the pumpkin crop returns or is it all hardcoded?

**Comment by InfinityRaider** [comment]
It's based on the oredictionary, pumpkin seeds is seedPumpkin and the fruit it drops is cropPumpkin. The drops are initialized on game launch, so changing OreDict entries with MineTweaker won't work because its too late.
