### ISSUE TITLE
Wooden tank multiblocks unstable.

### ISSUE THREAD

**Issue by Armigus** [InfinityRaider/AgriCraft#439]
If filled with water and I reset the game they reset to individual blocks.  You might want to have them block update on game start to reform the multiblocks.

**Comment by InfinityRaider** [comment]
Was this right after updating to 1.4.3?

**Comment by Armigus** [comment]
Could have been earlier.  Discovered it after updating to 1.4.3.

**Comment by InfinityRaider** [comment]
Updating from older to 1.4.3 will make that happen yes, see this:http://minecraft.curseforge.com/projects/agricraft/files/2263798

>IMPORTANT: in this build the multi block code for tanks has been completely rewritten from scratch. This means a lot of issues have been resolved and performance should be better now. However this also means that multi-block tank structures in existing pre 1.4.3 worlds will break. BACK UP YOUR WORLD BEFORE UPDATING! To fix this, you will either have to manually break and replace one block for each of your tanks, or break all tanks in your world before updating.
