### ISSUE TITLE
Sprinkler becomes semi-transparent when Extr. Utils. tank is in foreground

### ISSUE THREAD

**Issue by Cobra1117** [InfinityRaider/AgriCraft#44]
Sprinklers appear semi-transparent if there is an extra utilities tank containing a liquid in the foreground on the screen

Tested with:
Extra Utilities: 1.2.1
Agricraft: 1.1.1

**Comment by InfinityRaider** [comment]
Failing to reproduce, can you attach a screenshot please?

**Comment by Cobra1117** [comment]
As far as I can tell, the bug is already fixed with the latest Agricraft. I was able to reproduce it reliably before, but am unable to now. (Issue can be  closed)
