### ISSUE TITLE
Crash when automating seed analyzer

### ISSUE THREAD

**Issue by drz2k** [InfinityRaider/AgriCraft#441]
As a tester of my pack reported here : https://github.com/MyM-ModpackTeam/hypovolemia/issues/88

We are on 1.4.2 but I didnt see any fix related to this.

Singleplayer crash report - http://paste.ee/p/DGsao

The setup - http://imgur.com/MMsfB85

"

I'm trying to automate my seed analyzer. These are the crashes I've encountered. Building the system doesn't cause the crash, but when the system tries to move any seed, the crash happens.

chest->mekanism logistical transporter->seed analyzer => server crash
seed analyzer->translocator->seed storage => client crash
"

**Comment by InfinityRaider** [comment]
Try with buildcraft pipes and/or extra utilities transfer nodes and/or TD conduits, if all those crash as well its on Mekanism's side. The stacktrace points towards Mekanism though.

**Comment by drz2k** [comment]
XU pipes work well ....
