### ISSUE TITLE
Irrigation channel & tank not changing water level

### ISSUE THREAD

**Issue by Spectrekillol** [InfinityRaider/AgriCraft#442]
Water levels in my wooden water tank are not increasing from my railcraft water tank adjacent to the them. They water is however being taken from the tank.

Setup: 
http://imgur.com/a/F69MJ

Agricraft Version 1.4.1
Playing FTB Infinity 2.0.2

**Comment by InfinityRaider** [comment]
Known bug, has been fixed a while ago.
