### ISSUE TITLE
Minetweaker Fertilizer Request

### ISSUE THREAD

**Issue by SkullyGamingMC** [InfinityRaider/AgriCraft#443]
Since you can add Custom Soils and Custom Crops using AgriCraft and Minetweaker, I was wondering if you can add the ability to create Custom Fertilizers, similar to Bone Meal. You would be able to state what item is a Fertilizer, how 'potent' it is, what tiers of seeds it works on, and a blacklist of seeds it works on, including any other features that a modpack creator may need.

~SkullyGamingMC

**Comment by InfinityRaider** [comment]
MineTweaker is too limited for this, there is an interface (https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/api/v1/IFertiliser.java)  for this though, so you would have to create your own mod for this.
