### ISSUE TITLE
slow growth even though max stats

### ISSUE THREAD

**Issue by blarghhh** [InfinityRaider/AgriCraft#444]
i have 10/10/10 potato seeds from a previous ssp world(ftb infinity 1.12.1) and i found out that the sprinklers are not accelerating the growth tick. for troubleshooting purposes, i increased the chance to 100% and at 5 second intervals at the global growth rate of 2.0. i am using ftb infinity evolved 2.0.2 and using the 1.4.3.jar version of agricraft.

**Comment by InfinityRaider** [comment]
The sprinkler code hasn't changed in ages. There might be another mod slowing down crop growth.

**Comment by InfinityRaider** [comment]
It appears you are right. However this change is very very old. My apologies, I'll fix it.

**Comment by blarghhh** [comment]
so i assume fixed in 1.4.3 version?

**Comment by InfinityRaider** [comment]
No it'll be fixed in the next one.

**Comment by blarghhh** [comment]
here's a question. the config says growth rate multiplier. is it supposed to increase the rate of growth or decrease the rate of growth? cause when i use 1.4.3 and change the rate to 0.0, the growth rate is high but at 2.0 it is extremely slow.

**Comment by InfinityRaider** [comment]
Yes, this was a little bug by me, will be corrected in the next version: https://github.com/InfinityRaider/AgriCraft/commit/40f49ba180651b686dd525d7709a01d89df0887c#diff-766954c4303b52309bfefd01003d3d75L108

**Comment by blarghhh** [comment]
i mean what was your original intention for the multiplier? cause it can work both ways

**Comment by InfinityRaider** [comment]
I don't remember what my original intention was, but I think this makes more sense (higher = faster)
