### ISSUE TITLE
option to set custom stats/ranks

### ISSUE THREAD

**Issue by InkDragon** [InfinityRaider/AgriCraft#446]
Would it be feasible to add a config option to set custom stats/ranks?

Such that you could use either something like 'Rank 3' or '★★★' or something similar rather than 3/10 or whatever level it happens to be set to

**Comment by InfinityRaider** [comment]
I don't understand what you mean.

**Comment by InkDragon** [comment]
okay currently corp stats are displayed as a # out of 10

What I am asking is if it would be possible to set a custom display option for that so that it shows up as something like 
Rank 3 for 3/10 or using a single text element repeatedly as such ★★★ for the same 3/10 crop

Basically it would be a purely cosmetic option

**Comment by InfinityRaider** [comment]
Oh, you mean in the tooltips and Waila?

**Comment by InkDragon** [comment]
Yah!

**Comment by InfinityRaider** [comment]
Added this client only config setting:

# This defines how to display the stats of plants. Possible settings are 'NUMBER': just display a simple number (ex: "6"), 'FRACTION': number/maximum (ex: "6/10"), 'CHARACTER-'char'': number of characters equal to the stats (ex: CHARACTER-• will give "••••••") and 'KEYWORD-'type'-'keyword'': keyword followed by the type and then the stat, type is NUMBER, FRACTION or CHARACTER (ex: KEYWORD-FRACTION-Rank will give "Rank: 6/10") . Invalid entries will default to NUMBER  [default: NUMBER]
    S:"Stat Display"=FRACTION

For instance "CHARACTER-•" resulted in:
http://puu.sh/lgydm/15f686403c.jpg

and  "KEYWORD-CHARACTER-•-Rank" in:
http://puu.sh/lgyHa/2a4a0a96bc.jpg

Also added a way to define different stat display methods using the API

**Comment by InfinityRaider** [comment]
And yes it works fully recursively, although I have no idea why you what want something like
> KEYWORD-KEYWORD-CHARACTER-X-Rank-Because I can

**Comment by InkDragon** [comment]
thank you so much!
