### ISSUE TITLE
Seed Storage Disconnects from Server

### ISSUE THREAD

**Issue by ChromeMystic** [InfinityRaider/AgriCraft#447]
In the Current version of Agricraft (1.4.3) i get disconnected whenever I try to take seeds out of the Storage on a server with a "A fatal error has occurred, this session is terminated".

The Server Console shows nothing of note. 

The Server keeps running just fine 

There is no error on single player and I wasn't able to test yet if others get disconnected as well.

I run my own pack (JesterMage on Curse) and can give you access to my server if you need it. And I am pretty sure they worked at some point but I am not 100% sure. I haven't updated Agricraft since I created the pack, therefore it might be one of the other Mods.

Thanks a ton for looking into it.

**Comment by InfinityRaider** [comment]
I'll need server and client logs

**Comment by InfinityRaider** [comment]
Also a question, did you change your name/nickname or do you have a nickname set on the client?

**Comment by ChromeMystic** [comment]
I indeed install Servertools https://github.com/MCServerTools and it added Prefixes to the Names, i disabled those and now it is working fine. Since I don't need them you can close the ticket, if you want to. If you still need the logs, add another comment and I will change my nick and generate a set of fresh logs for you.

**Comment by InfinityRaider** [comment]
Someone else was experiencing this as well, has been fixed by https://github.com/InfinityRaider/AgriCraft/pull/433
You'll be able to add the mod again after I release a build with the fix.
