### ISSUE TITLE
Add Jabba Dolly Support to Seed Storage

### ISSUE THREAD

**Issue by ChromeMystic** [InfinityRaider/AgriCraft#449]
Just as the Title says. I would love to use the Jabba Dolly to move my seed Storage around.

**Comment by InfinityRaider** [comment]
Does it have an API?

**Comment by ChromeMystic** [comment]
My Knowhow of Mods coding is rather limited: the Source is https://bitbucket.org/ProfMobius/jabba

It doesn't seem there is an api but someone is working on it. If you think this should rather be on ProfMobius side I shall register it there.

**Comment by InfinityRaider** [comment]
ah its on BitBucket, i'll have a look at it.
And imo this should be on my side, it'd be silly for him to implement it for every single mod that adds some kind of storage.

**Comment by InfinityRaider** [comment]
It seems there is no API, and the code suggests that ProfMobius added compat for quite some mods on his side.

**Comment by artdude543** [comment]
This is the [code](https://bitbucket.org/ProfMobius/jabba/src/4c1ccec85db33e4e43e5a68f2983d80da5b96093/src/main/java/mcp/mobius/betterbarrels/common/items/dolly/api/MovableRegistrar.java?at=forge_1187&fileviewer=file-view-default) which other mods use to register there block to be able to be picked up.

**Comment by InfinityRaider** [comment]
That makes things a lot easyer, thanks

**Comment by InfinityRaider** [comment]
It appears the IDollyHandler is incomplete though

**Comment by hron84** [comment]
As I see, currently [this](https://bitbucket.org/ProfMobius/jabba/src/4c1ccec85db33e4e43e5a68f2983d80da5b96093/src/main/java/mcp/mobius/betterbarrels/common/items/dolly/ItemBarrelMover.java?at=forge_1187&fileviewer=file-view-default#ItemBarrelMover.java-51) code is used to figure out what could be placed on dollies. It seems like we have to kindly ask him to add seed storages here.
