### ISSUE TITLE
Refactoring hot spots

### ISSUE THREAD

**Issue by Imasius** [InfinityRaider/AgriCraft#45]
This is a running TODO list of all the places which need some refactorings badly. Prefer editing this post compared to additional comments.

- [x] Recipes: CustomWood recipe registration has lots of duplicated code
- [x] CustomWood (MineTweaker3): duplicated code in addShapless and addShaped
- [x] Seed blacklist and soil whitelist are nearly identical
- [ ] NBTHelper does manual sorting

**Comment by RlonRyan** [comment]
I don't think the NBTHelper thing is a big deal, due to the way that tag lists are implemented, and the degree of control we need.

**Comment by RlonRyan** [comment]
Also, we should probably jettison the 1.8 branch seeing as the internals on the main branch have changed so much that the 1.8 port is outdated.

**Comment by InfinityRaider** [comment]
It doesn't hurt having the 1.8 branch around, I'm keeping it for now.
