### ISSUE TITLE
(low priority) harvestcraft blackberries returning natura's item instead of own berries

### ISSUE THREAD

**Issue by usafphoenix** [InfinityRaider/AgriCraft#450]
not sure if a bug or not, but harvestcraft blackberries are returning the natura version of blackberry instead of harvestcraft's. seed analyzer shows it has two fruits associated with the seed. not sure how to make it return a specific one of the two, or if it picks by random (or a config setting).

**Comment by usafphoenix** [comment]
(what does it mean when a seed has TWO fruits listed as it's produce under the agricultural journal entry for that seed?)

**Comment by usafphoenix** [comment]
closing. item returns random.

**Comment by InfinityRaider** [comment]
What version are you using?

**Comment by usafphoenix** [comment]
AgriCraft-1.7.10-1.4.3,
Pam's HarvestCraft 1.7.10k
natura-1.7.10-2.2.1a2

--at first I thought i had an Item ID overridden, but it appears that sometimes i get the harvestcraft fruit, and other times the natura fruit. not sure if that's intended or not.

**Comment by usafphoenix** [comment]
(Also occurs with Raspberry and other similarily named fruits that both natura and harvestcraft have items for.)

**Comment by InfinityRaider** [comment]
Yes, it's oredicted, but I thought I applied a filter for this kind of stuff, I know it works for Plant Mega Pack and HarvestCraft, but apparently not for HC and Natura, I'll have a further look.
