### ISSUE TITLE
Weeds refuse to be disabled

### ISSUE THREAD

**Issue by xenoflot** [InfinityRaider/AgriCraft#451]
Howdy,

Private pack. Agricraft 1.4.3, HO 1.0.0, Pam's 1.7.10i

I have disabled weeds and disabled "overrun plants" in the cfg, however weeds are still appearing!

**Comment by InfinityRaider** [comment]
Give me your config in a pastebin please, failing ot reproduce, and if I go over the code I don't see why this should happen.
Sat here afk for 5 minutes, no weeds: http://puu.sh/ldS2h/a7da1666e4.png

**Comment by xenoflot** [comment]
Thanks for the quick reply! I also don't seem to be getting any stat improvements.
Mature plant on crops, crossed-sticks on the next block. It spawns a new plant but the seed has no improvement. Am I derping?

http://pastebin.com/w2w0hbMg

**Comment by xenoflot** [comment]
/facepalm

I was modifying the config in the wrong folder.   Going to nip out the back and commit sudoku.   Sorry for wasting your time.

**Comment by InfinityRaider** [comment]
Okay
