### ISSUE TITLE
ticking entity crash when placing water tank

### ISSUE THREAD

**Issue by tyler489** [InfinityRaider/AgriCraft#452]
Hi I get  this crash when placing oak wood tanks.. im not forsure if this is an issue for you or for the pack im playing

**Comment by tyler489** [comment]
https://gist.github.com/chikinnuggit/b24859fee1458b96ab75

**Comment by tyler489** [comment]
running agricraft 1.4.2

**Comment by zed-hex** [comment]
I would recommend updating to the newest build of agricraft it should fix the issue. 
Latest build (1.4.3): http://minecraft.curseforge.com/projects/agricraft/files/2263798

**Comment by tyler489** [comment]
ah I shall inform the pack maker and hope for a pushed update.

**Comment by InfinityRaider** [comment]
Multi Block code has been rewritten entirely:
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/resources/changelog.txt#L12

**Comment by InfinityRaider** [comment]
Commits: https://github.com/InfinityRaider/AgriCraft/commit/375edbc3a989dc5aa9e5c407c74c7d053445374b, https://github.com/InfinityRaider/AgriCraft/commit/af974fd1f0407e5e24d7233edacb176dd6e995dc

**Comment by tyler489** [comment]
thank you the pack maker pushed an update will report if it happens in 1.4.3
