### ISSUE TITLE
API.isEmpty() returns inverted result

### ISSUE THREAD

**Issue by HenryLoenwind** [InfinityRaider/AgriCraft#453]
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/apiimpl/v1/APIimplv1.java#L199

```return crop.hasPlant();```

oops...

**Comment by InfinityRaider** [comment]
My bad, will fix

**Comment by InfinityRaider** [comment]
Ill actually compile and reupload a new build with this fix as well.

**Comment by InfinityRaider** [comment]
New build is up.
