### ISSUE TITLE
API.isWeeds() doesn't clear after weeding with API.removeWeeds()

### ISSUE THREAD

**Issue by HenryLoenwind** [InfinityRaider/AgriCraft#454]
API.isWeeds() keeps reporting true after weeding with API.removeWeeds() until the next growth tick. Planting by API (isEmpty(), canApplySeeds(), applySeeds()) works in such a spot.

Weeding by hand clears it, too.

Update: Visually the weeds stay in the plot. Unless a seed is api-planted there, then the plant is displayed---but the plot can still be hand-weeded and that also yields the weed drop. But the planted plant stays there when hand-weeding. Hand-planting doesn't work.

Seen in 1.4.3 and 1.4.4.

**Comment by InfinityRaider** [comment]
I'm failing to reproduce this, according to my testing:
API.removeWeeds(world, x, y, z, false) -> removes weeds (both visually and if querried by API.isWeeds())
API.removeWeeds(world, x, y, z, true) -> doesn't remove weeds if config requires a rake.
API.removeWeeds(world, x, y, z, rake)  -> removes weeds (both visually and if querried by API.isWeeds())

**Comment by HenryLoenwind** [comment]
It doesn't happen all the time. I had the weed module off on this field for a while and it cleared ou nearly all weeds without issue until:

![](http://i.imgur.com/sQg7Knd.png)

Thought I fire it up in the debugger:

![](http://i.imgur.com/DIFh3wh.png)

My code:

```
    workTile.doWeed = workTile.agricraft.isWeeds(workTile.farm.getWorldObj(), workTile.bc.x, workTile.bc.y, workTile.bc.z);
    if (workTile.doWeed) {
      MinecraftServer.getServer().addChatMessage(new ChatComponentText("weeds at: " + workTile.bc));
```

```
    if (workTile.doWeed [...]
        boolean ret = workTile.agricraft.removeWeeds(world, workTile.bc.x, workTile.bc.y, workTile.bc.z, stack);
        MinecraftServer.getServer().addChatMessage(new ChatComponentText(ret + " from weeding at: " + workTile.bc + " with " + stack));
        TileEntity tileEntity = world.getTileEntity(workTile.bc.x, workTile.bc.y, workTile.bc.z);
        System.out.println(tileEntity); // breakpoint here
```

**Comment by InfinityRaider** [comment]
Before you posted this I though it was some server/client syncing issue, but that's obviously not the case. I'll write some tests and try to debug this.

**Comment by HenryLoenwind** [comment]
thx

**Comment by HenryLoenwind** [comment]
```while (!world.isRemote && weedGrowthStage > 0) {``` in the apiImpl will not remove weeds at growthstage 0.

**Comment by InfinityRaider** [comment]
Good find.

**Comment by InfinityRaider** [comment]
Actually I have no idea why there is a while loop there.

**Comment by HenryLoenwind** [comment]
it would make sense if the rakes took damage, but as the API method always removes weed it doesn't. Maybe only run it once and return false if the weeds were not removed completely? I was wondering why anyone would want to put a better rake into a machine.

**Comment by InfinityRaider** [comment]
I'm going to make a method in IRake and forward the API call and the onItemUse methods to that one.

**Comment by InfinityRaider** [comment]
This should have fixed everything, I tested wooden rake and iron rake both via the rakes and via the API, behaviour is as expected. Sorry for the inconvenience.
