### ISSUE TITLE
Add isAnalyzed() and analyze() methods to API

### ISSUE THREAD

**Issue by HenryLoenwind** [InfinityRaider/AgriCraft#455]
It always returns the values, even for unanalyzed seeds. (haven't yet checked getSeedStats(worldxyz))

BTW: The next API version should probably add isAnalyzed() to ISeedStats and analyze(ItemStack) to the API.

**Comment by InfinityRaider** [comment]
It's intended that it always returns the values. But you're right, it's not a bad idea to add those methods.

**Comment by HenryLoenwind** [comment]
If it's intended, you need to update the Javadoc...

**Comment by InfinityRaider** [comment]
I'm not sure how I should chagne this then, with the added methods to ISeedStats I think this is adequate:

>/**
> * Gives the statistics for the given seeds.
> *
> * @param seed
> *          Any ItemStack that is a seed.
> * @return An ISeedStats object that describes the given seeds, or null if the
> *         given item was no seed.
> */

**Comment by HenryLoenwind** [comment]
This one:

```
	/**
	 * @return The growth value of the seed. Will be -1 if the seed is not analyzed.
	 */
```

**Comment by InfinityRaider** [comment]
Oh there, my apologies.

**Comment by HenryLoenwind** [comment]
np, it is easy to overlook being only documented there. The original idea was to force mods to be honest, so they can't even cheat by accident when only using the API.

**Comment by InfinityRaider** [comment]
That's a good mindset, but if people want to cheat they will
