### ISSUE TITLE
1.4.4 java.lang.NullPointerException

### ISSUE THREAD

**Issue by SvEgiiVEteR** [InfinityRaider/AgriCraft#456]
the error in the log without breaking client
http://hastebin.com/qesisitixi.avrasm

**Comment by InfinityRaider** [comment]
I can't access that paste, can  you remake it please?

**Comment by SvEgiiVEteR** [comment]
http://paste.ubuntu.com/13227089/
:)

**Comment by InfinityRaider** [comment]
I expect that this is when hovering over a clipping? could you tell me what plant this clipping is from?

**Comment by SvEgiiVEteR** [comment]
no. This error occurs only when I go to the server. without any action.
sorry I do not know much english.

**Comment by InfinityRaider** [comment]
That is not possible, this line in  the log:
>at com.InfinityRaider.AgriCraft.handler.ItemToolTipHandler.addSeedStatsTooltip(ItemToolTipHandler.java:28) ~[ItemToolTipHandler.class:?]

is ClientSide only code: 
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/handler/ItemToolTipHandler.java#L18
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/proxy/ClientProxy.java#L98-L99

And it also says client thread:
>[Client thread/ERROR]

**Comment by SvEgiiVEteR** [comment]
Yes that's right. the error in the log on the client side.

**Comment by InfinityRaider** [comment]
So when does it happen?

**Comment by InfinityRaider** [comment]
Actually, some mod seems to be searching the ItemRegistry, including tooltips:

>at stevesaddons.threading.SearchItems.setItems(SearchItems.java:82) [SearchItems.class:?]
>at stevesaddons.network.message.SearchRegistryGenerateMessage.onMessage(SearchRegistryGenerateMessage.java:29) [SearchRegistryGenerateMessage.class:?]

And because a clipping without NBT doesn't make sense this is happening.

**Comment by InfinityRaider** [comment]
I'll add a check to see if there is NBT present or not to prevent this from happening.

**Comment by SvEgiiVEteR** [comment]
When I go to the server.
but it does not break the client and server.
thank. I will wait for the new version and check
