### ISSUE TITLE
API.isEmpty() returns true for cross crops

### ISSUE THREAD

**Issue by HenryLoenwind** [InfinityRaider/AgriCraft#457]
API documentation says it should not.

**Comment by InfinityRaider** [comment]
But how?
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/apiimpl/v1/APIimplv1.java#L200

**Comment by HenryLoenwind** [comment]
You fixed that after 1.4.4. Sneaky. ;)

**Comment by InfinityRaider** [comment]
Okay then :p
