### ISSUE TITLE
ExU 1.2.12 Watering Can has no effect on AgriCraft 1.4.4 crops

### ISSUE THREAD

**Issue by ButterChicken** [InfinityRaider/AgriCraft#458]
Using Forge 10.13.4.1517, seems like ExU Watering Can has no effect on growth of AgriCraft crops in version 1.4.4?

Watering Can seems to be working fine with vanilla crops.

**Comment by InfinityRaider** [comment]
I didnt rly do anything related to that though.

**Comment by ButterChicken** [comment]
As far I know the Watering Can was working fine before I updated to 1.4.4, but maybe it is some other cross-mod interaction? Bonemeal still works on AgriCraft crops as well.

**Comment by InfinityRaider** [comment]
what version did you update from?

**Comment by ButterChicken** [comment]
Version 1.4.3

**Comment by blarghhh** [comment]
Well I am on infinity 2.1.2 and using 1.4.4 agricraft and it works fine with exu watering can

**Comment by InfinityRaider** [comment]
Well I didn't change anything, and I'm not going to try figuring out why it wouldn't work in your case, probably some other mod doing it then.
