### ISSUE TITLE
User "AgriCrafting" crops of other mods

### ISSUE THREAD

**Issue by Belgabor** [InfinityRaider/AgriCraft#46]
It would be nice if a user (or more probably mod pack author) could easily add support to crops of unsupported other mods. As far as I can see this would require (additionally over custom settings already possible):

 * Identifying the seed item
 * Full resource path to the respective textures

**Comment by thephoenixlodge** [comment]
Is there a specific mod you're referencing? Agricraft works outright with most crops without having any special compatibility, even respecting special harvest systems - see witchery's mandrake and snowbell

**Comment by InfinityRaider** [comment]
What thepoenixlodge said. What mod/seed is not acting nicely?

**Comment by Belgabor** [comment]
I'm mostly thinking of two, Apple Milk and Tea, which has one true crop (incompatible) but also three other plants I'd like to make compatible with as least duplication as possible. Second is Thaumcraft, things like growing shimmerleaf and cinderpearl could be possible reusing the resources of the original mod.
Honestly, my main concern is being able to reuse the original "seed" item, so I don't have to cater for two items that are essentially the same and will confuse pack players.

**Comment by InfinityRaider** [comment]
I have no idea what that first mod is, can you give me a link to it? And about Thaumcraft shimmerleaf & Cinderpearl, this isn't the first time someone mentioned that. They are not crops and don't have seeds and therefore can't be supported. What you can do is add in a custom crop that produces shimmerleaf/Cinderpearl.

**Comment by Belgabor** [comment]
Apple, Milk and Tea is a mod by a Japanese modder, Links:
http://forum.minecraftuser.jp/viewtopic.php?t=17657
http://defeatedcrow.wiki.fc2.com/wiki/AppleMilkTea%20ver2
Second link is the wiki, which translates rather well with google translate.

You are probably correct on the TC plants, I'd have liked to be able to directly reference the texture from TC for the fully grown version though as TC isn't open source. Maybe add some optional overrides for the texture resource paths?

**Comment by Belgabor** [comment]
Oh, the plants I was referring to in AMT is the mint crop and (the non-crop ones) tea, cassis and camelia.

**Comment by InfinityRaider** [comment]
I've looked at AMT, the mint seeds is not instance of ItemSeeds so I can't and will not support it. If you want support for it, ask the author of AMT to let his seeds extend ItemSeeds. As for the other non-crop ones the same counts as for cinderpearl/shimmerleaf.
About the textures, you can just grab the texture out of the jar and rename it. I'm not going trough the hassle of grabbing existing textures and programming exceptions and cases if users specified something wrong or if that mod does something strange with his textures (for instance generating textures at runtime).
