### ISSUE TITLE
Lapender Seeds Not Growing Correctly

### ISSUE THREAD

**Issue by ReportBot9009** [InfinityRaider/AgriCraft#461]
I'm not quite sure if I'm doing this wrong or if this is a bug. I can't seem to mutate lapender seeds and when I creatively gave myself the seed, it wouldn't grow. I have normal farmland over a block of Lapis Lazuli just like the instructions say, but WAILA says it cannot grow here. 

Here is a screenshot:
http://imgur.com/ojdhVcG

**Comment by InfinityRaider** [comment]
http://puu.sh/llM1I/52610605a7.png
Seems to be a little bug
