### ISSUE TITLE
Tanks dont form when generating in vilalges

### ISSUE THREAD

**Issue by Rukachan** [InfinityRaider/AgriCraft#462]
The watertanks spawning in a village are not multiblock and I have to replace one of them to make them multiblock. http://b.1339.cf/cfnzqyo.png

When breaking a colum of a multiblock watertank it does not re-form unless I replace one of the blocks. http://b.1339.cf/cubevyc.png

**Comment by InfinityRaider** [comment]
The first one I can fix, the second one I could fix, but I will not, because else the number of operations needed to perform checks and form sub multiblocks would be to large.

**Comment by Rukachan** [comment]
Have you considered checking the code forestry uses for its multiblocks?

**Comment by InfinityRaider** [comment]
No, but Forestry has limited sizes, and if you break a column it wont reform either.
