### ISSUE TITLE
1.4.5 and BloodMagic

### ISSUE THREAD

**Issue by SvEgiiVEteR** [InfinityRaider/AgriCraft#463]
http://paste.ubuntu.com/13286089/
Crush the client is not, but I decided to report an error in the log.
Error loading the game menu.

forge 1558
BloodMagic-1.7.10-1.3.3-17
and full log
http://paste.ubuntu.com/13286242/

**Comment by TehNut** [comment]
Not an issue on this end. Close.

We access internal methods unsafely and they were changed.

**Comment by InfinityRaider** [comment]
Odd, didn't knwo BM had its own handler. I registered oen myself: https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/compatibility/bloodmagic/HarvestHandler.java

**Comment by TehNut** [comment]
Oh cool. Guess we'll remove the one on our end. @WayofTime

**Comment by InfinityRaider** [comment]
Closing this then.
