### ISSUE TITLE
crash with nei or at least from what i can see

### ISSUE THREAD

**Issue by joshuabrody2001** [InfinityRaider/AgriCraft#464]
http://pastebin.com/GSYzTJYt
that is the error report if someone could help me this would be great

**Comment by InfinityRaider** [comment]
Thanks for reporting, Ill look into it

**Comment by joshuabrody2001** [comment]
Thanks it would really help!

**Comment by InfinityRaider** [comment]
Is this while playing SSP, SMP or on LAN?

**Comment by joshuabrody2001** [comment]
Smp

**Comment by joshuabrody2001** [comment]
Im impatient so i thought i would ask how it was going

**Comment by InfinityRaider** [comment]
I'm busy with something else atm, I'll look at it when I have time.

**Comment by joshuabrody2001** [comment]
Ah np take your time

**Comment by joshuabrody2001** [comment]
I managed to fix it by rewriting a few nei recipe "codes" im not sure if you got around to looking at this problem but if you did thanks for your time

**Comment by InfinityRaider** [comment]
what do you mean recipe "codes"?

**Comment by joshuabrody2001** [comment]
I found the fastest way being editing nei with intellij idea and tweaked the way it handled the agricraft recipes

**Comment by InfinityRaider** [comment]
Could you share your adaptions please? Others might be experiencing this crash too, so it can be fixed for everyone.

**Comment by joshuabrody2001** [comment]
Sure i just need about 1-2 hours i have something around my house i need to do

**Comment by InfinityRaider** [comment]
Can't really reproduce this, but since you said you've managed to fix it, I'll close it again until someone else encounters it.
