### ISSUE TITLE
Limit some seeds to only be plantable on crops on certain soils

### ISSUE THREAD

**Issue by thephoenixlodge** [InfinityRaider/AgriCraft#47]
I'd like to be able to make it so that some plants will only be able to be planted on crop sticks if the crop sticks are placed on specific soils. One example of this would be nether wart - with what I'm proposing, it would only be possible to place netherwart on the crops if they were on soul sand. Another example would be witchery's Water Artichoke. Normally it can only be planted on water, but in Regrowth I have it only obtainable by a mutation, requiring it to be used with crop sticks, potentially leading people to believe that in a normal environment in would be able to be planted on dirt. This system I'm proposing would let me have it only be be able to be mutated if the crops were placed on the surface of water.
This would allow a more faithful method of allowing such plants to be used with crops and having the benefits of such things, but without the weirdness of planting them on a surface other than initially intended.

**Comment by InfinityRaider** [comment]
Added in d422de140011d06b325b0f2f4e511494a370bc32
