### ISSUE TITLE
Journal doesn't handle animated growth stages correctly

### ISSUE THREAD

**Issue by HenryLoenwind** [InfinityRaider/AgriCraft#470]
![](http://i.imgur.com/CeNzQnS.png)

**Comment by InfinityRaider** [comment]
Well this is something I'll need to fix, thanks for letting me know.

**Comment by InfinityRaider** [comment]
Also can you tell me what mod that is from?

**Comment by HenryLoenwind** [comment]
Ender IO Addons, unreleased
