### ISSUE TITLE
[Compatabilty Issue] Water Tanks eat Buckets on being filled.

### ISSUE THREAD

**Issue by BraynStorm** [InfinityRaider/AgriCraft#473]
Self-explanatory. Running v.1.4.5. (I have only tried it on Spruce tanks)

**Comment by InfinityRaider** [comment]
I'll see if I can duplicate it. Type of tank shouldn't matter btw.

**Comment by InfinityRaider** [comment]
Works fine for me, have you tried in an instance with only agricraft?
http://puu.sh/luvZ5/190d5b3d30.png
http://puu.sh/luw0u/3d986e3abe.jpg

**Comment by BraynStorm** [comment]
It works properly on a clean instance, Mhm... No idea which mod breaks it.

**Comment by InfinityRaider** [comment]
Youll have to add half of your mods to the instance, check it. If it happens then keep that half and repeat, if not, repeat with the other half. And so on until you pinpointed what caused it.

**Comment by BraynStorm** [comment]
Yeah I thought about that but thats 100+ mods. Not today :)
