### ISSUE TITLE
AgriCraft freezing server startup

### ISSUE THREAD

**Issue by Plobby** [InfinityRaider/AgriCraft#476]
Hello.

I have been previously running the FTB Infinity modpack (Version 2.1.3) on my server. This has been working fine for a fair duration of time. However, upon trying to start up the server recently, I am getting errors from AgriCraft in the console, causing the server startup to freeze completely and not run whatsoever.

AgriCraft Version: AgriCraft-1.7.10-1.4.3
Forge Version: ForgeMultipart-1.7.10-1.2.0.345-universal

Error message in console:

26.11 09:40:42 [Server] AgriCraft Error when reading mutation: resulting stack is not correct. (line: AgriCraft:seedPlombean=AgriCraft:seedFerranium+AgriCraft:seedPotato)
26.11 09:40:42 [Server] AgriCraft Error when reading mutation: resulting stack is not correct. (line: AgriCraft:seedPetinia=AgriCraft:seedLapender+AgriCraft:seedDaisy)
26.11 09:40:42 [Server] AgriCraft Error when reading mutation: resulting stack is not correct. (line: AgriCraft:seedCuprosia=AgriCraft:seedRedstodendron+AgriCraft:seedTulipRed)
26.11 09:40:42 [Server] AgriCraft Error when reading mutation: resulting stack is not correct. (line: AgriCraft:seedQuartzanthemum=AgriCraft:seedNitorWart+AgriCraft:seedLapender)
26.11 09:40:42 [Server] AgriCraft Error when reading mutation: resulting stack is not correct. (line: AgriCraft:seedNitorWart=minecraft:nether_wart+AgriCraft:seedTulipOrange)
26.11 09:40:42 [Server] AgriCraft Error when reading mutation: resulting stack is not correct. (line: AgriCraft:seedEmeryllis=AgriCraft:seedFerranium+AgriCraft:seedRedstodendron)
26.11 09:40:42 [Server] AgriCraft Error when reading mutation: resulting stack is not correct. (line: AgriCraft:seedDiamahlia=AgriCraft:seedAurigold+AgriCraft:seedLapender)
26.11 09:40:42 [Server] AgriCraft Error when reading mutation: resulting stack is not correct. (line: AgriCraft:seedAurigold=AgriCraft:seedRedstodendron+AgriCraft:seedTulipOrange)
26.11 09:40:42 [Server] AgriCraft Error when reading mutation: resulting stack is not correct. (line: AgriCraft:seedFerranium=AgriCraft:seedLapender+AgriCraft:seedTulipWhite)
26.11 09:40:42 [Server] AgriCraft Error when reading mutation: resulting stack is not correct. (line: AgriCraft:seedLapender=AgriCraft:seedTulipPink+AgriCraft:seedOrchid)
26.11 09:40:42 [Server] AgriCraft Error when reading mutation: resulting stack is not correct. (line: AgriCraft:seedRedstodendron=AgriCraft:seedTulipRed+AgriCraft:seedDaisy)

Any help would be appreciated. I have tried resetting the config files to no avail, removing and reinstall the mod, all to no avail. If I change the world name and create a fresh world, I sometimes do not get these errors. However, the world I am using runs perfectly fine on a singleplayer client.

Thanks.

**Comment by InfinityRaider** [comment]
Complete log please.

**Comment by InfinityRaider** [comment]
Closing due to lack of response.
