### ISSUE TITLE
Title Entity Load issues

### ISSUE THREAD

**Issue by Fatthunder** [InfinityRaider/AgriCraft#477]
Hello,
I am using Agricraft 1.7.10-1.4.5 and am experiencing a weird bug with Sprinklers and Wood Channels.    While in the dimension with these everything is fine, however when I leave that dimension (chunk loaded) there seems to be a massive jump in timing causing tps issues.  Attached is album of timing pictures gotten from Opis (http://imgur.com/a/UcTff).

**Comment by InfinityRaider** [comment]
Hmm, is it possible that your irrigation channel is crossing a chunk boundary to a chunk which is not chunkloaded?

**Comment by Fatthunder** [comment]
So, just did some tests. While it was considered 'Chunk Loaded' via Railcraft Admin Anchors, it seems like the admin anchors weren't actually loading the chunks, switching to world anchors seemed to fixed the timing issues. Sorry for the inconvenience.

**Comment by InfinityRaider** [comment]
But they were still receiving ticks?

**Comment by Fatthunder** [comment]
Don't know the technical stuff behind it, but know that when I had my main irri system loaded by world anchor and part of that loaded by admin anchor, tps was going insane. After switching the admin to world, so whole system loaded by world anchors, it went away.  Doesnt really make much sense, think it could be on RC side.

**Comment by InfinityRaider** [comment]
I honestly have no idea how chunkloaders work, but if you say its fine by using another one, Im going to close this.
