### ISSUE TITLE
Render Bug - Seed Storage

### ISSUE THREAD

**Issue by xKillerbees** [InfinityRaider/AgriCraft#478]
http://pastebin.com/JGerrV6S

Tried putting a "canola seed" from rotarycraft into a seed storage chest and now I can't log back onto the server.

**Comment by InfinityRaider** [comment]
I must have removed a null check in some refactoring of code, apologies. WIll fix this at once, thanks for reporting.

**Comment by xKillerbees** [comment]
Thank you, looking forward to 1.4.6
