### ISSUE TITLE
Seed Storage visual bug

### ISSUE THREAD

**Issue by HenryLoenwind** [InfinityRaider/AgriCraft#479]
https://github.com/HenryLoenwind/EnderIOAddons/issues/14

I think it's this:

```
protected void drawScaledFaceDoubleXY(
        float minU = 0;
        float maxU = icon.getIconWidth();
        float minV = 0;
        float maxV = icon.getIconHeight();
...
   icon.getInterpolatedU(u), icon.getInterpolatedV(v)
```

getInterpolatedU() takes a value between 0 and 16, where getIconWidth() gives the size of the icon in pixels. Vanilla icons are 16x16 pixels, so it sometimes works.

**Comment by InfinityRaider** [comment]
You're right, oversight on my part, will fix.

**Comment by InfinityRaider** [comment]
https://github.com/InfinityRaider/AgriCraft/commit/a7d67b50704e0cd187aad307052578f9f1226ea7

Tagged wrong issue in the commit, damn you tiredness.
