### ISSUE TITLE
More option for produce

### ISSUE THREAD

**Issue by Belgabor** [InfinityRaider/AgriCraft#48]
I'd like to have more options for the produce of custom crops

 * More than one different item
 * Probability (eg crop that always gives item A, but has a rare chance to give item B as well, like for example the Witchery Snowbell). Could also allow for cases where you want plentiful produce. I Imagine a syntax similar to Minetweaker, like mincraft:clay * 2;minecraft:clay * 0.5;minecraft:clay * 0.1
 * NBT data (maybe through #42 as MineTweaker already has a syntax for that)

**Comment by InfinityRaider** [comment]
I will look into it

**Comment by InfinityRaider** [comment]
I'm not sure if this can be implemented trough minetweaker  though. I'd have to look if it's actually possible to add/register new items and blocks when the world is already loaded

**Comment by Belgabor** [comment]
Well, maybe the user needs to register it via the txt file but can then change the produce with MineTweaker?

**Comment by Belgabor** [comment]
For example have the produce be null in the textfile and implement a MineTweaker function like this

    addProduce(crop, item, probability)

that can be called multiple times on the same crop.

**Comment by InfinityRaider** [comment]
Added this functionality in adc579eef2fb8c374a21dee904081dc224bb3d49
