### ISSUE TITLE
Harvestcraft Sesame Seed plant not dropping drop on harvest.

### ISSUE THREAD

**Issue by TheDarkPreacher** [InfinityRaider/AgriCraft#482]
So I'm helping test a modpack for Tedyhere (Cthulhu Awakens) and I have a Harvestcraft sesame seed plant set up in some Agricraft cropsticks. When the plant is mature, I right click to harvest the plant, and it goes down to 28% grown and doesn't drop a sesame seed. This is with version 1.7.10La of Harvestcraft and version 1.4.5 of Agricraft. Not sure if this is a Harvestcraft bug or an Agricraft bug, will be reporting to Harvestcraft's dev as well.

**Comment by InfinityRaider** [comment]
This is because the seed and the fruit are not correctly registered in the OreDict on Pam's side.
It needs to be seed<plantName> and crop<plantName>, for the seeds one is registered as 'sesameSeed' and the other as 'sesameSeeds'. That's why it doesn't work.
