### ISSUE TITLE
Sprinkler being destroyed by trees.

### ISSUE THREAD

**Issue by Keridos** [InfinityRaider/AgriCraft#484]
We have a treefarm irrigated with sprinklers 5 blocks above the plantlings (oak). Occassionally when a tree grows it seems to replace one of the sprinklers.

**Comment by InfinityRaider** [comment]
what version?

**Comment by InfinityRaider** [comment]
Closing due to lack of response

**Comment by Keridos** [comment]
Oh sorry, had too much issues, did not notice this. Using AgriCraft-1.7.10-1.4.5

**Comment by InfinityRaider** [comment]
Apparently I used the wrong method for this, I though this would have fixed it:
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/blocks/BlockSprinkler.java#L45-L48

But it's actually this:
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/blocks/BlockSprinkler.java#L51-L54

This is why I was confused and thought it was fixed, apologies. But it should definatly be fixed now.

**Comment by Keridos** [comment]
Thanks for the ultra quick fix :) Good job on that, might want to add that in in my mods as well, did not even know that existed, hehe.
