### ISSUE TITLE
B:GenerateDefaults doesn't set itself back to false

### ISSUE THREAD

**Issue by misterhaan** [InfinityRaider/AgriCraft#486]
In Configuration.cfg the comment suggests that I can set GenerateDefaults to true and have AgriCraft regenerate Mutations.txt and then set GenerateDefaults back to false:

    # set to true to regenerate a default mutations file (will turn back to false afterwards)
    B:GenerateDefaults=false

It stays true for me both on single player / client on Windows and server on Linux.  This made issue #485 more difficult to fix because it kept regenerating the broken mutations file.

**Comment by InfinityRaider** [comment]
Hmm yes, I removed that automatic reset a while ago but I never updated the description. I'm kind of undecisive to what I want to do, keep it like this and change the description or add the automatic reset back.
