### ISSUE TITLE
Server Crash Seed analyzer vs Harden item duct!

### ISSUE THREAD

**Issue by KaneHart** [InfinityRaider/AgriCraft#487]
http://pastebin.com/s3qvb9jh

From what I'm told by @KingLemming is that the Analyzer has 36 slots? But I'm pretty sure it's only meant to have one. So in the end I guess it's causing a bit of a issue there.

**Comment by InfinityRaider** [comment]
It has only 2 slots though, but they use the same ID's as for the Container:
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/tileentity/TileEntitySeedAnalyzer.java#L284-L314

**Comment by InfinityRaider** [comment]
Reference to this issue on the COFH tracker: https://github.com/CoFH/Feedback/issues/954
