### ISSUE TITLE
Hunger Overhaul growth ticks

### ISSUE THREAD

**Issue by InfinityRaider** [InfinityRaider/AgriCraft#49]
AgriCraft crops grow at normal speed, despite presence of Hunger Overhaul

**Comment by InfinityRaider** [comment]
Need to wait for Hunger Overhaul to add support

**Comment by Imasius** [comment]
Leaving this here for future reference [TiCon Tooltips dev post](http://forum.feed-the-beast.com/threads/1-7-10-agricraft.50964/page-16#post-890556)
