### ISSUE TITLE
Seed piping...

### ISSUE THREAD

**Issue by therealericbj** [InfinityRaider/AgriCraft#490]
Seed piping to Agricraft Seed Storage blocks.

I really hope that I am not missing something really obvious.  I just can't get a piping system to work.

Each different mod pipes have their own problems.  The most common problem is that I can't seem to numb them down enough to ignore the different stats of the individual type of seed and just put them in the appropriate block.

So, is it possible to pipe seeds to their appropriate storage block?

If it is, how is the data for the stats on the individual seed stored?  I can tell the various filters to look at or ignore meta data, nbt data, ore dictionary info, mod type, etc.

I really hope that the problem is something like, there is still another part of your storage system being developed and I just have to be patient.  I can do that...

**Comment by InfinityRaider** [comment]
What version are you running?

**Comment by therealericbj** [comment]
Oh, right, what was I thinking...

Forge 1566
Minecraft 1.7.10
AgriCraft-1.7.10-1.4.5.jar

Sorry

**Comment by InfinityRaider** [comment]
I think it's due to the same reason as #487: I'm not giving slots from 0 to sizeInventory, I made my own system and I made it comply with ISidedInventory. I'll have to look into this.

**Comment by InfinityRaider** [comment]
I've disabled automatic input/output for now, I'll readd it with #492
