### ISSUE TITLE
Correctly implement ISidedInventory for Seed Storages

### ISSUE THREAD

**Issue by InfinityRaider** [InfinityRaider/AgriCraft#492]

**Comment by therealericbj** [comment]
Hi, hope this is the right place for these comments.

I saw your update, AgriCraft-1.7.10-1.4.6-pre2.jar and how it mentioned solutions to the Seed Storage problem I mentioned earlier.  So I tried it out in a single player test world, that was created at the same time as the server world where I discovered the above mentioned issue #490.

This is what I found when I tried it...

Piping the seeds in with EnderIO item conduits worked just fine.There seemed to be no difference whether there were already seeds in the storage block or not.

Piping the seeds out was a different matter.  I put 3 seeds in the storage block and proceeded to pipe them out.  I stopped trying to get the 3 seeds out when I had about a stack and a half of seeds in the receiving chest.  Also, the original 3 seeds never did leave the storage block.  If you needed extra seeds that would definitely be one way to solve the problem, but I pretty sure a feature like that was not your goal.  :P 

The seed type that is in the storage block, showing up in the WAILA tool tip is excellent, that is a huge help.  Now my wall of seed storage blocks will not be quite so frustrating to deal with.  Finding a particular seed will be easy.  :)  

I wonder how the storage blocks will behave if I hook them up to an EnderIO Inventory Panel?  I love experimenting.

I hope this information is helpful to you.

**Comment by InfinityRaider** [comment]
I didn't test with EnderIO conduits, but hoppers and thermal dynamics conduits worked fine. I'm suspecting that EnderIO conduits are getting the ItemStack when they pull out an item from a slot and then directly changing the stacksize. However the seeds are not saved as ItemStacks, and therefore reducing the stacksize doesn't actually do anything.
I'll have to investigate the source code, but I think this is on their end. Thanks for reporting

**Comment by InfinityRaider** [comment]
Right it was my side, has been fixed.
