### ISSUE TITLE
Seed Storage question...

### ISSUE THREAD

**Issue by therealericbj** [InfinityRaider/AgriCraft#493]
I have no idea if this is a hard thing or not...

Is it possible to have the name of the seed being stored displayed on the front of the storage block or maybe in the WAILA tool tip?

I was thinking if displayed on the front of the storage block like the JABBA barrel or the Router Reborn Storage Unit.

**Comment by InfinityRaider** [comment]
:D
Waaay ahead of you:
https://github.com/InfinityRaider/AgriCraft/commit/4dbff7eeb6602e34b1e7e76fa94099ac5c4f4f85

**Comment by InfinityRaider** [comment]
And also the seed stored in it should be rendered on the frotn of the block
