### ISSUE TITLE
Computer Controller Seed Analyzer: Invalid arguments

### ISSUE THREAD

**Issue by DavsX** [InfinityRaider/AgriCraft#494]
Hi!
I'm playing FTBInfinity Evolved and after upgrading to the latest version of it, I'm keep getting the following error: "Method analyze errored: invalid arguments". I'm calling it the same way as before the update (I have a turtle which uses it to analyze a seed):

```lua
p = peripheral.wrap('bottom')
p.analyze()
```

Agricraft version: 1.4.5, ComputerCraft version: 1.74

**Comment by InfinityRaider** [comment]
It's workign fine for me though:
http://puu.sh/lRnfU/e521c57c72.png

**Comment by DavsX** [comment]
Which Java version are you using? 1.8 here. Could that be the problem?

**Comment by InfinityRaider** [comment]
Might be, I'm using 1.7

**Comment by DavsX** [comment]
Same problem here with jdk 1.7

**Comment by InfinityRaider** [comment]
Can you test with the beta build on CF?

**Comment by DavsX** [comment]
AgriCraft 1.4.6pre + ComputerCraft 1.75 = working again. Thanks for the suggestion.

**Comment by InfinityRaider** [comment]
Okay, probably in build 1.4.5 something was bugged, which I must have fixed but forgot about it.
