### ISSUE TITLE
Botania api crash.

### ISSUE THREAD

**Issue by TheDarkPreacher** [InfinityRaider/AgriCraft#497]
Loaded up Cthulhu Awakens latest update, which has no Botania in it, and even changing line 51 of the config to false doesn't fix it, and agricraft continually causes the same crash. Game doesn't even load. reported issue to Tedyhere as well so he is aware.

http://pastebin.com/hKHy85x4

**Comment by InfinityRaider** [comment]
Surely my fault, I forgot to add @Optional interfaces to some methods, thanks for reporting and sorry for the inconvenience.

**Comment by TheDarkPreacher** [comment]
no problem, just gonna downgrade for now, since i know that v. 1.4.5 works. Tedy added 1.4.6-pre to the pack.

**Comment by InfinityRaider** [comment]
Alright, not that this fix is not yet in 1.4.6-pre2 (which I pushed minutes before this issue was created).

And on an unrelated note, that accidently pinged a user named 'Optional'
