### ISSUE TITLE
Kitchen mod

### ISSUE THREAD

**Issue by zHawky** [InfinityRaider/AgriCraft#502]
Hey, if you have time take a look on kitchen mod aka modular sandviches, actually they dont have seeds but maybe you make own seeds and breed system?

**Comment by InfinityRaider** [comment]
Could you link to the mod please?

**Comment by zHawky** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2091948-the-kitchen-mod-v1-3-17-modular-sandwiches-now

**Comment by InfinityRaider** [comment]
Thanks

**Comment by InfinityRaider** [comment]
It was not a sync issue, but good find.
