### ISSUE TITLE
Seed Storage HD Texturepack Bug

### ISSUE THREAD

**Issue by oninoni** [InfinityRaider/AgriCraft#503]
When you use a high res texturepack seeds displayed in the seed storage are displayed smaller. You can also see other neiboured textures on the Texturemap

![2015-12-15_18 05 51](https://cloud.githubusercontent.com/assets/4203340/11817708/73d47d90-a356-11e5-9a7e-8e37bc565184.png)

Im using FTB Infinity Evolved (2.2.2) With Agricraft 1.4.5

**Comment by InfinityRaider** [comment]
I should have fixed that, check out version 1.4.6-pre2, it should be fixed in that one.

**Comment by InfinityRaider** [comment]
Closing due to no response and I believe it has been fixed.
