### ISSUE TITLE
Harvestcraft Cranberry Seed soil type

### ISSUE THREAD

**Issue by Hazmatik** [InfinityRaider/AgriCraft#505]
Normally the Harvestcraft cranberry seeds are planted on water like the rice and seaweed seeds, yet I noticed in Agricraft unlike the rice and seaweed seeds they don't require the water pad. Was this intentional?

**Comment by InfinityRaider** [comment]
Didn't realize I haven't implemented that yet, someone else has brougth this up before, and I could have sworn I changed it, I'll add it in now then.
