### ISSUE TITLE
Weeds...

### ISSUE THREAD

**Issue by therealericbj** [InfinityRaider/AgriCraft#506]
I think I may have found a visual bug with regards to weeds.

I have been trying the latest version, AgriCraft-1.7.10-1.4.6-pre2.jar, you released.  Checking out the piping of seeds to storage blocks and the displaying of the contents in the WAILA tool tip.  (The second one is a huge help, Thank you.)

I noticed something odd.  Quite regularly, I would start breeding up a seed from just one seed.  At the beginning, there are usually lots weeds.  It makes sense when you are using an EnderIOAddon Agricraft Farming Station on a 5x5 plot, lots of places for weeds.

Since updating to your newest file, I haven't seen any weeds at all.  I have noticed that during the breeding process, when the cross crop on top would disappear and a seed or weed would show up, the seed shows up as normal, but then sometimes nothing would show up.  The tool tip on that place would say no seed is planted.

I checked my config file to see if weeds are still turned on, which they are.

I'm using Minecraft 1.7.10, Forge 1566, AgriCraft-1.7.10-1.4.6-pre2.jar and EnderIOAddons-1.7.10-2.3.0.421_beta-0.9.12.040_beta.jar

**Comment by InfinityRaider** [comment]
Probably a sync issue, I'll investigate this, thanks for reporting it.

**Comment by Fabboz** [comment]
got the same problem too. 
when cross breeding the cropstick disappear but no weed or new seed appear.

**Comment by InfinityRaider** [comment]
this is fixed in #502, tagged wrong issue.
