### ISSUE TITLE
Multiblock tank causing server crash when chunk is loaded

### ISSUE THREAD

**Issue by helkarakse** [InfinityRaider/AgriCraft#509]
Hello. I am currently running Agricraft 1.4.5 (Regrowth pack - 0.8.6) on a server and I am receiving this error whenever the chunks with the tanks are loaded by a player: http://pastebin.com/Tiff06xc. Please let me know if you need further information. I can't load the chunks to tell if they're made of oak or not.

**Comment by helkarakse** [comment]
I was able to obtain a mcedit screenshot of the blocks in question: http://i.imgur.com/waiyXaa.jpg

**Comment by helkarakse** [comment]
The wood used was "Fir" from ExtraBiomesXL.

**Comment by InfinityRaider** [comment]
Type of wood doesn't matter.

**Comment by InfinityRaider** [comment]
The fact that hte stacktrace is obfuscated isn't really helping.
Is the tank crossing a chunk boundary?

**Comment by Zaflis** [comment]
I don't know how related this is, but for me the multiblock tank isn't forming properly. Or sometimes after a while it loses the form. I was having roughly 4x4x4 tank, and with fluid transfer node it was only able to fill it 10% full last time i tried. Now built a 2x2x2 tank, piped water in from bottom and it filled 100%. Whole irrigation network, tank included fit well inside 1 chunk.

So while i may not crash now, it could be a problem if there is an error with the structure. I tend to hotfix it by using 1x1x1 size tank, and it works really well if i do have a piped water source.

FTB Infinity evolved, with agricraft 1.7.10-1.4.6-hotfix, and config set to not create water source blocks when tanks are broken.
