### ISSUE TITLE
Suggestion: Vertical Water Transfer

### ISSUE THREAD

**Issue by Fatthunder** [InfinityRaider/AgriCraft#511]
So I am building a multi-layer farm and I would like to use the irrigation system on all levels, but don't want to have to have multiple tanks for each level.  So it would be nice QoL if the enclosed wooden irrigation channels allowed for downward water transfer so I would only need a tank at the top and water to flow downward.  Don't really know if this is feasible, but would be nice.

Side note: im using Agricraft-1.7.10-1.4.6-pre2 and while the smooth lighting changes helped a little, there is still about a 20-40 fps drop between no smooth lighting and max smooth lighting.

**Comment by InfinityRaider** [comment]
Thanks for the suggestion but I'm not going to implement this, you can simply use tanks instead of enclosed irrigation channels for downwards transfer.
