### ISSUE TITLE
can't place crops on water pads

### ISSUE THREAD

**Issue by Tomatoh** [InfinityRaider/AgriCraft#512]
AgriCraft-1.7.10-1.4.6-pre2.jar
forge-1.7.10-10.13.4.1558-1.7.10-universal.jar

Can't place crops on water pads since updating from the previous version.

I checked  the previous post and it referenced a commit but i just built off gradle and same issue.. rolling back to AgriCraft-1.7.10-1.4.5.jar the issue does not appear..

**Comment by InfinityRaider** [comment]
Thanks for reporting this, but it has already been reported: see #498 and fixed.
