### ISSUE TITLE
[Compatibility] Garden Stuff Candililla seeds

### ISSUE THREAD

**Issue by thephoenixlodge** [InfinityRaider/AgriCraft#515]
As of version 1.7.0 Garden stuff has a Candililla crop for growing the wax for its candles.

**Comment by InfinityRaider** [comment]
Ill sneak that in before the next release then. Also I still need a DL link for Millenaire.

**Comment by thephoenixlodge** [comment]
Millenaire is here: http://millenaire.org/index.php?l=en

**Comment by InfinityRaider** [comment]
Whaw, I hope I'll be able to get that workign in my dev env.
