### ISSUE TITLE
[Compatibility] Pam's Harvest the Nether

### ISSUE THREAD

**Issue by mamgar** [InfinityRaider/AgriCraft#516]
Innate support for pam's harvest the nether would be nice since there is already support for harvestcraft and wee flowers

**Comment by InfinityRaider** [comment]
Wee flowers should already be supported, Ill have a look at that other mod.

**Comment by mamgar** [comment]
The crops aren't anything unique. essentially a nether lettuce, nether berry and a 'meat' plant.

It also adds a glowstone plant which treads a bit on nitor wart. being craftable into glowstone at a 3:2 ratio.
