### ISSUE TITLE
Client crash on startup

### ISSUE THREAD

**Issue by therealericbj** [InfinityRaider/AgriCraft#517]
I'm not certain who's issue this is, so I am posting it in both places...

Loaded up to new update, AgriCraft-1.7.10-1.4.6.jar, started up the client and got this...

http://openeye.openmods.info/crashes/d2fd59606e6ca57d6b760173d19d231e

Client will not start up, crashes every time.

Forge 1566
AgriCraft-1.7.10-1.4.6.jar
EnderIOAddons 0.9.13 for Ender IO 2.3.0.422

**Comment by InfinityRaider** [comment]
I may have fucked up completely.
