### ISSUE TITLE
Server Crash, and Client Crash

### ISSUE THREAD

**Issue by Exoticburrito** [InfinityRaider/AgriCraft#521]
Some sort of Wooden Water Tank visual glitch, probably due to the connected textures, causes for both client-side crash, and server crash. I went to break the Tank, but the textures wouldn't connect, so i broke it, and replaced it, and crashed. Odd, but whenever the chunk is loaded, the client and server both crash. On version 1.4.5, in the infinity evolved pack.

**Comment by InfinityRaider** [comment]
Crash logs please

**Comment by Exoticburrito** [comment]
Will do as soon as I can

**Comment by Exoticburrito** [comment]
Issue seems to have been fixed with hot fix, many apologies, thanks
