### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by GreatOrator** [InfinityRaider/AgriCraft#522]
Crash on startup:

http://pastebin.com/5SuDhNFb

**Comment by InfinityRaider** [comment]
I don't know why this happens, but you'll have to redownload the jar from CurseForge.

**Comment by GreatOrator** [comment]
I will try again later, but just re-downloaded and got the same crash error.  Do you possibly have another place to download?

**Comment by InfinityRaider** [comment]
No, but I have no idea why this happens, it has happened to other people before, jsut randomly. Redownloading works mostly.

**Comment by GreatOrator** [comment]
Yeah, just tried 3 more different ways to download the hotfix and still getting the same crash, will just revert back to 1.4.5

**Comment by InfinityRaider** [comment]
There is nothing I can do about this though, there appears to be a missing class, but it should be right here: https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/blocks/BlockCrop.java

**Comment by GreatOrator** [comment]
Is it being added by ASM?  maybe another mod is removing the reference?  it is very odd.  and I know, I looked through the classes myself

**Comment by InfinityRaider** [comment]
What version of Botania do you have in your instance?

**Comment by GreatOrator** [comment]
in my case, 193, so an older version

**Comment by InfinityRaider** [comment]
That will be your problem, Botania added a new interface to its API, older versions which don't have that will crash. You'll have to update Botania.

**Comment by GreatOrator** [comment]
Or stick with the version of agricraft I am on.  Not keen on the changes in botania after 193.  We will just have to live with 1.4.5 then.  Vazkii will not budge on a compromise for the changes made.

**Comment by InfinityRaider** [comment]
Right, but please don't submit any more issues for 1.4.5, very likely that the stacktrace will not match the current code.

**Comment by GreatOrator** [comment]
Oh, don't worry, now that we know the cause it is a simple thing.  1.4.5 works just fine for me :D.  Thanks for looking into it.
