### ISSUE TITLE
Turtle Can't interact with Crop Stick

### ISSUE THREAD

**Issue by MrPotatoGaming** [InfinityRaider/AgriCraft#525]
Agricraft: 1.4.6-Hot Fix
Computer Craft: 1.75
Forge: 1558
MCP: 9.05
FML: 7.10.99.99

I created a testing environment to test if the bug is an incompatible with another mod, resulting in only the above listed mods being played with.

When a turtle/farming turtle is attempting to place seeds on a cropstick the action returns true, however nothing happens. I've used turtle.digDown() [which breaks the crop sticks, returning product, seed and output], I've used turtle.placeDown() [which will place the crop stick or the seed, not both], and I've used turtle.attackDown() [which was a ditch effort and does nothing.]

I've also attempted to do it direct on, as in turtle.dig() from the side of the farmland but that also didn't succeed. 

I don't assume this is intended, as there is an add-on for computers that allows them to check the stat of the seed and output to the turtle.

**Comment by InfinityRaider** [comment]
Doesn't the turtle have a right click command?

**Comment by MrPotatoGaming** [comment]
Not that I'm aware of. From my knoweldge, turte.place is the closet that is available. The entire api is documented on a webpage,  here's the link http://computercraft.info/wiki/Category:APIs

**Comment by InfinityRaider** [comment]
I know the robots from OpenComputers can right click blocks, but apperently those from ComputerCraft can't (or the documentation is incomplete, which I doubt), there is nothing I can do about that, apologies.

**Comment by MrPotatoGaming** [comment]
Ah no worries, I prefer OpenComputers anyway - but the pack I'm playing isn't mine.

**Comment by InfinityRaider** [comment]
I was under the impression they could right click, but since that's not the case it turns my peripheral into a little gimmick rather than a tool for automated crop levelling using ComputerCraft.

**Comment by MrPotatoGaming** [comment]
It's useful with Open Computers, on the bright side. Most people use Open Computers over Computer Craft anyways.

**Comment by InfinityRaider** [comment]
Maybe give Dan200 a suggestion to add useLeft(), useRight(), ... etc to the Turtle LUA API?

**Comment by MrPotatoGaming** [comment]
I'll link to this GitHub as well so Dan200 can get a little bit of context.

**Comment by MrPotatoGaming** [comment]
I posted the suggestion, but I have to wait for an administrator to approve of it.

**Comment by MrPotatoGaming** [comment]
Here's the [Link](http://www.computercraft.info/forums2/index.php?/topic/25591-use-item-support/) to the page.
