### ISSUE TITLE
Crash During Pack Load

### ISSUE THREAD

**Issue by Sanityy** [InfinityRaider/AgriCraft#526]
Hai,

So I've been adding some mods to my pack and I added Agricraft and it doesn't seem to be working. Everytime i open the pack, while loading mods it crashes. I've redownloaded the mod a few times and that does not seem to help. I don't know why this is happening, and if you could help me that would be great.

I downloaded the Agricraft file from Curse
file:
AgriCraft-1.7.10-1.4.6-hotfix.jar

And my forge version is 10.13.2.12.91

the crash report is down below

http://paste.atlauncher.com/view/a67cf612

**Comment by InfinityRaider** [comment]
This crash has been occurring for multiple versions randomly. I have no idea why it happens, you'll ahve to manually redownload the jar from CurseForge and try again.
I am stumped why this happens.

**Comment by InfinityRaider** [comment]
Seems to be an issue with the Botania API, continued in #522
