### ISSUE TITLE
Computer Controlled seed analyzer directions

### ISSUE THREAD

**Issue by yimmit303** [InfinityRaider/AgriCraft#527]
When ever i try to select a direction on one of the seed analyzer methods i get the same error. I've tried "right" "north" "ForgeDirection.right" and nothing works. I looked for about an hour all over the internet and there is pretty much nothing about it anywhere. I have 1.4.5 agricraft and 1.74 computercraft.

![2016-01-04_19 38 55](https://cloud.githubusercontent.com/assets/16549376/12104593/ef0b9db2-b31a-11e5-8a81-0e1f6c151af9.png)
![2016-01-04_19 39 00](https://cloud.githubusercontent.com/assets/16549376/12104594/ef36b542-b31a-11e5-9072-0135909ef691.png)

**Comment by InfinityRaider** [comment]
First update to 1.4.6-hotfix, there is a bug with the CC compat. And the directions specified are NORTH, EAST, SOUTH or WEST, fully capitalized.

**Comment by yimmit303** [comment]
Thank you so much! I was so frustrated after looking for so long and the answer was so simple. Works like a dream now.
