### ISSUE TITLE
Last round of 1.7.10 compat modules:

### ISSUE THREAD

**Issue by InfinityRaider** [InfinityRaider/AgriCraft#528]
- [x]  Gany's Surface
 - [x]  Gany's Nether
 - [x]  Et Futurum
 - [x] Calculator
 - [x] Harder Wildlife

**Comment by hron84** [comment]
[ ] [Calculator](https://github.com/SonarSonic/Calculator/issues/64)

**Comment by InfinityRaider** [comment]
Gany's End doesn't seem to have any crops, so I have removed it from the list.
