### ISSUE TITLE
[Suggestion] [Issue] No documentation / Api about the new peripherial for CC

### ISSUE THREAD

**Issue by frenchiveruti** [InfinityRaider/AgriCraft#529]
It would be nice to have at least a wiki or an API to make the peripherial easier to use, I'm getting a lot of errors trying to make it work :cry:

**Comment by frenchiveruti** [comment]
Just to showcase an example of error.
![screenshot_1](https://cloud.githubusercontent.com/assets/1095997/12189754/a38a737c-b59f-11e5-952d-8b9ee2dd5168.jpg)

**Comment by frenchiveruti** [comment]
Even making it raw:
![screenshot_2](https://cloud.githubusercontent.com/assets/1095997/12189963/d6667118-b5a1-11e5-9d41-3dbfa6f8019d.jpg)

**Comment by frenchiveruti** [comment]
I hope this helps.

**Comment by frenchiveruti** [comment]
Ok, I'm feeling kinda stupid, and I'm sorry, this was an old version bug, that it happends on FTB infinity evolved, as it uses a previous AgriCraft version (as for the 2.2.2 STABLE version), I found that you have to use Cardinal names as a workaround as stated at #527 
I'll close this now, and hope that no one notices :panda_face:

**Comment by InfinityRaider** [comment]
Notice what? Something happened?

**Comment by frenchiveruti** [comment]
I don't know

**Comment by frenchiveruti** [comment]
Hi, I have to reopen this issue, even with the latest version of Agricraft (the 1.4.6 hotfix) the system seems to still have to use cardinal names, and it won't do anything when issued an order like "getSeedStats".

**Comment by InfinityRaider** [comment]
Cardinal names are intended and will stay (make sure they are all capitalized)

**Comment by frenchiveruti** [comment]
Ok, but it's counter-intuitive, I mean, normally CC has "back, front, right, left" for the sides of machines/computers, could you at least add the ways of using the computer analyzer in a video? for all the methods, as you are the only one around who knows how to use it :smile:

**Comment by InfinityRaider** [comment]
Right, but how are you going to distinguish left and right for a perfectly symmetric machine?
And I'll do that if I have some time.

**Comment by frenchiveruti** [comment]
The ol' notch style, adding an L on the texture?

**Comment by frenchiveruti** [comment]
Damn, misclicked.

**Comment by InfinityRaider** [comment]
Here's a GIF with an example usage of hte peripheral: http://puu.sh/muexT/b4761341a9.gif

**Comment by frenchiveruti** [comment]
Thanks for it!
May I suggest using imgur.com for gifs? they use HTML5 for processing them as webm, making load times faster (also small videos are smaller).

**Comment by InfinityRaider** [comment]
You may, but I like puush, its just a single click and then you can ctrl+v

**Comment by frenchiveruti** [comment]
Oh, ok, I understand.
Maybe Open Broadcast Software in a future? for recording this, I'm eager to automate my crosscrops haha
