### ISSUE TITLE
Resourcefulcrops integration issue

### ISSUE THREAD

**Issue by Saereth** [InfinityRaider/AgriCraft#530]
Resourceful crops seeds when grown on Agricraft Cropsticks drop the final product not the shards. 

When you typically grow a Resourceful Crops seed, a wither wheat seed for instance, you'll get 1 wither wheat shard when you  harvest, you then craft 8 of those shards into a wither skull. So by giving the final product immediately instead of the shards its effectively multiplying the outputx8. 

This raises all kinds of balance concerns, 4 wither skulls per harvest on a 10/10/10 for instance etc.

currently using 
Forge 1558
Agricraft: 1.7.10-1.4.6-pre2
Resourceful Crops: 1.7.10-1.0.0-26

**Comment by InfinityRaider** [comment]
I'll have a look at it

**Comment by TehNut** [comment]
In the [`getFruits()`](https://github.com/InfinityRaider/AgriCraft/blob/1.7.10/src/main/java/com/InfinityRaider/AgriCraft/compatibility/resourcefulcrops/ResourcefulCropsAPI.java#L57) call, the return should be `new ItemStack(ResourcefulAPI.shard, 1, meta)`

**Comment by InfinityRaider** [comment]
Okay, thanks.
