### ISSUE TITLE
Witchery integration

### ISSUE THREAD

**Issue by SigurdCole** [InfinityRaider/AgriCraft#531]
First off, thanks a ton! Your Thaumcraft and Ars Magica 2 integration have made my day! And the clipping feature is just neat! Your mod is awesome!

I was wondering (hoping) that there would be support in the future for Witchery crops, since it seems that others are being included, but I didn't see it in the roadmap anywhere. Is that planned, or could that happen?

Thank you!

**Comment by InfinityRaider** [comment]
Witchery crops are supported

**Comment by SigurdCole** [comment]
Ah, I see now. I didn't see seed recipes, so I assumed that they weren't implemented.

Are there plans to take it any further? For example, water artichokes should probably go in water pads instead of farmland.

**Comment by InfinityRaider** [comment]
They used to, but a little refactor bugged that up, this will be fixed: see #532
