### ISSUE TITLE
[1.4.6-hotfix] Water Artichoke default soil no longer waterpads

### ISSUE THREAD

**Issue by thephoenixlodge** [InfinityRaider/AgriCraft#532]
At least as far as Witchery's Water artichoke is concerned, WaterPads are still broken, though this was supposed to have been fixed in the full release of 1.4.6. They are defaulting to regular soil requirements, and if I use MT to set the soil manually it shows up in NEI, but I cannot plant them on it.
EDIT: I'm a derp, MT works, I stupidly forgot to actually put down cropsticks -.-
Still weird that I have to manually set it to grow on water pads now though.

**Comment by InfinityRaider** [comment]
Ya, I forgot about this, I'll fix it
