### ISSUE TITLE
[1.4.6-hotfix] Snowbell seeds no longer producing snowballs

### ISSUE THREAD

**Issue by thephoenixlodge** [InfinityRaider/AgriCraft#533]
As per the title, snowbells are now only producing the icy needles

**Comment by thephoenixlodge** [comment]
Wondering if the bit about agricraft in this post might be relevant: http://forum.feed-the-beast.com/threads/1-7-10-regrowth-a-wip-hqm-pack-now-listed.57184/page-745#post-1549086

**Comment by InfinityRaider** [comment]
This is fixed with #532's fix

**Comment by InfinityRaider** [comment]
And that divide by zero was indeed what was causing it, I had changed the way CropPlants are registred, but for the Witchery plants the tier was not set correctly so it defaulted to java's 0 and hence they were not registered with the correct Objects. After the normal registering was done, the Witchery seeds were picked up by the ore dictionary registering system and added in with default methods, this is why the soil was just farmland, mandrakes didn't spawn and snowbells didn't drop snowballs.
