### ISSUE TITLE
[Crash] Reiterative crash using GUI from Computer Seed Analyzer

### ISSUE THREAD

**Issue by frenchiveruti** [InfinityRaider/AgriCraft#534]
Here's the logs of the crash, I hope you can fix it, the way to reproduce it (Easy) is to click like crazy on the GUI of the Computer Seed Analyzer Methods buttons.

**Logs:**
[crash-2016-01-10_21.56.34-client.txt](https://github.com/InfinityRaider/AgriCraft/files/88113/crash-2016-01-10_21.56.34-client.txt)

[crash-2016-01-12_19.48.20-client.txt](https://github.com/InfinityRaider/AgriCraft/files/88114/crash-2016-01-12_19.48.20-client.txt)

**Comment by frenchiveruti** [comment]
Just to expand on the issue, only by clicking on the "isAnalyzed" button, the crash happends.

**Comment by InfinityRaider** [comment]
Fixed, thanks for reporting.

**Comment by frenchiveruti** [comment]
:+1:

**Comment by InfinityRaider** [comment]
https://github.com/InfinityRaider/AgriCraft/commit/f52ba22d37a9264119c1c295bd59df9ed68557d5

**Comment by InfinityRaider** [comment]
(Forgot to tag this issue)
