### ISSUE TITLE
Problem when logging into my server

### ISSUE THREAD

**Issue by AvonteOquendo** [InfinityRaider/AgriCraft#537]
Whenever trying to log into the server my server just crashes and gets this error

Server thread/ERROR [FML]: 2: ASM: com.InfinityRaider.AgriCraft.handler.PlayerInteractEventHandler@5d12260f waterPadCreation(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V 14.01 20:04:22 [Server] Server thread/ERROR [FML]: 1: ASM: com.InfinityRaider.AgriCraft.handler.PlayerInteractEventHandler@5d12260f vanillaSeedPlanting(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V 14.01 20:04:22 [Server] Server thread/ERROR [FML]: 0: HIGHEST 14.01 20:04:22 [Server] Server thread/ERROR [FML]: Index: 16 Listeners:

If anything prior to the craft I think my friend planted a cotton seed.
The server is FTB Infinity Evolved version 2.3.3.

**Comment by InfinityRaider** [comment]
I need the crash log from the server

**Comment by AvonteOquendo** [comment]
[crash-2016-01-14_20.04.22-server.txt](https://github.com/InfinityRaider/AgriCraft/files/91247/crash-2016-01-14_20.04.22-server.txt)

**Comment by AvonteOquendo** [comment]
Any idea what's wrong with it?

**Comment by AvonteOquendo** [comment]
[crash-2016-01-14_21.39.35-server.txt](https://github.com/InfinityRaider/AgriCraft/files/91294/crash-2016-01-14_21.39.35-server.txt)

Here's a more recent one, Idk if anything changed

**Comment by InfinityRaider** [comment]
Yes, report this to FTB Utilities, this has nothign to do with Agricraft.
