### ISSUE TITLE
Fix witchery seeds issues?

### ISSUE THREAD

**Issue by ProFFesor117** [InfinityRaider/AgriCraft#538]
When you add a fix([#532] (https://github.com/InfinityRaider/AgriCraft/commit/7d02426343a2fa2a8ed415036ba51bd219418d8a)) to a modification?
Sorry for my english. And sorry.)))

**Comment by InfinityRaider** [comment]
What do you mean?

**Comment by ProFFesor117** [comment]
This fix is not in the latest release.

**Comment by InfinityRaider** [comment]
No, because this fix was done after the latest release, it will be in the next release though.
