### ISSUE TITLE
Seed Duplication bug with Seed Analyzer

### ISSUE THREAD

**Issue by thephoenixlodge** [InfinityRaider/AgriCraft#54]
Shift-clicking a seed to remove it from the analyzer while it is being processed will result in twice as many seeds being returned to the players inventory. Caps out at returning a stack. Occurs specifically with either a shift-left click or shift-right click. Occurs independent of presence of journal in the analyzer.

**Comment by InfinityRaider** [comment]
O.o

**Comment by InfinityRaider** [comment]
Narrowed it down: only while analyzing and there is no stack the seed can stack with in the inventory.
