### ISSUE TITLE
Agricraft crop clipping bug

### ISSUE THREAD

**Issue by RyanmFisher** [InfinityRaider/AgriCraft#541]
I know this is a small bug but if you click a seed on a cross crop it makes it into a single crop with a seed and gives a crop stick back if you use clippings it won't work at all

**Comment by InfinityRaider** [comment]
Can you elaborate, because I'm afraid I don't catch the point you're trying to make.

**Comment by RyanmFisher** [comment]
Basically if you click on a cross crop with a clipping it won't work you can do it with seeds but not clippings  it will break the cross crop into a single crop only if you use a seed I know this is just a overseen thing in the code
