### ISSUE TITLE
[Request] Add support to Buildcraft blueprints

### ISSUE THREAD

**Issue by frenchiveruti** [InfinityRaider/AgriCraft#542]
So, it would be nice if I could copy the crops and the channels and sprinklers in a blueprint for fast building my farms on my games.  
Thanks

**Comment by InfinityRaider** [comment]
You mean a BuildCraft bluepring?

**Comment by frenchiveruti** [comment]
Oh, I'm sorry, I didn't edit the title as I intended to.  But yes, I mean Buildcraft Blueprints, the architect table doesn't recognize AgrICraft stuff.

**Comment by frenchiveruti** [comment]
Is it possible to do?

**Comment by InfinityRaider** [comment]
Dunno, I'll have to take a look at the BC api

**Comment by frenchiveruti** [comment]
Ok, if it helps, @Mineshopper from carpenter blocks did something similar, and it's code it's on GitHub.  
I hope you can make it work!

**Comment by InfinityRaider** [comment]
I'm going to delay this until 1.8 because I want to bring this update asap (it has been postponed long enough now).
I had a look at the BC schematic API and I don't think I can implement this in a day, it will require some trial and error.

**Comment by frenchiveruti** [comment]
Ok! Thanks for the update on the issue.


Enviado desde Android






On Mon, Feb 22, 2016 at 3:36 AM -0800, "InfinityRaider" <notifications@github.com> wrote:





I'm going to delay this until 1.8 because I want to bring this update asap (it has been postponed long enough now).
I had a look at the BC schematic API and I don't think I can implement this in a day, it will require some trial and error.

---

**Comment by Mineshopper** [comment]
If it helps, the way it was done was specifying block drops in Block.getDrops() method in 1.7.  But I recall that there were a few different ways BC could identify block parts.  The difficulty was getting block parts to drop only under certain situations in Carpenter's Blocks.

**Comment by InfinityRaider** [comment]
I think the problem mainly lies in the setting of the correct material.

**Comment by frenchiveruti** [comment]
Any news regarding this?
