### ISSUE TITLE
Illegible Unicode Text in Agricultural Journal and Computer Controlled Seed Analyzer

### ISSUE THREAD

**Issue by oldjunyi** [InfinityRaider/AgriCraft#543]
If a player is playing the Minecraft in Unicode Font mode, with screen size less than 960 pixels in height (for example, screen resolution = 1600 x 900), all text with small font size will be illegible (Small font size -> text with less than 1.0 OpenGL scale ratio). Changing the GUI mode from "auto" to "large" won't fix it.

![2016-02-01_19 11 41](https://cloud.githubusercontent.com/assets/641817/12716223/d0278f40-c919-11e5-9563-8e86ba3f41a4.png)
![2016-02-01_19 28 38](https://cloud.githubusercontent.com/assets/641817/12716260/06d2f854-c91a-11e5-91c9-f5629588abbb.png)

As the author of [Unicode Font Fixer][1] mod, I suggest the text scale ratio in any place should not be less than 1.0.

In addition, please do not use "String[] words = text.split(" ")" to separate words. The space character (\32) is NEVER used in Asian language (maybe also in many other languages). Please use FontRenderer.listFormattedStringToWidth() instead. Otherwise it will bring some trouble to translation work.

Thanks!

[1]: http://minecraft.curseforge.com/projects/unicode-font-fixer

**Comment by InfinityRaider** [comment]
I can do FontRenderer.listFormattedStringToWidth(), didn't know it had those methods, also how do I properly scale down text?

**Comment by oldjunyi** [comment]
It is hard to scale down text, maybe you can try some anti-aliasing rendering method. I know [AcademyCraft][1] uses this technique, but the text in its GUI still looks a bit strange.
So I think the best way to solve this problem is set the scale ratio to 1.0.
[1]: http://minecraft.curseforge.com/projects/academycraft?gameCategorySlug=mc-mods&projectID=236188
