### ISSUE TITLE
Irrigation system suspected in serverside crash

### ISSUE THREAD

**Issue by blaklafter** [InfinityRaider/AgriCraft#544]
I've been having issues on my server when players are creating agricraft irrigation systems.  Let me say that their configurations are probably not set up in the manner intended.  Large water tanks near and touching each other and also systems of alternating tank block and channel.

I've seen client side crashes while trying to remove some of the channels and tanks.  But last night I started getting server-side crashes as well.

I am running FTB Infinity, expert mode version 2.3.5.  
AgriCraft-1.7.10-1.4.6-hotfix.jar

I was unable to log in without crashing the server, and could only do so after restoring the region data in the affected chunk.  After doing this, I could log in and dismantle the irrigation system.  So far - no more crashes.  Here is the stacktrace:

`---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/1/16 12:36 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at com.InfinityRaider.AgriCraft.tileentity.irrigation.TileEntityTank.set
FluidLevel(TileEntityTank.java:186)
        at com.InfinityRaider.AgriCraft.tileentity.irrigation.TileEntityTank.fun
c_145845_h(TileEntityTank.java:70)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at com.InfinityRaider.AgriCraft.tileentity.irrigation.TileEntityTank.setFluidLevel(TileEntityTank.java:186)
        at com.InfinityRaider.AgriCraft.tileentity.irrigation.TileEntityTank.func_145845_h(TileEntityTank.java:70)

-- Block entity being ticked --
Details:
        Name: AgriCraft:TileEntity_waterTank // com.InfinityRaider.AgriCraft.tileentity.irrigation.TileEntityTank
        Block type: ID #232 (tile.agricraft:waterTank // com.InfinityRaider.AgriCraft.blocks.BlockWaterTank)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-376,36,1247), Chunk: (at 8,2,15 in -24,77; contains blocks -384,0,1232 to -369,255,1247), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
        Actual block type: ID #232 (tile.agricraft:waterTank // com.InfinityRaider.AgriCraft.blocks.BlockWaterTank)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
        Level name: peewee
        All players: 1 total; [EntityPlayerMP['AhavatOlam'/720, l='peewee', x=-358.32, y=46.00, z=1229.29]]
        Chunk stats: ServerChunkCache: 521 Drop: 0
        Level seed: -1402199929580839342
        Level generator: ID 00 - default, ver 1. Features enabled: false
        Level generator options:
        Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Level time: 0 game time, 0 day time
        Level dimension: 0
        Level storage version: 0x00000 - Unknown?
        Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 3.13.0-32-generic
        Java Version: 1.8.0_25, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 775694048 bytes (739 MB) / 2726576128 bytes (2600 MB) up to 8520204288 bytes (8125 MB)
        JVM Flags: 4 total; -Xms2048m -Xmx8192m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 414325, allocated: 1, tallocated: 93167
        FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 174 mods loaded, 174 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHIJAAAA       mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
        UCHIJAAAA       FML{7.10.99.99} [Forge Mod Loader] (FTBServer-1.7.10-1558.jar)
        UCHIJAAAA       Forge{10.13.4.1558} [Minecraft Forge] (FTBServer-1.7.10-1558.jar)
        UCHIJAAAA       appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar)
        UCHIJAAAA       CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar)
        UCHIJAAAA       NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar)
        UCHIJAAAA       ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar)
        UCHIJAAAA       OpenModsCore{0.9} [OpenModsCore] (minecraft.jar)
        UCHIJAAAA       <CoFH ASM>{000} [CoFH ASM] (minecraft.jar)
`

**Comment by InfinityRaider** [comment]
This should be fixed in the next version, but I'll leave it open for now.
Thanks for reporting.

**Comment by InfinityRaider** [comment]
New build is up on CurseForge, feel free to reopen or create a new ticket if this persists.
