### ISSUE TITLE
Hydraulicraft compat

### ISSUE THREAD

**Issue by InfinityRaider** [InfinityRaider/AgriCraft#545]
Add harvesting support for Hydraulicraft:
https://github.com/K-4U/Hydraulicraft/blob/1.8.9/java/k4unl/minecraft/Hydraulicraft/api/IHarvesterTrolley.java

**Comment by hron84** [comment]
For 1.7.10 use [this](https://github.com/K-4U/Hydraulicraft/blob/1.7.10/java/k4unl/minecraft/Hydraulicraft/api/IHarvesterTrolley.java) class instead of 1.8.9 one.
