### ISSUE TITLE
Irrigation Channel Exhibits Deleterious Directionality

### ISSUE THREAD

**Issue by esotericist** [InfinityRaider/AgriCraft#546]
I was trying to build a system that worked on multiple tiers, so I decided to try using taller water tanks to receive water from larger tanks on the higher Y level. To my surprise, this didn't work the way I expected.

https://dl.dropboxusercontent.com/u/37472066/mc%20bits/2016-02-01_15.42.44.png

The tank on the higher level, when brought over the minimum threshold for sending water into the channel, would simply delete the water rather than put it into the channel (and water would never reach the lower tank).

Further testing with two tanks on the same level connected with a single channel suggested one tank could successfully send water to the other, but never the reverse. There is no visible indication of the directionality of the channel, nor any obvious way of changing it (if possible).

**Comment by InfinityRaider** [comment]
There is no directionality, if the water level is lower in one of the neighbouring channels/tanks it'll flow to there. That setup should work though, I'll do some testing myself.

**Comment by InfinityRaider** [comment]
Also it might look like it deletes it, but if it's small amounts of water, it will have transferred in the server thread, but it won't be synced to the client yet. It only syncs when a certain treshold of water is reached (to avoid sending too many update packets).

**Comment by InfinityRaider** [comment]
This is probably due to the same cause as #566, two tanks with one channel, first tank deposits water in the channel, but channel still uses 0 when it tries to deposit in the receiving tank.
Continue conversation in the other issue, even though this was first, the other one is documented better.
