### ISSUE TITLE
request : balance agricraft ;)

### ISSUE THREAD

**Issue by choum33** [InfinityRaider/AgriCraft#548]
Hello,

Agricraft is overpowered. For me the main thing is that plants drop too much goods. An idea for exemple would be to drop 1 tiny pile of redstone dust rather than 1 redstone dust, or even less, the same for other ressources exept wheat maybe. Or get fruits that must be processed like combs to get a small ressource part. 

My best regards

**Comment by InfinityRaider** [comment]
Maximum stat cap can be set in the config and fruit drops from agricraft crops can be changed with MineTweaker.
