### ISSUE TITLE
[Improvement] Accept more airy blocks

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#549]
Crops do not grow if there's a TiCon torch right above them. Please accept more airy blocks above crops.

Modpack: FTB Infinity (but I observed it in more packs)

**Comment by InfinityRaider** [comment]
There's not really a good way that I know off to check if a block is considered "airy", I'm checking for Material.air, so if the block does not use that material it is not considered "airy". So I suggest putting your torches one block higher.

**Comment by hron84** [comment]
If I remember correctly, there's a method isAir or similar, that would help. It would be important as other mods also add some invisible air-like blocks like Railcraft.

**Comment by InfinityRaider** [comment]
I use that method, and that method does as I described before. RailCraft invisible blocks have material air, so they are no problem.
