### ISSUE TITLE
Destroying multiblock water tank containing anything other than even bucket's worth crashes server

### ISSUE THREAD

**Issue by plazia** [InfinityRaider/AgriCraft#551]
I was messing about with various water tanks to see if their surface area increased the water collection amount during rainfall. Turns out I was right. I then tried to destroy them and upon destruction of the first block of the multiblock my server would crash.

I repeated this several times with the other tanks that had collected rainwater.

I then tried with a 4x4 water tank and filled it with just 1 bucket. It worked fine. I could destroy it. So perhaps it's something to do with the water level.

Here is a crash log

http://pastebin.com/1d1jcHJc

**Comment by RlonRyan** [comment]
Looks like might be same issue as #544...

**Comment by InfinityRaider** [comment]
It is.
