### ISSUE TITLE
The Journal

### ISSUE THREAD

**Issue by sylent-flame** [InfinityRaider/AgriCraft#554]
I'm having an issue with reading my Agricultural Journal.

The biggest confusion is that on my desktop, np. Works fine. My laptop... 4 out of every 5 times when I start to look at the recipies, the game crashes.

I do have all the same settings (in game / curse / computer (as best a possible)).

Been dealing with this for 3 weeks or so and have been trying numerous muliple options, but nothing.

Why?

**Comment by InfinityRaider** [comment]
Crash log would be nice to have

**Comment by sylent-flame** [comment]
[AgriCrash.txt](https://github.com/InfinityRaider/AgriCraft/files/120573/AgriCrash.txt)

Thanks for such a quick response

**Comment by RlonRyan** [comment]
Thanks for the log. Next time please use gist.

The provided log says that your crash was not AgriCraft's fault...

**Comment by InfinityRaider** [comment]
Report it to MFR's issue tracker.
