### ISSUE TITLE
Server freezing while listing mutations

### ISSUE THREAD

**Issue by UberAffe** [InfinityRaider/AgriCraft#559]
I don't have a proper log to post because it doesn't crash but the section of the console log where it is freezing is at the bottom.

This issue is happening after updating an existing world from infinity evolved 2.2.2 to 2.3.5

> 07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedBotaniaLightBlue:0 = AgriCraft:seedBotaniaBlue:0 + AgriCraft:seedBotaniaWhite:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedBotaniaCyan:0 = AgriCraft:seedBotaniaGreen:0 + AgriCraft:seedBotaniaBlue:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedBotaniaLime:0 = AgriCraft:seedBotaniaWhite:0 + AgriCraft:seedBotaniaGreen:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedBotaniaPink:0 = AgriCraft:seedBotaniaPurple:0 + AgriCraft:seedBotaniaWhite:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedBotaniaMagenta:0 = AgriCraft:seedBotaniaRed:0 + AgriCraft:seedBotaniaBlue:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedBotaniaGreen:0 = AgriCraft:seedBotaniaBlue:0 + AgriCraft:seedBotaniaYellow:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedBotaniaPurple:0 = AgriCraft:seedBotaniaMagenta:0 + AgriCraft:seedBotaniaBlue:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedBotaniaOrange:0 = AgriCraft:seedBotaniaYellow:0 + AgriCraft:seedBotaniaRed:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedBotaniaBlue:0 = AgriCraft:seedOrchid:0 + AgriCraft:seedAllium:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedBotaniaYellow:0 = AgriCraft:seedDandelion:0 + AgriCraft:seedTulipOrange:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedBotaniaRed:0 = AgriCraft:seedPoppy:0 + AgriCraft:seedTulipRed:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedShroomBrown:0 = minecraft:nether_wart:0 + AgriCraft:seedPotato:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedShroomRed:0 = minecraft:nether_wart:0 + AgriCraft:seedPoppy:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedDaisy:0 = AgriCraft:seedDandelion:0 + AgriCraft:seedOrchid:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedTulipPink:0 = AgriCraft:seedAllium:0 + AgriCraft:seedDandelion:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedTulipWhite:0 = AgriCraft:seedDaisy:0 + AgriCraft:seedDandelion:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedTulipOrange:0 = AgriCraft:seedDaisy:0 + AgriCraft:seedOrchid:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedTulipRed:0 = AgriCraft:seedPoppy:0 + AgriCraft:seedAllium:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedAllium:0 = AgriCraft:seedPoppy:0 + AgriCraft:seedOrchid:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedOrchid:0 = AgriCraft:seedPoppy:0 + AgriCraft:seedDandelion:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedDandelion:0 = AgriCraft:seedSugarcane:0 + minecraft:melon_seeds:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedPoppy:0 = AgriCraft:seedSugarcane:0 + minecraft:pumpkin_seeds:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - minecraft:melon_seeds:0 = AgriCraft:seedCarrot:0 + minecraft:pumpkin_seeds:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - minecraft:pumpkin_seeds:0 = AgriCraft:seedPotato:0 + AgriCraft:seedCarrot:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedCactus:0 = AgriCraft:seedSugarcane:0 + AgriCraft:seedPoppy:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]:  - AgriCraft:seedSugarcane:0 = minecraft:wheat_seeds:0 + AgriCraft:seedCarrot:0
07.02 20:21:47 [Server] Server thread/INFO [AgriCraft]: Registered Mutations:
07.02 20:21:47 [Server] Server thread/INFO [FML]: Forge Mod Loader has successfully loaded 178 mods

These are the mutations I removed from mutations.txt because they said invalid stack result.

>AgriCraft:seedPlombean=AgriCraft:seedFerranium+AgriCraft:seedPotato
AgriCraft:seedPetinia=AgriCraft:seedLapender+AgriCraft:seedDaisy
AgriCraft:seedCuprosia=AgriCraft:seedRedstodendron+AgriCraft:seedTulipRed
AgriCraft:seedQuartzanthemum=AgriCraft:seedNitorWart+AgriCraft:seedLapender
AgriCraft:seedNitorWart=minecraft:nether_wart+AgriCraft:seedTulipOrange
AgriCraft:seedEmeryllis=AgriCraft:seedFerranium+AgriCraft:seedRedstodendron
AgriCraft:seedDiamahlia=AgriCraft:seedAurigold+AgriCraft:seedLapender
AgriCraft:seedAurigold=AgriCraft:seedRedstodendron+AgriCraft:seedTulipOrange
AgriCraft:seedFerranium=AgriCraft:seedLapender+AgriCraft:seedTulipWhite
AgriCraft:seedLapender=AgriCraft:seedTulipPink+AgriCraft:seedOrchid
AgriCraft:seedRedstodendron=AgriCraft:seedTulipRed+AgriCraft:seedDaisy
AgriCraft:seedPlatiolus=AgriCraft:seedDiamahlia+AgriCraft:seedFerranium)
AgriCraft:seedNiccissus=AgriCraft:seedAurigold+AgriCraft:seedDandelion)
AgriCraft:seedJaslumine=AgriCraft:seedFerranium+minecraft:wheat_seeds)
AgriCraft:seedSilverweed=AgriCraft:seedAurigold+AgriCraft:seedAllium)

**Comment by RlonRyan** [comment]
Unfortunately, without a stack trace (that is an error) there is no way to pinpoint if this is actually an AgriCraft error...

Is there an error log pointing to AgriCraft?

**Comment by InfinityRaider** [comment]
What version of agricraft is this? Also the fact that they have an invalid result means that resource crops have been disabled in the config, but where enabled before.

**Comment by UberAffe** [comment]
version 1.4.5

But I think the actual problem was a conflict between ae2 being in rv3 and enderio being built against rv2. When I downgraded ae2 the issue stopped. It's just odd that it didn't crash. And since it never crashed all I had was the console log which didn't list an error on any of the mods loaded, it just stopped when it got to agricraft mutations.

**Comment by InfinityRaider** [comment]
Okay, closing this then.
