### ISSUE TITLE
Directional Infinite Water Setup

### ISSUE THREAD

**Issue by Vritra22189** [InfinityRaider/AgriCraft#566]
placing a water tank-channel-another water tank in chain can cause water-generating property.

in the picture, i have a one-high tank flowing to a two-high tank, with around 3 buckets of water in the first, it starts generating water in the second.
and water generation also only appear in west-flowing or north-flowing water

with a channel extracting water from the lower block, it will be an infinite water setup
![2016-02-15_11 33 33](https://cloud.githubusercontent.com/assets/9210589/13039362/e1174286-d3d8-11e5-9ebe-5a38ff23fb25.png)
![2016-02-15_11 33 52](https://cloud.githubusercontent.com/assets/9210589/13039363/e11996da-d3d8-11e5-940c-534d467762d4.png)

**Comment by RlonRyan** [comment]
Probably a rounding issue, an issue with any system that involves floats...

**Comment by InfinityRaider** [comment]
Was my first thought too, but will have to do some testing and debugging to be sure.

**Comment by RlonRyan** [comment]
Sounds like a good plan.
I like how well @Vritra22189 documented the issue.

**Comment by Vritra22189** [comment]
i have just looked into the source of TileEntityChannel, 
and i think it might have found the problem

firstly, the directional issue is probably about the update order (north > south > west > east)

secondly, in the tick function, 
the FluidLevel is not updated after each channel-tank transfer
such that each calculation uses the initial FluidLevel of the tick, even after it is emptied into some tank 
`int V_tot = tank.getFluidLevel() + this.lvl;`
then the channel FluidLevel is updated with the LAST calculation only.

thus in every ticks:
-the target tank receive water from the channel
-the channel will regenerate water (update-order and non-updating FluidLevel)
-the source tank will have no loss (because of equilibrium)

here is an excel showing some iteration, 
if you reverse the update order  (about which intermediate value is used as final)
the water is disappeared instead, probably is also the cause of issue #546 
[iteration.xlsx](https://github.com/InfinityRaider/AgriCraft/files/132051/iteration.xlsx)

**Comment by InfinityRaider** [comment]
Impressive, nice work.
Indeed good find on https://github.com/InfinityRaider/AgriCraft/blob/1.7.10/src/main/java/com/InfinityRaider/AgriCraft/tileentity/irrigation/TileEntityChannel.java#L214 it should indeed be
`int V_tot = tank;getFluidLevel() + updatedLevel;`
I'll change that.
But there isn't much I can do about update order though.

**Comment by esotericist** [comment]
I'm glad this got sorted. :) Thanks!

**Comment by InfinityRaider** [comment]
It *should* be fixed, but I'm leaving this open in case it isn't.

**Comment by InfinityRaider** [comment]
New build is up on CurseForge, feel free to reopen or create a new ticket if this persists.
