### ISSUE TITLE
Ability to revert water pad back to farmland

### ISSUE THREAD

**Issue by blay09** [InfinityRaider/AgriCraft#574]
It quite frequently happens that you accidentally create water pads and breaking it and placing the dirt again is a struggle, especially in a skyblock map where the dirt tends to fall into the void.

Maybe just allow turning the water pad back to farmland by right clicking it with a hoe once more?

**Comment by InfinityRaider** [comment]
Sounds reasonable.

**Comment by InfinityRaider** [comment]
Also add a config option to have it only create water pads while sneaking.
