### ISSUE TITLE
Crash with Thaumaturge's Brazier

### ISSUE THREAD

**Issue by Danymaddox** [InfinityRaider/AgriCraft#575]
Hi! My game crash when I try to place the Thaumaturge's Brazier, here's the crash log:

http://pastebin.com/4pRLdTjq

Test with:
 -Forge 11.15.1.1755
 -Thaumcraft 5.1.6
 -DummyCore 2.2.189.0
 -Thaumic Bases 2.1.1.189.23

**Comment by InfinityRaider** [comment]
agricraft is mentioned nowhere in the crash logs, also this is 1.8??? Agricraft isn't released for 1.8

**Comment by Danymaddox** [comment]
I dont know why Agricraft is mentioned in the crash log, im my minecraft folder I only have Forge, Thaumcraft, DummyCore and Thaumic Bases...

**Comment by RlonRyan** [comment]
AgriCraft is not mentioned in the log. You are using MineCraft 1.8.9, for which there is no AgriCraft version yet.

This is a Thaumcraft problem.
