### ISSUE TITLE
MFR fertile soil incompatibility

### ISSUE THREAD

**Issue by Staegrin** [InfinityRaider/AgriCraft#580]
I've used the whitelist to add minefactoryreloaded's fertile soil to the allowed soils. 
After upgrading my version of mfr to MineFactoryReloaded-[1.7.10]2.8.1-174 the crop sticks can no longer be placed on the block even though the whitelist and NEI say it's a valid soil block. 

I've also tried using minetweaker to add the fertile soil to the valid soil types.

import mods.agricraft.growing.FertileSoils;

FertileSoils.add(<MineFactoryReloaded:farmland>);

**Comment by InfinityRaider** [comment]
agricraft version?

**Comment by Staegrin** [comment]
AgriCraft-1.7.10-1.4.6-hotfix

sorry should have posted that with the first post.

**Comment by InfinityRaider** [comment]
And you could place them on that soil in the previous MFR version with the same version of AgriCraft?

**Comment by Staegrin** [comment]
Yes, on jan 25 of 2016 I updated to the newest version of mfr. Now is the first time since the update I want to place crop sticks on the fertile soil and they can't be placed even though it's on the whitelist and NEI says it's allowed.

**Comment by InfinityRaider** [comment]
Check metadata, what is the metadata of the block in the world, and what is the metadata in the config.

**Comment by Staegrin** [comment]
Apparently the metadata is :3 while the item is :0 Must have been changed in the latest version. 
Went to the whitelist and added :3 behind the name and now the crop sticks can be placed.

Thank you for the quick help.

**Comment by InfinityRaider** [comment]
you're welcome, glad I could be of service.

**Comment by jinks** [comment]
Apparently the MFR soil can somehow "store" fertility. When you apply bonemeal repeatedly to the soil the metadata value changes slowly from 3 up to 15.

Is there a way for Agricraft to ignore the metadata or do I have to add all variants to the whitelist?

**Comment by InfinityRaider** [comment]
If you don't specify metadata, it should ignore it, but the fact that this got reported means it doesnt.

**Comment by jinks** [comment]
Yeah, it doesn't, tested that myself.

You know your code better than I do, but I guess it just assumes :0 somewhere if it isn't specified?

**Comment by InfinityRaider** [comment]
I have a calls BlockWithMeta, which ignores meta if no meta is passed to the constructor, I just need to find where I call it, it's been a while too.
