### ISSUE TITLE
Crash with the new rendering setting

### ISSUE THREAD

**Issue by Neodark7** [InfinityRaider/AgriCraft#581]
http://pastebin.com/9SHQEri1

I crash when connecting on my server if set to B:"Crop rendering setting"=true"

**Comment by InfinityRaider** [comment]
Does the server have it too?

**Comment by Neodark7** [comment]
Yep both on true, i think you know that but it's a client crash :)

**Comment by InfinityRaider** [comment]
Yes, just making sure.

**Comment by InfinityRaider** [comment]
Are you sure this only happens with the setting set to true?

**Comment by Neodark7** [comment]
Yep

**Comment by InfinityRaider** [comment]
I am closing this because I'm no longer doing any work on agricraft for 1.7.
