### ISSUE TITLE
[Bug] OpenBlocks Sprinkler causing plants to grow when they shouldn't.

### ISSUE THREAD

**Issue by mysticdrew** [InfinityRaider/AgriCraft#584]
The Openblocks sprinkler causes ore plants to grow when they should not be able to grow. An example is when you're required to have the ore block under the plant, it says "It cannot grow here" but add a sprinkler and it still grows. 

This is currently AgriCraft-1.7.10-1.5.0 but my guess is it happens with all versions.

**Comment by InfinityRaider** [comment]
I am closing this because I'm no longer doing any work on agricraft for 1.7.
