### ISSUE TITLE
Computer Controlled Seed Analyszer bad return of getSepciemenStats method

### ISSUE THREAD

**Issue by Shotman** [InfinityRaider/AgriCraft#587]
There is a problem in the output of the `getSpeciemenStats`, maybe I am doing something wrong since I am  not really an expert at ComputerCraft but here is my output : 
The Code : 
![ccsaoutput](https://cloud.githubusercontent.com/assets/6579166/13729285/a01f2564-e931-11e5-836b-b46543de96d3.JPG)

The Output : 
![ccsaoutput2](https://cloud.githubusercontent.com/assets/6579166/13729286/a01fa69c-e931-11e5-8974-6bb35b3d4d13.JPG)

**Comment by InfinityRaider** [comment]
I'm not sure how LUA works, but I'm returning an array of size 3 from that method, and I think you maybe have to do a, b, c = seed.getSpecimenStats() to assign a, b and c to growth, gain and strength respectively, then again, I might be wrong.

**Comment by Shotman** [comment]
`a,b,c = seed.getSpeciemenStats()`
with 
`print(a);
print(b);
print(c)`;
works, thanks !

**Comment by InfinityRaider** [comment]
Great! For clarity and readability I'd name them growth, gain and strength instead of a, b and c though ;)
