### ISSUE TITLE
[Bug] Sesame seeds from Pam's Harvestcraft have no crop drop Agricraft 1.5.0 for minecraft 1.7.10

### ISSUE THREAD

**Issue by Mathijsvand** [InfinityRaider/AgriCraft#588]
I just wanted to drop this bug report. I can't get any sesame seeds (not sesame seed seeds) from Pam's Harvestcraft from the Sesame Seed plants. When I right click the plant, it reverts to the earlier growth state, but no sesame seeds are dropped.

**Comment by InfinityRaider** [comment]
Bug is known if you search the tracker you'd see this has been reported multiple times.
This has to be fixed from Pam's side, the seeds and the drops are not consistently regsitered to the ore dictionary.
