### ISSUE TITLE
when i try to add agricraft it happen to crash "already decorating"

### ISSUE THREAD

**Issue by lightning02** [InfinityRaider/AgriCraft#589]
http://pastebin.com/09kkKAyr

**Comment by InfinityRaider** [comment]
Agricraft doesn't do any biome decorating.

**Comment by lightning02** [comment]
hello, I'm sorry to bother, I've tryed to add NEID 1.4.2 and it happen to crash with a mod called Monoblocks, in the crash it says the block com.monoblocks.blocks.SteelOre@6c477475 is not registered. I've tryed to update the mod and delete its config file, but the crash seems still occur. What does it mean with "the block is not registered"? is a mistake the author made? is something solvable in any way, even manually fixing it? 

The first crash happen to the server side, but on the client side the crash is almost the same with the only difference that the modpack starts normally then when you try to create a world it crash with that report

http://pastebin.com/cwSF0H31

**Comment by InfinityRaider** [comment]
It's not tessellation,

first does it happen every time you make a new world? Second if you remove agricraft then it doesn't happen anymore?
If this is the case, there must be a mod that adds world gen if agricraft is enabled.
Also you could try to disable the agricraft greenhouses, but I don't think that will fix it.

**Comment by lightning02** [comment]
I made some test, if I disable the greenhouses in the config file the crash still occur; if I remove the world tryng to recreating it, the crash still occur, even with the greenhouses disabled in the config file. If I don't add agricraft the crash doesn't occur :l I'm not sayng is your mod fault, I really would like to figure out which mod is that create problems to yours, I would even contact other author if I would be aware of which one could be the responsable
