### ISSUE TITLE
[1.8.9] version 2.0.0a crash

### ISSUE THREAD

**Issue by ashly138** [InfinityRaider/AgriCraft#591]
http://paste.ee/p/H5HL5

**Comment by RlonRyan** [comment]
On it! Thanks!

**Comment by RlonRyan** [comment]
Alright! Can you please try the latest release again, I think I found the problem.

**Comment by ashly138** [comment]
Its starts but now i got another crash. I whase in creative scrolling in this mods tab whene it crashed.

http://paste.ee/p/Ipg9n

**Comment by RlonRyan** [comment]
Well the first crash was me being stupid, so hopefully I can get the mod working for you quickly here...

**Comment by RlonRyan** [comment]
Wait... Are you using Minecraft 1.8.8?

**Comment by ashly138** [comment]
no using 1.8.9 just didnt change folder name lols

**Comment by RlonRyan** [comment]
Ah... I just wanted to make sure, thank you.

**Comment by RlonRyan** [comment]
So the crash occurs in the AgriCraft Mod tab correct?

**Comment by ashly138** [comment]
yes

**Comment by RlonRyan** [comment]
I see it now thank you!

**Comment by RlonRyan** [comment]
Yup, the first official 1.8.9 rendering hack bug. Yay!

**Comment by RlonRyan** [comment]
Ok, I managed to stop the crashing... This will require additional work to correct the functionality of the affected components of the mod.

**Comment by RlonRyan** [comment]
Ok. I think that should do it!

**Comment by RlonRyan** [comment]
I just need conformation that it works for you when the latest alpha for AgriCraft gets posted, and this issue can be closed!

**Comment by RlonRyan** [comment]
Alright the alpha is up.

**Comment by ashly138** [comment]
Test it and creative tab no longer crashes me.

Allso had whene hitting grass and got a agricraft seed got a crash but seams.. this new verion allso fix that lols

**Comment by RlonRyan** [comment]
Awesome! Thanks for the quick reply! Let me know if you run into any more issues!
