### ISSUE TITLE
[2.0.0a] 1.8.9 Crash on Load

### ISSUE THREAD

**Issue by Tsukiumy** [InfinityRaider/AgriCraft#592]
i got a crash on the initializing on agricraft, but this is why ima playing this version, to test any mod :3 
so there is the crashlog
http://pastebin.com/9TdDgiLc

**Comment by Sasikaa** [comment]
Not post the my crash report, because of the same problem...

**Comment by RlonRyan** [comment]
This error doesn't even make sense to me... All the arguments for that function are type-checked before assignment, so I have no clue what is happening here...

**Comment by juanmelk** [comment]
I think the bug could be related to Thaumic Infusion- minecraft launched with Agricraft when I removed Thaumic Infusion from my mods folder.

**Comment by Royal-Jelly** [comment]
yeah im pretty sure its on DrunkMafia's end to fix this bug, its been kinda hard to catch him online well for me atleast :L

**Comment by InfinityRaider** [comment]
he's probably adding a method with an identical name and argument types but with a different return type to a vanilla class as a method we to a subclass.

**Comment by Tsukiumy** [comment]
https://github.com/TheDrunkMafia/ThaumicInfusion/issues/74
just posted the aditional info he needed there too, and linking the 2 posts for easy reference

**Comment by Sasikaa** [comment]
Yes, this mod is disabled, and working the Agricraft... But not showing SOME of recipes in the JEI. Crafting works, and adding the Creative mode, but JEI not showing icons, and recipes...
(Seed analyzer, other seeds, material seed crafting recipes.)

**Comment by TheDrunkMafia** [comment]
Fixed in the latest version of TI: http://minecraft.curseforge.com/projects/thaumic-infusion/files/2290725

**Comment by InfinityRaider** [comment]
Cheers!
