### ISSUE TITLE
[2.0.0a]Server Crash on Start

### ISSUE THREAD

**Issue by oitsjustjose** [InfinityRaider/AgriCraft#593]
Sorry for the vague crash-log, it seems like maybe some client-only code is being called on the server? Not a huge deal, we can wait for the awesomeness that is AgriCraft just a little while longer!

[FML Crash Log](http://puu.sh/nVdxp/dd2a4f0047.txt)

**Comment by RlonRyan** [comment]
It looks like I must have missed a @SideOnly annotation somewhere...

It appears that the server side is trying to load rendering code, which is client only...
