### ISSUE TITLE
Clippers Crash Game

### ISSUE THREAD

**Issue by shrael** [InfinityRaider/AgriCraft#597]
w/e I try to use the clippers in game the client crashes upon use. This is for 1.8.9

**Comment by InfinityRaider** [comment]
We can't do anything without a crash log.

**Comment by juanmelk** [comment]
Here you go!
http://paste.ee/p/8G9vj

Had the same crash, happens on world load and started as soon as I used clippers. Something about how clippings are rendered.

**Comment by RlonRyan** [comment]
Yay! Logs! Thanks for replying!

**Comment by shrael** [comment]
sorry hadnt had the chance to play the game and crash it.
