### ISSUE TITLE
I do not know whether Agricraft bug?! (1.8.9!!)

### ISSUE THREAD

**Issue by Sasikaa** [InfinityRaider/AgriCraft#599]
I do not know whether Agricraft bug, or Tinkers' Construct, but simple crashing when running my game one hour.

This is MY crash log:
http://pastebin.com/TQxAf1UW

**Comment by InfinityRaider** [comment]
Report this to Elec (ElecCore dev) or the Mantle devs, nowhere here it shows an agricraft class call in the stacktrace.
