### ISSUE TITLE
Infinity server freezes after agricraft starts loading 

### ISSUE THREAD

**Issue by EnderCorpsAlpha** [InfinityRaider/AgriCraft#600]
Hi, I saw a similar post in here earlier, but it was closed because the person who started it never posted a log, but i'm getting the same error when updating infinity on my server to the most recent, with the updated agricraft that comes with it, the log is below

http://pastebin.com/wgkUKfjN

the log just stops because the server freezes at that point when trying to load the rest of the mutations, if there are any.

**Comment by RlonRyan** [comment]
I don't see anything wrong here... Are you sure that it is due to AgriCraft?

**Comment by InfinityRaider** [comment]
Either way, I'm not going to do anything anymore on 1.7, either roll back to a previous version or contact the other person having this issue to find out what the casue was and how he fixed it.
