### ISSUE TITLE
Compatibility issue with SpongeForge

### ISSUE THREAD

**Issue by Xiaminou** [InfinityRaider/AgriCraft#601]
Agricraft is incompatible with SpongeForge.
(reported on both githubs)

Crash Report: http://pastebin.com/AZxAe9uV

**Comment by RlonRyan** [comment]
Well that's just great...

Anyways, it looks like it's my fault and not Sponge's... Probably.

It looks like I still haven't separated the client side code and the server side code fully enough yet...

**Comment by simon816** [comment]
https://github.com/InfinityRaider/AgriCraft/blob/1.8.9/src/main/java/com/infinityraider/agricraft/blocks/BlockCrop.java#L50
Needs `@SideOnly(Side.CLIENT)`
There may be more cases but this is an example of one that needs fixing

**Comment by RlonRyan** [comment]
Yup... There are a few of those... My fault... Sorry.

**Comment by Eufranio** [comment]
No fix for this?

**Comment by InfinityRaider** [comment]
1.8.9 will not have any more releases. The rendering code is one big hack and should have never been released in the first point.

**Comment by Eufranio** [comment]
D: Fix this guys, please, even if its the last thing that they will do in 1.8.9 :/
I really like this mod and i dont want abandon in 1.8.9 :/

**Comment by Xiaminou** [comment]
Any work done on the 1.9.4 version?

**Comment by InfinityRaider** [comment]
No, there will not be anything coming for 1.8, I have other priorities. Work has been done, and still has to be done on 1.9, however seeing the rate at which mojang is pushing out updates, itll probably be 1.10.
