### ISSUE TITLE
Tessalating Block in World Crash

### ISSUE THREAD

**Issue by ElvenChaos** [InfinityRaider/AgriCraft#602]
I was exploring a test world, and as I was approaching a village (first village I've seen in my pack since I added AgriCraft) I got the following crash:
http://pastebin.com/NB65pPtV
This is with AgriCraft 2.0.0a on 1.8.9
Edit: Tested with 2.0.0a1 as well, still get the same crash.

**Comment by RlonRyan** [comment]
Well it looks like something in one of the crops threw off the rendering code... This may take a bit to fix...

The best I can say now is to turn off AgriCraft worldgen and recreate the world for now... (If that's o.k.)

Also you might want to turn off seed storage.

**Comment by RlonRyan** [comment]
See also the log from #618, http://pastebin.com/7YABZaF5.

**Comment by InfinityRaider** [comment]
I think this is due to the fact that when I created that class I assumed that blocks would be rendered with DefaultVertexFormats.BLOCK, my first guess is that it's rendering with a different VertexFormat and hence too much data is passed to the vertexbuffer when tessellating a vertex.
1.9 Should ahve fixed this though as this has been fully rewritten.

**Comment by RlonRyan** [comment]
That's what I figured about 1.9...

**Comment by claws61821** [comment]
For the sake of clarification, will this fix be back-ported to 1.8.9? --or, now that I see it, is this in 2.0.0a3?

**Comment by claws61821** [comment]
Given the lack of response to the latest post in this thread, I have gone ahead and tested this issue in 2.0.0a3 and verified that it remains symptomatic.

**Comment by InfinityRaider** [comment]
I am not doing any work on 1.8 or 1.7 anymore, so it'll be up to @RlonRyan if the wants to backport it or not.

**Comment by RlonRyan** [comment]
Yup.

**Comment by Cobra1117** [comment]
Is there a work-around for this? I've had to resort to deleting all Agricraft blocks from region files that fail to render correctly because players can't load their bases.
