### ISSUE TITLE
Rendering Block Entity Crash - 1.7.10

### ISSUE THREAD

**Issue by Terpo** [InfinityRaider/AgriCraft#604]
AgriCraft-1.7.10-1.5.0.jar
Forge 1566
http://blog.terpo.org/upload/mc/modlist.txt

---------------------

Today I've got a weird crash for you. We are playing on a server but only the client disconnects.

I built an tank of agricraft (we tried a 7x7x1 (l * w * h)) and started breaking it again. After a few blocks everyone in the area get render crash: 

http://pastebin.com/EPbVfcPM
http://pastebin.com/qq633Axr (another player)

The tanks was build over one chunk border.

**Comment by insuusvenerati** [comment]
Is there an invisible railcraft block somewhere in there? Also, inb4 always render issues.

**Comment by RlonRyan** [comment]
It looks more like a tank went out of bounds into a railcraft block.

**Comment by InfinityRaider** [comment]
My guess ts multiblock issue and thread racing again, always has been with the multiblock code, on the server thread the tank is broken, but in the rendering thread the multiblock data hasn't synced to all tanks yet.

**Comment by Terpo** [comment]
There was no railcraft block nearby. Thats something I can confirm^^.
Any tips how to prevent that crash? Our server is quite small and there is not a big problem to tell it all players.

**Comment by InfinityRaider** [comment]
It's a railcraft hidden blocks, it is created where a player is and goes away after a few seconds, used for the trackign aura.
When breaking a tank, break the most NORTH, EAST, DOWN block last.

**Comment by InfinityRaider** [comment]
But since I am focusing on 1.9, I won't be doing any work on 1.7 anymore, my apologies: https://github.com/InfinityRaider/AgriCraft#minecraft-versions

**Comment by asiekierka** [comment]
This problem is also present on the server, in the same function - see http://pastebin.com/KQHFW7Gs
