### ISSUE TITLE
Rendering shenanigans

### ISSUE THREAD

**Issue by Stabington** [InfinityRaider/AgriCraft#606]
I'm getting some strange lines on the ground if I try running this and Intangible. Not sure which mod is causing this, but disabling either fixes it.
Forge 11.15.1.1808

![2016-03-31_18 22 01](https://cloud.githubusercontent.com/assets/8779331/14182877/b128d554-f76d-11e5-9545-636182fb3d89.png)

**Comment by RlonRyan** [comment]
What mods?

**Comment by RlonRyan** [comment]
Sorry, I was thinking Intangable was a modpack for a second there...

The lines look too precise to be a glitch, but who knows... Are there any AgriCraft blocks within the loaded radius?

**Comment by InfinityRaider** [comment]
I rly want to figure out why that happens, this could make for a neat rendering effect for a potion effect/spell (unrelated). But I'd also like to know why this happens to fix it (related).

**Comment by Stabington** [comment]
This is occurring on a newly generated world.
More pictures \o/
![2016-04-01_20 53 51](https://cloud.githubusercontent.com/assets/8779331/14217032/343a77c0-f84c-11e5-9442-412833153f5c.png)
![2016-04-01_20 54 14](https://cloud.githubusercontent.com/assets/8779331/14217033/343b43c6-f84c-11e5-80c8-8ad669e5d319.png)
![2016-04-01_20 55 13](https://cloud.githubusercontent.com/assets/8779331/14217030/34386282-f84c-11e5-9cde-0376ca12be5e.png)
