### ISSUE TITLE
[BUG?] [1.7.10] Shearing cacti does not yield cactus block

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#609]
I tried to shear a 10/10/10 cactus with vanilla shears and ThermalFoundation bronze shears but none yielded a cactus block, instead just harvested the crop normally (as right click do). Please restore original behavior for getting cactus block by shearing.

AgriCraft 1.5.0

**Comment by VT-14** [comment]
Check your configs, and try with vanilla shears if that option is enabled.

**Comment by hron84** [comment]
Checked configs, vanilla shears also not work.

**Comment by InfinityRaider** [comment]
It's a bug as seen in #609, however I'm focusing on 1.9 and not doing any more work on 1.7 (https://github.com/InfinityRaider/AgriCraft#minecraft-versions)

**Comment by hron84** [comment]
Ohh, I see. I think this was a bit early move, but I accept your decision.
