### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lightning02** [InfinityRaider/AgriCraft#613]
https://github.com/CoFH/Feedback/issues/1128#issuecomment-205052929

**Comment by RlonRyan** [comment]
Please provide the full issue explanation here and not just a link to a closed issue in another repository.

Also please provide a gist or pastebin version of the log.

**Comment by InfinityRaider** [comment]
No idea why this is on our side.

**Comment by lightning02** [comment]
I'm sorry have you right, i don't want to create any kind of problem.
Anyway here is the log http://pastebin.com/ZFSRSKkC

**Comment by lightning02** [comment]
Why you wontfix?

**Comment by RlonRyan** [comment]
It looks like you had it right the first time... It does indeed appear to be a thermal expansion error...

I would add your pastebin error log to your old thermal expansion issue and ask the devs there to take another look at it.

**Comment by lightning02** [comment]
Yes, after all a fixed issue more means a more stability and better interaction with mods, expecially in 1.7.10 where is located the greatest quantity of mods

**Comment by InfinityRaider** [comment]
I have no idea how this is an issue with agricraft, and even if it was, I am not doing any more work for 1.7.10, sorry.

**Comment by KingLemming** [comment]
Sorry man, this can only happen when things are being added to the OreDict too late. Basically what happens is that there's a first pass in all of our things and machines get their recipes.

Then, due to Item ID remapping, we have to re-sync the maps. If the OreIDs have changed, the HashMap breaks. That's what is happening here.

**Comment by insuusvenerati** [comment]
But where is the issue with AgriCraft? The only mod I see erroring out is UCHIJEE ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar)

**Comment by KingLemming** [comment]
I agree that's where the error is being thrown. That's not in dispute, but I've already explained why. The only reason it's coming up here is because it happens with AgriCraft is added to the pack.

It's entirely possible that it's a bad interaction from another mod entirely that only triggers when both TE and AgriCraft are together.

**Comment by lightning02** [comment]
After some hours of tests on thermos carried by me and my boyfriend, results almost clear that the problem is not related with Thermal expansion + agricraft itself, the problem resides in TSteelworks (and no matter what version of the mod you put, it does still generate that error that conflict with agri and blame Thermal expansion but seems it's not because of TE itself or neither agri). The wrost thing of this is that does not generate a crash-report. I'm gonna to move this tread to Tsteelworks guy to see if there is something it can be done about this.

**Comment by InfinityRaider** [comment]
@KingLemming I didn't know there is a conventional moment in FML's cycle to register things in the oredict, what I do is do it as soon as possible.

But for example MineTweaker, with it's scripts, the OreDict is shuffled around on server start and whenever the player reloads them.

**Comment by KingLemming** [comment]
Yeah, the OreDict isn't meant to be reloaded/altered like that. Minetweaker is a plague.

**Comment by InfinityRaider** [comment]
Well tbh, how can we know? There is nowhere anything about that in the OreDictionary javadoc.
