### ISSUE TITLE
Cannot interact with AgriCraft Villager in 1.8.9

### ISSUE THREAD

**Issue by MastaC729** [InfinityRaider/AgriCraft#614]
When I try to trade with a villager, the following shows up:

http://pastebin.com/ichwPBf0

Also, the localization for the villager does not appear. (It just shows entity.agricraft.villager_farmer.name)

**Comment by RlonRyan** [comment]
What version?

**Comment by insuusvenerati** [comment]
This happens even in the latest btw. I thought the villager was just not finished yet. I'm bad at bug reporting

**Comment by insuusvenerati** [comment]
I should mention the latest before GreenHouses were wiped out : (

**Comment by RlonRyan** [comment]
The fix was the removal of greenhouses. 1.8.9 isn't a true release so...
