### ISSUE TITLE
Melon plants do not give melons when harvested in 1.8.9

### ISSUE THREAD

**Issue by MastaC729** [InfinityRaider/AgriCraft#615]
As the title says. Unless I'm doing something wrong, breaking the matured plant does not yield any melons; it only yields the seed.

**Comment by RlonRyan** [comment]
Confirmed. Both melons and pumpkins yield no fruit ATM.

**Comment by insuusvenerati** [comment]
Yea i was gonna mention that but um..never got to it :S

**Comment by RlonRyan** [comment]
This issue has been addressed on the 1.8.9 branch. It may exist in the 1.9 branch...

**Comment by shrael** [comment]
yep having the same issue here as well. 10/10 seeds
