### ISSUE TITLE
[1.8.9] [2.0.0a2] Tessellating Water Channel crashes clients (MP Server)

### ISSUE THREAD

**Issue by claws61821** [InfinityRaider/AgriCraft#618]
While placing spruce Water Channels (aka irrigation channels) in a grid pattern, all clients were simultaneously kicked from the server. Clients are able to reconnect to the server, but crash again immediately upon completing the connection. The server does not crash.

http://pastebin.com/7YABZaF5 - Original crash report from offending client.

**Comment by RlonRyan** [comment]
Thanks for the issue! I needed something to confirm that #602 wasn't just a crops rendering issue.

Anyways looks like it's the same bug as #602, so I am just going to go ahead and merge these two issues!
