### ISSUE TITLE
Buildcraft Rendering bug

### ISSUE THREAD

**Issue by CJL48** [InfinityRaider/AgriCraft#620]
Agricraft appears to cause buildcraft's docking station to render incorrectly when both mods are installed.
Versions:
MC - 1.8.9
Forge 1.8.9-11.15.1.1764
Buildcraft 7.2.5
Agricraft 2.0.0a3
Steps to Reproduce:
Install Forge
Install both BC and Agricraft
Start Minecraft
[Also in BC's repo](https://github.com/BuildCraft/BuildCraft/issues/3291)

**Comment by RlonRyan** [comment]
You have a broken issue link. Also rendering changed so much in 1.8.9 that most mods have had to do some questionable things, so mod interactions like this are hard to address.

**Comment by CJL48** [comment]
My apologies...updating the link now. And yeah, I just wanted to make sure that both mod authors knew about it.
