### ISSUE TITLE
(1.8.9) Crash on game load

### ISSUE THREAD

**Issue by drewbit** [InfinityRaider/AgriCraft#622]
Unsure what the cause is, can't track it down myself. Here's the log:

http://paste.ee/p/LNoMh

Agricraft Version: agricraft-2.0.0a3
Forge Version: forge-1.8.9-11.15.1.1855-universal

**Comment by InfinityRaider** [comment]
If you have Thaumic Infusion, update it.

**Comment by drewbit** [comment]
Sorry for the late reply.

Updating Thaumic Infusion didn't help. Though now it isn't exactly crashing. Now it simply sits at a part of loading until it starts Not Responding, no matter how long I leave it there. To double check that it was actually Agricraft, I tried loading up again without the mod installed and I got to the main menu fine. Here's a log: http://paste.ee/p/MQkTM

**Comment by insuusvenerati** [comment]
This isn't going to make sense but could you try running the modpack without using MultiMC. I've had multiple instances of crashes like this with MultiMC but it ends up working fine without it.

**Comment by drewbit** [comment]
.. I have no earthly idea why that old version of Forge was in there. Hell, I even updated it serverside. Derp. Either way, problem persists on latest forge.

Unsure how to launch without MultiMC, it's a custom pack and I'm not sure how to launch otherwise.

**Comment by drewbit** [comment]
Although trying it again and leaving it for .. quite a long time gave me a slightly new log. Although it's just about it exceeding how much ram I gave it. Doesn't this hint at a memory leak?

Here's the log if it helps at all: http://paste.ee/p/9dq24

**Comment by RlonRyan** [comment]
That or increase the Java VM memory allocation amount.

**Comment by drewbit** [comment]
It's already at 2.5 gigs. I can't really spare any more than that.

**Comment by TehNut** [comment]
Try disabling the splash screen in `../config/splash.properties`.

**Comment by drewbit** [comment]
Disabling the splash screen didn't seem to have any effect.

**Comment by RlonRyan** [comment]
Might be a memory leak...
