### ISSUE TITLE
Issue with some Forestry wood types

### ISSUE THREAD

**Issue by Managarmr719** [InfinityRaider/AgriCraft#625]
I'm having an issue where I can't craft anything from agricraft with some of the wood types that forestry adds. The wood types that gave me problems were Palm and Zebrawood but there might be more.

**Comment by RlonRyan** [comment]
Which version of AgriCraft are we talking about?

**Comment by Managarmr719** [comment]
1.5.0

**Comment by Managarmr719** [comment]
Tried with Forestry 4.2.12.60 but I'm still intermittently having this issue.

**Comment by InfinityRaider** [comment]
Are these planks oredicted?

**Comment by Managarmr719** [comment]
Yes, they are and they sometimes work. It's really weird so I tried with a client with only Agricraft and Forestry installed and still had the same problem, but the other day when I tested it again it worked so I tried going back to the client with more mods but the problem reappeared.

**Comment by Managarmr719** [comment]
It seems this was a problem with Forestry and it's going to be fixed in a new version.
ForestryMC/ForestryMC#1127

**Comment by InfinityRaider** [comment]
Glad this was figured out, I had no idea what would be causing this.
