### ISSUE TITLE
Pam's HarvestCraft Sesame Seeds (1.7.10)

### ISSUE THREAD

**Issue by Wolf68k** [InfinityRaider/AgriCraft#628]
Sesame Seeds from crop sticks when matured does not give any sesame seeds.

**Comment by InfinityRaider** [comment]
Multiple times I have stated that this is not an agricraft bug, but should be fixed from harvestcraft's side:
https://github.com/InfinityRaider/AgriCraft/issues/588
https://github.com/InfinityRaider/AgriCraft/issues/482
etc...
