### ISSUE TITLE
Filling/Emptying water pad eats bucket if inventory is full

### ISSUE THREAD

**Issue by Chais** [InfinityRaider/AgriCraft#629]
Filling or emptying a water pad places the empty/full bucket in the player's inventory instead of the hotbar slot it was used from. If the inventory is full the bucket just disappears. It won't be dropped and won't go to the now empty hotbar slot either.
Occurring with Infinity Evolved: Skyblock modpack on MC 1.7.10

**Comment by InfinityRaider** [comment]
Don't expect a fix for 1.7 (https://github.com/InfinityRaider/AgriCraft#minecraft-versions), however I'm leaving this open for 1.9
