### ISSUE TITLE
Cannot place torches on fences

### ISSUE THREAD

**Issue by KeepOnDigging** [InfinityRaider/AgriCraft#630]
I like to place a torch on the fence post either side of a gate. So when I'm rushing for the gate with an angry horde on my heels I know where to head!

But I cannot place a torch on top of an Agricraft fence.

It would be great to have this fixed. I'm using AgriCraft-1.7.10-1.5.0.

Love the mod!!!

Thank you, and
KeepOnDigging!

**Comment by InfinityRaider** [comment]
If this doesn't work in 1.7.10 it will most likely also be the case in 1.9, thanks for the report.
