### ISSUE TITLE
Water tank render issue

### ISSUE THREAD

**Issue by Managarmr719** [InfinityRaider/AgriCraft#631]
I'm having an issue where when I look at a full water tank from certain angles the water doesn't render correctly. I'm using Agricraft version 1.5.0.

![2016-04-29_14 22 52](https://cloud.githubusercontent.com/assets/7836631/14917259/11a32952-0e16-11e6-80e9-01697701abac.png)

**Comment by InfinityRaider** [comment]
No more work is being done on 1.7.10 (https://github.com/InfinityRaider/AgriCraft#minecraft-versions), apologies.

**Comment by InfinityRaider** [comment]
No more work is being done on 1.7.10 (https://github.com/InfinityRaider/AgriCraft#minecraft-versions), apologies.

**Comment by InfinityRaider** [comment]
Are you using Optifine?

**Comment by Managarmr719** [comment]
No.
