### ISSUE TITLE
More Pipe/channels

### ISSUE THREAD

**Issue by Drakoflame** [InfinityRaider/AgriCraft#633]
I was recently watching Mallrat208 playing his Craft Arcanum series, and noticed that he was using Greatwood for the channels and sprinklers, and I thought "Oh thats right, Agricraft can use pretty much any ore dictionaried wood!" and then I saw what I THOUGHT was a stone channel, but was actually just an upside down cobblestone fence, and that's when the idea hit me, there should be stone/cobblestone channels alongside the wood ones! The difference would be they transport faster and hold more water than their wooden counterparts, but to actually craft then you either need cactus green/slimeballs or pipe sealant from Buildcraft, to keep the stone water tight! I'd think it would use the same things as the default wood ones, such that it just looks for ore dictionary "stone" or "cobblestone" to determine if its a valid option for a channel/barrel

**Comment by dredgemage** [comment]
Or better yet, perhaps the stone channels just doesn't connect to the wood ones that way we can have more possible control over the systems.

**Comment by InfinityRaider** [comment]
You can have different type of wood channels which dont connect to eachother
