### ISSUE TITLE
FTB Unstable 1.8.9 modpack (lastest download)

### ISSUE THREAD

**Issue by Undrhil** [InfinityRaider/AgriCraft#635]
When I add Agricraft to the Unstable modpack, it gets to phase 2/7 on the Forge loading screen and then crashes with this error report.  Yes, I know it's unstable and no guaranteed to run, but the pack *does* run until I launch it with Agricraft.  I am just trying to figure out what is causing the crash and I have no idea how to read this crash report.  I have gone through and removed the mods in the "Return of the compat" issues post, but it still crashes.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.83.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
  dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 5/1/16 12:49 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    com/infinityraider/agricraft/blocks/BlockModPlant.func_180660_a(Lnet/minecraft/block/state/IBlockState;Ljava/util/Random;I)Lnet/minecraft/item/Item; @31: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'net/minecraft/item/Item' (from method signature)
  Current Frame:
    bci: @31
    flags: { }
    locals: { 'com/infinityraider/agricraft/blocks/BlockModPlant', 'net/minecraft/block/state/IBlockState', 'java/util/Random', integer }
    stack: { 'java/lang/Object' }
  Bytecode:
    0x0000000: 2bb2 00cb b900 ee02 00c0 003f b600 4310
    0x0000010: 07a1 000a 2ab6 0193 a700 072a b601 97b0
    0x0000020:                                        
  Stackmap Table:
    same_frame(@27)
    same_locals_1_stack_item_frame(@31,Object[#57])

	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    com/infinityraider/agricraft/blocks/BlockModPlant.func_180660_a(Lnet/minecraft/block/state/IBlockState;Ljava/util/Random;I)Lnet/minecraft/item/Item; @31: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'net/minecraft/item/Item' (from method signature)
  Current Frame:
    bci: @31
    flags: { }
    locals: { 'com/infinityraider/agricraft/blocks/BlockModPlant', 'net/minecraft/block/state/IBlockState', 'java/util/Random', integer }
    stack: { 'java/lang/Object' }
  Bytecode:
    0x0000000: 2bb2 00cb b900 ee02 00c0 003f b600 4310
    0x0000010: 07a1 000a 2ab6 0193 a700 072a b601 97b0
    0x0000020:                                        
  Stackmap Table:
    same_frame(@27)
    same_locals_1_stack_item_frame(@31,Object[#57])

	at com.infinityraider.agricraft.init.AgriCraftCrops.init(AgriCraftCrops.java:21)
	at com.infinityraider.agricraft.AgriCraft.preInit(AgriCraft.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 192591600 bytes (183 MB) / 612651008 bytes (584 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1855 82 mods loaded, 82 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1855.jar) 
	UCH	Forge{11.15.1.1855} [Minecraft Forge] (forge-1.8.9-11.15.1.1855.jar) 
	UCH	CoreXU2{1} [CoreXU2] (minecraft.jar) 
	UCH	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCE	agricraft{2.0.0a3} [AgriCraft] (agricraft-2.0.0a3.jar) 
	UCH	bagginses{2.1.5b} [Bagginses] (Bagginses-1.8.9-2.1.5b.jar) 
	UCH	BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
	UCH	BetterThanBunnies{1.8.9-1.0.1} [BetterThanBunnies] (BetterThanBunnies-1.8.9-1.0.1.jar) 
	UCH	BloodMagic{1.8.9-2.0.0-19} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-19.jar) 
	UCH	bookshelfapi{2.3.6} [Bookshelf] (Bookshelf-API-1.8.9-2.3.6.jar) 
	UCH	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCH	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCH	Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
	UCH	BuildCraft|Core{7.2.0} [BuildCraft] (buildcraft-7.2.0.jar) 
	UCH	BuildCraft|Builders{7.2.0} [BC Builders] (buildcraft-7.2.0.jar) 
	UCH	BuildCraft|Transport{7.2.0} [BC Transport] (buildcraft-7.2.0.jar) 
	UCH	BuildCraft|Energy{7.2.0} [BC Energy] (buildcraft-7.2.0.jar) 
	UCH	BuildCraft|Silicon{7.2.0} [BC Silicon] (buildcraft-7.2.0.jar) 
	UCH	BuildCraft|Robotics{7.2.0} [BC Robotics] (buildcraft-7.2.0.jar) 
	UCH	BuildCraft|Factory{7.2.0} [BC Factory] (buildcraft-7.2.0.jar) 
	UCH	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCH	BuildCraft|Compat{7.2.0} [BuildCraft Compat] (buildcraft-compat-7.2.0.jar) 
	UCH	buildingbrickscompatvanilla{1.8.9-1.4.2} [Building Bricks Vanilla Compat] (BuildingBricks-1.8.9-1.4.2.jar) 
	UCH	buildingbricks{1.8.9-1.4.2} [Building Bricks] (BuildingBricks-1.8.9-1.4.2.jar) 
	UCH	Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
	UCH	mcmultipart{1.0.8} [MCMultiPart] (MCMultiPart-1.0.8-universal.jar) 
	UCH	CharsetLib{0.2.1} [â€½] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCH	CharsetTweaks{0.2.1} [*] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCH	CharsetWires{0.2.1} [+] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCH	CharsetAudio{0.2.1} [â™«] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCH	CharsetStorage{0.2.1} [#] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCH	CharsetPipes{0.2.1} [|] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCH	CharsetGates{0.2.1} [&] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCH	chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
	UCH	chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.11.jar) 
	UCH	compasscoords{1.8.9-0.2.6} [Compass Co-ords] (CompassCoords-1.8.9-0.2.6.jar) 
	UCH	craftingtweaks{3.0.52} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.52.jar) 
	UCH	crafttweaker{3.0.0} [crafttweaker] (CraftTweaker-1.8.8-3.0.2.jar) 
	UCH	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
	UCH	ElecCore{1.4.247} [ElecCore] (ElecCore-1.8.9-1.4.247.jar) 
	UCH	deepresonance{1.1.4beta17} [DeepResonance] (deepresonance-1.8.9-1.1.4beta17.jar) 
	UCH	dsurround{2.0.4.10} [Dynamic Surroundings] (DynamicSurroundings-1.8.9-2.0.4.10.jar) 
	UCH	ShetiPhianCore{3.1.0} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.1.0.jar) 
	UCH	EnderTanks{1.2.1} [EnderTanks] (EnderTanks-1.8.9-1.2.1.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.1.jar) 
	UCH	ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.6.jar) 
	UCH	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCH	flatcoloredblocks{mc1.8.9-v1.8} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.8.jar) 
	UCH	forgeanalytics{0.0.0.13} [Forge Analytics] (ForgeAnalytics-1.8.9-0.0.0.15.jar) 
	UCH	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UCH	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UCH	furnus{1.73} [Furnus] (Furnus-1.8.9-1.73.jar) 
	UCH	graves{1.8.9-b46-universal} [Graves Mod] (graves-1.8.9-b46-universal.jar) 
	UCH	hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar) 
	UCH	IGWMod{1.2.4-4} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
	UCH	intangible{0.0.25} [Intangible] (intangible-1.8.9-0.0.25.jar) 
	UCH	inventorysorter{0.7.4+26} [Simple Inventory sorting] (inventorysorter-1.8.9-0.7.4+26.jar) 
	UCH	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCE	jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.jar) 
	UCH	k4lib{1.8.9-1.0.16} [K4Lib] (k4lib-1.8.9-1.0.16-universal.jar) 
	UCH	llor{1.0.5-mc1.8.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.5-mc1.8.9.jar) 
	UCH	mantle{1.8.9-0.9.1.jenkins99} [Mantle] (Mantle-1.8.9-0.9.1.jar) 
	UCH	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCH	ModLister{1.8.9-1.0.7} [ModLister] (ModLister-1.8.9-1.0.7.jar) 
	UCH	Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
	UCH	MouseTweaks{2.6.2} [Mouse Tweaks] (MouseTweaks-2.6.2-mc1.8.9.jar) 
	UCH	neotech{2.4.1} [NeoTech] (NeoTech-1.8.9-2.4.1.jar) 
	UCH	notenoughkeys{@MOD_VERSION@} [NotEnoughKeys] (NotEnoughKeys-1.8.9-3.0.0b1-dev-universal.jar) 
	UCH	fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
	UCH	playerrugs{0.0.1} [Player Rugs] (PlayerRugs-1.8.8-1.2.0.jar) 
	UCH	PneumaticCraft{1.13.8-12} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.8-12-universal.jar) 
	UCH	progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
	UCH	Psi{beta-23} [Psi] (Psi-beta-23.jar) 
	UCH	randomthings{3.6.6} [Random Things] (RandomThings-MC1.8.9-3.6.6.jar) 
	UCH	ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
	UCH	rftools{4.23beta33} [RFTools] (rftools-1.8.9-4.23beta33.jar) 
	UCH	simpleretrogen{2.2.2+3} [Simple Retrogen] (simpleretrogen-1.8.9-2.2.2+3.jar) 
	UCH	StorageDrawers{1.8.9-2.4.4} [Storage Drawers] (StorageDrawers-1.8.9-2.4.4.jar) 
	UCH	thaumicinfusion{4.83} [Thaumic Infusion] (ThaumicInfusion-1.8.9-4.83.jar) 
	UCH	wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
	UCH	denseores{1.0} [denseores] (denseores-1.8-alpha-2.0.0.jar) 
	Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
thaumicinfusion (ThaumicInfusion-1.8.9-4.83.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.82' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'

**Comment by Insufficient-Charge** [comment]
Looks like Just Enough Resources is returning with UCE, rather than UCH. The 'E' in UCE means error. Probably a recipe issue if Agricraft has anything to do with it at all.

**Comment by Undrhil** [comment]
I removed Just Enough Resources and the game is still crashing.  I see in the error log I posted previously, that agricraft also has UCE.  Without jeresources, agricraft is now the only one with UCE status.

None of the first part of the crash-report changed with jeresources removed.
