### ISSUE TITLE
Support for MFR BioReactor

### ISSUE THREAD

**Issue by zlepper** [InfinityRaider/AgriCraft#637]
The MFR Bioreactor can accept seed/saplings and use it to create biofuel. 
This however doesn't work with agricraft seeds. 

This support would be nice, considering that MFR harvesters are already supported by AgriCraft.

**Comment by zlepper** [comment]
And i see that 1.7.10 isn't supported anymore.

**Comment by InfinityRaider** [comment]
Seeing that the community is not (or very slowly) moving forward, I have come back on my decision to discontinue 1.7 and will bring another update as soon as I have time to do modding again.

**Comment by TheOldOne822** [comment]
Actually that isn't feasible as the Bioreactor shares it's list with the planter such that to make the Bioreactor take something you register it with the planter. It is possible to register non plantable items and blocks with the planter and have the Bioreactor take them but that will cause the planter to take them too and try to "plant" them.
