### ISSUE TITLE
(1.8.9) Water tank render issue

### ISSUE THREAD

**Issue by Managarmr719** [InfinityRaider/AgriCraft#642]
Water inside a full tank doesn't render correctly when looking at it from certain angles.

![2016-05-02_11 27 00](https://cloud.githubusercontent.com/assets/7836631/14952573/460911da-1059-11e6-99d5-3517d2c9eac2.png)

**Comment by VT-14** [comment]
Duplicate of #631

**Comment by RlonRyan** [comment]
The real issue here is the fact that the 1.8.9 rendering code is a hack wrapped up in a bigger hack. This issue has been addressed by removing the 1.8.9 code altogether.

Note, don't worry, the rendering is completely retooled for the 1.9 version of AgriCraft.
