### ISSUE TITLE
[1.8.9] JEI recipe issues?

### ISSUE THREAD

**Issue by Insufficient-Charge** [InfinityRaider/AgriCraft#644]
No idea why, but every single recipe in order to mutate a plant in JEI comes up with a pumpkin seed and a wheat seed. If this is a problem on JEI's end, then please tell me and I'll forget about it...since my modpack needs an earlier version of forge, if JEI is the issue, I'll just have to live with it :)
![2016-05-08_10 57 45](https://cloud.githubusercontent.com/assets/13188566/15098825/c65f8bdc-150b-11e6-8ede-4dcba2d49f6a.png)
![2016-05-08_10 58 03](https://cloud.githubusercontent.com/assets/13188566/15098826/c9ebdc42-150b-11e6-9390-356ae5ef8821.png)
![2016-05-08_10 58 15](https://cloud.githubusercontent.com/assets/13188566/15098827/cc353a66-150b-11e6-9b63-f1bfca7a10e8.png)

**Comment by Redhandjane** [comment]
I am not getting any recipes for any of the Agricraft or Pam's Harvestcraft seeds.

**Comment by RlonRyan** [comment]
No issue here. It's just simply that all the mutations are set to use pumpkin and wheat seeds for the 1.8.9 builds. As this is a minor issue for an alpha version, this issue will be closed.

Not to worry however, as this issue will most certainly not be present in later versions of Agricraft..
