### ISSUE TITLE
[1.7.10 - 1.5.0] Crop tier overrides not affecting bonemealability 

### ISSUE THREAD

**Issue by thephoenixlodge** [InfinityRaider/AgriCraft#647]
Since 1.4.6 at least, overriding a higher tier crop to be tier 2 or lower doesn't allow it to be bonemealed. Specifically noticed with the essence seeds from magical crops 3 while working on regrowth. They correctly showed up in game in the journal as being a tier 2 seed (down from the default tier 4), but still would not allow bonemeal to be applied.

**Comment by InfinityRaider** [comment]
Probably due to some hardcoded overrides: https://github.com/InfinityRaider/AgriCraft/blob/1.7.10/src/main/java/com/InfinityRaider/AgriCraft/compatibility/magicalcrops/CropPlantMagicalCropsBeta.java#L85
Easy fix.
