### ISSUE TITLE
[1.8.9] NullPointerException: Tesselating block in world

### ISSUE THREAD

**Issue by Xiaminou** [InfinityRaider/AgriCraft#648]
Client crashes when I teleport back to my base, might be a duplicate or might be architecturecraft's fault, I do not know, please point me in the right direction.

Crash Report: http://pastebin.com/VgcCCqUT

**Comment by JoelZBub** [comment]
Try updating AppleCore to 1.3.1.

**Comment by InfinityRaider** [comment]
Its agricraft, part of the reason i pulled the build from curseforge

**Comment by Xiaminou** [comment]
I don't think it is, I tried without agricraft and architecturecraft and still get the same crash, but feel free to re-open if you think it's still relevant.

**Comment by InfinityRaider** [comment]
Ah no it actually is architecturecraft, you are correct.
