### ISSUE TITLE
[1.8.9] Files vanished from CurseForge

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#651]
I installed AgriCraft 2.0.0a3 few days ago. I checked Curse pages right now, and they are now vanished. I am not knowing it is intended or not, I decided to report it anyway.

**Comment by InfinityRaider** [comment]
Intended, the 1..8 release was a mistake. The rendering was one big hack and resulted in too many issues.

**Comment by hron84** [comment]
@InfinityRaider if you value a honest opinion: this is a best qualified hack I ever seen. I experience absolute no issues w/ rendering. Melon is not harvestable (does not drop anything) but that's all the bad things I faced with.

**Comment by InfinityRaider** [comment]
That's because you haven't looked at the code then.

**Comment by RlonRyan** [comment]
The rendering code literally depends on a package with a name ending in hack, if that gives you a sense of the state of the code...

**Comment by hron84** [comment]
I'm not talking about the code, I absolute understand your problem. My opinion is about game experience.
