### ISSUE TITLE
ResourcefulCrops Integration Crash

### ISSUE THREAD

**Issue by condensedapple** [InfinityRaider/AgriCraft#656]
The following crash occurs when starting Minecraft with AgriCraft and ResourcefulCrops (both latest version) with ResourcefulCrops-integration enabled:
https://gist.github.com/condensedapple/59814d427eb25465aff47e20a67659a8
With the integration disabled everything works fine.

**Comment by TehNut** [comment]
https://github.com/TehNut/ResourcefulCrops/issues/26

**Comment by condensedapple** [comment]
so i assume i have to wait for infinityraider to fix this?

**Comment by InfinityRaider** [comment]
yes

**Comment by TehNut** [comment]
Yes. 

In the 1.9+ versions of ResourcefulCrops, this shouldn't be a problem as I moved to an `IForgeRegistry` instead of the hacky little thing I used in 1.7.10 and early 1.8(.9).

**Comment by condensedapple** [comment]
Thanks for the fast clarification!

**Comment by Xaikii** [comment]
Sorry  to be "that guy" but this problem still exists. https://pastebin.com/Sf2uBTAy
The wierd thing is... it came out of nowhere, I've done was adding new crops for Resourceful Crops. Even after deleting them didnt fix, neither reinstalling both or Configs regenerating. Seriously nothing was I tried helped... Any Ideas how to fix it? Yes this is 1.7.10

**Comment by TehNut** [comment]
I don't think either of us support 1.7.10 anymore.

**Comment by Xaikii** [comment]
:/
Well actually they worked for **6 Months** together with no problems, I don't know why it happens, it is actually sh*tty I've been working actually quit hard with Minetweaker "disabling" the AgriCraft spreading and increase the Crops LvL by Crafting, actually If I should change into active time about 86 hours, with success. that'd be awful if that'd be for nothing. And yes I tried to remove the scripts, it didn't help.
