### ISSUE TITLE
[1.2.2] Issue with netherwart?

### ISSUE THREAD

**Issue by Belgabor** [InfinityRaider/AgriCraft#66]
While bug hunting for my custom crops I found this line in the logs, something seems to be wrong...

     [AgriCraft]: Error when reading mutation: first parent stack is not correct (line: AgriCraft:seedShroomRed=minecraft:nether_wart+AgriCraft:seedPoppy)

The respective line was C&Pd from the default mutations file I generated after the upgrade, but I also don't see anything wrong with the line. Not sure what's going on there.

**Comment by InfinityRaider** [comment]
I've had this report before, I still need to look into this though

**Comment by thephoenixlodge** [comment]
I'm honestly of the mind to suggest you add a nether wart seed. It's currently the only crop whose seed is the same item as its fruit.

**Comment by InfinityRaider** [comment]
That's because in Vanilla code it is an nistance of ItemSeeds, I kinda looked over this one in the initial stages of the mod until someone pointed out it made agricraft crash.
I could use reflection to make it implement IPlantable instead but for one it could break other mods that are expecting it to be a seed and two I'm too lazy.

**Comment by marcin212** [comment]
I rewrite getStack() and works for me:
``` Java
	public static ItemStack getStack(String input) {
		String[] data = input.split(":");
		int meta = 0;

		if (data.length <= 1) {
			return null;
		}
		if (data.length == 3) {
			meta = Integer.parseInt(data[2]);
		}

		Item item = GameRegistry.findItem(data[0], data[1]);
		if (item != null) {
			return new ItemStack(item, 1, meta);
		}
		return null;
	}
```

**Comment by InfinityRaider** [comment]
Thanks, can you make a pull request please?
