### ISSUE TITLE
1.7.10+ Harvestcraft Compat Sesame seed seeds.

### ISSUE THREAD

**Issue by Nirek-K** [InfinityRaider/AgriCraft#662]
Harvestcraft Sesame seeds..seeds don't work correctly on cropsticks, rightclick harvesting them manually returns planting seeds and not the 'produce' seeds.

**Comment by InfinityRaider** [comment]
I've had it with this, search this tracker and you'll see the followign issues:
https://github.com/InfinityRaider/AgriCraft/issues/482
https://github.com/InfinityRaider/AgriCraft/issues/588
https://github.com/InfinityRaider/AgriCraft/issues/540
https://github.com/InfinityRaider/AgriCraft/issues/628

This is on Pam's side.

**Comment by Nirek-K** [comment]
Ah, so it is, sorry, forgot to check closed ones. Was tracing a harvesting bug in Forestry when this turned up, was just passing it along.

**Comment by InfinityRaider** [comment]
It's, fine, I'm sorry for my rude reaction. I just get a message/comment/ticket every week or two about this and its really starting to annoy me.
