### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by InfinityRaider** [InfinityRaider/AgriCraft#663]
- [x]  Extend ICropPlant with a name method (e.g. "potato", "wheat", ... for compat purposes: #661)
- [x]  Rework ISeedStats to be a lot more extendable
- [ ]  Create a new interface IBreedable, which will be used by the mutation engine logic. Allows for mutating with other things besides agricraft crop sticks.
- [x] Expose the Mutation Engine to the api again, just like in 1.7.10

**Comment by RlonRyan** [comment]
I think some of this stuff might be changed if we decide to go with the JSON crops...

**Comment by lolorz13** [comment]
that third api change is rather interesting, by other things do you mean any adjacent tiles potentially? :D

**Comment by InfinityRaider** [comment]
Yes
