### ISSUE TITLE
You owe me a bucket

### ISSUE THREAD

**Issue by Dijkstra1** [InfinityRaider/AgriCraft#664]
I was filling some water pads, with water and speed filling is so easy, with jumping to the next free spot in my inventory, so with one free slot a split a stack of item so that the bucket would have to go in the slot, it came from, no it just disappeared, so then I had to make another, and by time I went back to my farm, I had full inventory, and not think guess  what another bucket gone.

**Comment by InfinityRaider** [comment]
https://github.com/InfinityRaider/AgriCraft/issues/629
