### ISSUE TITLE
[Request/Enhancement] Add crop stats to tooltip for trowels

### ISSUE THREAD

**Issue by Timeslice42** [InfinityRaider/AgriCraft#668]
When I pick up a crop with the trowel and scan it in the seed analyzer, I can't see any of the stats for that crop until I replant it. It would be nice to see them in the tooltip for the trowel. It would also be a subtle clue to let a few more people know that you can scan crops in a trowel.

**Comment by RlonRyan** [comment]
Lol. I actually just added that last night on the 1.9 branch...

**Comment by Timeslice42** [comment]
Nice :)

**Comment by InfinityRaider** [comment]
I could have sworn this was already the case, going to have to look into that.

**Comment by Timeslice42** [comment]
It's not the case in FTB Infinity, although I wouldn't be suprised if they weren't using the latest version.
