### ISSUE TITLE
Add Soil information to NEI Handler or tooltip

### ISSUE THREAD

**Issue by thephoenixlodge** [InfinityRaider/AgriCraft#67]
Currently it can be quite hit and miss figuring out what soil a crop may require, especially in the case of more ambiguous options such as sugarcane. This could probably be alleviated by adding soil information to the existing NEI handler or to a tooltip (possibly even requiring analysis?)

**Comment by Belgabor** [comment]
If you do that, please also include "needs to grow above" information for custom crops.

**Comment by InfinityRaider** [comment]
I will put it in the journal, right now all the seed portraits use farmland as a background texture, I will change that so they use the soil they require as background.

**Comment by Belgabor** [comment]
I'm not sure this is the optimal solution. You only can only get the information once you have the seeds, but you need it to mutate it successfully.

**Comment by Imasius** [comment]
I added the soil to the NEI GUI today. It will be in 1.3.
