### ISSUE TITLE
agri-hydraulic compat - working trolley, but...

### ISSUE THREAD

**Issue by Vine999** [InfinityRaider/AgriCraft#674]
Working with agricraft 1.5.0 and Hydraulicraft 2.1.253, on forge 10.13.4.1614 for MC 1.7.10. Also using NEI 1.0.4.107.

During some preliminary testing of mods in a creative world before entering a survival SP world, attempted to construct the Hydraulicraft harvester, with Agricraft's specific trolley attachment. In testing, all seems to work fine. However, upon trying to find the recipe using NEI's functionality, the only recipe visible was that of a separate trolley for the pneumaticraft plastic plants, with the proper recipe still unknown. I've checked with Hydraulicraft's author to make sure the issue's not in his mod, and he confirms it's an agricraft issue.

**Comment by InfinityRaider** [comment]
Adding a recipe, of course. Thanks for reporting.
