### ISSUE TITLE
Botania flower crops not dropping flowers (v1.2.2)

### ISSUE THREAD

**Issue by Amadeus99** [InfinityRaider/AgriCraft#68]
I am playing the Regrowth modpack v0.6.3 which updated to AgriCraft 1.2.2.  I made white, yellow, red, blue, and black mystical flowers and none of them drop flowers when right-clicking the crops.  Breaking them drops seeds and only seeds.  I created the flowers from the parent crops I had made with the previous version so they all had stats of 10/10/10 which gave the botania seeds the same stats.  Just mentioning that in case it matters.  Let me know if you need any other information.

**Comment by Belgabor** [comment]
Honestly, I think they should drop petals instead of flowers. But not dropping anything seems like a bug =)

**Comment by Imasius** [comment]
We need more information. I just tried to reproduce this bug in our development environment and the crops dropped the botania petals just fine. (I used 1/1/1 creative spawned seeds though)

**Comment by Amadeus99** [comment]
Same problem with a SSP creative world with using items from creative tabs.

However, I get the following warning when I try to harvest a botania crop:
[Server thread/WARN]: Attempted to add a EntityItem to the world with a invalid item at (-936.78,  65.17, 370.48), this is most likely a config issue between you and the server. Please double check your configs

Those are the coordinates of the crop.  Not sure how I can have a config issue between me and the server in SSP.

Sorry about not noticing that warning before.

Suggestions on what to do/check next?

**Comment by InfinityRaider** [comment]
I will move the botania crops to post init and compile a test version, so you can test if it persists there or not.

**Comment by InfinityRaider** [comment]
There is a test build under releases, can you test if you still cannot harvest botania crops or not?
https://github.com/InfinityRaider/AgriCraft/releases/tag/1.2.3-Snapshot-1

**Comment by Amadeus99** [comment]
That version works fine.  I can harvest petals, now, thanks.  Tried both in an SSP creative world and my established SMP play server.

Any other changes in that test build that would be useful to know?

**Comment by InfinityRaider** [comment]
Ehm check the changelog, (it's in the jar), I've added some more things today and I'm not sure anymore what's in the jar and what not

**Comment by Amadeus99** [comment]
Thanks.  Didn't think of looking in the jar for a change log.
