### ISSUE TITLE
Cactus crops dropping Cactus Green instead of Cactus (v1.2.2)

### ISSUE THREAD

**Issue by Amadeus99** [InfinityRaider/AgriCraft#69]
Regrowth modpack v0.6.3.

Let me know if you need any more info.

**Comment by InfinityRaider** [comment]
Intended

**Comment by Amadeus99** [comment]
Oops, sorry about that.  Just figured a cactus crop would drop cactus.

**Comment by InfinityRaider** [comment]
np, I might change it, I just want to reconsider the pros/cons

**Comment by thephoenixlodge** [comment]
My position on this would be to have it drop the actual cactus. For a vanilla setting it kinda makes sense to have it drop the dye based on what you've done with the other flowers. However, in a modded environment, various mods use cactus as an ingredient for different things. 
I actually removed other easy ways of getting cactus from Regrowth in favour of the crop, expecting it to give cactus as its fruit. In hindsight I probably should've tested that first.

**Comment by InfinityRaider** [comment]
I will throw in a config option
