### ISSUE TITLE
[Feature Request] GMO Machine (creative block)

### ISSUE THREAD

**Issue by zlyfire** [InfinityRaider/AgriCraft#691]
I know this has been requested in the past, at least in the form of a chat command, but I'd like to request a creative-only block that you put a seed into, modify the levels (ex: 1/1/1 -> 10/10/10), then pull out.  
I'd imagine that would be relatively simple to implement (three text boxes to accept numbers, saving those values to the nbt of the seed inside).  
This would be good for packmakers, map makers, and for server runners (spawn area with 10/10/10 crops) to save them time and frustration.

**Comment by InfinityRaider** [comment]
Thanks for the feature request, but this/similar things have been requested before and I have always replied with the same answer: I'm not implementing a way to cheat. For map makers, they can use command blocks to spawn seeds with the correct NBT tags.
