### ISSUE TITLE
[Question] Computer Controlled Seed Analyzer

### ISSUE THREAD

**Issue by chaos234** [InfinityRaider/AgriCraft#693]
Hi,

actually I want to to automate the Seed analysation from cross/mutaded crops but I found nothing related to the Computer Controlled Seed Analyzer.

How he works? Does he need RF/EU or smth. else to run? On which page can I find all the methods for this Device?

Will be glad to get any help for this.

Sidequestion: How many seeds can be stored in the Seed Storage, will the content be safed if I want to move it to another position and will the Seed Storage Warehouse ever come alive in 1.7.10 or only in 1.10.2?

**Comment by InfinityRaider** [comment]
Computer Controlled Seed analyzer doesn't need power, it needs a computer controlling it. By itself it doesn't do anything, you need to write a computer program to control it.
The device itself has a gui explaining each method.
Seed storage can store an infinite amount of the same seed. I think it drops its contents when you break it though.

**Comment by chaos234** [comment]
Ok, then I'll move it with a Dolly which safe :).

Good to know that the GUI explains each method. Thanks for the fast replay :) .
