### ISSUE TITLE
[Suggestion] Better sorting option for Seed Storage

### ISSUE THREAD

**Issue by chaos234** [InfinityRaider/AgriCraft#694]
Actually, for 1.7.10 - not looked in the 1.10.2 version - you can only sort for on of the three stats but why?
Why not sorting in 2 steps? E. G. Strength/Growth or Gain/Strength?

THis means taht it will be glad if you can hit a first sorting option and after that you can choose a secound sorting option from the three which will then sort according to the first and secound highest value.

So if you have say 20 seed with Grwoth 10 but different Gain and Strength then u hit one of the buttons left and it will then look wich has the highest value.

I hope that you can follow me from what I suggest, otherwise feel free to ask for more specific details :) .

**Comment by InfinityRaider** [comment]
I know what you mean, right now it sorts according to the stat you selected, and then by the total sum of all stats. I'm not sure if I will implement what you are askign for.

**Comment by chaos234** [comment]
Ok, but thanks for the fast response :) .
