### ISSUE TITLE
Shears not working on Cacti, other crops in 1.5.0 (part of Infinity Evolved modpack)

### ISSUE THREAD

**Issue by Simon-Bitdiddle** [InfinityRaider/AgriCraft#695]
Attempting to harvest a 10/10/10 Cacti on sand, with the indicator stating 'This plant is fertile and can grow' with a vanilla shears (with less than perfect durability) in my hotbar, slot one does not give me cactus blocks when I attempt to harvest with the shears or with an empty hand, crouching or not crouching.

I have tried it with other 10/10/10 plants as well with similar effects, yielding components but not the intact block.

Please advise as to further information needed or test to perform.

**Comment by samitefan1** [comment]
Li have the same problem in the current regrowth modpack. Please advise if any testing is desired from me as well.

**Comment by InfinityRaider** [comment]
I have managed to reproduce this.

**Comment by RlonRyan** [comment]
Wait... This is a 1.10 issue too?

If that's true, then, wow...
