### ISSUE TITLE
Water Pad Consumes Bucket. Agricraft 1.5.0 for forge-1.7.10-1614

### ISSUE THREAD

**Issue by JosEffigy** [InfinityRaider/AgriCraft#696]
with no items filling the inventory, the bucket teleports to the top-left most slot instead of being picked up. bypassing this with filling everything with items reproduces this bug.
tested on client with nothing but agricraft and fastcraft. reproducable.
http://imgur.com/gallery/ELNNc

**Comment by InfinityRaider** [comment]
Has been fixed, but there hasn't been a new release with this fix: https://github.com/InfinityRaider/AgriCraft/commit/6a0c5e222c5697a0753f9a17e83a667fad130c81

Also see #629
