### ISSUE TITLE
[Feature Request] Allow overriding soil type for existing crops

### ISSUE THREAD

**Issue by thephoenixlodge** [InfinityRaider/AgriCraft#70]
Basically I'd like to be evil and make Magical crops require being planted on the harder to get Tilled Garden Soil from Garden Stuff for my pack. A way of overriding the existing soil requirements of a crop would let me achieve this.
It should probably be part of the MT compat, since that seems to be the way the configurability of the mod is headed in general.

**Comment by InfinityRaider** [comment]
This will be possible once https://github.com/InfinityRaider/AgriCraft/pull/71 is finished
