### ISSUE TITLE
Allow mutation with non-crop sticked plants via minetweaker

### ISSUE THREAD

**Issue by lolorz13** [InfinityRaider/AgriCraft#701]
Would it be feasible to allow mutation with plants that do not or cannot be put on crops?

Behavior:
Breeding crops check adjacent blocks for a matching breeding pattern defined either by the mod or a minetweaker script.
Result:
Breeding crops either do or do not find a matching breeding pattern in the adjacent blocks and mutate to their defined plant if crossbreeding succeeds.

While I realize that your minetweaker integration does have a nearby option in its growth stages I feel like this might provide an interesting addition to crop mutation itself. For instance, while you might not be able to crop aspect infused plants, you could require a lucrum and herba infused "parent" plants adjacent to breeding sticks to produce agricraft's gold seeds, or maybe require that certain botania flowers are adjacent to your crop sticks.
- also as an aside note about using thaumic tinkerer soils and plants, I have been experimenting with planting agricraft crops on soils with interesting results, such as requiring lucrum aspected plants/soils nearby in order for gold to grow which is what caused this idea to surface for mutation (allowing for some very interesting minetweaker scripts).

another good example of this functionality might be if you choose to remove all pumpkins and pumpkin seeds from the world and you want to force the player to progress by finding an orange flower not in a crop and a melon block/plant in or not in a crop adjacent to the cross breed crop in order to breed a pumpkin.

**Comment by RlonRyan** [comment]
I think that this might be addressed by the upcoming JSON plants, and their customizable growth requirements...

**Comment by lolorz13** [comment]
will it be backported to 1.7.10? or do you plan to leave it behind in favor of 1.10.2? Different developers have different policies on this at the moment, so it would be nice to know where you stand :)

**Comment by InfinityRaider** [comment]
1.7.10 is dead unless you find som

**Comment by lolorz13** [comment]
@InfinityRaider  good to know, a pack I am currently developing is stuck on 1.7 until you release a 1.10 version on CF :) as well as a 2-3 other mods but I can make do without those until then, I also need to look into potentially developing a skyblock plugin utilizing sponge in my spare time.  feel free to close if you feel it is appropriate as you are already working on this with another issue

**Comment by InfinityRaider** [comment]
I'll leave it open, flagged with 1.7. But don't expect anything from me on this.
