### ISSUE TITLE
I don't know 

### ISSUE THREAD

**Issue by EverythingGM** [InfinityRaider/AgriCraft#702]
http://pastebin.com/0xYBFkY6

so............. fix ?

**Comment by EverythingGM** [comment]
so..............................................................................................................what do i do ?

**Comment by Ravin890** [comment]
What did you do prior to crash?

**Comment by InfinityRaider** [comment]
I was away for the weekend, tx for reporting this.
Patience is appreciated.

**Comment by EverythingGM** [comment]
is there any mod else i need to download for Agricraft to work ?

**Comment by InfinityRaider** [comment]
remove TooManyItems and see if it still crashes

**Comment by HeXReapers** [comment]
Can confirm that it crashes with TMI, but works fine without it.

**Comment by InfinityRaider** [comment]
Since Im no longer going to do anything 1.7, I'm closing this.
Ill stick a label on it, if anyone ever wants to maintain 1.7.10, they can quickly find all tehse issues.
