### ISSUE TITLE
when book turn the page ,the client crashes.

### ISSUE THREAD

**Issue by JoshuaCheng** [InfinityRaider/AgriCraft#703]
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 16-10-16 下午9:32
Description: Rendering screen

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at com.InfinityRaider.AgriCraft.gui.GuiJournal.splitInLines(GuiJournal.java:556)
	at com.InfinityRaider.AgriCraft.gui.GuiJournal.drawIntroduction(GuiJournal.java:285)
	at com.InfinityRaider.AgriCraft.gui.GuiJournal.func_73863_a(GuiJournal.java:158)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.String.charAt(String.java:658)
	at com.InfinityRaider.AgriCraft.gui.GuiJournal.splitInLines(GuiJournal.java:556)
	at com.InfinityRaider.AgriCraft.gui.GuiJournal.drawIntroduction(GuiJournal.java:285)
	at com.InfinityRaider.AgriCraft.gui.GuiJournal.func_73863_a(GuiJournal.java:158)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)

-- Screen render details --
Details:
	Screen name: com.InfinityRaider.AgriCraft.gui.GuiJournal
	Mouse location: Scaled: (310, 195). Absolute: (620, 89)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['lazycheng'/790923, l='MpServer', x=-100.08, y=62.62, z=341.80]]
	Chunk stats: MultiplayerChunkCache: 292, 292
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (81,72,344), Chunk: (at 1,4,8 in 5,21; contains blocks 80,0,336 to 95,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2006664 game time, 2006664 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 43 total; [EntityClientPlayerMP['lazycheng'/790923, l='MpServer', x=-100.08, y=62.62, z=341.80], EntityItem['item.item.egg'/790414, l='MpServer', x=-89.09, y=68.13, z=287.72], EntityCreeper['爬行者'/791304, l='MpServer', x=-117.50, y=38.00, z=377.50], EntityVoidwalker['虚空步行者'/791303, l='MpServer', x=-122.50, y=38.00, z=374.50], EntityClientPlayerMP['lazycheng'/790923, l='MpServer', x=-98.30, y=56.62, z=336.70], EntityZombie['僵尸'/791582, l='MpServer', x=-51.50, y=66.00, z=313.50], EntityBushBaby['灌木婴'/791569, l='MpServer', x=-75.50, y=77.00, z=360.50], EntityStinger['毒刺'/791571, l='MpServer', x=-138.50, y=24.00, z=384.50], EntityBushBaby['灌木婴'/791457, l='MpServer', x=-138.50, y=71.00, z=344.50], EntityVoidwalker['虚空步行者'/791484, l='MpServer', x=-123.69, y=21.00, z=377.75], EntityVoidwalker['虚空步行者'/791485, l='MpServer', x=-122.94, y=21.93, z=375.50], EntityVoidwalker['虚空步行者'/791482, l='MpServer', x=-121.50, y=21.00, z=376.69], EntitySheep['羊'/791244, l='MpServer', x=-157.47, y=81.00, z=388.47], EntityPig['猪'/791240, l='MpServer', x=-158.50, y=66.00, z=352.50], EntityBat['蝙蝠'/791496, l='MpServer', x=-103.40, y=52.78, z=360.08], EntityPig['猪'/791241, l='MpServer', x=-148.06, y=65.00, z=358.03], EntityBat['蝙蝠'/791497, l='MpServer', x=-112.77, y=58.34, z=370.88], EntitySheep['羊'/791242, l='MpServer', x=-157.47, y=81.00, z=389.53], EntitySheep['羊'/791243, l='MpServer', x=-157.47, y=81.00, z=388.47], EntitySheep['羊'/791237, l='MpServer', x=-144.53, y=66.00, z=340.50], EntitySheep['羊'/791238, l='MpServer', x=-144.50, y=68.00, z=341.50], EntityPig['猪'/791239, l='MpServer', x=-159.50, y=68.00, z=353.50], EntitySheep['羊'/791261, l='MpServer', x=-160.47, y=81.00, z=389.47], EntityChicken['鸡'/787672, l='MpServer', x=-88.53, y=68.00, z=287.47], EntityPig['猪'/788058, l='MpServer', x=-113.22, y=69.00, z=387.94], EntityBoat['船'/788059, l='MpServer', x=-103.25, y=63.28, z=318.25], EntityPig['猪'/787668, l='MpServer', x=-69.50, y=73.00, z=312.09], EntityPig['猪'/787667, l='MpServer', x=-90.72, y=68.00, z=296.88], EntityShadow['暗影'/791151, l='MpServer', x=-55.31, y=40.00, z=283.75], EntityPig['猪'/787681, l='MpServer', x=-92.53, y=75.00, z=374.47], EntityPig['猪'/787682, l='MpServer', x=-94.50, y=90.00, z=374.50], EntityFacelessRunner['无面跑者'/791395, l='MpServer', x=-106.09, y=14.00, z=402.16], EntityPig['猪'/788092, l='MpServer', x=-138.47, y=67.00, z=360.97], EntityCow['牛'/788093, l='MpServer', x=-136.38, y=76.00, z=366.19], EntityFacelessRunner['无面跑者'/791165, l='MpServer', x=-61.50, y=10.00, z=295.50], EntitySheep['羊'/788094, l='MpServer', x=-143.47, y=66.00, z=340.50], EntitySheep['羊'/788095, l='MpServer', x=-137.38, y=69.00, z=349.47], EntityShadow['暗影'/791416, l='MpServer', x=-147.53, y=26.00, z=375.69], EntityCow['牛'/788091, l='MpServer', x=-132.66, y=74.00, z=372.22], EntityPig['猪'/787701, l='MpServer', x=-43.94, y=69.00, z=280.03], EntityZombie['僵尸'/791536, l='MpServer', x=-49.78, y=72.00, z=345.31], EntityShadow['暗影'/791153, l='MpServer', x=-58.50, y=40.00, z=283.50], EntityZombie['僵尸'/791537, l='MpServer', x=-54.50, y=72.00, z=344.50]]
	Retry entities: 0 total; []
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.12
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 252826632 bytes (241 MB) / 671088640 bytes (640 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 5 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1564 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1564-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1564} [Minecraft Forge] (forge-1.7.10-10.13.4.1564-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJA	eatable_mobs{1.0} [Eatable Mobs] (1.7.X Eatable Mobs 1.0.jar) 
	UCHIJA	nevermine{2.5(S2)-汉化:§6Remilia} [§cNevermine] ([1.7.10][ZH]Nevermine-2.5(S2).jar) 
	UCHIJA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJA	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
	UCHIJA	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHIJA	cfm{3.4.8} [MrCrayfish's Furniture] ([1.7.10]MrCrayfish's Furniture-3.4.8.jar) 
	UCHIJA	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) 
	UCHIJA	dungeonpack{1.7.10-1.0} [Dungeon Pack] ([1.7.10]更多地牢——DungeonPack[心殇搬运]-V1.0.jar) 
	UCHIJA	moreShearables{1.0} [More Shearables] ([更多剪刀的用途]More-Shearables-Mod-1.7.10(Chopper汉化).jar) 
	UCHIJA	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) 
	UCHIJA	craftguide{1.6.8.2} [CraftGuide] (CraftGuide-1.6.8.2-forge.jar) 
	UCHIJA	DynamicLights{1.3.9} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJA	journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar) 
	UCHIJA	mobends{0.20.1} [Mo' Bends] (MoBends-0.20.1 for MC 1.7.10.jar) 
	UCHIJA	placeableitems{PreAlpha 2.0} [Placeable Items Mod] (placeableitems-PreAlpha 1.7.10.jar) 
	UCHIJA	UnicodeFontFixer{1.1.12-mc1.7.10} [UnicodeFontFixer] (UnicodeFontFixer-1.1.12-mc1.7.10.jar) 
	UCHIJA	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJA	yarr_cutemobmodels{1.0.8} [Cute Mob Models] (yarrcutemobmodels-1.0.8-1.7.10[酒仙·老陈汉化].jar) 
	UCHIJA	VehicularMovement{1.1.0} [VehicularMovement] (yxzoo1.7.10VehicularMovementMOD.jar) 
	UCHIJA	ironbackpacks{1.7.10-1.2.15} [Iron Backpacks] (背包IronBackpacks-1.7.10-1.2.15.jar) 
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.18.65' Renderer: 'Intel(R) Iris(TM) Graphics 6100'
	Launched Version: HMCL 2.5.3.88
	LWJGL: 2.9.1
	OpenGL: Intel(R) Iris(TM) Graphics 6100 GL version 2.1 INTEL-10.18.65, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Ravin890** [comment]
Maybe use a more recent version of agricraft? You are using 1.3.1 and currently the latest is 1.5.0

**Comment by InfinityRaider** [comment]
1.3.1? Really?
