### ISSUE TITLE
Problem While Building 'gradlew build'

### ISSUE THREAD

**Issue by nizarnizario** [InfinityRaider/AgriCraft#709]
Hi !
Thanks for your efforts in developing such great mod ; 
While i was trying to build Agricraft using Gradle i faced this problem : 
http://i.imgur.com/McODMtP.png
Is it a problem from my computer ?

**Comment by RlonRyan** [comment]
What version of the mod are you trying to build?

**Comment by nizarnizario** [comment]
Latest.. master..
should i build it in a different way?

**Comment by nizarnizario** [comment]
Can you provide us a pre-built version of the mod for 1.10 for noobs like me :)?

**Comment by Drakma** [comment]
I'd love an alpha build available in curse.

On Nov 19, 2016, at 11:40 AM, nizarnizario <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you provide us a pre-built version of the mod for 1.10 for noobs like me :)?

**Comment by nizarnizario** [comment]
@Drakma Me too :)

**Comment by RlonRyan** [comment]
Odd... have you used forge gradle before? It could be an issue with the cache...

**Comment by RlonRyan** [comment]
I'd offer up an alpha, but last time it didn't turn out too well, and @InfinityRaider wasn't too happy with me.

**Comment by InfinityRaider** [comment]
If we disable the irrigation we could release an alpha without that.

**Comment by RlonRyan** [comment]
That would work...

**Comment by nizarnizario** [comment]
@RlonRyan I tried that command , and the results were like this : http://i.imgur.com/UuGObWR.png

**Comment by RlonRyan** [comment]
How odd... You are clearly using windows 10, like me, but it is refusing to work on your computer...

Are you using the latest JDK?

**Comment by RlonRyan** [comment]
I'll talk to @InfinityRaider about trying to get that alpha to you in the next week...

**Comment by RlonRyan** [comment]
So... we might not have to disable the Irrigation stuff... We would probably need pre-alpha testers though...

**Comment by Drakma** [comment]
I would happily test it.
On Nov 23, 2016, at 6:42 PM, RlonRyan <notifications@github.com<mailto:notifications@github.com>> wrote:

So... we might not have to disable the Irrigation stuff... We would probably need pre-alpha testers though...

**Comment by nizarnizario** [comment]
@RlonRyan Yup , Latest JDK :) we'll be happy to test 👍

**Comment by Volune** [comment]
@nizarnizario Have you run `git submodule update --init` to set up the submodules? I think I had a similar issue and I forgot that point.

**Comment by RlonRyan** [comment]
So since AgriCraft depends on a newer version of InfinityLib, we have to wait to release the official alpha, but I might be able to get InfinityRaider to let me distribute a zip of the new InfinityLib and the AgriCraft build, on Discord.

**Comment by nizarnizario** [comment]
@Volune That was it :) Thanks mate.
@RlonRyan Well , good luck with that. Quick question : will the new Agricraft support the new villager mechanics (MC 1.8+) ?

**Comment by RlonRyan** [comment]
I had no clue that there were new villager mechanics in 1.8+... Infinity dealt with all of the entity coding, so he'd probably know more than me about that.

(So... Since you were able to build it, I take I don't need to build it for you?)

**Comment by RlonRyan** [comment]
By the way, if you want to help create and balance all the default plants, you are welcome to contribute here: [AgriPlants Repo](https://github.com/AgriCraft/AgriPlants)!

**Comment by nizarnizario** [comment]
(So... Since you were able to build it, I take I don't need to build it for you?)
Yup :) but what about others?
I'll take a look at AgriPlants.

**Comment by RlonRyan** [comment]
By the way, the latest pr added to master should have fixed several possible issues. I would recommend updating.
