### ISSUE TITLE
Agricraft rice paddy making

### ISSUE THREAD

**Issue by patrdm83** [InfinityRaider/AgriCraft#710]
I know this was closed a long time ago but I'm still getting TC shovel compatibility issues using Agricraft and Growthcraft. I'm able to make a rice pad using a vanilla shovel on farm dirt in which water and rice work fine. When I use a TC shovel, it won't let me create a water pad. I've checked into the config which everything's good to go.. I just need TC shovels or a mattock to behave like a vanilla shovel. Also, I'm aware sneak right-clicking creates rice pads using TC shovels but it won't let me plant rice using this method. Even vanilla shovels don't work, I've already tried. I'm using the latest version of all 3 mods. Thank you for your help.

**Comment by Ravin890** [comment]
Did you put water in the rice pad?

**Comment by patrdm83** [comment]
Yes. The steps are as followed:
 right-click on dirt with hoe to turn into farm dirt
right-click on farm dirt with shovel to make a water pad
right-click with water bucket to water the rice pad
right-click with rice to plant rice in the water pad

This only works with vanilla tools but TC shovels aren't working. It just moves the shovel like it wants to be used but nothing happens to the farm dirt. I'm using Agricraft 1.5, Growthcraft 2.7, and Tinker's Construct 1.8.8.

**Comment by InfinityRaider** [comment]
Just to be sure, you are putting crop sticks in the water pad right?

**Comment by patrdm83** [comment]
Then I have to shift right-click the farm dirt to place crop sticks. So if I have this correct TConstruct tools and Growthcraft farming only work with support from Agricraft. Right-clicking on farm dirt to create a rice pad is the Growthcraft/vanilla way. Shift right-clicking farm dirt is the Agricraft way which requires using crop sticks to place rice. So there isn't a workaround to grow rice without using crop sticks?

**Comment by InfinityRaider** [comment]
Growthcraft rice outside of crop sticks on growthcraft water pads, growthrcraft rice inside crop sitcks on agricraft water pads.
