### ISSUE TITLE
AE2&Ender IO Integration

### ISSUE THREAD

**Issue by BurovB** [InfinityRaider/AgriCraft#713]
Please add in Agricraft crop which will give certus quarts and add integration with Ender IO Farming Station.

**Comment by Ravin890** [comment]
Well if it is like how it was before i think you would be able to add your own crops though with enderIO i doubt there is an easy way to go about it since agricraft isn't the one fully dictating how the crops are broken when harvested.

**Comment by BurovB** [comment]
Please, add certus quartz crops and when Agricraft will release on 1.10.2 I will make issue to Ender IO's creator with Agricraft with Agricraft integration.

**Comment by TehNut** [comment]
EnderIO provides full control over the harvesting of a crop.

**Comment by InfinityRaider** [comment]
Compat will be look into later, priority is getting the mod to work by itself.
Concerning custom crops, RlonRyan set up a great system for it, and I have some ideas to make sharing/selecting custom crops really easy.
