### ISSUE TITLE
[1.10.2] Items made wholly of wood have no recipe

### ISSUE THREAD

**Issue by dshadowwolf** [InfinityRaider/AgriCraft#717]
AgriCraft 2.0.0a1
Infinitylib 0.3.0
Forge 12.18.2.2151

All other recipes exist, but it looks like there is no call in the recipe initialization to "registerCustomWoodRecipes()" - I think the solution is to put the call in after the registration of the sprinkler, somewhere in the conditional started on line 88 of init/AgriRecipes.java  :)

Otherwise, good work!

**Comment by RlonRyan** [comment]
Interesting...

I'll have to look into this one more...

In my testing recipes were showing up in JEI, but perhaps they are uncraftable?

**Comment by RlonRyan** [comment]
Ok... They are uncraftable, but this looks like a deeper rooted issue than first thought so it might take a while to resolve. I hope to have it fixed by day's end. However, I currently have to go to the store, so it won't be immediate, like the server crash fix, sorry.

**Comment by dshadowwolf** [comment]
Yeah, found that my eyes had just passed right over the call to "registerCustomWoodRecipes()"...  At this point I'm wondering if there is an issue in how the "custom wood types" are registered or if it has to do with something else.

With a bit of hacking it is looking like 'woodList' is never getting filled...  AgriRecipes.initWoodList() is completing with zero custom woods found. I'm going to go add some debugging to utility/CustomWoodType.java and see if that is the source of the issue next.

**Comment by RlonRyan** [comment]
I solved it. It was an issue with getting the wrong instance of the block registry.
