### ISSUE TITLE
[1.10.2] Villager Crash on World Creation / Load

### ISSUE THREAD

**Issue by oitsjustjose** [InfinityRaider/AgriCraft#718]
[Crashlog](http://puu.sh/sL46e/e211341694.txt)

Running:
* MinecraftForge 12.8.3.2185

* AgriCraft 2.0.0-i0.3.0-a2

* InfinityLib-0.3.0

Villager creation seems to be crashing on world creation. Not a huge deal, just disabled the villagers in the config and it's loading fine :)

EDIT: not related, but cropsticks now have a collision box, is this a new change or a bug?

**Comment by RlonRyan** [comment]
Thank you for using the GitHub issue tracker!

Given that the villagers are not the core focus of this mod, this issue might not be resolved for some time. As such, they will likely be disabled by default until such a time is found as to have them fixed.

(The crop stick bounding box is a side effect of the port.)

**Comment by InfinityRaider** [comment]
Villagers was one of the things that changed, yes...
I ported the code to compile but forgot to actually test that, I'm gna have to figure this one out, thanks for reporting.
