### ISSUE TITLE
[1.10.2] Weed config does not seem to work

### ISSUE THREAD

**Issue by DeadSix27** [InfinityRaider/AgriCraft#719]
Forge version: `forge-1.10.2-12.18.3.2185`
Agricraft version: `agricraft-2.0.0-i0.3.0-a2.jar`
Infinitylib version: `infinitylib-0.3.0.jar`
List of mods: _`(Ask me if you need that)`_

Server seems to not follow config options
I set (on client and Server):
```
# Set to false if you wish to disable weeds [default: true]
B:"Enable weeds"=false
```
and weeds still grow.

**Comment by RlonRyan** [comment]
Thank you for using the github issue tracker!

The enable weeds option is a legacy setting that I probably should have already been removed. For the new crops system, goto `config/agricraft/json` and chose the world you want to disable the weeds in, or, alternatively, edit the defaults folder to change all default settings for worlds made thereafter.

I am closing this issue in favor of opening a 'Config Contains Legacy Options' issue.

**Comment by ChaosTherum** [comment]
Sorry for commenting on a closed issue but I didn't think this justified opening a new one.  I can't seem to find the folder that you are mentioning. All that is in that folder is a folder labeled default I've also checked in my world folder for an agricraft folder no luck maybe I'm just overlooking something obvious.

**Comment by RlonRyan** [comment]
The default folder is the one used locally for the world. Update that to remove the weeds.

**Comment by Franck2945** [comment]
Sorry but I still don't get what you are supposed to do whith the "defaults" file in "config>agricraft>json".
I might just be missing it. Would love a response!

**Comment by olback** [comment]
Franck2945, change "enabled": true, to "enabled": false,. Should do the trick. json/defaults/vanilla/plants/weed_plant.json

**Comment by HalJordan** [comment]
IMO leaving a comment in the config file pointing this out would have been helpful. I get why the change was made. With it configured this way, you have a lot more control, marking a vast improvement over just on/off. There was just -nothing- to tell you about this change. I've been searching for 2 days trying to find a way to turn them off. Everything leads to the old way.
