### ISSUE TITLE
Glitch with the weed

### ISSUE THREAD

**Issue by StuardBr** [InfinityRaider/AgriCraft#72]
Hello! I'm here to report a strange thing.

As known, weeds will destroy and spread over all the farmland. Ok, this is ok. But, in a crop with weed, i put another crop (putting a cross-crop) the weed disappear, but my tooltip stay saying that a "Weed have sprouted here" and another weed or a normal crop don't spread to it.
The weed is gone, but the status of "weed" don't disappear. I think only adding a way to not put another crops in a farmland with weed solves the problem.

Here is a image with a small farm with weed and some cross-crops with the message and without weed. http://imageshack.com/a/img540/126/auJLu1.png

Tks for the attention :)

**Comment by InfinityRaider** [comment]
Probably a sync issue between server and client, thanks for reporting

**Comment by InfinityRaider** [comment]
@Imasius fixed this in 84963301b093e8af9f0a8ce94740c7662325ba96
