### ISSUE TITLE
InfinityLib is *not* registered as a dependancy on CurseForge

### ISSUE THREAD

**Issue by majix560** [InfinityRaider/AgriCraft#720]
InfinityLib is **_not_** registered as a dependancy on CurseForge.
I would like to respectfully request that you properly register InfinityLab as a dependancy in AgriCraft's CurseForge registration as InfinityLib does not currently show up as a dependancy on CurseForge,
even though it actually _is_ a dependancy.

**Comment by RlonRyan** [comment]
My fault. Thank you for notifying me!

**Comment by RlonRyan** [comment]
I might have to research how to set that up...

**Comment by majix560** [comment]
I meant the dependencies tab in the top menu.

**Comment by RlonRyan** [comment]
Yeah, I can't figure out why it isn't displaying there...

**Comment by InfinityRaider** [comment]
Its because the build using it as a dep is tagged as alpha.
Alpha builds do not appear on the launcher or on Curse.com,
it is simply the nature of CurseForge and beyond our control.
There is no way we're tagging this as beta or release, apologies.

**Comment by RlonRyan** [comment]
Totally tagging the next alpha as release now... Just to mess with you... (Not really, I'm not Joker-level insane)...
