### ISSUE TITLE
[1.10.2] Breaking of Seed Analyzer Causes Client game to freeze

### ISSUE THREAD

**Issue by Morpheus1101** [InfinityRaider/AgriCraft#722]
When breaking a Seed Analyzer in a Village Crop House, during the process of breaking it causes the client to Feeze untill forcibly closed.  I think this may all ready be a known issue, but wasnt able to find anything specific about it

**Comment by InfinityRaider** [comment]
log?

**Comment by Morpheus1101** [comment]
I'll try an get something useful, but due to the fact the game completely freezes and u have to force close it , there was nothing produced.

**Comment by InfinityRaider** [comment]
There is always a log though.

**Comment by Morpheus1101** [comment]
https://puu.sh/sLDKJ/0ec55ba0b3.log

**Comment by Morpheus1101** [comment]
With this time it closing by itself, i can see its not your end but CCL's end with bakedmodels, which ive reported to covers to look at
