### ISSUE TITLE
Crop Sticks do not update properly

### ISSUE THREAD

**Issue by Xiaminou** [InfinityRaider/AgriCraft#723]
Using the Gardening Trowel on seed in crop sticks will not update its render.
Using Clippers on a mature seed in crop sticks will not diminish its growth stage resulting in infinite clipping (pretty sure that's not how it worked back in 1.7.10)
Planting a seed in crop sticks does not consume the seed.
Removing a crop stick from a breeding pair of crop sticks will not update its render.

It's also worth noting that crop sticks are now solid and full block, I don't know if that is intended or not.

Here is a couple of videos showing some of these bugs:
https://www.youtube.com/watch?v=SfkaX-jxqCQ&feature=youtu.be
https://youtu.be/C6PbQFFnzTI

Confirmed with agricraft only.

Environment: Server
Minecraft: 1.10.2
Forge: 2185
Mods: [list.txt](https://github.com/InfinityRaider/AgriCraft/files/644504/list.txt)

**Comment by RlonRyan** [comment]
Fixed by #739.

**Comment by eslachance** [comment]
Can confirm seed duplication, crop sticks being solid, and lack of render update when removing breeding crop sticks. Have not tested the others.

**Comment by RlonRyan** [comment]
Partially fixed in #739.
