### ISSUE TITLE
Crops do not grow

### ISSUE THREAD

**Issue by Xiaminou** [InfinityRaider/AgriCraft#725]
Crops do not grow, weeds will spawn just fine and then never grow, other crops do not do anything at all.

https://youtu.be/R1m20nwP1FE

Environment: Server
Minecraft: 1.10.2
Forge: 2185
Mods: [list.txt](https://github.com/InfinityRaider/AgriCraft/files/644504/list.txt)

**Comment by kurokuno** [comment]
can confirm

**Comment by abellb19** [comment]
Yes, bone meal makes them grow but they do not grow on their own.  You can use bone meal on them to maturity.

**Comment by ChaosTherum** [comment]
I'll also confirm that I can not get anything to grow.

**Comment by RlonRyan** [comment]
Fixed with #739.
