### ISSUE TITLE
1.10.2 possible agricraft crash

### ISSUE THREAD

**Issue by snacdaws** [InfinityRaider/AgriCraft#726]
when i try and break the agricraft water tank and water chanels  it crashes minecraft

[crash-2016-12-12_16.40.07-client.txt](https://github.com/InfinityRaider/AgriCraft/files/647303/crash-2016-12-12_16.40.07-client.txt)

**Comment by InfinityRaider** [comment]
Are you sure that is the correct crash  report?

**Comment by VindellePounze** [comment]
I got a similar crash while trying to break the seed analyzer. It became invisible (but I was able to use it/interact with it) so I thought to try breaking it and placing it again.

[crash-2016-12-13_10.23.31-client.txt](https://github.com/InfinityRaider/AgriCraft/files/648475/crash-2016-12-13_10.23.31-client.txt)

**Comment by Volune** [comment]
Seems related to the issue InfinityRaider/InfinityLib#8 (with the missing `quadBuilder.setTexture(icon);`), I had similar stacktrace at the time.

**Comment by VindellePounze** [comment]
Just for the sake of it I just tried with only Agricraft and Infinitylib installed. Same result when breaking the analyzer. Using same (latest) forge.

[crash-2016-12-13_11.03.52-client.txt](https://github.com/InfinityRaider/AgriCraft/files/648542/crash-2016-12-13_11.03.52-client.txt)

**Comment by snacdaws** [comment]
glad to know it's not just me


and @InfinityRaider yes it is, tried running my instance multiple times disabling multiple mods but leaving agricraft active and that report is one of them, opened it from the console to make sure it was the right one

**Comment by InfinityRaider** [comment]
Nvm, my mistake, was looking on mobile and i derped

**Comment by InfinityRaider** [comment]
@Volune is right, this is an InfinityLib issue

**Comment by InfinityRaider** [comment]
Moved issue over to InfinityLib tracker: https://github.com/InfinityRaider/InfinityLib/issues/11
