### ISSUE TITLE
[1.10.2] Crash due to Villager Registry

### ISSUE THREAD

**Issue by Viatos** [InfinityRaider/AgriCraft#727]
I keep crashing because apparently a villager is being assigned a profession of "5 null." Here's my log - since no one else has reported this I'm wondering if it might be on my end and if there's something I can do to correct it?

[crash-2016-12-12_20.22.07-server.txt](https://github.com/InfinityRaider/AgriCraft/files/647707/crash-2016-12-12_20.22.07-server.txt)

**Comment by InfinityRaider** [comment]
Has been reported and fixed (#718)
