### ISSUE TITLE
A way to specify number of growth stages?

### ISSUE THREAD

**Issue by renadi** [InfinityRaider/AgriCraft#728]
Is there any way to specify number of growth stages on a plant?  It seems everything is programmed to go through 8 stages from what I can tell, I tried putting less individual texture references and it seemed to loop around in texture, but I don't think it actually worked to slow the growth rate.

**Comment by InfinityRaider** [comment]
Not at the moment, but Im going to move over teh growth stage from meta to a value on the TileEntity anyway.

**Comment by RlonRyan** [comment]
Lol. Thank goodness. Keeping the meta value up to date with the tile entity was getting annoying...

**Comment by RlonRyan** [comment]
The number of growth stages will now be inferred from the number of textures provided in the json descriptor file.
