### ISSUE TITLE
Crashed game while pre-generating world

### ISSUE THREAD

**Issue by CrankyScott** [InfinityRaider/AgriCraft#729]
I added this mod to All the Mods Lite (latest version) and, after disabling railcraft, began pregenerating the world. Saved and quit last night, came home from work today and restarted it and it crashed after ~10 seconds. Had a similar issue on another pack with a different mod.

Here is the crash report: http://pastebin.com/QEGT9j9j

**Comment by InfinityRaider** [comment]
Has been reported and fixed (#718)
