### ISSUE TITLE
[1.10.2] Crash when clicking "Show All Mutations" in JEI

### ISSUE THREAD

**Issue by ElvenChaos** [InfinityRaider/AgriCraft#730]
In JEI, clicking "Show All Mutations" leads to a client crash.
Crash log: http://pastebin.com/tUgDMSWD
agricraft-2.0.0-i0.3.0-a3
MC 1.10.2
Forge 2185
JEI 390

**Comment by RlonRyan** [comment]
There's a show all mutations button?

**Comment by ElvenChaos** [comment]
If you are viewing a certain crafting recipe, you can click the text of the crafting type to view all recipes under that crafting type, which in this case is a Crop Mutation.

**Comment by RlonRyan** [comment]
Does this still occur in the latest releases?
