### ISSUE TITLE
NullPointerException: Tesselating block model (tile.agricraft:crop)

### ISSUE THREAD

**Issue by sab0tic** [InfinityRaider/AgriCraft#732]
This is a clientside crash, happens consistently after getting close to a village with AgriCraft generated structures in it, but did not happen until AgriCraft blocks were chunk loaded.

Crash details are below, full report is attached

> Description: Tesselating block model
> 
> java.lang.NullPointerException: Tesselating block model
> 	at com.infinityraider.infinitylib.render.block.BakedInfBlockModel.func_188616_a(BakedInfBlockModel.java:69)
> 	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:129)
> 	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)
> 	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
> 	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
> 	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
> 	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
> 	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
> 	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
> 	at java.lang.Thread.run(Thread.java:745)

> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at com.infinityraider.infinitylib.render.block.BakedInfBlockModel.func_188616_a(BakedInfBlockModel.java:69)
> 	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:129)
> 	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)
> 
> -- Block model being tesselated --
> Details:
> 	Block: com.infinityraider.infinitylib.block.blockstate.BlockStateWithPos@25da74aa
> 	Block location: World: (2196,63,3605), Chunk: (at 4,3,5 in 137,225; contains blocks 2192,0,3600 to 2207,255,3615), Region: (4,7; contains chunks 128,224 to 159,255, blocks 2048,0,3584 to 2559,255,4095)
> 	Using AO: true
> Stacktrace:
> 	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
> 	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
> 
> -- Block being tesselated --
> Details:
> 	Block type: ID #299 (tile.agricraft:crop // com.infinityraider.agricraft.blocks.BlockCrop)
> 	Block data value: 0 / 0x0 / 0b0000
> 	Block location: World: (2196,63,3605), Chunk: (at 4,3,5 in 137,225; contains blocks 2192,0,3600 to 2207,255,3615), Region: (4,7; contains chunks 128,224 to 159,255, blocks 2048,0,3584 to 2559,255,4095)
> Stacktrace:
> 	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)

[crash-2016-12-15_00.34.58-client.txt](https://github.com/InfinityRaider/AgriCraft/files/653865/crash-2016-12-15_00.34.58-client.txt)

**Comment by ChaosTherum** [comment]
Been having this issue as well but don't know which crash report is related to it. Just figured I would mention that it's more than one person.

**Comment by InfinityRaider** [comment]
First of all, don't just paste entire hunks of text in the issue, use something like pastebin, it keeps the discussion clean and readable.
Second, this is not an Agricraft issue but an InfinityLib issue, so I'm moving this over to the InfinityLib tracker.

Thanks for reporting either way.
