### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by lendrick** [InfinityRaider/AgriCraft#733]
I'm getting random InfinityLib crashes that I suspect are being caused by AgriCraft.  I'm pretty sure I was just standing around when it crashed.  Here's a copy of the error log:

http://pastebin.com/SiUKi4N4

**Comment by InfinityRaider** [comment]
This is an infinitylib issue and has already been reported multiple times:
https://github.com/InfinityRaider/InfinityLib/issues/11
