### ISSUE TITLE
random crash while travelling the world

### ISSUE THREAD

**Issue by Hypsellis** [InfinityRaider/AgriCraft#734]
I get this crash sometimes when I travel the world. The last time I got it I watched an AgriCraft tank. I don't know what cause it. http://pastebin.com/egAPdMuP

**Comment by Serico86** [comment]
i have same problem, I was traveling by boat and the game ended suddenly
the mod is the lib or agricraft
http://pastebin.com/iTjYqmDC

**Comment by InfinityRaider** [comment]
This has been reported multiple times already, check the tracker before you report an issue please.
