### ISSUE TITLE
[1.10.2] Crash when breaking soil

### ISSUE THREAD

**Issue by xSparky911x** [InfinityRaider/AgriCraft#735]
If I break the soil under the crop sticks the game crashes. This was tested in single player (opened to lan) in creative mode.

http://pastebin.com/vzVV2jMD

**Comment by InfinityRaider** [comment]
Please do not directly post logs or crash reports into the tracker, it casues a mess, use something like pastbin instead.

Thanks for reporting, it will be looked into.

**Comment by RlonRyan** [comment]
Fixed by #739.
