### ISSUE TITLE
Resource Crops not placing

### ISSUE THREAD

**Issue by DrSquishie** [InfinityRaider/AgriCraft#736]
So tried to breed the iron crops on farmland with and without iron ore, and tried spawning a seed in and placing it with no luck, checked config and crops are set to true. Using mod on All the mods pack version 1.51 Minecraft 1.10

**Comment by RlonRyan** [comment]
Are you on a server?

What light level are you using?

**Comment by RlonRyan** [comment]
Turns out that this is a JSON issue. There are no valid soils defined for the resource crops, and as such, they cannot be planted. I will define some in the next iteration of the AgriPlants Repo.

**Comment by RlonRyan** [comment]
Ok. The real truth is that it had to do with a bad range check, that would skip the last z layer in a 3d range.

**Comment by RlonRyan** [comment]
Fixed by #739.
