### ISSUE TITLE
Agricraft Nuggets are not OreDict to be used by other Mods (agricraft-2.0.0-i0.3.0-a3)

### ISSUE THREAD

**Issue by Boomflex** [InfinityRaider/AgriCraft#737]
When you create nuggets of any metal (excluding Gold) the nuggets are not able to work with recipes that need them.

For example the iron nuggets can not be used in a recipe as the AgriCraft version is not working with OpenComputers memory/battery and other recipes similar.

Thanks and I hope this makes sense.

**Comment by whatthedrunk** [comment]
All nuggets need to change from nugget_name to nuggetName

**Comment by RlonRyan** [comment]
Yeah I just have to update the name. Thanks for reporting.

**Comment by RlonRyan** [comment]
Fixed by #739.
