### ISSUE TITLE
Crash Upon Trying to Break Channel Blocks on Server

### ISSUE THREAD

**Issue by Rebelyrocks** [InfinityRaider/AgriCraft#738]
[First Crash Client Crash Log](http://pastebin.com/YWfHNhg0)  - Crash when right clicking to place sprinkler on channel
[Second Crash Client Crash Log](http://pastebin.com/vGFtDghL)  - Crash when left clicking channel to break it
[Third Crash Client Crash Log](http://pastebin.com/eeJhwxCK)  - Crash when left clicking tank to break it

Left clicking channels crashes my game, but the server stays running. The water tanks are interactable via right click but crash MC when you left click them like the channels.

**Comment by InfinityRaider** [comment]
Yeh this is an infinitylib issue, tx for reporting, I'm going to move it to the InfinityLib tracker.
It's probably related to the other rendering crashes.

**Comment by RlonRyan** [comment]
Is this still an issue?

**Comment by Rebelyrocks** [comment]
I have not tested it recently. Can not confirm.

**Comment by RlonRyan** [comment]
Seeing as there have been no new reports of this in over 24 days, I am closing the issue as resolved.
