### ISSUE TITLE
Render type "cross" does not function properly

### ISSUE THREAD

**Issue by heatherhaks** [InfinityRaider/AgriCraft#745]
The render type "cross" does not function as intended. It renders still as a hash, and there seems to be some graphical glitching off to the side, as you can see in the screenshot.

![image](https://cloud.githubusercontent.com/assets/24635117/21293675/f09e8cee-c4e8-11e6-9e62-4700fe7047c5.png)

**Comment by InfinityRaider** [comment]
Probably my mistake, thanks for reporting.

**Comment by RlonRyan** [comment]
Yeah... @InfinityRaider you'll have to fix this one. The cross rendering function from the PlantRenderer class is completely wrong atm, and I dunno how to fix it...

**Comment by RlonRyan** [comment]
Fixed as per 2.0.0a6.
