### ISSUE TITLE
Crash while exploring

### ISSUE THREAD

**Issue by SombrioFe** [InfinityRaider/AgriCraft#749]
Crashed while exploring the world.  [Error Report Pastebin](http://pastebin.com/4zVFGT9H)

**Comment by InfinityRaider** [comment]
InfiniytLIb bug, has been reported before.

**Comment by SombrioFe** [comment]
I'm sorry for causing you more work.  I am new to reporting bugs, as I'm a usually a silent user.  I wasn't aware what caused the issue, and just wanted to help.

**Comment by InfinityRaider** [comment]
Np, just check the tracker, its pointless to report issues which have been reported before :)
