### ISSUE TITLE
Crops grow with no water

### ISSUE THREAD

**Issue by MrSapient** [InfinityRaider/AgriCraft#75]
As title says the crops will grow without any water.

https://i.imgur.com/WNWilOk.png

The Water tank has no water in it.

**Comment by InfinityRaider** [comment]
Does the farmland not dry out wihtout sprinkling it or having a water source nearby?

**Comment by MrSapient** [comment]
I never watered them at all.. just made farm land and put the sticks and crop in ..

**Comment by MrSapient** [comment]
Also new thing i found is when i right click on them it will harvest them and i never get seeds just the item i planted.

**Comment by InfinityRaider** [comment]
Thats quite strange. And yes you're not supposed to get seed when harvesting

**Comment by kc7zzv** [comment]
@MrSapient 
> I never watered them at all.. just made farm land and put the sticks and crop in ..

Is there any chance that it rained after you tilled the ground?

**Comment by ate0ate** [comment]
With the right clicking, are you using ttCore or Ender Core by any chance? They modify that.

**Comment by InfinityRaider** [comment]
I haven't looked much at this, but since this is so old, the codebase has almost entirely changed. If this is stilla problem, feel free to make a new issue.
