### ISSUE TITLE
JSON Greenhouse Structures

### ISSUE THREAD

**Issue by RlonRyan** [InfinityRaider/AgriCraft#752]
Currently AgriCraft uses two massive and utterly confusing java files to represent the greenhouse structures. This is not an optimal way of doing things, and is subject to breaking with minor changes in minecraft versions. As such we should use JSON files to represent the village structures, considering as they are more data-oriented and version independent, and there likely exists some tool already to create them.

**Note:** The trick here would be randomizing the plants that are found in the crops, so that village greenhouses aren't just massive weed farms.

**Comment by TehNut** [comment]
Why not the vanilla structure format?

**Comment by InfinityRaider** [comment]
Because if they update their system,

**Comment by TehNut** [comment]
Vanilla doesn't break backwards compatible with their own stuff besides the registry changes (which only affect command blocks). I doubt they would break it for this.

**Comment by InfinityRaider** [comment]
Like when they overhauled their rendering? Or swapped integer ids for strings? Or with the loottables? Or...

**Comment by TehNut** [comment]
All vanilla things moved forward without issue. If the structure format changes (which I doubt it will as it is properly written) there will be tools to move it over. The format is also easily parsable by hand.

**Comment by RlonRyan** [comment]
Closed so that may focus on other issues for now.

Plus I have no idea as how to even go about doing this...
