### ISSUE TITLE
[1.10.2] Pam's HC Seed Mutations

### ISSUE THREAD

**Issue by addrever** [InfinityRaider/AgriCraft#755]
Hello,

I am currently using version 2.0.0-i0.3.0-a3 with Pam's HC 1.9.4-1.10.2h.  I load up the game but there isn't any mutations for Pam's.  As per documentation it specifies that there are default mutations for HC.  Is there a download that I need to get in order to facilitate them?

> Currently there are default mutations for: Vanilla, AgriCraft, Pam's Harvestcraft, Natura, Plant Mega Pack and Pam's Weee Flowers.

Please let me know.  I have attached the logs and config files.

[config.zip](https://github.com/InfinityRaider/AgriCraft/files/665103/config.zip)
[2016-12-20-7.log.gz](https://github.com/InfinityRaider/AgriCraft/files/665108/2016-12-20-7.log.gz)

**Comment by addrever** [comment]
Helps if I read.  That was for older versions of Agricraft.  Sorry about that.

Is there default Pam's JSONs for 1.10.2 or do we have to generate them manually?

**Comment by RlonRyan** [comment]
Someone has to write a default Pam's JSONs, and then we could add them here: [AgriPlants Repo](https://github.com/AgriCraft/AgriPlants). The main issue is that due to the customizability of the JSON system, there is a lot of information to add, so that myself and InfinityRaider haven't the time to go through it all. You are welcome to contribute it though!

**Comment by addrever** [comment]
I'll give it a whirl.

**Comment by Intrebute** [comment]
Is there anywhere we can find what mutations had been added for this in older versions, other than installing the mod for 1.7.10 and going through NEI taking note of each and every mutation?

**Comment by addrever** [comment]
I have created most of the mutations, but I am having an issue with the flower seeds.  They seem to be missing in this version.  I have attached the logs for your review as well as a zip of my json files.

Cheers

[agricraft.zip](https://github.com/InfinityRaider/AgriCraft/files/670294/agricraft.zip)
[fml-client-latest.txt](https://github.com/InfinityRaider/AgriCraft/files/670295/fml-client-latest.txt)

**Comment by addrever** [comment]
Any updates?

**Comment by RlonRyan** [comment]
Sorry busy time of year. Still have to look further into it.

**Comment by shadetree4hire** [comment]
I made changes to you're config files. I had to change the recipes that included flower seeds, since they are not included in the mod as of now. I used soybean instead. They seem to work for me. Let me know if I missed one.

[agricraft.zip](https://github.com/InfinityRaider/AgriCraft/files/680366/agricraft.zip)

**Comment by sperly** [comment]
Great, you fixed the missing curly brackets as well!
Seems to work great now.

**Comment by addrever** [comment]
Thank you!

**Comment by shadetree4hire** [comment]
I fixed the growth stages of the crops. 
[harvestcraft.zip](https://github.com/InfinityRaider/AgriCraft/files/691883/harvestcraft.zip)

**Comment by renadi** [comment]
Shadetree4hire you mind if I use this config in my pack?

**Comment by shadetree4hire** [comment]
I don't think that I have the right to say yes or no. Any permission you need from me is granted. Hope it helps.

**Comment by RlonRyan** [comment]
The files look good, but I just have to implement a method so that the JSON loader doesn't freak out if a mod isn't present, and just ignores the files instead.

**Comment by RlonRyan** [comment]
Thank you very much for your help! I have added your HarvesCraft JSON files as the defaults in [AgriPlants](https://github.com/AgriCraft/AgriPlants)!
