### ISSUE TITLE
A few problems with (primarily) crop sticks

### ISSUE THREAD

**Issue by Tannex** [InfinityRaider/AgriCraft#757]
I installed the version from curse forge: **agricraft-2.0.0-i0.3.0-a3** to the direwolf20 1.10.2 pack (FTB), and encountered a few problems:
- [x] The journal was uncraftable since it required turnip seeds from biomes o' plenty, but i was running default world gen.
- [x] ~~Seeds planted on crop sticks will not grow passively, or by means of extrautils2 watering can / Not enough wands Acceleration Wand, they can however be grown using bone meal.~~ (Duplicate issue)
- [x] ~~Bone meal can be used on empty crop sticks, both single and crossed.~~ (Not going to change)
- [x] ~~Seeds are not used when planting on crop sticks~~ (Duplicate issue)
- [x] Using the same seed on crop sticks, then breaking them **will** dupe the seeds, however even with identical stats. these seeds go somewhat evenly into two stacks (What does this mean?)

I cannot say for sure if this behaviour is a side effect of some other mod in the pack, however i thought i would report them here regardless.

Best, Tannex

Edit: using **infinitylib-0.3.0**

**Comment by RlonRyan** [comment]
Thanks for reporting in the issue tracker. Please do check pre-existing issues to check if they are not duplicates.

**Comment by Tannex** [comment]
Yes, sorry. I should be able to clarify the last one with a video later today, as I am not at my computer right now.

**Comment by RlonRyan** [comment]
Oh yeah... they were getting growth stages attached to them. I resolved this, but it wasn't reported in the issue tracker until now.

**Comment by RlonRyan** [comment]
I'm pretty sure this was resolved in a5? Can you please confirm?
