### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by knoxhack** [InfinityRaider/AgriCraft#758]
Modpack: Project Ultimate

Server: MMD Public Server

Related Links:
https://minecraft.curseforge.com/projects/mmd-project-ultimate
https://github.com/MinecraftModDevelopment/Project-Ultimate/issues

Crash Report:
https://gist.github.com/knoxhack/6e20ce57675af1071109da36d37b8a9a

**Comment by InfinityRaider** [comment]
No point in reporting an issue on two trackers, this is an InfinityLib issue and has been reported.
