### ISSUE TITLE
MineTweaker Integration Error

### ISSUE THREAD

**Issue by WitherBlaster** [InfinityRaider/AgriCraft#759]
I've been trying to use MineTweaker to change some AgriCraft 'recipes', but nothing I've done worked. I'm hoping someone here can help me figure out what I'm doing wrong.

This is the error I'm getting.
`ERROR: Error parsing AgriCraft Custom Base Blocks.zs:3 -- ; expected`

Here's my script.
```
import mods.agricraft.growing.BaseBlock;

BaseBlock.clear(<AgriCraft:seedTaintedRoot>);
```

**Comment by RlonRyan** [comment]
What version of AgriCraft are we talking about here?

**Comment by WitherBlaster** [comment]
1.5.0

**Comment by RlonRyan** [comment]
Well, I have no idea how to use minetweaker, and we have been phasing out the 1.7.10 issues so we can focus on the 1.10 release, given that the versions of the mod are drastically different internally.
