### ISSUE TITLE
Tanks crossing chunk boundaries glitch out

### ISSUE THREAD

**Issue by InfinityRaider** [InfinityRaider/AgriCraft#76]
When part of a tank is in a loaded chunk and another part is in an unloaded one weird stuff can happen

**Comment by marcin212** [comment]
Maybe repository: https://github.com/erogenousbeef/BeefCore will be helpful.

**Comment by InfinityRaider** [comment]
Thanks I will check it out.

**Comment by InfinityRaider** [comment]
After rewriting tanks for performance reasons I haven't been able to duplicate this.
