### ISSUE TITLE
Breaking the seed analiser crashes

### ISSUE THREAD

**Issue by MichaelHillcox** [InfinityRaider/AgriCraft#760]
[Crash log here](https://hastebin.com/sipegulibu.swift)

When you hit the seed analiser the game will crash because of the breaking render ( I think )

**Comment by RlonRyan** [comment]
It looks like it's that dang InfinityLib issue again, @InfinityRaider...

**Comment by RlonRyan** [comment]
Unless... Do you have foamfix installed?

**Comment by InfinityRaider** [comment]
Has been fixed
