### ISSUE TITLE
[Question]Turn off Weed

### ISSUE THREAD

**Issue by Venom1987** [InfinityRaider/AgriCraft#761]
I dont know if i'm simply too dump or i cant turn it off...or am i overseeing something?
![image](https://cloud.githubusercontent.com/assets/7864301/21481647/6c441e68-cb6a-11e6-887a-d1ab4cb4257c.png)

**Comment by InfinityRaider** [comment]
The enabled flag doesnt work atm, simply delete the file for now, should work.

**Comment by Venom1987** [comment]
Did not work...the file reappeared. =(

**Comment by InfinityRaider** [comment]
What is the "Enable JSON Writeback"-setting set to in the config?

**Comment by Venom1987** [comment]
ok...that option fixed it. thank's a ton ;) thumbs up for the mod  ;)
