### ISSUE TITLE
java.lang.IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by Hypsellis** [InfinityRaider/AgriCraft#765]
I started to get this crash recently when travelling or loading a world. I haven't any ideas which mod provocate it. A lot of mods seem to be involved. http://pastebin.com/DJWL1D3W

**Comment by InfinityRaider** [comment]
Thanks for reporting, I might not have implemented the new villager profession system correctly, going to have to look into it.

**Comment by Hypsellis** [comment]
I got a shorter version of the crash, maybe more readable http://pastebin.com/vfNdY299

**Comment by InfinityRaider** [comment]
Has been fixed
