### ISSUE TITLE
Seed Analyzer

### ISSUE THREAD

**Issue by jamesfhj** [InfinityRaider/AgriCraft#767]
I accidentally posted this on InfinityLib Github, because I'm dub. Moving it here. 

So, I grabbed the newest version of Agricraft (2.0.0-0.4.0-a5) and Infinitylib (0.4.0). The cropsticks no longer crash my game, which is awesome. However, now the Seed Analyzer doesn't work. I can't put seeds in it at all. For clarification, I've only tried regular old Seeds that you get from breaking tall grass. I also can't seem to plant those seeds with the cropsticks either. I can place the cropsticks, but not with seeds. I've tried placing the cropsticks, then the seeds, as well as placing seeds then cropsticks.

Second issue, the book has no recipe on JEI. Not sure if you do that on your end, or if I should hit up the JEI folks for that one.

**Comment by heatherhaks** [comment]
I was unable to replicate your issue with the analyzer. I've tested the wheat seeds and custom seeds I have made, along with several 'generations' of seeds (meaning different levels of stats) and they all work fine. Based on your other symptoms I think perhaps you have the old plant json files. Please try exiting your game, deleting the json files that autogenerated with the previous version, and reloading your game.

**Comment by jamesfhj** [comment]
That worked. Thank you very very strawberry much.

... Sorry. I'm a dork...
