### ISSUE TITLE
crash: Exception ticking world

### ISSUE THREAD

**Issue by smenes** [InfinityRaider/AgriCraft#772]
Hi

http://pastebin.com/raw/ypd2qK8x

good luck !

**Comment by RlonRyan** [comment]
Infinitylib issue. It would appear that infinitylib is passing down null tags, which it isn't supposed to do.

@InfinityRaider, I'll leave you this one.

**Comment by InfinityRaider** [comment]
Has been fixed in a recent commit, I discovered this indev before anyone reported it.

**Comment by RlonRyan** [comment]
Good job then, @InfinityRaider!
