### ISSUE TITLE
Questions on custom seeds and plants

### ISSUE THREAD

**Issue by xenoflot** [InfinityRaider/AgriCraft#773]
Hi,

I'd like to add custom seeds and plants to my 1.10 modpack (Copper, Tin, etc.) I have downloaded AgSkies2 which includes all the configs and textures from 1.7 and I've been doing some snooping.

* In the 1.10 json files, it's asking for names like minecraft:gold_nugget and minecraft:gold_ore. If I wanted to create a Cuprosia plant, can I use oredict names like ore:nuggetCopper and ore:oreCopper?

* Copying textures and models from the 1.7 zip (into the 1.10 zip) isn't going to work, is it? Due to the new blockstates etc.

**Comment by RlonRyan** [comment]
Ore dictionary names don't work, as they don't always reference items nicely.

The old custom crops won't work, without modification.
