### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Snipe13051** [InfinityRaider/AgriCraft#774]
Check here:

[Minecraft Forum](http://www.minecraftforum.net/forums/support/modded-client-support/2778061-1-10-2-self-modded-crash-exception-in-server-tick#c2)

[Hastebin](https://hastebin.com/qukatufazo.sql)

Thanks

**Comment by RlonRyan** [comment]
This is a greenhouse generation issue it looks.

**Comment by InfinityRaider** [comment]
It seems to be something returning null from our villager.
I've tried to look at the Dynamic Surroundings source to see what exactly, but the code on the repo does not match the stacktrace.

**Comment by RlonRyan** [comment]
How odd...

**Comment by RlonRyan** [comment]
Feels like more of a dynamic surroundings issue to me...

**Comment by RlonRyan** [comment]
Yeah pretty sure that this is a dynamic surrounding issue to me. Please report this to them. If they disagree then I can reopen this issue and look into it further, but for now we have other things to focus on.
