### ISSUE TITLE
[1.10.2] Stats switching place

### ISSUE THREAD

**Issue by sperly** [InfinityRaider/AgriCraft#779]
On 2.0.0-0.4.0-a5, When I plant a seed with for example: 
* Growth: 5
* Gain: 3
* Strength: 1

it will be 3/5/1 when planted and if I break it it will still be 3/5/1.
If I plant it again it will switch once more to the original values.

**Comment by RlonRyan** [comment]
Dang. That was probably my fault. The words both start with the same letter making them easy to mix up. Sounds like it is probably an nbt transcription issue.

**Comment by InfinityRaider** [comment]
Good find though, thanks for reporting.
