### ISSUE TITLE
Melon Texture looks like Wheat

### ISSUE THREAD

**Issue by CamaroKing59** [InfinityRaider/AgriCraft#782]
https://gyazo.com/6cc8b8105f46ce115c1c7e79b905d357

**Comment by RlonRyan** [comment]
Please post your version, and melon plant JSON descriptor file.

**Comment by InfinityRaider** [comment]
Gourd renderer isnt implemented yet (pumpkins, melons, etc), so i think i set it to render wheat instead, im not sure though.

**Comment by RlonRyan** [comment]
That might be it...

**Comment by RlonRyan** [comment]
Fixed, the textures weren't set in the bundled jsons, so that they defaulted to wheat. The bundled jsons have been updated.

**Comment by CamaroKing59** [comment]
ok is there going to be an update for it soon? no rush just curious
