### ISSUE TITLE
Feature Request: Native Mass Harvesting

### ISSUE THREAD

**Issue by Voxel-Friend** [InfinityRaider/AgriCraft#784]
When using Agricraft in the past, I would create very large farms, utilizing crops from Pam's HC. I would however have to harvest using a different mod such as Ender IO with an addon to THAT to support Agricraft. A native way to make harvesting easier would be nice, be it a scythe like tool that harvests in a radius, a block that requires Forge-Energy/Coal/Time/Etc, or some other way. plus it would incentivize the creation of larger farms, and thus requiring an irrigation system that your mod so conveniently provides.

**Comment by InfinityRaider** [comment]
The point of agricraft is that you can improve youor crops as to not create huge fields.
Incentivizing massive automated agricraft farms is incentivizing lag.

**Comment by Voxel-Friend** [comment]
Hmrm. Very true. How silly of me. Thank you for your time.
