### ISSUE TITLE
java.lang.NoSuchFieldError: plant

### ISSUE THREAD

**Issue by Ryahn** [InfinityRaider/AgriCraft#786]
Hello,

We have a few users within our mod pack who will experience this crash randomly. I have replicated it myself by just using AgriCraft and playing for a few hours. Once it happens, you will not be able to use that save again.

Crash - https://gist.github.com/Ryahn/a0207b73a5e557e809711b41b4c742fc

**Comment by RlonRyan** [comment]
Fixed by switch to JSONs in 2.0.0.
