### ISSUE TITLE
[1.10.2] Tesselating block model (NPE)

### ISSUE THREAD

**Issue by SnowShock35** [InfinityRaider/AgriCraft#788]
### Important Info

- Minecraft 1.10.2
- Minecraft Forge 12.18.3.2185
- AgriCraft 2.0.0.0.4.0-a5
- InfinityLib 1.10.2-0.4.0

### Issue Description

While breaking an agricraft multi-block tank found in a village the game crashed to desktop. Unsure whether a rare edge case scenario or a consistent bug.

### Issue Media

http://pastebin.com/eAn0B0Af

**Comment by InfinityRaider** [comment]
This is an InfinityLib issue, it has already been reported multiple times on both issue trackers.
