### ISSUE TITLE
Server/Client crash when placing down Grate.

### ISSUE THREAD

**Issue by harry2258** [InfinityRaider/AgriCraft#790]
Recreate/Issues: 
- Server crashes when someone places down a grate.
- Client crashes when it tries to render the item.

Server Log: http://pastebin.com/9ggafSNn
Client Log: http://pastebin.com/5PjBGGq4 (Was running FoamFix Anarchy Edition. Retried with Lawful edition and still caused the crash.)

**Comment by InfinityRaider** [comment]
already fixed in dev.
