### ISSUE TITLE
Fonte Size Issue - 1.7.10

### ISSUE THREAD

**Issue by chaos234** [InfinityRaider/AgriCraft#792]
![2017-01-14_04 00 29](https://cloud.githubusercontent.com/assets/340106/21951826/1d3125de-da0e-11e6-87aa-4737ac9931b2.png)

Like the image above I can't prove any fix for #543 or better it is still such a small font which is inacabtable.
Normaly the font from the vanilla mc or from the RP should be used where the text should be defined in a language variable and then displayed with the current used font.

So please fix this since it is not readable because it is to small and no, optifine is not the problem since it is with and without it like the image above :(

EDIT: GUI Scale: Normal

Cheers

**Comment by RlonRyan** [comment]
Sorry, we know that that is an issue, but given that the port to 1.10 is quite involved we have dropped 1.7.10 support to focus solely on the port. Pr's fixing issues in 1.7.10 are welcome at all times though.
