### ISSUE TITLE
Just updated Agricraft and InfinityLib rendering crash

### ISSUE THREAD

**Issue by CamaroKing59** [InfinityRaider/AgriCraft#798]
http://pastebin.com/XAEj2ABV

**Comment by MokahTGS** [comment]
Not sure if this is the same crash, but sounds similar:

http://pastebin.com/ZTYVBrGa

**Comment by RlonRyan** [comment]
Duplicate #770. Your issue is a different one though @MokahTGS. If you'd please open a new issue with just that log, it would be greatly appreciated.
