### ISSUE TITLE
Agricraft/InifinityLib dependency

### ISSUE THREAD

**Issue by Cobra1117** [InfinityRaider/AgriCraft#799]
Very minor issue: Agricraft 2.0.0-0.5.0-a6 has a dependency on InfinityLib 0.5.0, but having the wrong version does not cause the game to fail to start (it dies at runtime when starting a world). Presumably the metadata for Agricraft needs to be updated to reflect the new dependency.

**Comment by RlonRyan** [comment]
Fixed, thank you!
