### ISSUE TITLE
Crop Stick Crops not Stacking with Regular Crops

### ISSUE THREAD

**Issue by MokahTGS** [InfinityRaider/AgriCraft#800]
Harvesting crops from regularly planted (vanilla) crops do not stack with crops harvested from Agricraft crop sticks.  This seems like the NBT data isn't the same.

**Comment by Ravin890** [comment]
I can confirm what Mokah said.
When you harvest the agricraft stuff they get a '0 nbt tag' tag unlike normal crops.

**Comment by RlonRyan** [comment]
I'm kinda not sure I want to fix this, given that it adds a little more complexity to the mod, but I suppose I can...

**Comment by RlonRyan** [comment]
Fixed.

**Comment by RlonRyan** [comment]
@InfinityRaider This one's up to you...

**Comment by RlonRyan** [comment]
This is the same issue as #848, while this one was reported first, the documentation of #848 is better so that this report is getting marked as the duplicate.
