### ISSUE TITLE
Harvesting Weeds

### ISSUE THREAD

**Issue by Ravin890** [InfinityRaider/AgriCraft#802]
When you harvest weeds, it may drop something like grass or fern, but you can't pick it up for some reason.

**Comment by RlonRyan** [comment]
Sounds like a client/server desync, wherin the client is dropping something for the plants that the server isn't.

**Comment by RlonRyan** [comment]
What version are you running, and what is your weed_plant.json file?

**Comment by RlonRyan** [comment]
Any updates on this issue? Is it still occurring in the latest versions?

**Comment by Ravin890** [comment]
kinda forgot about this, let me check with a10

**Comment by Ravin890** [comment]
With version a10, it does still occur. I also didn't touch the weed plant file, so that is default. If you want I can send you the file either way. Also infinitylib is the latest (0.6.2) and its running on single player.

**Comment by RlonRyan** [comment]
Ok that's all I needed thanks!

**Comment by RlonRyan** [comment]
Consolidated to #863.
