### ISSUE TITLE
Weeds and Seed Analyzer

### ISSUE THREAD

**Issue by Ravin890** [InfinityRaider/AgriCraft#803]
For some reason, if you right click on weeds with the seed analyzer the weeds will disappear. Hoe is also the same, but not sure if that was intended or not.

**Comment by RlonRyan** [comment]
Probably just the hand rake setting messing up.

**Comment by RlonRyan** [comment]
Same as #802 probably.

**Comment by RlonRyan** [comment]
Consolidated to #863.
