### ISSUE TITLE
Can't place crop sticks on farmland

### ISSUE THREAD

**Issue by theCorvid** [InfinityRaider/AgriCraft#805]
After updating to the latest version of Agricraft (0.5.0-a6), all existing crops in the world disappeared, and new crop sticks crafted won't place into farmland, or anywhere else.

**Comment by QuantumWraith** [comment]
I'm having the same issue. Can't place crop sticks on wet farmland. They do place on dry farmland, however. Care to post your modlist?

**Comment by RlonRyan** [comment]
Try deleting the config/AgriCraft/JSON/default directory and letting it regenerate.

**Comment by QuantumWraith** [comment]
Fixed it for me, thanks :)

**Comment by RlonRyan** [comment]
I think that it's probably just out-of-date JSONs, so I am closing this issue.

**Comment by RlonRyan** [comment]
(It's more impressive that the mod doesn't crash with out-of-date jsons than anything...)
