### ISSUE TITLE
Village Greenhouses Generate Poorly

### ISSUE THREAD

**Issue by Exsolutus** [InfinityRaider/AgriCraft#807]
I came across this problem recently while working on my modpack for 1.10.2. Generation of greenhouse structures in villages seems to have been terribly broken. Firstly, I have yet to find one which contained crops. Secondly, the buildings themselves are more often than not deformed, as if multiple generation passes have occurred or the generation was cut part way. Some are missing walls and features, others have too many walls/features. Additionally, none of the torches place properly, ending up as items all over the ground.

A few example images:
![greenhouse1](https://cloud.githubusercontent.com/assets/23705866/22168770/0cfb73b6-df3d-11e6-98a9-1fd46acc937e.png)
![greenhouse2](https://cloud.githubusercontent.com/assets/23705866/22168775/0fd3ffa4-df3d-11e6-8670-9b5408b3d0ed.png)
![greenhouse3](https://cloud.githubusercontent.com/assets/23705866/22168777/10e54fba-df3d-11e6-9a10-ede87b58b4c0.png)

**Comment by quantumtweaker** [comment]
Ive seen this aswell in my worlds. The building is messed up but the water tank and irrigation channels seem to be fine.

**Comment by RlonRyan** [comment]
I am consolidating this issue with #752, as the resolution of that issue would resolve this one incidentally.
