### ISSUE TITLE
Argicraft + Spongeforge java.lang.NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by BiohazardStuff** [InfinityRaider/AgriCraft#809]
I'm getting a crash on my server running sponge when it starts to rain. 
Since it appears to be related to tanks I should note that I have set B:"Enable Irrigation" to false in the config as an attempt to fix this without disabling the entire mod. 
I also have forge set to automatically remove any erroring tile entities and entities but the server still crashes.

Log: https://pastebin.com/M5R5Eaft
Versions:
- Forge: 12.18.3.2221
- Sponge: 5.1.0-BETA-2056
- Agricraft: 2.0.0-0.5.0-a6
- InfinityLib: 0.5.0

**Comment by RlonRyan** [comment]
Should be fixed.
