### ISSUE TITLE
1/1/1 seed + 10/10/10 sugar cane = 6/6/6 seed even though no mutation between those seeds

### ISSUE THREAD

**Issue by Amadeus99** [InfinityRaider/AgriCraft#81]
Sorry, couldn't think of a decent title.

If the following is intentional, please just close this.

You can put down a 1/1/1 whatever seed crop and a 10/10/10 sugar cane crop with a cross crop in between and you will get a new seed of the same type of the whatever seed crop that is 6/6/6.  (those stats could obviously vary, but that is what I got)  In other words, new seeds inherit stats from all crops around them even if they are not a mutation of those crops.  This allows you to improve the stats very quickly on 1/1/1 seeds.  Sugar cane is just one of the easiest to do this with since it won't cross breed on non-sand.

This may not matter too much with default seeds since the smart method is to improve seeds to 10/10/10 before cross breeding them so that the child mutations are 10/10/10 as well. (unless that was not intended)  However, with modpacks that modify things like Regrowth, players can only get 1/1/1 magical crop seeds and then have to work on improving them.  Using the above method, they can improve a 1/1/1 seed to a 10/10/10 seed in ~4 generations.  2 generations is possible if you surround the cross crop with sugar cane on 3 sides.  I went from a 1/1/1 to a 9/9/9 in one generation when I tried that.

It just seems like this is a cheap way to improve crops from 1/1/1 to 10/10/10 with little effort.

**Comment by InfinityRaider** [comment]
Good point, I might need to look into the math on this and give lower stats a higher weight

**Comment by Imasius** [comment]
What if crops only consider the stats the neighbours of

* the same seed type when spreading?
* the parent seeds type when mutating?

We still could use this as the "base" stats and include the stats of different type neighbour seeds in a scaled down fashion so they have less impact than their "natural" type neighbour seeds (same or parent).

**Comment by InfinityRaider** [comment]
I like that, but I'd make it even more severe, neighbours that aren't parents or the same seed affect the stat gain in a negative fashion

**Comment by Belgabor** [comment]
I would suggest making this a config option because it can make the process a lot more grindy if you are dealing with a pack with lots of crops.

You could also consider having an intermediate option, taking stats only works if the plants are compatible (aka have the same growth conditions). That at least adds the "risk" of the wrong plant spreading.

**Comment by InfinityRaider** [comment]
There will be config options, don't worry.

**Comment by InfinityRaider** [comment]
Beta with this is on CurseForge
