### ISSUE TITLE
Other Mod Compatability

### ISSUE THREAD

**Issue by MokahTGS** [InfinityRaider/AgriCraft#810]
What needs to be done to add compatibility with other mods such as Magical Agriculture and Immersive Engineering?  I see Harvestcraft got added in in the latest update and I was wondering if it is as simple as adding a JSON file for each mod?

Can others do that and give it to you to integrate?

**Comment by RlonRyan** [comment]
Yup! Whomever produces a working set of JSONs for a mod is encouraged to submit them to make them the default set of JSONs for compatibility with that mod! The repo for all the JSON files is located here: [AgriPlants Repo](https://github.com/AgriCraft/AgriPlants).
