### ISSUE TITLE
Breeder cropsticks not using items

### ISSUE THREAD

**Issue by Tukanen** [InfinityRaider/AgriCraft#811]
agricraft-2.0.0-0.6.0-a9

When making the crossed cropsticks it doesn't take the cropsticks from the inventory, but breaking them still gives back two items, effectively giving you and endless supply of cropsticks for free.

**Comment by RlonRyan** [comment]
Well, at least it ain't diamonds. Still, good catch, thanks for reporting.

**Comment by RlonRyan** [comment]
Fixed!
