### ISSUE TITLE
Beetroots?

### ISSUE THREAD

**Issue by Tukanen** [InfinityRaider/AgriCraft#812]
agricraft-2.0.0-0.6.0-a9

They don't seem to be usable on cropsticks, or indeed as parents or mutations. Are there plans to include these?

**Comment by InjuredWolf** [comment]
You can make them useable on crop sticks if you make your own JSON file for them, but as far as mutations go, wait for dev to push an update, I'd say.

**Comment by RlonRyan** [comment]
You can even make your own mutations if you'd so like, both plants and mutations are done by JSON files.

**Comment by InjuredWolf** [comment]
Yeah, but what are the dev's plans for the mutations? Or are there none?

**Comment by RlonRyan** [comment]
I fail to understand what you are asking, given that last I checked, I am a dev and mutation JSONs have been implemented in every 1.10.2 alpha release of AgriCraft.

**Comment by InjuredWolf** [comment]
I mean what are the plans for the default mutations (like the carrot default with potatoes and wheat, etc.) Are there any plans regarding that?

**Comment by InjuredWolf** [comment]
Also, beetroot JSON that I use: http://pastebin.com/zj1JGUzj

**Comment by VT-14** [comment]
I think GitHub has:
Owners -> Created that Git
Collaborators -> additional Developers
Contributors -> Outside people who have contributed (like pull requests)

**Comment by InjuredWolf** [comment]
Cheers. makes more sense now.

**Comment by RlonRyan** [comment]
I'll add them as plants to the default set. Incorporating them into the default mutation tree will come later.
