### ISSUE TITLE
Request: Vertical / Step decrease in irrigation channels.

### ISSUE THREAD

**Issue by dragonpc75** [InfinityRaider/AgriCraft#817]
I was wondering if this has ever been mentioned, but is there a way of going from Higher ground to lower ground with these irrigation channels? cause i have tried several times to try and get it to go down a step but to no avail. if this could be Implemented as a request or something that you can go gradually down a step every couple blocks at least or a strait vertical drop through some sort of tube or something that would Help Immensely!

**Comment by RlonRyan** [comment]
This is already possible with wooden tanks. Simply build a multi-layer tank to connect the two levels of pipes.
