### ISSUE TITLE
[1.10.2] Render crash with water tanks

### ISSUE THREAD

**Issue by Tencao** [InfinityRaider/AgriCraft#818]
https://paste.ee/r/zGTRj

More information - This happened when I encountered a village generated by the world, not by placing the blocks directly in the world.

**Comment by Waisse** [comment]
Got the same issue. New world, find a village with agricraft house, game freeze for several minutes, CPU load goes to 100%.
First time I got a crash, second time the game just froze forever.
https://paste.ee/p/Vkr6q

**Comment by jaquadro** [comment]
I've also got this crash a couple times, but not from nearby villages.  I just have a few crop sticks placed with some wheat or weeds growing in them, and a nearby seed analyzer.

I'm not 100% convinced it's AgriCraft's fault -- I've also had Bibliocraft crash out in similar fashion, but there might be some unexpected data that needs to be guarded against in the render pipe.

https://paste.ee/p/ZkbVt

**Comment by RlonRyan** [comment]
This appears to be the same as #770, so I am closing this issue in favor of consolidation.

Somehow it seems like despite how many null checks I add, the issue remains.

I wonder... could it be an issue with threading?
