### ISSUE TITLE
Missing Nether Wart JSON File

### ISSUE THREAD

**Issue by XisplayA** [InfinityRaider/AgriCraft#819]
When I try to put them on a crops, nothing happens
pic: http://imgur.com/mQtucgc

**Comment by InjuredWolf** [comment]
They probably don't have the JSON file set up for them. You'll have to create it. Apparently there isn't one for it by default. Basically just copy the wheat one, change the textures (make sure you match the number of stages nether wart has), change the soil (soul sand is a pre-defined soil) and set the seed item and drop. Should help.

**Comment by XisplayA** [comment]
Can u write code for nether wart ?

**Comment by RlonRyan** [comment]
Yeah... I must have missed creating a JSON file for nether wart in the port.

**Comment by RlonRyan** [comment]
I added a default JSON for nether wart.
