### ISSUE TITLE
Seed Stat degrades

### ISSUE THREAD

**Issue by roboliutas** [InfinityRaider/AgriCraft#82]
Basically plated a sugarcane 4/4/4 on sand, places double crops next to it and got after a while a 2/2/2, tested a few times with it - same result, tried to do it with the 2/2/2 - 1/1/1 came out

Version : Agricraft 1.3.0alpha1

**Comment by InfinityRaider** [comment]
Only one crosscrop next to a crop?

**Comment by thephoenixlodge** [comment]
Just a guess, but I'm guessing this new config option:    
 # On a mutation the stats on the crop will be divided by this number [range: 1 ~ 3, default: 2]
    I:"Crop stat divisor"=2
is probably unintentionally taking effect on spreading instead of only on the intended mutation.

**Comment by roboliutas** [comment]
Yes only one crosscrop

**Comment by InfinityRaider** [comment]
Yes it is like @thephoenixlodge said, I added in a divisor on mutations, however sometimes it seems to divide when it didn't mutate.
