### ISSUE TITLE
Possible issue with seed items

### ISSUE THREAD

**Issue by heatherhaks** [InfinityRaider/AgriCraft#820]
I've been unable to get someone else to confirm it's an issue and not user error on my part, but in trying to get a custom crop set up for Mystical Agriculture, I've run into an issue where I am unable to use the Inferior Inferium Seeds item and Agricraft instead creates a seed item itself. I suspect it has to do with the way Mystical Agriculture names its items, 'tier1_inferium_seeds', it has not just a number but also a second underscore. My guess is perhaps the second underscore is causing the issue?

Attached is a pastebin of my custom plant json, as well as a screenshot showing the seed item details in the game.

http://pastebin.com/YrSDYbSd

![image](https://cloud.githubusercontent.com/assets/24635117/22402424/5973c794-e5b3-11e6-9495-e63fba02714d.png)

**Comment by InjuredWolf** [comment]
Try clearing the seed name? I made beetroot work without adding a string to the seed name. ¯\_(ツ)_/¯

This is what it looks like: http://pastebin.com/zj1JGUzj
Dunno if that will help.

**Comment by InjuredWolf** [comment]
One last thing, what is your JSON file for it called?

**Comment by heatherhaks** [comment]
Tried that. It simply creates a blank-named auto-generated seed.

**Comment by heatherhaks** [comment]
it's called tone_plant.json just like it says in the pastebin

**Comment by InjuredWolf** [comment]
huh. No idea then. Wait for a dev response, I guess.

**Comment by heatherhaks** [comment]
It's nothing like that. The crop itself works, it's just that it doesn't use my specified seed item and instead uses an auto-generated seed. Other custom crops I have made do not have this issue.

**Comment by InjuredWolf** [comment]
dunno then. just copy your other JSONs and edit that with the relevant files, but other than that I have no idea.

**Comment by RlonRyan** [comment]
I doubt that it is the extra underscores. I'd have to look into it more in depth. It might have something to do with the item validation step.

**Comment by RlonRyan** [comment]
What's printing out in the log files? The validator should be sending error messages to the log if something doesn't validate properly.

**Comment by Ravin890** [comment]
Somehow I managed to get my attempt for the inferium seed to work, how is still the question.

**Comment by RlonRyan** [comment]
This might be fixed in a11... will need testing.

**Comment by RlonRyan** [comment]
I'm just going to merge this with #838...

**Comment by killerkitt** [comment]
@Ravin890 may i see the code for your inferium seed?

**Comment by Ravin890** [comment]
its actually same as OP but i am using the resource folder as my path so "resource/plants/inferium_plant.json"

**Comment by killerkitt** [comment]
so i actually got the tier 1-5 seeds working so far but soo far i cant find a way to get more items even when the items for each differnt json is like 1-2 then 2-3 then 3-4 then 4-5 and 5-6 is there another way of geting more or am i just derping

**Comment by killerkitt** [comment]
aso anyone know of a way to make it so it can drop a certain amount per plant?
because i changed  min to 5 and max to 6 and when its 10/10/10 it still only drops 4
