### ISSUE TITLE
Add to the Magnifying Glass the ability to check light level

### ISSUE THREAD

**Issue by Waisse** [InfinityRaider/AgriCraft#821]
It's very important to grow certain crops and there's no easy way to check that.

**Comment by VT-14** [comment]
Unless I'm mistaken, you can see the light level of the block you are standing on in the F3 screen.

**Comment by RlonRyan** [comment]
I actually think this is a reasonable addition. It kinda fits with the theme of the magnifying glass.

**Comment by RlonRyan** [comment]
Added!
