### ISSUE TITLE
Biomes o' Plenty support for 1.10.2

### ISSUE THREAD

**Issue by lendrick** [InfinityRaider/AgriCraft#822]
I managed to get AgriCraft working on BoP soils, with this farmland_soil.json file:

`{
  "enabled": true,
  "path": "vanilla/soils/farmland_soil.json",
  "id": "farmland_soil",
  "name": "Farmland",
  "varients": [
    {
      "item": "minecraft:farmland",
      "meta": 0,
      "tags": "",
      "ignoreMeta": true,
      "ignoreTags": [
        "*"
      ],
      "useOreDict": true
    },
    {
      "item": "biomesoplenty:farmland_0",
      "meta": 0,
      "tags": "",
      "ignoreMeta": true,
      "ignoreTags": [
        "*"
      ],
      "useOreDict": true
    },
    {
      "item": "biomesoplenty:farmland_1",
      "meta": 0,
      "tags": "",
      "ignoreMeta": true,
      "ignoreTags": [
        "*"
      ],
      "useOreDict": true
    }
  ]
}
`

**Comment by RlonRyan** [comment]
I think I'll hold off on adding BoP support until we have a better method of accounting for soil-cross compat.
