### ISSUE TITLE
enhancement: Json file for industrial hemp by immersive engineering

### ISSUE THREAD

**Issue by petulko8080** [InfinityRaider/AgriCraft#824]
for my world i created JSON file for industrial hemp form Immersive enginering
give seed and industrial hemp string (50/50 probability)
so if you find it interesting, feel free to include it

currently instaled under resource/plants, my question: it is possible to have separate directory for custom created JSON files?

[hemp_plant.json.txt](https://github.com/InfinityRaider/AgriCraft/files/742055/hemp_plant.json.txt)

**Comment by RlonRyan** [comment]
Yes, you can place JSON files under any directory in the `config/agricraft/json/defaults` directory.

Furthermore, if you place them in a folder named `mod_<mod id>` then AgriCraft will automatically skip the loading if a mod with that id is not present.
