### ISSUE TITLE
[1.10.2] Seed Journal Screen Goes Black on Mouse Over

### ISSUE THREAD

**Issue by MokahTGS** [InfinityRaider/AgriCraft#829]
In 2.0.0-.06.0-a10 when I mouse over the seeds that I have scanned the entire screen goes black and then goes back to normal when I move my cursor away.  The journal and seeds are still visible, just the game in the background goes black.

**Comment by RlonRyan** [comment]
I have this fixed in the dev-storage branch, I just haven't decided if it is stable enough as to warrant merging into the master branch.

Thanks for reporting, as it helps keep track of these issues.
