### ISSUE TITLE
[1.3.0-alpha1] Unhydrated farmland not registered as soil by default

### ISSUE THREAD

**Issue by thephoenixlodge** [InfinityRaider/AgriCraft#83]
As per the title, vanilla farmland that is not hydrated seems to not be listed as a soil by default, resulting in cropsticks not being placeable on it.
I presume this is intended behaviour so you have to have your farm hydrated, but the side effect of this is that the vanilla farming disabling also no longer applies to unhydrated farmland, so non-Agricraft seeds can all be planted on it.

**Comment by InfinityRaider** [comment]
I'll fix this as soon as I get home
