### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by Waisse** [InfinityRaider/AgriCraft#830]
When I play on my own [modpack](https://minecraft.curseforge.com/projects/nukocraft) my memory cap shortly after I start planting Agricraft crops, making my game freeze every 5s. This never happen without Agricraft. I tried on several new worlds to be sure. I play with 2.5 G dedicated, and Optifine.

**Comment by RlonRyan** [comment]
What version?

**Comment by Waisse** [comment]
Latest available from Curse.

**Comment by Ravin890** [comment]
a10?

**Comment by Waisse** [comment]
v10

**Comment by RlonRyan** [comment]
And which version of InfinityLib?

**Comment by Waisse** [comment]
I think the issue might be something else not related with Agricraft, I'll close this for now. Sorry.

**Comment by RlonRyan** [comment]
Ok. If you are sure.

**Comment by STS15** [comment]
I was having a memory leak on my modpack until I removed Agricraft.  With Version a10 and InfinityLib 0.6.2.  Just thought you might want to know.

**Comment by RedstoneMaster256** [comment]
FTB Beyond also has this issue, with version a17 and infinitylib 0.10.0
