### ISSUE TITLE
Double cropstick crops

### ISSUE THREAD

**Issue by Ravin890** [InfinityRaider/AgriCraft#833]
Looks like the crop in the crop sticks isn't recognized or something.
![2017-02-10_00 41 15](https://cloud.githubusercontent.com/assets/13302573/22815482/ed91e5d0-ef29-11e6-8fa6-2b1504bf3f01.png)

*If the seed is in the crop sticks you can still put a crop stick on it to make it like that.
-Using Agricraft version 0.6.0-a10 and infinitylib-0.6.2

**Comment by RlonRyan** [comment]
That is quite unusual...

**Comment by Ravin890** [comment]
due note, crop still grows while like that.

**Comment by RlonRyan** [comment]
How funny...

**Comment by RlonRyan** [comment]
Is this still an issue?

**Comment by Zero5211** [comment]
Still an issue.

![2017-03-12_14 21 37](https://cloud.githubusercontent.com/assets/8635924/23836067/3cf356d2-072f-11e7-8c9f-91bd4fbb634a.png)

**Comment by RlonRyan** [comment]
Thanks!

**Comment by RlonRyan** [comment]
Fixed in 2.0.0a12
