### ISSUE TITLE
crash when pressing "e"

### ISSUE THREAD

**Issue by felix920506** [InfinityRaider/AgriCraft#834]
[crash-2017-02-10_17.23.06-client.txt](https://github.com/InfinityRaider/AgriCraft/files/766897/crash-2017-02-10_17.23.06-client.txt)

**Comment by RlonRyan** [comment]
The mod tmi appears to be passing an invalid meta value, so I guess I'll have to account for such.

**Comment by RlonRyan** [comment]
Sorry. This is a 1.7.10 issue, which has been discontinued. It may or may not be fixed.
