### ISSUE TITLE
Mutations not occuring

### ISSUE THREAD

**Issue by grundyboy34** [InfinityRaider/AgriCraft#835]
I'm using the latest available version for 1.10.2 via curseforge. [agricraft-2.0.0-0.6.0-a10], and I've noticed that crossbreeding as well as mutation doesn't work. It seems that the strategies for spreading/mutating just aren't happening.

Update: I actually found the issue.
File: AgriCraft/src/main/java/com/infinityraider/agricraft/blocks/tiles/TileEntityCrop.java
Line: 81   `else if (this.isCrossCrop() && (Math.random() < AgriCraftConfig.weedSpawnChance)) {
                this.crossOver();
            }`

Naturally weedSpawnChance is low, so it's keeping mutations from occuring. No idea why spreading doesn't happen though.

**UPDATE:**  Spreading is occuring as well. So this is simply a matter of using the wrong comparison. 
`Math.random() < AgriCraftConfig.weedSpawnChance`    should be
`Math.random() >= AgricraftConfig.weedSpawnChance` in order to provide expected functionality as documented in the config.

**Comment by Jomik** [comment]
Seems like this is correct. Though.. You can link directly to the line: https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/infinityraider/agricraft/blocks/tiles/TileEntityCrop.java#L81

Also, I'd suggest making a pull request on this.

**Comment by RlonRyan** [comment]
In truth, the a new constant needs to be introduced for the crossover chance. The code itself is correct however, given that taking >= would change the probability to (1 - weedSpawnChance) instead of the intended probability of  weedSpawnChance.

**Comment by RlonRyan** [comment]
I think that I have this logic error fixed. There were several other spots in the code that factored into this.
