### ISSUE TITLE
[1.10.2 a10] Bugs

### ISSUE THREAD

**Issue by Rudy2D2** [InfinityRaider/AgriCraft#836]
I'm having a lot of problems with this version; is this because it is still in alpha and is a work in progress or are these actual bugs? Here are some of my issues:

1. Sprinklers do nothing. They do not irrigate farmland nor do they increase crop growth. I have tried this while running only Agricraft and with the sprinklers placed at varying heights.
2. Weeds are very bugged. Using a rake can drop an item that cannot be picked up (but is affected by magnets?). Using a weed seed can cause weeds to appear and disappear instantly, sometimes fully mature.
3. ~~Missing recipes for sugar cane and cactus seeds, and mushroom spores. And shouldn't all resource plants need ores underneath?~~ Fixed.

Other than these issues, the mod seems to cause the game to slow down, sometimes to a dead stop, and overall, it just feels kind of wonky.

**Comment by Ravin890** [comment]
Not sure about the sprinkler part, but the rest of your issues are already known. The item drop from weed is a desync issue and the sugar cane, cactjs, ect. seeds was yet to be implemented as drops properly

**Comment by RlonRyan** [comment]
The de-sync is a known issue. As such I am making a new, concise issue for the sprinklers and closing this one.
