### ISSUE TITLE
Farmer Villager harvest crops

### ISSUE THREAD

**Issue by epiz** [InfinityRaider/AgriCraft#837]
Brown-robed villagers can break and plant vanilla crops. I think they should be able to harvest from AgriCraft crops. If it's too difficult to implement for the vanilla Villagers, then maybe the AgriCraft Farmer could do this.

**Comment by InfinityRaider** [comment]
Its really easy to implement, and it makes the agricraft villager redundant even.

**Comment by RlonRyan** [comment]
Closing for now, as to focus on other issues. Will revisit when AgriCraft reaches a more stable state.
