### ISSUE TITLE
Mystical Agriculture Custom seed issues

### ISSUE THREAD

**Issue by TokkenGmr** [InfinityRaider/AgriCraft#838]
I was working on creating custom seeds for mystical agriculture, everything works fine until I try to add the output for the seed/plant. Some outputs work fine like "minecraft:diamond" or even "mysticalagriculture:inferium_essence" but then when I try and use "mysticalagriculture:ardite_essence" or various other items the seed is no longer in nei/jei, however if I change the output back to say  "minecraft:diamond" it works fine and shows up again. The other issue I am having is that when I reference "seed_items" and refer to something from mystical agriculture a new seed is created instead of using the seed from the stated mod

Here is a link to the json that works for me using "minecraft:diamond" and then one where the seed is gone just by changing the output to "mysticalagriculture:ardite_essence"

http://pastebin.com/mwR2KCNR - working but wrong output
http://pastebin.com/yjdfJPU3 - not working but right output

**Comment by RlonRyan** [comment]
I think that mystical agriculture does something funny with their items. Try using the spawn command to check if the item works.

**Comment by TokkenGmr** [comment]
To see if which item works, the one that is referenced in "seed_items"? The seed that is created but does not show up?

The Test Seeds from my json spawn in no problem depending on the output. However none of the seeds use my specified seed item and instead uses an auto-generated seed. I also have other jsons that work 100% correctly no issues.

**Comment by RlonRyan** [comment]
No, try spawning in "mysticalagriculture:ardite_essence" to see what happens.

**Comment by Jomik** [comment]
This works fine for me. I don't use the "seed_items" array in the JSON though, I only specify a seed texture at the bottom.
http://pastebin.com/1NeDKt5N

**Comment by Ravin890** [comment]
its a bit finicky in all honesty. For some it works how its supposed to while for others it doesn't.

**Comment by TokkenGmr** [comment]
@RlonRyan: As far as spawning in "mysticalagriculture:ardite_essence" there is no issue there I can span it in no problem. The problem is on the seed when i change it to "mysticalagriculture:ardite_essence" the seed just disappears. The seed works or doesn't work depending on what you change the output to.
@Jomik: Yes when I refer to just a texture it works and creates the seed sometimes just depends on the output 
@Ravin890: That is what I am seeing some of my custom json files work with no issues at all and some just are just not there at all

Guess i will try botania and see if the same thing happens

**Comment by Ravin890** [comment]
I set up my own but placed them in the resource folder as opposed to making a folder for them and no issues on my end, maybe try to see if there would be any issue changing the folder file.

**Comment by TokkenGmr** [comment]
@Ravin890: No the seed still either works or doesn't work based on what I change the output to regardless of where I have the json saved.

**Comment by Ravin890** [comment]
its just being finicky

**Comment by TokkenGmr** [comment]
I wish the issue was just with mystical agriculture. Changed the seed output to a tinkers item and seed still disappears. Finicky is the best way to describe it some work and some do not for no reason that I can see

**Comment by RlonRyan** [comment]
Must be some oddity with the way that nbt tags get added to the items.

**Comment by RlonRyan** [comment]
Could you please post a paste of the log files for the erroring plants?

**Comment by TokkenGmr** [comment]
@RlonRyan: Will do. Working out of town atm. Will post when I get back in town.

**Comment by TokkenGmr** [comment]
which log files are you wanting? All the log files that are in the log folder? Or is there a certain one you need like latest.log or fml-client-latest.log.

**Comment by TokkenGmr** [comment]
I think this may be what you want 

log file
http://pastebin.com/PxdTaQfx

these are the current jsons I have that go with that log
http://pastebin.com/QPv2utA0 - Hemp Seed: everything is correct
http://pastebin.com/GZKs3sFR - Test Seed: does not refer to the correct seed, seed disappears 
http://pastebin.com/9XeTVD6V - Test1 Seed: creates "agricraft" seed  and has an output
http://pastebin.com/Y4hdVqzc - Test2 Seed: does not refer to correct seed, creates "agricraft" seed and does not show an output

**Comment by RlonRyan** [comment]
Interesting. Thank you very much.

**Comment by TokkenGmr** [comment]
Tested new alpha version and same issues are till present. I know it is just going to take time, if there is anything that I can do to help let me know.

**Comment by killerkitt** [comment]
any update on this? and any files to give out like for the seeds? all or some thanks

**Comment by killerkitt** [comment]
an update from me is i got the seeds working just having trouble with dropping more essence for the different tiers of the seeds

**Comment by TokkenGmr** [comment]
@RlonRyan  When I get back in town I will test the latest release and see what happens. Thanks for all the work put in 
@killerkitt  If you arent having problems like I was then that is great.

**Comment by killerkitt** [comment]
@TokkenGmr don't think I am I got everything working besides the amount of items dropped by the crop like I want it so that the tier 1 drops 1-2 10-10-10 is 2 drops and tier 5 drops 5-8 10-10-10 is 8 drops but can't figure out how

**Comment by killerkitt** [comment]
I'll post a file or code so that you all can just download and use whenever after the amount dropped is fixed for me

**Comment by killerkitt** [comment]
ok so first steps on how to make this work is to
1. create a folder called mod_mysticalagriculture (that will load the mod) in the folder called defaults in json folder
2. in that folder make 2 more called plants and mutations and open the plants one
3. is to copy over a json file from one of the vanilla plants like carrots is what i used
4. rename it to tier1 (what i called it for the tier 1 inferium seed) then in the file i wrote my own stuff you guys can change it if you want but thats up to you this is a code for you guys to work with so yeah... back to it
5. -------------------------------------code-----------------------------------------------
{
  "path": "mod_mysticalagriculture/plants/tier1_plant.json",
  "enabled": true,
  "id": "tier1",
  "plant_name": "Inferior Inferium Plant",
  "seed_name": "Inferior Inferium Seeds",
  "seed_items": [
    {
      "item": "mysticalagriculture:tier1_inferium_seeds",
      "meta": 0,
      "tags": "",
      "ignoreMeta": false,
      "ignoreTags": [
        "*"
      ],
      "useOreDict": false
    }
  ],
  "description": {
    "translations": {},
    "default": "A Mystical Agriculture plant."
  },
  "growth_chance": 0.9,
  "growth_bonus": 0.025,
  "bonemeal": false,
  "tier": 1,
  "weedable": false,
  "aggressive": false,
  "spread_chance": 0.1,
  "spawn_chance": 0.0,
  "grass_drop_chance": 0.0,
  **"products": {
    "products": [
      {
        "min": 1,
        "max": 2,
        "chance": 1.0,
        "required": true,
        "item": "mysticalagriculture:inferium_essence",
        "meta": 0,
        "tags": "",
        "ignoreMeta": false,
        "ignoreTags": [],
        "useOreDict": false**
      }
    ]
  },
  "requirement": {
    "min_light": 10,
    "max_light": 16,
    "soils": [
      "farmland_soil"
    ],
    "bases": [],
    "nearby": {}
  },
  "texture": {
    "render_type": "hash",
    "seed_texture": "mysticalagriculture:items/inferium_seeds",
    "plant_textures": [
      "mysticalagriculture:blocks/crop0",
      "mysticalagriculture:blocks/crop0",
      "mysticalagriculture:blocks/crop1",
      "mysticalagriculture:blocks/crop1",
      "mysticalagriculture:blocks/crop2",
      "mysticalagriculture:blocks/crop3",
      "mysticalagriculture:blocks/crop4",
      "mysticalagriculture:blocks/inferium_crop"
    ]
  }
}
----------------------------------------code-------------------------------------------

btw i use notepad++ to help make it all look good so if i dont know if you will get same looking spacing of code as me or not but here it is now the bolded area is what i am having trouble with so if someone could help that would be much appreciated

**Comment by killerkitt** [comment]
but here was just an update btw so give me a bit to see if this is even still valid

**Comment by killerkitt** [comment]
no it didnt change it but the problem is still there

**Comment by TokkenGmr** [comment]
@killerkitt  Thank you for that, however that was not the issue. I have not tested further than the scripts that I have listed. I will be looking forward to what you have to share. Remember to post it to the AgriPlants repo.
@RlonRyan  In regards to the scripts that I have posted 

http://pastebin.com/QPv2utA0 - Hemp Seed: everything is correct   
**(still works)**
http://pastebin.com/GZKs3sFR - Test Seed: does not refer to the correct seed, seed disappears 
**(everything is now working as intended)**
http://pastebin.com/9XeTVD6V - Test1 Seed: creates "agricraft" seed and has an output   
**(works as intended)**
http://pastebin.com/Y4hdVqzc - Test2 Seed: does not refer to correct seed, creates "agricraft" seed and does not show an output
**(refers to correct seed however still does not show an output. This one is not mysticala griculture output it is a tinkers construct)**

Also I was working on adding the vanilla flowers like poppy, blue orchid, and the like and everything works fine because all the assets are still in the agricraft jar, however they to seem to not show an output. I think it may have to do with metadata. For instance the issue above the output has a metadata value in it same as minecraft dyes, which is what i was using as the output
http://pastebin.com/tfNit8Cr

**Comment by TokkenGmr** [comment]
Everything seems to be working as intended. I did not notice the meta portion in the json right after the product name, that was my mistake. I think this issue can be closed Im not sure about killerkitt's issue. I can control the output for the "basic seed" no problem, not sure if you can be that specific with the 10/10/10.

**Comment by RlonRyan** [comment]
I think that that means the issue can be closed then thanks!
