### ISSUE TITLE
Ars Magica 2 integration

### ISSUE THREAD

**Issue by Maulkin12** [InfinityRaider/AgriCraft#841]
There's a version of AM2 for 1.10.2, and I was wondering if it is possible to modify the json files to add the support, or if that requires a change to the actual code to accomplish.

**Comment by Ravin890** [comment]
there probably is a way, setting up the json files i what is needed.

**Comment by RlonRyan** [comment]
The JSON system should be able to handle it. If not, submit a new issue requesting the requisite hooks to be implemented in the JSON files.
