### ISSUE TITLE
How to find mod ids

### ISSUE THREAD

**Issue by urbanlime** [InfinityRaider/AgriCraft#842]
I'm having trouble defining the seeds when creating the JSON files could you help me figure out how to define the seeds please

**Comment by TehNut** [comment]
F3+H in-game will enable the advanced tooltips. Look for the line that looks like `minecraft:cobblestone`. The bit before the `:` (like `minecraft`) is the modid.

**Comment by RlonRyan** [comment]
The mod id should also be displayed on the mod info page of the main menu.

**Comment by MatthewIsTaken0** [comment]
Very helpful!
