### ISSUE TITLE
Agricraft crops in mekanism

### ISSUE THREAD

**Issue by Aphenon** [InfinityRaider/AgriCraft#848]
For some reason, crops harvested from cropsticks cannot be made into Bio fuel in the mekanism crusher. Things like pumpkin can be placed on the ground and then picked up again and it will work.

**Comment by RlonRyan** [comment]
Weird. Mechanism must intercept drops in some manner...

**Comment by RlonRyan** [comment]
Dang it wrong button.

**Comment by Aphenon** [comment]
Glowstone dust gathered from glowstone crops doesn't actually stack with glowstone dust dropped from breaking the glowstone blocks, so the crop produce is different in some way,

**Comment by Aphenon** [comment]
Inspecting the glowstone dust reveals a slight difference, AgriCraft produce has a compund that vanilla dust does not.

![2017-02-26_21 23 18](https://cloud.githubusercontent.com/assets/9679372/23343340/3c9a9d96-fc6a-11e6-85bb-2f1165e5febd.png)

**Comment by InjuredWolf** [comment]
Yeah, I've noticed this with a lot of plants, the produce from crops has an NBT tag, whereas if you get the same item from other methods (like potatoes from zombies) then those ones do not have the NBT tag, ergo the two "different" potatoes do not stack.

**Comment by RlonRyan** [comment]
Thanks for the in-depth investigation! It is very helpful, and I think I should have the issue fixed soon!

**Comment by RlonRyan** [comment]
This issue has been fixed in the upcoming 2.0.0a11 release.
