### ISSUE TITLE
Glowstone crops

### ISSUE THREAD

**Issue by Aphenon** [InfinityRaider/AgriCraft#849]
When trying to level up glowstone crops, the offspring do not grow, and do not drop seeds if broken. The player-planted parents grow fine. (EDIT: i'm having the same problem with other resource plants, so the problem is not limited to glowstone.)
using:
agricraft-2.0.0-0.6.0-a10
Forge 12.18.3.2221
![2017-02-25_21 14 03](https://cloud.githubusercontent.com/assets/9679372/23334472/d53a64e4-fb9f-11e6-800c-54ba8e972347.png)

**Comment by InjuredWolf** [comment]
Did they transfer over to Cross-Sticks or regular Crop Sticks? I've noticed that sometimes they like to 'expand' to regular crop sticks when they shouldn't, with WAILA saying 'This plant can not grow here' and the plant not dropping anything when broken. Generally works fine with Cross-Sticks, at least that I've noticed.

**Comment by Aphenon** [comment]
That may be the case, i will test when i have the opportunity later today.

**Comment by InjuredWolf** [comment]
Yeah. I thought I saw it reported a while back, but I might be mistaken...

**Comment by RlonRyan** [comment]
It looks like ghost plant being spread. The spreading code was messed up so that an actual spread event was far rarer than it should have been.

**Comment by RlonRyan** [comment]
Consolidated to #863
