### ISSUE TITLE
[Question] Custom crop JSON: Metadata for crop base requirement?

### ISSUE THREAD

**Issue by Doomathon** [InfinityRaider/AgriCraft#851]
So I'm attempting to create custom resource crops for Cobalt and Ardite from Tinker's Construct, and I almost got it working as desired, but JEI reports that my crop for Ardite doesn't require any block beneath the soil, unlike the Cobalt crop which is working as expected. The only difference between the two is that Ardite Ore requires a meta value, and the cobalt ore does not.

Working crop JSON: http://pastebin.com/iLpMM8Dm
Not working crop JSON: http://pastebin.com/d2vJ5zqH

There's a very real chance of user error here, but I hope what I'm trying to achieve is clear here. What is needed to get the crops to work as expected here?

**Comment by TokkenGmr** [comment]
It does not look like the JSON is incorrect. This is kind of like similar to my ardite crop that does not show an output that I posted about. I am sure things will get work out soon or later

**Comment by RlonRyan** [comment]
This has been updated in the 2.0.0a11 version, so that bases are instead pointers to agri_blocks files that can act as bases and/or soils.

**Comment by RlonRyan** [comment]
I just fixed the system so that your metavalue should now work the way you have it.
