### ISSUE TITLE
[Request] Mystical Agriculture JSONS

### ISSUE THREAD

**Issue by urbanlime** [InfinityRaider/AgriCraft#855]
I am currently trying to create jsons for the mystical agriculture mod, but am continually running into issues. I was wondering if anybody else has been able to do this successfully and would be willing to share their jsons with me. If not I totally understand, but it would be a big help. Thank you in advance.

**Comment by TokkenGmr** [comment]
Mystical Agriculture and Agricraft are hit and miss currently. Some work with no problems and others are just "wonky". Just have to wait or try using one of the other resource crop mods.

**Comment by KebnTheFirst** [comment]
I have 1 for energetic alloy crops working here: http://pastebin.com/YCtUrAdh

I took the one posted by somebody in a different issue and made some adjustments for the seeds. I'm trying to make more but I'm currently having issues finding plant names and none of them are working. If I can figure out the plant names for them I plan on making JSONs for all the seeds and passing them out so we can put this issue to rest.

**Comment by RlonRyan** [comment]
If you could move this to the AgriPlants repository that would be greatly appreciated.
