### ISSUE TITLE
Weed Growth speed seems to be reversed in config

### ISSUE THREAD

**Issue by tfox83** [InfinityRaider/AgriCraft#857]
After testing the speed of weeds, 0.05 seems to be super fast, where 0.95 is more normal.
    # The percent chance of weeds to spawn or spread. At 95% abandon all hope of farming. [range: 0.05 ~ 0.95, default: 0.15]
    S:"Weed Spawn Chance"=0.05

Bugs submitted to me about this:
https://forum.feed-the-beast.com/threads/misc-agricraft-bugs.220523/
https://support.feed-the-beast.com/t/ftb-beyond-agricraft-bugs/30863

Thanks!

**Comment by RlonRyan** [comment]
Thanks for the bug report. I have fixed this issue in the dev version.
