### ISSUE TITLE
Cannot craft channels/tanks with Oak planks

### ISSUE THREAD

**Issue by tfox83** [InfinityRaider/AgriCraft#858]
All other vanilla planks seem to work except oak.
I can work around this with CT in FTB Beyond, but wanted to give you a heads up!

OP: https://forum.feed-the-beast.com/threads/cant-make-water-tank-or-water-channel.220510/#post-1843850

Thanks!

**Comment by RlonRyan** [comment]
Duplicate of #724. Thanks for the update though!
