### ISSUE TITLE
Crop spreading and upgrading unreliable

### ISSUE THREAD

**Issue by TheChance** [InfinityRaider/AgriCraft#859]
I'm on Beyond, with the traditional X-shaped grinding pit. I have four mature Pam's cotton plants surrounding the double crop sticks, as usual.

I've been through - no joke - two dozen watering cans. From those, I've gotten two brand new 1/1/1 seeds, and one improved seed (which I promptly added to the cross.) This doesn't seem normal.

I'll go through 2-3 watering cans with nothing happening or weeds growing. Obviously, weeds growing is a lot more common than a new cotton plant growing (having been through two dozen watering cans and gotten three new seeds out of it.) Weeds taking over a double-stick surrounded by four mature plants _really_ doesn't seem normal.

**Comment by TheChance** [comment]
Update: I got a third 1/1/1 seed after four more watering cans. It was invisible. I'm now using a magnifying glass on the breeding sticks every 1/3 of a watering can.

The watering can matures planted seeds in no time at all. It's only spreading/breeding affected.

**Comment by RlonRyan** [comment]
This was due to an error in the probability logic. This should be fixed in the next release.
