### ISSUE TITLE
[1.3.0alpha] Mutation requirements gone?

### ISSUE THREAD

**Issue by Belgabor** [InfinityRaider/AgriCraft#86]
Honestly, I'm really sad to see the needs-block-near mutation specific requirement gone, I had some fun ones done for our pack :(
The block below one I don't really miss, that was confusing (Indeed I did shoot myself in the foot with that one), but please reconsider removing the block near condition.

**Comment by thephoenixlodge** [comment]
They're still there, but as the BaseBlock Minetweaker function

**Comment by Belgabor** [comment]
True, but they are now a general growth requirement, not specific to the mutation event.

**Comment by Imasius** [comment]
We made the design decision that 2 different requirements, one for growing and one for mutating, was a very confusing thing. So we unified them into "growth requirements".

If a base block is specified, it is still needed for mutation; its only (like you said) not specific to the mutation event anymore.
