### ISSUE TITLE
Debug spam in latest.log

### ISSUE THREAD

**Issue by DeGariless** [InfinityRaider/AgriCraft#866]
I'm getting Debug messages to logs/lastest.log even though debug mods is set to false in the configs.

MC: 1.10.2
Forge: build 2254
AC: agricraft-2.0.0-0.6.0-a11

[latest.txt](https://github.com/InfinityRaider/AgriCraft/files/836017/latest.txt)

**Comment by RlonRyan** [comment]
This has been addressed, and will be fixed in the next alpha.
