### ISSUE TITLE
Is agricraft for 1.10 dead?

### ISSUE THREAD

**Issue by CamaroKing59** [InfinityRaider/AgriCraft#867]
haven't seen any updates in a while and last time i tried to use it it kept crashing due to rendering of village

**Comment by TehNut** [comment]
There was an update on Curse 3 days ago.

**Comment by CamaroKing59** [comment]
is it under something else bc all im getting is one from February 27

**Comment by TehNut** [comment]
https://minecraft.curseforge.com/projects/agricraft/files/2390557

**Comment by CamaroKing59** [comment]
ok nvm it doesnt show an actual update but i see where it updated
