### ISSUE TITLE
Weed issue

### ISSUE THREAD

**Issue by CamaroKing59** [InfinityRaider/AgriCraft#871]
i rake the weeds and this is what i get https://gyazo.com/3b42868daf631cfd222c51c487d2f21f is this suppose to happen

**Comment by RlonRyan** [comment]
I have no idea as to what that image means.

**Comment by TheChance** [comment]
I'm not sure what the image means, either, but raking is definitely broken. When I rake weeds, the weeds remain in the crop sticks and drop grass items that cannot be collected. If I keep raking, they keep dropping.

Weed spawn chance also still seems to be messed up. I've been making half-stacks of crop sticks and getting 1-3 new plants per half-stack, whereas weeds spawn on about 4/5 double sticks.

**Comment by RlonRyan** [comment]
Fixed.
