### ISSUE TITLE
Bug: Cropsticks can be applied infinitely on a double cropstick!

### ISSUE THREAD

**Issue by Guinaro** [InfinityRaider/AgriCraft#872]
Minecraft: 1.10..2
Agricraft: 2.0.0.0.7.0-a12
When placing cropsticks on cropsticks you make a double cropstick.

Bug: You can keep applying these cropsticks onto those double cropsticks ad infinitum.
Breaking them only yields 2 cropsticks back.

Mods:
  agricraft-2.0.0-0.7.0-a12
  animania-1.10-1.0.2
  AppleCore-mc1.10.2-2.1.2
  AppleSkin-mc1.10.2-1.0.5
  BlockDrops-1.10.2-1.1.1
  CodeChickenCore-1.10.2-2.4.0.101-universal
  CodeChickenLib-1.10.2-2.5.6.233-universal
  compatlayer-1.10-0.2.2
  Controlling-1.0.4
  CookingForBlockheads_1.10.2-4.2.39
  craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42
  CraftingTweaks_1.10.2-6.1.16
  CraftTweaker-1.10.2-3.0.24
  extraalchemy-0.3.0.4-hotfix-release
  HelpFixer-1.10.2-1.4.15
  HungerOverhaul-1.10.2-1.1.0.jenkins111
  Hwyla-1.8.11-B25_1.10.2
  hydrogel-0.9
  infinitylib-0.7.0
  InitialInventory-1.0.1
  intwheel-1.1x-1.2.4
  InventoryTweaks-1.62-dev-66
  itemscroller-1.10.2-0.10.3
  jei_1.10.2-3.14.7.416
  JustEnoughResources-1.10.2-0.5.9.3
  JustEnoughTooltips-1.10.2-2.1.39
  Lots of Food-1.12.0
  Mantle-1.10.2-1.1.5
  MineMenu-1.10.2-1.4.5-universal
  ModTweaker2-2.0.10
  MouseTweaks-2.8-mc1.10.2
  MTLib-1.0.1
  NashornLib-1.9.4-1.8.77-1.3.1.8
  NotEnoughItems-1.10.2-2.1.3.201-universal
  Pam's HarvestCraft 1.9.4-1.10.2h
  PotionCore-1.4_for_1.10.2
  SpiceOfLife-mc1.9.4-1.3.8
  TConstruct-1.10.2-2.6.3
  WailaHarvestability-mc1.10.2-1.1.9
  Wawla-1.10.2-2.3.1.214

**Comment by Lethann** [comment]
Can confirm this bug as well.

**Comment by RlonRyan** [comment]
Fixed.
