### ISSUE TITLE
Sprinkler Visual Bug

### ISSUE THREAD

**Issue by Aw3som3Guy** [InfinityRaider/AgriCraft#874]
When I use the sprinklers and look under what I presume is the horizon, the water particles turn dark similar to the void in Skyblock/Void worlds.

I'm running AgriCraft version 1.5.0 and Optifine if that helps. Sorry if this is a duplicate.

**Comment by RlonRyan** [comment]
1.7.10 has been discontinued so that we may focus on the next versions of agricraft. Plus this is a relatively minor issue so it is highly doubtful that a fix will ever be made, sorry. Thanks for using the issue tracker though!
