### ISSUE TITLE
Seeds will not load from mod_botania

### ISSUE THREAD

**Issue by TokkenGmr** [InfinityRaider/AgriCraft#875]
So I created jsons for botania flowers, they work with no problem until you move them to the mod_botania folder. Yes i have the json in the sub folder plants as well. The jsons work fine in the vanilla folder. Seems to skip the json thinking that botania is not installed, of course it is installed. Here is the [log](http://pastebin.com/1VmDCjVW)

**Comment by bookerthegeek** [comment]
I believe that capitalisation might be the cause. Can you make sure the mod id is exactly the same as the file name?
