### ISSUE TITLE
Infinitylib requirement not listed on site. 

### ISSUE THREAD

**Issue by JRSofty** [InfinityRaider/AgriCraft#879]
Looking to see what other mods that I need for AgriCraft I checked under the Relations-->Dependencies and saw none listed. I install the mod and the game stops loading because it was missing the infinitylib jar file. Can you please add this to the site's listing?

**Comment by RlonRyan** [comment]
This is actually a curseforge issue with alpha releases. On the file we have set the dep, but curse refuses to acknowledge it for alpha releases.

**Comment by RlonRyan** [comment]
This is actually a curseforge issue with alpha releases. On the file we have set the dep, but curse refuses to acknowledge it for alpha releases.
