### ISSUE TITLE
[1.3.0alpha] Specifying a BaseBlock of type 2 hangs Minecraft

### ISSUE THREAD

**Issue by Belgabor** [InfinityRaider/AgriCraft#88]
If I use the minetweaker API to specify a BaseBlock of type 2 (nearby block) Minecraft hangs as soon as I try to plant the seed (Edit: not permanently, but for quite some time). I only tried in SSP, so I'm not sure whether it is a partial client hang or a server hang. I can still move around but I can no longer interact with the world or NEI. If I try to save and quit, it hangs on "shutting down internal server" for a long time.

I haven't tried to specify a BaseBlock of type 1 via the API, but I do know that doing so in CustomCrops.txt as in earlier versions works.

**Comment by thephoenixlodge** [comment]
Just confirmed this happens to me too

**Comment by Imasius** [comment]
I was able to reproduce this too. A first look at VisualVM says that there might be an infinite loop somewhere with the nearby check at the core of things.
