### ISSUE TITLE
[Request] liquids as base or nearby

### ISSUE THREAD

**Issue by TokkenGmr** [InfinityRaider/AgriCraft#881]
How about being able to use liquids as a nearby requirement or even as the base under the soil. Just a thought.

**Comment by RlonRyan** [comment]
This should already be possible as liquids are blocks.

**Comment by TokkenGmr** [comment]
Ok, well I have tried a few different liquids and was unable to get them to work. I thought maybe not  feature. Will do a few more tests and see if I can get it to work. Sorry to have bothered

**Comment by RlonRyan** [comment]
Glad that you were able to figure it out.
