### ISSUE TITLE
10/10/10 seeds super slow

### ISSUE THREAD

**Issue by Heathenism** [InfinityRaider/AgriCraft#884]
Hey  Im having an issue on the FTB Beyond 1.10 modpack on a server, for some reason my 10/10/10 pumpkins, wheat and potatoes (everything crop from what I can tell).  And they are slower than vanilla crops, I have sat and watched vanilla seeds next to 10/10/10 wheat seeds in crop sticks grown about 3 times as slow. I thought changing
S:"Growth rate multiplier"=1  
to
S:"Growth rate multiplier"=.7
which didnt help, then I tried changing it to 
S:"Growth rate multiplier"=2
and they are still slow no matter what.

**Comment by RlonRyan** [comment]
I had no idea the alpha made it into a ftb pack...

Which version of the alpha are you using?

**Comment by RlonRyan** [comment]
Fixed. The plants were ignoring the base growth chance and were using only the bonus growth chance which is low.

**Comment by Heathenism** [comment]
Awesome!  this might sound dumb but how can I fix it on my end? or do I need to wait for the FTB team to update the pack?

**Comment by RlonRyan** [comment]
You will have to wait sorry. Or set the growth multiplier to a very high number (10+).
