### ISSUE TITLE
Hwyla (Waila) Analysing info (minor issue)

### ISSUE THREAD

**Issue by Mrbysco** [InfinityRaider/AgriCraft#885]
I'm currently playing the Foolcraft modpack and it has Agricraft and Hwyla.
Foolcraft uses Agricraft alpha 2.0.0-0.7.0-a12 and Hwyla-1.8.11-B25_1.10.2

As you might know Hwyla is a fork of Waila and should be 100% compatible but apparently there's a tiny issue.
Even when analysed it still shows that the crop hasn't been analysed while also displaying the stats:
![Image of Hwyla](http://i.imgur.com/IK6BLJC.png)

Just wanted to let you know about the issue.

-Mrbysco

**Comment by RlonRyan** [comment]
Fixed. Thanks for reporting!
