### ISSUE TITLE
Cropsticks deleting extra crop sticks clicked (1.10.2 alpha)

### ISSUE THREAD

**Issue by Mrbysco** [InfinityRaider/AgriCraft#886]
You can continue right-clicking with more crop sticks and it will eat every extra crop stick that you use.
Using Alpha 2.0.0-0.7.0-a12

To demonstrate I have recorded the issue on a fresh instance with just Agricraft and it's needed infinitylib:
_(You can click on the image to go to the Youtube video)_
[![Video proof](https://i.ytimg.com/vi/s9bebI4DNYY/maxresdefault.jpg)](https://www.youtube.com/watch?v=s9bebI4DNYY)

**Comment by RlonRyan** [comment]
Already fixed in next version.
