### ISSUE TITLE
Please add the ability to disable/enable weeds back into the config

### ISSUE THREAD

**Issue by BrewAndCode** [InfinityRaider/AgriCraft#893]
The 1.7.10 version had the ability to disable weeds.  Is it possible to get that configuration and associated behavior back into the versions for the newer releases of MC?

**Comment by Doomathon** [comment]
check the json files for the plants. Specifically: config/agricraft/json/defaults/plants/weed_plant.json

Change the value for enabled to false.

This could definitely be made more obvious, but this is already possible

**Comment by RlonRyan** [comment]
Changing the JSON file is correct. There are no longer weeds proper like in 1.7.10 to be disabled through config.
