### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by sfPlayer1** [InfinityRaider/AgriCraft#90]
AgriCraft 1.2.3 logs a lot to the console during startup, 207 lines in total for my test setup, suppressing anything actually important.

Please remove extraneous logging or at least reduce the log level to DEBUG or less. INFO and higher end up in the console.

**Comment by InfinityRaider** [comment]
I've hidden everything not needed in a non-dev environment behind the debug config. Except things for feedback towards modpack creators (like adding crops/changing mutations/...).
