### ISSUE TITLE
Villager Registry Crash

### ISSUE THREAD

**Issue by Akjoutrageous** [InfinityRaider/AgriCraft#93]
Hi I've been trying to install the 1.0.3 Alpha3, and find myself with this crash.
http://pastebin.com/wC9ZHGrD

I'm not familiar with Villager-related conflicts-- so I'm not totally sure it's Agricraft's fault, but either way here ya go.

EDIT:  Never mind, didn't understand the whole villager id conflict.  Closing issue.

**Comment by InfinityRaider** [comment]
Okay then :p
