### ISSUE TITLE
Random color change on irrigation channel

### ISSUE THREAD

**Issue by StoneWall82** [InfinityRaider/AgriCraft#94]
I was placing some of the irrigation channels and then for some reason the color changed from block to block.
I tired every thing i could think of as to why this would happen but nothing was the cause.

![2015-02-20_01 42 13](https://cloud.githubusercontent.com/assets/11087672/6283477/4df552c4-b8a2-11e4-96d5-1998ebb4bbce.png)

**Comment by Imasius** [comment]
From the screenshot it looks like a lightning problem. Which version of AgriCraft are you using? Also are you using optifine and if so has disabling optifine any impact?

**Comment by InfinityRaider** [comment]
Definatly a lighting issue

**Comment by StoneWall82** [comment]
I am currently using 1.2.1 and I am not using optifine. It is most definitely a lighting problem because when i put a tourch right next to it it goes away  but then comes back when i remove it. also if i place a channel on top of the dark on seen it this pick the one on top is just fine.

**Comment by hron84** [comment]
@StoneWall82 do you have any mod that modifies lighting such as some hardcore darkness stuff?

**Comment by StoneWall82** [comment]
all I had installed was the infinity mod pack

**Comment by LucidCrux** [comment]
I have got all kinds of rendering issues with the tanks and channels in the regrowth pack. All the channels and tanks are made of spruce but as you can see they show up in four different colors. I've had rendering issues in other packs as well.

![Uploading 2015-03-19_12.01.51.png . . .]()

**Comment by adamkdean** [comment]
I am also getting this, on the tanks as well as the irrigation channels. No other mods except this ModPack.

**Comment by InfinityRaider** [comment]
I think I know what's causing it and it will be fixed once I get the time to do a whole lot of work on AgriCraft, for now I'm very busy with other stuff.
