### ISSUE TITLE
Custom Item not rendering in journal

### ISSUE THREAD

**Issue by ubermentat** [InfinityRaider/AgriCraft#98]
Forge: 1291
AgriCraft: 1.3.0 alpha 3 (from curseforge)

After using Quadrum to make a custom item and setting it as the fruit for a custom crop, the journal instead uses the missing-texture icon instead of the actual one. All of the other textures render just fine, both in-journal and in-game, and the custom item shows the right texture in NEI and my inventory. Could it possibly be caused by Quadrum storing its textures in its config folder?

**Comment by InfinityRaider** [comment]
That's most definatly it, I'll use a different method to render items in the journal. When I wrote that journal code I wasn't aware of certain methods in the Gui class, however I'm aware of those now. It'll simplify things a lot.
For now, all you can do is make a resource pack and put that texture in it, my apologies
