### ISSUE TITLE
[1.2.3] Cactus drops with metadata 2

### ISSUE THREAD

**Issue by MadMax-XIII** [InfinityRaider/AgriCraft#99]
I play the Regrowth modpack with 
B:"Cactus produces cactus blocks"=true
and cactus drops with metadata 2 which produces some incompatabilities.
With my basic understanding of java this seems to be an artifact of the way you switch between cactus green (which has metadata 2) and cactus (which shouldn't have metadata) as a drop.

**Comment by InfinityRaider** [comment]
Oversight on my part, fixed it. Thanks for the report
